package com.learney.contentaudit.revisioninfrastructure.lemmaabsenceagent;

import com.learney.contentaudit.revisiondomain.lemmaabsence.LemmaAbsenceGeneratorResponse;
import com.sentinel.agents.framework.state.RunState;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
interface AgentCandidateParser {
    LemmaAbsenceGeneratorResponse parse(RunState runState, String taskId, String strategyName);
}
