package com.learney.contentaudit.revisioninfrastructure.lemmaabsenceagent;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.learney.contentaudit.revisiondomain.ProposalStrategyFailedException;
import com.learney.contentaudit.revisiondomain.lemmaabsence.LemmaAbsenceGeneratorResponse;
import com.learney.contentaudit.revisioninfrastructure.lagen.LlmGenerationFailureCategory;
import com.sentinel.agents.framework.state.ArtifactPointer;
import com.sentinel.agents.framework.state.RunState;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import javax.annotation.processing.Generated;

/**
 * Parses the agent's output artifact into a {@link LemmaAbsenceGeneratorResponse}.
 *
 * <p><strong>Adapter↔graph contract (artifact side):</strong>
 * <ul>
 *   <li>Artifact key in the RunState artifacts map: {@code "quizCandidate"}</li>
 *   <li>Artifact format: UTF-8 JSON file with two required text fields:
 *       {@code quizSentence} (fill-in-the-blank sentence with {@code [[lemma]]} marker)
 *       and {@code translation} (Spanish translation of the sentence).</li>
 *   <li>Example: {@code {"quizSentence":"She [[goes]] to school.","translation":"Ella va a la escuela."}}</li>
 * </ul>
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultAgentCandidateParser implements AgentCandidateParser {

    /** Key under which the declarative graph must emit the final candidate artifact. */
    static final String ARTIFACT_KEY = "quizCandidate";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Override
    public LemmaAbsenceGeneratorResponse parse(RunState runState, String taskId,
            String strategyName) {
        Map<String, ArtifactPointer> artifacts = runState.artifacts();
        if (artifacts == null || !artifacts.containsKey(ARTIFACT_KEY)) {
            throw new ProposalStrategyFailedException(
                    strategyName,
                    taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_EMPTY.name()
                            + ": agent did not emit the expected artifact '"
                            + ARTIFACT_KEY + "'");
        }

        ArtifactPointer pointer = artifacts.get(ARTIFACT_KEY);
        Path location = pointer.location();

        String rawJson;
        try {
            rawJson = Files.readString(location);
        } catch (Exception e) {
            throw new ProposalStrategyFailedException(
                    strategyName,
                    taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_MALFORMED.name()
                            + ": cannot read artifact file at " + location + " — " + e.getMessage());
        }

        return parseJson(rawJson, taskId, strategyName);
    }

    private static LemmaAbsenceGeneratorResponse parseJson(String rawJson, String taskId,
            String strategyName) {
        if (rawJson == null || rawJson.isBlank()) {
            throw new ProposalStrategyFailedException(
                    strategyName, taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_EMPTY.name()
                            + ": artifact content is empty");
        }

        String cleaned = stripJsonFence(rawJson.trim());
        JsonNode root;
        try {
            root = MAPPER.readTree(cleaned);
        } catch (Exception e) {
            throw new ProposalStrategyFailedException(
                    strategyName, taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_MALFORMED.name()
                            + ": artifact is not valid JSON — " + e.getMessage());
        }

        JsonNode quizSentenceNode = root.get("quizSentence");
        JsonNode translationNode = root.get("translation");

        if (quizSentenceNode == null || !quizSentenceNode.isTextual()
                || quizSentenceNode.asText().isBlank()) {
            throw new ProposalStrategyFailedException(
                    strategyName, taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_MALFORMED.name()
                            + ": missing or empty field 'quizSentence' in artifact");
        }

        if (translationNode == null || !translationNode.isTextual()
                || translationNode.asText().isBlank()) {
            throw new ProposalStrategyFailedException(
                    strategyName, taskId,
                    LlmGenerationFailureCategory.LLM_RESPONSE_MALFORMED.name()
                            + ": missing or empty field 'translation' in artifact");
        }

        return new LemmaAbsenceGeneratorResponse(
                quizSentenceNode.asText(),
                translationNode.asText());
    }

    private static String stripJsonFence(String text) {
        if (text.startsWith("```")) {
            int firstNewline = text.indexOf('\n');
            int lastFence = text.lastIndexOf("```");
            if (firstNewline >= 0 && lastFence > firstNewline) {
                return text.substring(firstNewline + 1, lastFence).trim();
            }
        }
        return text;
    }
}
