package com.learney.contentaudit.quizinstructioninfrastructure.instructionjudge;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
enum JudgeProviderClass {
    LOCAL_SESSION,

    REMOTE_SERVICE
}
