package com.learney.contentaudit.quizinstructioninfrastructure.instructionjudge;

import com.learney.contentaudit.agentruntimeinfrastructure.AgentGraphRunner;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationOutcome;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSubject;
import com.learney.contentaudit.evaluationledgerdomain.Evaluator;
import com.learney.contentaudit.quizinstructioninfrastructure.QuizInstructionJudgeConfig;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class QuizInstructionAgentJudge implements Evaluator {
    private final QuizInstructionJudgeConfig config;

    private final AgentGraphRunner agentGraphRunner;

    private final QuizInstructionJudgeVersionResolver versionResolver;

    public QuizInstructionAgentJudge(QuizInstructionJudgeConfig config,
            AgentGraphRunner agentGraphRunner,
            QuizInstructionJudgeVersionResolver versionResolver) {
        this.config = config;
        this.agentGraphRunner = agentGraphRunner;
        this.versionResolver = versionResolver;
    }

    @Override
    public String evaluatorId() {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public String evaluatorVersion() {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public EvaluationOutcome evaluate(EvaluationSubject subject) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
