package com.learney.contentaudit.quizinstructioninfrastructure.instructionjudge;

import com.learney.contentaudit.quizinstructioninfrastructure.QuizInstructionJudgeConfig;
import com.sentinel.agents.analyst.LlmFactory;
import com.sentinel.agents.framework.runner.FrameworkLlmListener;
import dev.langchain4j.model.chat.ChatModel;
import java.util.List;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class SentinelAgentsJudgeChatModelFactory implements JudgeChatModelFactory {

    private static final double DEFAULT_TEMPERATURE = 0.0;

    private static final int DEFAULT_MAX_TOKENS = 2048;

    /**
     * F-QINST-R016: el enrutamiento por clase de proveedor no se reimplementa aca.
     * {@link LlmFactory} ya elige entre shell-out a la herramienta local del
     * proveedor de suscripcion y cliente compatible OpenAI, y eso es precisamente
     * lo que hace que el juez admita las mismas clases de proveedor que el resto
     * del sistema en lugar de exigir siempre direccion y credencial.
     *
     * <p>El {@link FrameworkLlmListener} deja los transcripts de la conversacion en
     * el log de la corrida (queda inerte si no hay sink activo durante la corrida).
     */
    @Override
    public ChatModel create(QuizInstructionJudgeConfig config, JudgeProviderResolved provider) {
        Double temperature = config != null ? config.getTemperature() : null;

        LlmFactory.LlmConfig llmConfig = new LlmFactory.LlmConfig(
                provider.getProviderName(),
                config != null ? config.getModelName() : null,
                config != null ? config.getBaseUrl() : null,
                config != null ? config.getApiKey() : null,
                DEFAULT_MAX_TOKENS,
                temperature != null ? temperature : DEFAULT_TEMPERATURE
        );

        return LlmFactory.build(llmConfig, List.of(new FrameworkLlmListener()));
    }
}
