package com.learney.contentaudit.refinerdomain.lemmasuggestion;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableKnowledge;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.AuditableTopic;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.EvpCatalogPort;
import com.learney.contentaudit.auditdomain.LemmaCountConfig;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import com.learney.contentaudit.auditdomain.lemmacount.LemmaCountLevelDiagnosis;
import com.learney.contentaudit.auditdomain.lemmacount.LemmaCountStats;
import com.learney.contentaudit.auditdomain.lemmacount.LevelLemmaCountResult;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryCriteria;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryRejectedException;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryResult;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.IntStream;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaAbsenceContextSuggestedLemmaQueryPortTest {

    @SuppressWarnings("unchecked")
    private CorrectionContextResolver<LemmaAbsenceCorrectionContext> resolver =
            Mockito.mock(CorrectionContextResolver.class);

    private LemmaAbsenceContextSuggestedLemmaQueryPort sut;

    @BeforeEach
    void setUp() {
        // Use UnderexposedLemmaInventory (same-package) for the underexposed path (includeExposed=false).
        // For includeExposed=true tests, individual tests build their own sut with a
        // LevelWideLemmaInventory backed by a mocked EvpCatalogPort.
        UnderexposedLemmaInventory underexposedInventory = new UnderexposedLemmaInventory(resolver);
        // levelWide inventory is not exercised by CSLATDC tests (includeExposed defaults to false);
        // pass a simple stub that returns an empty list to avoid NPE if accidentally called.
        LeveledLemmaInventory levelWideStub = (report, task, level, pos) -> List.of();
        sut = new LemmaAbsenceContextSuggestedLemmaQueryPort(
                resolver, underexposedInventory, levelWideStub);
    }

    // ------------------------------------------------------------------
    // Tree builder helpers (same pattern as LemmaAbsenceContextResolverTest)
    // ------------------------------------------------------------------

    private AuditNode buildCourseNode() {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.COURSE);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        return node;
    }

    private AuditNode buildMilestoneNode(AuditNode parent, AuditableMilestone milestone,
            DefaultLevelDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.MILESTONE);
        node.setEntity(milestone);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildTopicNode(AuditNode parent, AuditableTopic topic) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.TOPIC);
        node.setEntity(topic);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildKnowledgeNode(AuditNode parent, AuditableKnowledge knowledge) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.KNOWLEDGE);
        node.setEntity(knowledge);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildQuizNode(AuditNode parent, AuditableQuiz quiz,
            DefaultQuizDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setEntity(quiz);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    /** Builds COURSE → MILESTONE → TOPIC → KNOWLEDGE → QUIZ tree. */
    private AuditReport buildReport(AuditableMilestone milestone, DefaultLevelDiagnoses milestoneDiagnoses,
            AuditableQuiz quiz, DefaultQuizDiagnoses quizDiagnoses) {
        AuditNode courseNode = buildCourseNode();
        AuditNode milestoneNode = buildMilestoneNode(courseNode, milestone, milestoneDiagnoses);
        AuditNode topicNode = buildTopicNode(milestoneNode,
                new AuditableTopic(List.of(), "topic-1", "Topic", null));
        AuditNode knowledgeNode = buildKnowledgeNode(topicNode,
                new AuditableKnowledge(List.of(), "Knowledge", "Instructions", true, "know-1", null, null, null));
        buildQuizNode(knowledgeNode, quiz, quizDiagnoses);
        return new AuditReport(courseNode);
    }

    private RefinementTask buildLemmaAbsenceTask(String quizId) {
        return new RefinementTask(
                "task-sq-1",
                AuditTarget.QUIZ,
                quizId,
                "Quiz label",
                DiagnosisKind.LEMMA_ABSENCE,
                1,
                RefinementTaskStatus.PENDING);
    }

    private AuditableQuiz buildQuiz(String id) {
        return new AuditableQuiz(List.of(), id, null, null,
                "El gato duerme.", List.of("The cat sleeps."), null);
    }

    private DefaultLevelDiagnoses buildMilestoneDiagnoses(CefrLevel level, List<AbsentLemma> absentLemmas) {
        LemmaAbsenceLevelDiagnosis absenceDiagnosis = new LemmaAbsenceLevelDiagnosis(
                level, 100, absentLemmas.size(), 10.0, 90.0,
                0.8, 0.7, 0.5, null, absentLemmas, List.of(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.HIGH).count(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.MEDIUM).count(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.LOW).count());
        DefaultLevelDiagnoses diagnoses = new DefaultLevelDiagnoses();
        diagnoses.setLemmaAbsenceDiagnosis(absenceDiagnosis);
        return diagnoses;
    }

    /** Milestone with no LemmaAbsence diagnosis — level cannot be inferred. */
    private DefaultLevelDiagnoses buildMilestoneDiagnosesNoLevel() {
        return new DefaultLevelDiagnoses();
    }

    private AbsentLemma buildAbsentLemma(String lemma, String pos, int cocaRank) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, pos),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                List.of(),
                PriorityLevel.HIGH,
                cocaRank,
                null);
    }

    private AbsentLemma buildAbsentLemmaWithPos(String lemma, String pos, int cocaRank,
            PriorityLevel priority) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, pos),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                List.of(),
                priority,
                cocaRank,
                null);
    }

    /** Builds a SuggestedLemmaQueryCriteria for the default (includeExposed=false) mode. */
    private SuggestedLemmaQueryCriteria defaultCriteria(Optional<Integer> limit,
            Optional<String> partOfSpeech, Optional<CefrLevel> explicitLevel) {
        return new SuggestedLemmaQueryCriteria(limit, partOfSpeech, explicitLevel, false);
    }

    /**
     * Builds a DefaultLevelDiagnoses that contains BOTH a LemmaAbsenceLevelDiagnosis (for level
     * inference by the port) AND a LemmaCountLevelDiagnosis (for sub-exposed classification by
     * LevelWideLemmaInventory). The sub-exposed list marks the given lemmas as underexposed
     * (score < 1.0 means sub-exposed, not yet reaching the threshold).
     */
    private DefaultLevelDiagnoses buildMilestoneDiagnosesWithLemmaCount(
            CefrLevel level,
            List<AbsentLemma> absentLemmas,
            List<LemmaAndPos> subExposedLemmasForCount) {
        DefaultLevelDiagnoses diagnoses = buildMilestoneDiagnoses(level, absentLemmas);
        List<LemmaCountStats> statsList = subExposedLemmasForCount.stream()
                .map(lp -> new LemmaCountStats(lp, 2, 0.4, Optional.empty()))
                .toList();
        LevelLemmaCountResult levelResult = new LevelLemmaCountResult(level, 0.4, 10, statsList);
        LemmaCountLevelDiagnosis lemmaCountDiagnosis = new LemmaCountLevelDiagnosis(levelResult);
        diagnoses.setLemmaCountDiagnosis(lemmaCountDiagnosis);
        return diagnoses;
    }

    // ------------------------------------------------------------------
    // Tests
    // ------------------------------------------------------------------

    @Test
    @DisplayName("should return the suggested lemmas of the task identified by taskId when invoked through the SuggestedLemmaQueryPort")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R001")
    public void shouldReturnTheSuggestedLemmasOfTheTaskIdentifiedByTaskIdWhenInvokedThroughTheSuggestedLemmaQueryPort(
            ) {
        String quizId = "quiz-r001";
        AbsentLemma absentLemma = buildAbsentLemma("sleep", "VERB", 500);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r001", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(absentLemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        Assertions.assertNotNull(result);
        Assertions.assertEquals("task-sq-1", result.getTaskId());
        Assertions.assertFalse(result.getSuggestedLemmas().isEmpty());
    }

    @Test
    @DisplayName("should include only suggested lemmas whose CefrLevel matches the level applied to the task")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R003")
    public void shouldIncludeOnlySuggestedLemmasWhoseCefrLevelMatchesTheLevelAppliedToTheTask() {
        String quizId = "quiz-r003";
        AbsentLemma a1Lemma = buildAbsentLemma("run", "VERB", 200);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r003", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(a1Lemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        Assertions.assertEquals(CefrLevel.A1, result.getCefrLevel());
        Assertions.assertFalse(result.getSuggestedLemmas().isEmpty());
    }

    @Test
    @DisplayName("should infer the CefrLevel from the task milestone ancestor when no explicit level is provided")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R004")
    public void shouldInferTheCefrLevelFromTheTaskMilestoneAncestorWhenNoExplicitLevelIsProvided() {
        String quizId = "quiz-r004";
        AbsentLemma absentLemma = buildAbsentLemma("walk", "VERB", 300);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r004", "B1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.B1, List.of(absentLemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        // The level inferred from the milestone ancestor must be B1 (not provided explicitly)
        Assertions.assertEquals(CefrLevel.B1, result.getCefrLevel());
    }

    @Test
    @DisplayName("should throw SuggestedLemmaQueryRejectedException when no level is provided and none can be inferred from the task")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R005")
    public void shouldThrowSuggestedLemmaQueryRejectedExceptionWhenNoLevelIsProvidedAndNoneCanBeInferredFromTheTask(
            ) {
        String quizId = "quiz-r005";

        // Milestone has no LemmaAbsence diagnosis — level cannot be inferred
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r005", "Unknown Level Milestone", null),
                buildMilestoneDiagnosesNoLevel(),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        Assertions.assertThrows(SuggestedLemmaQueryRejectedException.class, () ->
                sut.query(report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty())));
    }

    @Test
    @DisplayName("should use the explicit level provided in the filter when the task does not allow level inference")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R006")
    public void shouldUseTheExplicitLevelProvidedInTheFilterWhenTheTaskDoesNotAllowLevelInference(
            ) {
        String quizId = "quiz-r006";

        // Milestone has no LemmaAbsence diagnosis — inference not possible
        // Caller provides explicit level A2
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r006", "Milestone", null),
                buildMilestoneDiagnosesNoLevel(),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.of(CefrLevel.A2)));

        Assertions.assertEquals(CefrLevel.A2, result.getCefrLevel());
    }

    @Test
    @DisplayName("should restrict results to suggested lemmas whose partOfSpeech matches the requested partOfSpeech filter")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R007")
    public void shouldRestrictResultsToSuggestedLemmasWhosePartOfSpeechMatchesTheRequestedPartOfSpeechFilter(
            ) {
        String quizId = "quiz-r007";
        AbsentLemma verb1 = buildAbsentLemma("run", "VERB", 200);
        AbsentLemma noun1 = buildAbsentLemma("cat", "NOUN", 300);
        AbsentLemma verb2 = buildAbsentLemma("jump", "VERB", 400);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r007", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(verb1, noun1, verb2)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.of("VERB"), Optional.empty()));

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertFalse(lemmas.isEmpty());
        lemmas.forEach(l -> Assertions.assertEquals("VERB", l.getPos()));
    }

    @Test
    @DisplayName("should return at most N suggested lemmas when the limit filter equals N")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R008")
    public void shouldReturnAtMostNSuggestedLemmasWhenTheLimitFilterEqualsN() {
        String quizId = "quiz-r008";
        List<AbsentLemma> manyLemmas = List.of(
                buildAbsentLemma("run", "VERB", 100),
                buildAbsentLemma("walk", "VERB", 200),
                buildAbsentLemma("eat", "VERB", 300),
                buildAbsentLemma("sleep", "VERB", 400),
                buildAbsentLemma("talk", "VERB", 500));

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r008", "A2 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A2, manyLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        int limit = 3;
        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.of(limit), Optional.empty(), Optional.empty()));

        Assertions.assertTrue(result.getSuggestedLemmas().size() <= limit);
        Assertions.assertEquals(limit, result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return all available suggested lemmas without error when fewer than the requested limit match the filters")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R009")
    public void shouldReturnAllAvailableSuggestedLemmasWithoutErrorWhenFewerThanTheRequestedLimitMatchTheFilters(
            ) {
        String quizId = "quiz-r009";
        // Only 2 absent lemmas available
        List<AbsentLemma> twoLemmas = List.of(
                buildAbsentLemma("run", "VERB", 100),
                buildAbsentLemma("walk", "VERB", 200));

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r009", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, twoLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // Request 10 but only 2 are available
        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.of(10), Optional.empty(), Optional.empty()));

        // No exception thrown; returns the 2 available
        Assertions.assertEquals(2, result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return suggested lemmas ordered by recommendation priority so the caller does not need to sort them")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R010")
    public void shouldReturnSuggestedLemmasOrderedByRecommendationPrioritySoTheCallerDoesNotNeedToSortThem(
            ) {
        String quizId = "quiz-r010";
        // Lower cocaRank = higher frequency = higher priority in recommendation
        AbsentLemma highFrequency  = buildAbsentLemmaWithPos("run",  "VERB", 100, PriorityLevel.HIGH);
        AbsentLemma midFrequency   = buildAbsentLemmaWithPos("walk", "VERB", 500, PriorityLevel.HIGH);
        AbsentLemma lowFrequency   = buildAbsentLemmaWithPos("amble","VERB", 900, PriorityLevel.MEDIUM);

        // Provide lemmas out of priority order so we can verify the port sorts them
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r010", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(lowFrequency, highFrequency, midFrequency)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(3, lemmas.size());
        // Verify ordering: the first result should have a lower or equal cocaRank than the last
        Integer firstCocaRank = lemmas.get(0).getCocaRank();
        Integer lastCocaRank  = lemmas.get(lemmas.size() - 1).getCocaRank();
        Assertions.assertTrue(firstCocaRank <= lastCocaRank,
                "Results must be ordered by priority (ascending cocaRank): first=" + firstCocaRank + " last=" + lastCocaRank);
    }

    @Test
    @DisplayName("should return more suggested lemmas than the cap of 10 used by LemmaAbsenceContextResolver when the requested limit exceeds it")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R011")
    public void shouldReturnMoreSuggestedLemmasThanTheCapOf10UsedByLemmaAbsenceContextResolverWhenTheRequestedLimitExceedsIt(
            ) {
        String quizId = "quiz-r011";
        // 12 absent lemmas in the milestone diagnosis — more than the static cap of 10
        List<AbsentLemma> twelveLemmas = IntStream.rangeClosed(1, 12)
                .mapToObj(i -> buildAbsentLemma("lemma" + i, "NOUN", i * 100))
                .toList();

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r011", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, twelveLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // Request 12 — must get 12 (not capped at 10)
        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.of(12), Optional.empty(), Optional.empty()));

        Assertions.assertTrue(result.getSuggestedLemmas().size() > 10,
                "Port must return more than the resolver's static cap of 10; got: " + result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return an empty suggested lemma list with the effective level when the task has no compatible base for suggesting lemmas")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R012")
    public void shouldReturnAnEmptySuggestedLemmaListWithTheEffectiveLevelWhenTheTaskHasNoCompatibleBaseForSuggestingLemmas(
            ) {
        String quizId = "quiz-r012";

        // Milestone has a LemmaAbsence diagnosis with an empty absent-lemma list
        // (level is inferable but there is no base for suggestions)
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r012", "B1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.B1, List.of()),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        Assertions.assertNotNull(result);
        Assertions.assertTrue(result.getSuggestedLemmas().isEmpty());
        // The effective level must still be reported for traceability
        Assertions.assertEquals(CefrLevel.B1, result.getCefrLevel());
    }

    @Test
    @DisplayName("should expose each suggested lemma identifiably in the result with the list order representing its relative priority")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R014")
    public void shouldExposeEachSuggestedLemmaIdentifiablyInTheResultWithTheListOrderRepresentingItsRelativePriority(
            ) {
        String quizId = "quiz-r014";
        AbsentLemma first  = buildAbsentLemma("run",  "VERB", 100);
        AbsentLemma second = buildAbsentLemma("walk", "VERB", 200);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r014", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(first, second)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, defaultCriteria(Optional.empty(), Optional.empty(), Optional.empty()));

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(2, lemmas.size());

        // Each lemma is individually identifiable (non-null lemma string)
        lemmas.forEach(l -> Assertions.assertNotNull(l.getLemma()));
        // List order represents relative priority: position 0 is higher priority than position 1
        Assertions.assertNotEquals(lemmas.get(0).getLemma(), lemmas.get(1).getLemma());
    }

    // ------------------------------------------------------------------
    // FEAT-INCEXP tests
    // ------------------------------------------------------------------

    /**
     * Builds a port wired with a real LevelWideLemmaInventory backed by a mock EvpCatalogPort,
     * for testing the includeExposed=true path.
     */
    private LemmaAbsenceContextSuggestedLemmaQueryPort buildSutWithLevelWide(
            EvpCatalogPort mockEvpCatalog, LemmaCountConfig mockLemmaCountConfig) {
        UnderexposedLemmaInventory underexposedInventory = new UnderexposedLemmaInventory(resolver);
        LevelWideLemmaInventory levelWideInventory =
                new LevelWideLemmaInventory(mockEvpCatalog, mockLemmaCountConfig);
        return new LemmaAbsenceContextSuggestedLemmaQueryPort(
                resolver, underexposedInventory, levelWideInventory);
    }

    @Test
    @DisplayName("should exclude already-exposed lemmas and recommend only lemmas still needing exposure when includeExposed is false")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R001")
    public void shouldExcludeAlreadyexposedLemmasAndRecommendOnlyLemmasStillNeedingExposureWhenIncludeExposedIsFalse() {
        // Arrange — quiz with two absent (underexposed) lemmas at A1.
        // The default sut uses UnderexposedLemmaInventory, which only surfaces absent/underexposed lemmas.
        // The EvpCatalog is NOT consulted when includeExposed=false; the result must NOT contain
        // any already-exposed lemma (a lemma not in the absent list would be "already exposed").
        String quizId = "quiz-incexp-r001";
        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        AbsentLemma walk = buildAbsentLemma("walk", "VERB", 400);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r001", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(run, walk)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // Act — includeExposed=false (the default OFF mode, F-INCEXP-R001)
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), false);
        SuggestedLemmaQueryResult result = sut.query(report, task, criteria);

        // Assert — only the two underexposed lemmas are returned; none is from the "already-exposed" set.
        // The result contains exactly the two absent lemmas (run, walk) and no additional ones.
        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(2, lemmas.size(),
                "F-INCEXP-R001: default (includeExposed=false) must return only the " +
                "underexposed/absent lemmas. Got: " + lemmas.size());
        // Verify both returned lemmas are from the absent set (underexposed)
        List<String> lemmaNames = lemmas.stream().map(SuggestedLemma::getLemma).toList();
        Assertions.assertTrue(lemmaNames.contains("run"),
                "F-INCEXP-R001: absent lemma 'run' must be in the result");
        Assertions.assertTrue(lemmaNames.contains("walk"),
                "F-INCEXP-R001: absent lemma 'walk' must be in the result");
    }

    @Test
    @DisplayName("should include already-exposed lemmas of the requested level and partOfSpeech in the candidate universe when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R002")
    public void shouldIncludeAlreadyexposedLemmasOfTheRequestedLevelAndPartOfSpeechInTheCandidateUniverseWhenIncludeExposedIsTrue() {
        // Arrange — Critical regression scenario:
        // "run" is COMPLETELY_ABSENT in the LemmaAbsence signal (count=0, in absent list) AND
        // also present in the EVP catalog for A1. "sleep" is in EVP but NOT in the absent list
        // (already-exposed). This was the exact bug: the old LevelWideLemmaInventory would see
        // "run" in the EVP, not find it in the sub-exposed list (if LemmaCountLevelDiagnosis was
        // absent/incomplete), classify it as "already-exposed", and the limit could then drop it.
        // Result: ON was NOT a superset of OFF. The fix: needs-exposure block = identical to OFF
        // output; only already-exposed (not in needs-exposure) go into the tail.
        //
        // Verified property (F-INCEXP-R002): ON result ⊇ OFF result (strict superset).
        // Every lemma returned by OFF must also appear in ON.
        String quizId = "quiz-incexp-r002";

        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        LemmaAndPos runLap = new LemmaAndPos("run", "VERB");
        // Milestone label "A1" (exact CefrLevel name) so LevelWideLemmaInventory can match it.
        // LemmaCountLevelDiagnosis marks "run" as sub-exposed (underexposed); "sleep" is not in
        // the sub-exposed list → already-exposed. This reproduces the COMPLETELY_ABSENT-in-EVP scenario.
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r002", "A1", null),
                buildMilestoneDiagnosesWithLemmaCount(CefrLevel.A1, List.of(run), List.of(runLap)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // EVP catalog has both "run" (needs exposure, COMPLETELY_ABSENT) and "sleep" (already-exposed).
        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos sleepLap = new LemmaAndPos("sleep", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, sleepLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(sleepLap)).thenReturn(Optional.of(600));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // OFF query (includeExposed=false) — establishes the baseline set that ON must be a superset of
        SuggestedLemmaQueryCriteria offCriteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), false);
        SuggestedLemmaQueryResult offResult = sut.query(report, task, offCriteria);
        List<String> offLemmaNames = offResult.getSuggestedLemmas().stream()
                .map(SuggestedLemma::getLemma).toList();

        // Act — ON query (includeExposed=true): must return the needs-exposure set PLUS already-exposed
        SuggestedLemmaQueryCriteria onCriteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult onResult = sutWithLevelWide.query(report, task, onCriteria);
        List<SuggestedLemma> onLemmas = onResult.getSuggestedLemmas();
        List<String> onLemmaNames = onLemmas.stream().map(SuggestedLemma::getLemma).toList();

        // Assert — superset: ON ⊇ OFF (every lemma the OFF query returned must also be in ON)
        Assertions.assertFalse(offLemmaNames.isEmpty(),
                "F-INCEXP-R002: OFF query must return at least 'run' (COMPLETELY_ABSENT)");
        Assertions.assertTrue(onLemmaNames.containsAll(offLemmaNames),
                "F-INCEXP-R002: ON result must be a superset of OFF result. " +
                "OFF=" + offLemmaNames + " ON=" + onLemmaNames +
                ". The COMPLETELY_ABSENT lemma 'run' must NOT be lost when includeExposed=true");
        // ON must also include the already-exposed "sleep"
        Assertions.assertTrue(onLemmaNames.contains("sleep"),
                "F-INCEXP-R002: already-exposed lemma 'sleep' must be included when includeExposed=true");
        // Strict superset: ON has MORE lemmas than OFF
        Assertions.assertTrue(onLemmas.size() > offResult.getSuggestedLemmas().size(),
                "F-INCEXP-R002: ON must return more lemmas than OFF (adds already-exposed). " +
                "OFF size=" + offResult.getSuggestedLemmas().size() + " ON size=" + onLemmas.size());
    }

    @Test
    @DisplayName("should place lemmas still needing exposure first and already-exposed lemmas last by recommendation priority when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R003")
    public void shouldPlaceLemmasStillNeedingExposureFirstAndAlreadyexposedLemmasLastByRecommendationPriorityWhenIncludeExposedIsTrue() {
        // Arrange — Critical regression scenario: two needs-exposure lemmas ("run" COMPLETELY_ABSENT
        // + "walk" COMPLETELY_ABSENT), both also present in the EVP catalog at A1, plus one
        // already-exposed lemma ("sleep") that appears only in EVP. "sleep" has the LOWEST cocaRank
        // (100) — lower than "run" (200) and "walk" (300). Despite this, "sleep" (already-exposed)
        // must appear AFTER both needs-exposure lemmas (R003). This proves that the priority block
        // (needs-exposure first) takes precedence over COCA rank.
        //
        // This exercises the fixed composition: needs-exposure block = identical to OFF output
        // (includes COMPLETELY_ABSENT lemmas that are also in EVP), then already-exposed tail.
        String quizId = "quiz-incexp-r003";

        AbsentLemma run  = buildAbsentLemma("run",  "VERB", 200);
        AbsentLemma walk = buildAbsentLemma("walk", "VERB", 300);
        LemmaAndPos runLap  = new LemmaAndPos("run",  "VERB");
        LemmaAndPos walkLap = new LemmaAndPos("walk", "VERB");
        // Milestone label "A1" (exact CefrLevel name) for LevelWideLemmaInventory.
        // LemmaCountLevelDiagnosis marks "run" and "walk" as sub-exposed; "sleep" is not in the
        // sub-exposed list → already-exposed. This reproduces COMPLETELY_ABSENT-in-EVP for run and walk.
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r003", "A1", null),
                buildMilestoneDiagnosesWithLemmaCount(CefrLevel.A1, List.of(run, walk),
                        List.of(runLap, walkLap)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        // sleep has cocaRank=100 — lower than both run (200) and walk (300) — yet it is already-exposed.
        // It must appear AFTER both run and walk because the needs-exposure block is sorted first (R003).
        LemmaAndPos sleepLap = new LemmaAndPos("sleep", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, walkLap, sleepLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(walkLap)).thenReturn(Optional.of(300));
        Mockito.when(mockEvpCatalog.getCocaRank(sleepLap)).thenReturn(Optional.of(100));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — ALL needs-exposure lemmas (run, walk) appear before ALL already-exposed (sleep).
        // The position of every needs-exposure lemma must be less than the position of every
        // already-exposed lemma in the list.
        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(3, lemmas.size(),
                "F-INCEXP-R003: must have exactly 3 lemmas (run + walk needs-exposure, sleep exposed)");

        // Partition by exposure flag
        int maxNeedsExposurePos = -1;
        int minAlreadyExposedPos = Integer.MAX_VALUE;
        boolean runFound = false, walkFound = false, sleepFound = false;
        for (int i = 0; i < lemmas.size(); i++) {
            SuggestedLemma sl = lemmas.get(i);
            if (Boolean.FALSE.equals(sl.getIsUnderexposed())) {
                // already-exposed
                minAlreadyExposedPos = Math.min(minAlreadyExposedPos, i);
                if ("sleep".equals(sl.getLemma())) sleepFound = true;
            } else {
                // needs-exposure (isUnderexposed=true or null)
                maxNeedsExposurePos = Math.max(maxNeedsExposurePos, i);
                if ("run".equals(sl.getLemma()))  runFound  = true;
                if ("walk".equals(sl.getLemma())) walkFound = true;
            }
        }
        Assertions.assertTrue(runFound,   "F-INCEXP-R003: COMPLETELY_ABSENT lemma 'run' must be in ON result");
        Assertions.assertTrue(walkFound,  "F-INCEXP-R003: COMPLETELY_ABSENT lemma 'walk' must be in ON result");
        Assertions.assertTrue(sleepFound, "F-INCEXP-R003: already-exposed lemma 'sleep' must be in ON result");
        Assertions.assertTrue(maxNeedsExposurePos < minAlreadyExposedPos,
                "F-INCEXP-R003: all needs-exposure lemmas (max pos=" + maxNeedsExposurePos + ") must appear " +
                "before all already-exposed lemmas (min pos=" + minAlreadyExposedPos + "). " +
                "Even though 'sleep' has lower cocaRank (100), block priority overrides COCA rank.");
    }

    @Test
    @DisplayName("should break ties by ascending COCA frequency within both the underexposed block and the already-exposed block when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R004")
    public void shouldBreakTiesByAscendingCOCAFrequencyWithinBothTheUnderexposedBlockAndTheAlreadyexposedBlockWhenIncludeExposedIsTrue() {
        // Arrange — two underexposed lemmas (run@200, walk@400) and two already-exposed
        // lemmas (jump@300, eat@500). Expected order: run, walk (underexposed asc COCA),
        // then jump, eat (exposed asc COCA). F-INCEXP-R004.
        String quizId = "quiz-incexp-r004";

        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        AbsentLemma walk = buildAbsentLemma("walk", "VERB", 400);
        LemmaAndPos runLap  = new LemmaAndPos("run",  "VERB");
        LemmaAndPos walkLap = new LemmaAndPos("walk", "VERB");
        // Milestone label must be exactly "A1" so LevelWideLemmaInventory can parse it as CefrLevel.
        // LemmaCountLevelDiagnosis marks "run" and "walk" as sub-exposed (underexposed); "jump" and
        // "eat" are NOT in the sub-exposed list, so they get isUnderexposed=false (already-exposed).
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r004", "A1", null),
                buildMilestoneDiagnosesWithLemmaCount(CefrLevel.A1, List.of(run, walk),
                        List.of(runLap, walkLap)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);

        LemmaAndPos jumpLap = new LemmaAndPos("jump", "VERB");
        LemmaAndPos eatLap  = new LemmaAndPos("eat",  "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, walkLap, jumpLap, eatLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(walkLap)).thenReturn(Optional.of(400));
        Mockito.when(mockEvpCatalog.getCocaRank(jumpLap)).thenReturn(Optional.of(300));
        Mockito.when(mockEvpCatalog.getCocaRank(eatLap)).thenReturn(Optional.of(500));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(4, lemmas.size(), "F-INCEXP-R004: expected 4 lemmas in result");

        // First two must be underexposed, ordered by ascending COCA
        Assertions.assertEquals("run", lemmas.get(0).getLemma(),
                "F-INCEXP-R004: first lemma must be 'run' (underexposed, coca=200)");
        Assertions.assertEquals("walk", lemmas.get(1).getLemma(),
                "F-INCEXP-R004: second lemma must be 'walk' (underexposed, coca=400)");

        // Last two must be already-exposed, ordered by ascending COCA
        Assertions.assertEquals("jump", lemmas.get(2).getLemma(),
                "F-INCEXP-R004: third lemma must be 'jump' (exposed, coca=300)");
        Assertions.assertEquals("eat", lemmas.get(3).getLemma(),
                "F-INCEXP-R004: fourth lemma must be 'eat' (exposed, coca=500)");
    }

    @Test
    @DisplayName("should still restrict results to lemmas matching the applicable level even when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R005")
    public void shouldStillRestrictResultsToLemmasMatchingTheApplicableLevelEvenWhenIncludeExposedIsTrue() {
        // Arrange — task at A1 level. EVP catalog is only queried for A1.
        // With includeExposed=true, only A1 lemmas must be returned (never B1 or other levels).
        // The level is inferred from the milestone diagnosis (A1).
        String quizId = "quiz-incexp-r005";

        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r005", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(run)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos runLap = new LemmaAndPos("run", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1)).thenReturn(Set.of(runLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — result level is A1 (the inferred level) and EVP was called only for A1
        Assertions.assertEquals(CefrLevel.A1, result.getCefrLevel(),
                "F-INCEXP-R005: level filter must still apply; result level must be A1");
        Mockito.verify(mockEvpCatalog).getExpectedLemmas(CefrLevel.A1);
        Mockito.verify(mockEvpCatalog, Mockito.never()).getExpectedLemmas(Mockito.argThat(
                l -> l != null && l != CefrLevel.A1));
    }

    @Test
    @DisplayName("should still restrict results to the requested partOfSpeech among already-exposed lemmas when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R006")
    public void shouldStillRestrictResultsToTheRequestedPartOfSpeechAmongAlreadyexposedLemmasWhenIncludeExposedIsTrue() {
        // Arrange — EVP catalog has both VERB ("run") and NOUN ("cat") at A1.
        // With partOfSpeech="VERB" and includeExposed=true, only VERBs must be returned.
        // "cat" (NOUN, exposed) must not appear.
        String quizId = "quiz-incexp-r006";

        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r006", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(run)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos runLap = new LemmaAndPos("run", "VERB");
        // "sleep" is another VERB that is already-exposed (not in absent list)
        LemmaAndPos sleepLap = new LemmaAndPos("sleep", "VERB");
        // "cat" is a NOUN that is already-exposed — must be excluded by POS filter
        LemmaAndPos catLap = new LemmaAndPos("cat", "NOUN");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, sleepLap, catLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(sleepLap)).thenReturn(Optional.of(600));
        Mockito.when(mockEvpCatalog.getCocaRank(catLap)).thenReturn(Optional.of(300));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // Act — partOfSpeech="VERB" filter must exclude "cat" (NOUN)
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.of("VERB"), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — all returned lemmas are VERBs; "cat" must not be present
        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertFalse(lemmas.isEmpty(), "F-INCEXP-R006: result must not be empty");
        lemmas.forEach(l -> Assertions.assertEquals("VERB", l.getPos(),
                "F-INCEXP-R006: all lemmas must be VERB when partOfSpeech=VERB; got pos=" + l.getPos()));
        boolean catPresent = lemmas.stream().anyMatch(l -> "cat".equals(l.getLemma()));
        Assertions.assertFalse(catPresent,
                "F-INCEXP-R006: NOUN 'cat' must not appear when partOfSpeech=VERB filter is applied");
    }

    @Test
    @DisplayName("should truncate the widened ordered universe to at most the requested limit dropping already-exposed lemmas first when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R007")
    public void shouldTruncateTheWidenedOrderedUniverseToAtMostTheRequestedLimitDroppingAlreadyexposedLemmasFirstWhenIncludeExposedIsTrue() {
        // Arrange — Critical regression scenario: "run" and "walk" are COMPLETELY_ABSENT and also
        // present in the EVP catalog at A1. "jump" and "eat" are EVP lemmas that are already-exposed
        // (not in the absent list). limit=3, which is >= needs-exposure count (2) but < total (4).
        //
        // With the old buggy implementation (ON lost COMPLETELY_ABSENT lemmas from EVP by classifying
        // them as already-exposed), both "run" and "walk" could end up in the already-exposed tail,
        // and limit=3 would drop one of them. The fix guarantees the needs-exposure block (= OFF output)
        // is preserved intact; limit only trims already-exposed entries from the tail.
        //
        // F-INCEXP-R007: limit truncates from the already-exposed tail first; no needs-exposure lemma
        // is ever dropped as long as limit >= needs-exposure count.
        String quizId = "quiz-incexp-r007";

        AbsentLemma run  = buildAbsentLemma("run",  "VERB", 200);
        AbsentLemma walk = buildAbsentLemma("walk", "VERB", 400);
        LemmaAndPos runLap  = new LemmaAndPos("run",  "VERB");
        LemmaAndPos walkLap = new LemmaAndPos("walk", "VERB");
        // Milestone label "A1" (exact CefrLevel name) for LevelWideLemmaInventory lookup.
        // LemmaCountLevelDiagnosis marks "run" and "walk" as sub-exposed; "jump" and "eat" are not
        // in the sub-exposed list → already-exposed. Reproduces COMPLETELY_ABSENT-in-EVP scenario.
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r007", "A1", null),
                buildMilestoneDiagnosesWithLemmaCount(CefrLevel.A1, List.of(run, walk),
                        List.of(runLap, walkLap)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);

        // Two exposed lemmas in EVP: jump@300 (lower COCA, kept by limit) and eat@900 (higher, dropped)
        LemmaAndPos jumpLap = new LemmaAndPos("jump", "VERB");
        LemmaAndPos eatLap  = new LemmaAndPos("eat",  "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, walkLap, jumpLap, eatLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(walkLap)).thenReturn(Optional.of(400));
        Mockito.when(mockEvpCatalog.getCocaRank(jumpLap)).thenReturn(Optional.of(300));
        Mockito.when(mockEvpCatalog.getCocaRank(eatLap)).thenReturn(Optional.of(900));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // Act — limit=3, includeExposed=true; 4 candidates total (2 needs-exposure + 2 exposed)
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.of(3), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — exactly 3 returned; ALL needs-exposure lemmas kept; only already-exposed trimmed
        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        List<String> names = lemmas.stream().map(SuggestedLemma::getLemma).toList();

        Assertions.assertEquals(3, lemmas.size(),
                "F-INCEXP-R007: limit=3 must truncate the result to 3 lemmas. Got: " + names);

        // No needs-exposure lemma must be lost (this is the key regression guard)
        Assertions.assertTrue(names.contains("run"),
                "F-INCEXP-R007: COMPLETELY_ABSENT needs-exposure lemma 'run' must NOT be dropped by limit");
        Assertions.assertTrue(names.contains("walk"),
                "F-INCEXP-R007: COMPLETELY_ABSENT needs-exposure lemma 'walk' must NOT be dropped by limit");

        // The limit drops from the already-exposed tail; "eat" (highest COCA, already-exposed) must go
        Assertions.assertFalse(names.contains("eat"),
                "F-INCEXP-R007: already-exposed 'eat' (highest COCA) must be dropped by limit first");

        // The kept already-exposed entry ("jump", coca=300) must have isUnderexposed=false
        lemmas.stream()
                .filter(l -> "jump".equals(l.getLemma()))
                .forEach(l -> Assertions.assertEquals(Boolean.FALSE, l.getIsUnderexposed(),
                        "F-INCEXP-R007: kept already-exposed lemma 'jump' must have isUnderexposed=false"));
    }

    @Test
    @DisplayName("should infer level from the task and honor explicit level the same way as the default query when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R008")
    public void shouldInferLevelFromTheTaskAndHonorExplicitLevelTheSameWayAsTheDefaultQueryWhenIncludeExposedIsTrue() {
        // Arrange — task with no LemmaAbsence diagnosis (cannot infer level).
        // Explicit level B1 is passed in the criteria. With includeExposed=true,
        // the port must still honor the explicit level (B1), not throw.
        String quizId = "quiz-incexp-r008";

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r008", "Milestone", null),
                buildMilestoneDiagnosesNoLevel(),   // no level inferable
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos learnLap = new LemmaAndPos("learn", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.B1)).thenReturn(Set.of(learnLap));
        Mockito.when(mockEvpCatalog.getCocaRank(learnLap)).thenReturn(Optional.of(500));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // Act — explicit level B1, includeExposed=true
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.of(CefrLevel.B1), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — result uses B1 (the explicit level) without error
        Assertions.assertEquals(CefrLevel.B1, result.getCefrLevel(),
                "F-INCEXP-R008: explicit level B1 must be honored when includeExposed=true");
        Assertions.assertFalse(result.getSuggestedLemmas().isEmpty(),
                "F-INCEXP-R008: must return the B1 EVP lemma 'learn'");
    }

    @Test
    @DisplayName("should return an empty lemma list with a functional explanation and no error when no lemma of the requested level and partOfSpeech exists even with includeExposed true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R009")
    public void shouldReturnAnEmptyLemmaListWithAFunctionalExplanationAndNoErrorWhenNoLemmaOfTheRequestedLevelAndPartOfSpeechExistsEvenWithIncludeExposedTrue() {
        // Arrange — EVP catalog returns an empty set for A1 (no lemmas at all for this level).
        // With includeExposed=true, the result must still be an empty list, not an error.
        String quizId = "quiz-incexp-r009";

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r009", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of()),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        // EVP returns empty for A1
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1)).thenReturn(Set.of());

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // Act — no exception must be thrown
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — empty list returned, no exception, level is still reported
        Assertions.assertNotNull(result,
                "F-INCEXP-R009: result must not be null even when no lemmas are found");
        Assertions.assertTrue(result.getSuggestedLemmas().isEmpty(),
                "F-INCEXP-R009: result must be an empty list when no lemma is applicable");
        Assertions.assertEquals(CefrLevel.A1, result.getCefrLevel(),
                "F-INCEXP-R009: effective level must still be reported");
    }

    @Test
    @DisplayName("should return all available lemmas without error when fewer than the requested limit match the filters with includeExposed true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R010")
    public void shouldReturnAllAvailableLemmasWithoutErrorWhenFewerThanTheRequestedLimitMatchTheFiltersWithIncludeExposedTrue() {
        // Arrange — EVP catalog returns only 1 lemma for A1 VERB; limit=10 requested.
        // F-INCEXP-R010: partial list (1 < 10) is not an error.
        String quizId = "quiz-incexp-r010";

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r010", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of()),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos runLap = new LemmaAndPos("run", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1)).thenReturn(Set.of(runLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        // Act — request 10 but only 1 available; no exception expected
        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.of(10), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — 1 lemma returned, no error, no exception
        Assertions.assertNotNull(result, "F-INCEXP-R010: result must not be null");
        Assertions.assertEquals(1, result.getSuggestedLemmas().size(),
                "F-INCEXP-R010: all available lemmas (1) must be returned without error even though limit=10");
    }

    @Test
    @DisplayName("should preserve the observable shape of each suggested lemma and populate the exposure fields for an already-exposed lemma with isUnderexposed false when includeExposed is true")
    @Tag("FEAT-INCEXP")
    @Tag("F-INCEXP-R011")
    public void shouldPreserveTheObservableShapeOfEachSuggestedLemmaAndPopulateTheExposureFieldsForAnAlreadyexposedLemmaWithIsUnderexposedFalseWhenIncludeExposedIsTrue() {
        // Arrange — "run" is underexposed (in absent list); "sleep" is already-exposed (only in EVP).
        // F-INCEXP-R011: for an already-exposed lemma, isUnderexposed=false must be set,
        // and the lemma must be identifiable (non-null lemma string and pos).
        String quizId = "quiz-incexp-r011";

        AbsentLemma run = buildAbsentLemma("run", "VERB", 200);
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-incexp-r011", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(run)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        EvpCatalogPort mockEvpCatalog = Mockito.mock(EvpCatalogPort.class);
        LemmaCountConfig mockLemmaCountConfig = Mockito.mock(LemmaCountConfig.class);
        Mockito.when(mockLemmaCountConfig.getThreshold()).thenReturn(5);
        LemmaAndPos runLap   = new LemmaAndPos("run",   "VERB");
        LemmaAndPos sleepLap = new LemmaAndPos("sleep", "VERB");
        Mockito.when(mockEvpCatalog.getExpectedLemmas(CefrLevel.A1))
                .thenReturn(Set.of(runLap, sleepLap));
        Mockito.when(mockEvpCatalog.getCocaRank(runLap)).thenReturn(Optional.of(200));
        Mockito.when(mockEvpCatalog.getCocaRank(sleepLap)).thenReturn(Optional.of(600));

        LemmaAbsenceContextSuggestedLemmaQueryPort sutWithLevelWide =
                buildSutWithLevelWide(mockEvpCatalog, mockLemmaCountConfig);

        SuggestedLemmaQueryCriteria criteria = new SuggestedLemmaQueryCriteria(
                Optional.empty(), Optional.empty(), Optional.empty(), true);
        SuggestedLemmaQueryResult result = sutWithLevelWide.query(report, task, criteria);

        // Assert — find the already-exposed lemma "sleep" and verify isUnderexposed=false
        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertTrue(lemmas.size() >= 2,
                "F-INCEXP-R011: must have at least 2 lemmas (run + sleep)");

        // Each lemma is identifiable
        lemmas.forEach(l -> {
            Assertions.assertNotNull(l.getLemma(),
                    "F-INCEXP-R011: each lemma must have a non-null lemma string");
            Assertions.assertNotNull(l.getPos(),
                    "F-INCEXP-R011: each lemma must have a non-null pos");
        });

        // "sleep" is already-exposed: isUnderexposed must be false
        SuggestedLemma sleepLemma = lemmas.stream()
                .filter(l -> "sleep".equals(l.getLemma()))
                .findFirst()
                .orElseThrow(() -> new AssertionError(
                        "F-INCEXP-R011: 'sleep' (already-exposed) must be present in result"));
        Assertions.assertEquals(Boolean.FALSE, sleepLemma.getIsUnderexposed(),
                "F-INCEXP-R011: already-exposed lemma 'sleep' must have isUnderexposed=false");
    }
}
