package com.learney.contentaudit.refinerdomain.lemmasuggestion;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableKnowledge;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.AuditableTopic;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryRejectedException;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryResult;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;
import java.util.stream.IntStream;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaAbsenceContextSuggestedLemmaQueryPortTest {

    @SuppressWarnings("unchecked")
    private CorrectionContextResolver<LemmaAbsenceCorrectionContext> resolver =
            Mockito.mock(CorrectionContextResolver.class);

    private LemmaAbsenceContextSuggestedLemmaQueryPort sut;

    @BeforeEach
    void setUp() {
        sut = new LemmaAbsenceContextSuggestedLemmaQueryPort(resolver);
    }

    // ------------------------------------------------------------------
    // Tree builder helpers (same pattern as LemmaAbsenceContextResolverTest)
    // ------------------------------------------------------------------

    private AuditNode buildCourseNode() {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.COURSE);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        return node;
    }

    private AuditNode buildMilestoneNode(AuditNode parent, AuditableMilestone milestone,
            DefaultLevelDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.MILESTONE);
        node.setEntity(milestone);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildTopicNode(AuditNode parent, AuditableTopic topic) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.TOPIC);
        node.setEntity(topic);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildKnowledgeNode(AuditNode parent, AuditableKnowledge knowledge) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.KNOWLEDGE);
        node.setEntity(knowledge);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildQuizNode(AuditNode parent, AuditableQuiz quiz,
            DefaultQuizDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setEntity(quiz);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    /** Builds COURSE → MILESTONE → TOPIC → KNOWLEDGE → QUIZ tree. */
    private AuditReport buildReport(AuditableMilestone milestone, DefaultLevelDiagnoses milestoneDiagnoses,
            AuditableQuiz quiz, DefaultQuizDiagnoses quizDiagnoses) {
        AuditNode courseNode = buildCourseNode();
        AuditNode milestoneNode = buildMilestoneNode(courseNode, milestone, milestoneDiagnoses);
        AuditNode topicNode = buildTopicNode(milestoneNode,
                new AuditableTopic(List.of(), "topic-1", "Topic", null));
        AuditNode knowledgeNode = buildKnowledgeNode(topicNode,
                new AuditableKnowledge(List.of(), "Knowledge", "Instructions", true, "know-1", null, null));
        buildQuizNode(knowledgeNode, quiz, quizDiagnoses);
        return new AuditReport(courseNode);
    }

    private RefinementTask buildLemmaAbsenceTask(String quizId) {
        return new RefinementTask(
                "task-sq-1",
                AuditTarget.QUIZ,
                quizId,
                "Quiz label",
                DiagnosisKind.LEMMA_ABSENCE,
                1,
                RefinementTaskStatus.PENDING);
    }

    private AuditableQuiz buildQuiz(String id) {
        return new AuditableQuiz(List.of(), id, null, null,
                "El gato duerme.", List.of("The cat sleeps."), null);
    }

    private DefaultLevelDiagnoses buildMilestoneDiagnoses(CefrLevel level, List<AbsentLemma> absentLemmas) {
        LemmaAbsenceLevelDiagnosis absenceDiagnosis = new LemmaAbsenceLevelDiagnosis(
                level, 100, absentLemmas.size(), 10.0, 90.0,
                0.8, 0.7, 0.5, null, absentLemmas, List.of(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.HIGH).count(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.MEDIUM).count(),
                (int) absentLemmas.stream().filter(l -> l.getPriorityLevel() == PriorityLevel.LOW).count());
        DefaultLevelDiagnoses diagnoses = new DefaultLevelDiagnoses();
        diagnoses.setLemmaAbsenceDiagnosis(absenceDiagnosis);
        return diagnoses;
    }

    /** Milestone with no LemmaAbsence diagnosis — level cannot be inferred. */
    private DefaultLevelDiagnoses buildMilestoneDiagnosesNoLevel() {
        return new DefaultLevelDiagnoses();
    }

    private AbsentLemma buildAbsentLemma(String lemma, String pos, int cocaRank) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, pos),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                List.of(),
                PriorityLevel.HIGH,
                cocaRank,
                null);
    }

    private AbsentLemma buildAbsentLemmaWithPos(String lemma, String pos, int cocaRank,
            PriorityLevel priority) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, pos),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                List.of(),
                priority,
                cocaRank,
                null);
    }

    // ------------------------------------------------------------------
    // Tests
    // ------------------------------------------------------------------

    @Test
    @DisplayName("should return the suggested lemmas of the task identified by taskId when invoked through the SuggestedLemmaQueryPort")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R001")
    public void shouldReturnTheSuggestedLemmasOfTheTaskIdentifiedByTaskIdWhenInvokedThroughTheSuggestedLemmaQueryPort(
            ) {
        String quizId = "quiz-r001";
        AbsentLemma absentLemma = buildAbsentLemma("sleep", "VERB", 500);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r001", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(absentLemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        Assertions.assertNotNull(result);
        Assertions.assertEquals("task-sq-1", result.getTaskId());
        Assertions.assertFalse(result.getSuggestedLemmas().isEmpty());
    }

    @Test
    @DisplayName("should include only suggested lemmas whose CefrLevel matches the level applied to the task")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R003")
    public void shouldIncludeOnlySuggestedLemmasWhoseCefrLevelMatchesTheLevelAppliedToTheTask() {
        String quizId = "quiz-r003";
        AbsentLemma a1Lemma = buildAbsentLemma("run", "VERB", 200);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r003", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(a1Lemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        Assertions.assertEquals(CefrLevel.A1, result.getCefrLevel());
        Assertions.assertFalse(result.getSuggestedLemmas().isEmpty());
    }

    @Test
    @DisplayName("should infer the CefrLevel from the task milestone ancestor when no explicit level is provided")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R004")
    public void shouldInferTheCefrLevelFromTheTaskMilestoneAncestorWhenNoExplicitLevelIsProvided() {
        String quizId = "quiz-r004";
        AbsentLemma absentLemma = buildAbsentLemma("walk", "VERB", 300);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r004", "B1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.B1, List.of(absentLemma)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        // The level inferred from the milestone ancestor must be B1 (not provided explicitly)
        Assertions.assertEquals(CefrLevel.B1, result.getCefrLevel());
    }

    @Test
    @DisplayName("should throw SuggestedLemmaQueryRejectedException when no level is provided and none can be inferred from the task")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R005")
    public void shouldThrowSuggestedLemmaQueryRejectedExceptionWhenNoLevelIsProvidedAndNoneCanBeInferredFromTheTask(
            ) {
        String quizId = "quiz-r005";

        // Milestone has no LemmaAbsence diagnosis — level cannot be inferred
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r005", "Unknown Level Milestone", null),
                buildMilestoneDiagnosesNoLevel(),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        Assertions.assertThrows(SuggestedLemmaQueryRejectedException.class, () ->
                sut.query(report, task, Optional.empty(), Optional.empty(), Optional.empty()));
    }

    @Test
    @DisplayName("should use the explicit level provided in the filter when the task does not allow level inference")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R006")
    public void shouldUseTheExplicitLevelProvidedInTheFilterWhenTheTaskDoesNotAllowLevelInference(
            ) {
        String quizId = "quiz-r006";

        // Milestone has no LemmaAbsence diagnosis — inference not possible
        // Caller provides explicit level A2
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r006", "Milestone", null),
                buildMilestoneDiagnosesNoLevel(),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.of(CefrLevel.A2));

        Assertions.assertEquals(CefrLevel.A2, result.getCefrLevel());
    }

    @Test
    @DisplayName("should restrict results to suggested lemmas whose partOfSpeech matches the requested partOfSpeech filter")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R007")
    public void shouldRestrictResultsToSuggestedLemmasWhosePartOfSpeechMatchesTheRequestedPartOfSpeechFilter(
            ) {
        String quizId = "quiz-r007";
        AbsentLemma verb1 = buildAbsentLemma("run", "VERB", 200);
        AbsentLemma noun1 = buildAbsentLemma("cat", "NOUN", 300);
        AbsentLemma verb2 = buildAbsentLemma("jump", "VERB", 400);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r007", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(verb1, noun1, verb2)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.of("VERB"), Optional.empty());

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertFalse(lemmas.isEmpty());
        lemmas.forEach(l -> Assertions.assertEquals("VERB", l.getPos()));
    }

    @Test
    @DisplayName("should return at most N suggested lemmas when the limit filter equals N")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R008")
    public void shouldReturnAtMostNSuggestedLemmasWhenTheLimitFilterEqualsN() {
        String quizId = "quiz-r008";
        List<AbsentLemma> manyLemmas = List.of(
                buildAbsentLemma("run", "VERB", 100),
                buildAbsentLemma("walk", "VERB", 200),
                buildAbsentLemma("eat", "VERB", 300),
                buildAbsentLemma("sleep", "VERB", 400),
                buildAbsentLemma("talk", "VERB", 500));

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r008", "A2 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A2, manyLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        int limit = 3;
        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.of(limit), Optional.empty(), Optional.empty());

        Assertions.assertTrue(result.getSuggestedLemmas().size() <= limit);
        Assertions.assertEquals(limit, result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return all available suggested lemmas without error when fewer than the requested limit match the filters")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R009")
    public void shouldReturnAllAvailableSuggestedLemmasWithoutErrorWhenFewerThanTheRequestedLimitMatchTheFilters(
            ) {
        String quizId = "quiz-r009";
        // Only 2 absent lemmas available
        List<AbsentLemma> twoLemmas = List.of(
                buildAbsentLemma("run", "VERB", 100),
                buildAbsentLemma("walk", "VERB", 200));

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r009", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, twoLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // Request 10 but only 2 are available
        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.of(10), Optional.empty(), Optional.empty());

        // No exception thrown; returns the 2 available
        Assertions.assertEquals(2, result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return suggested lemmas ordered by recommendation priority so the caller does not need to sort them")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R010")
    public void shouldReturnSuggestedLemmasOrderedByRecommendationPrioritySoTheCallerDoesNotNeedToSortThem(
            ) {
        String quizId = "quiz-r010";
        // Lower cocaRank = higher frequency = higher priority in recommendation
        AbsentLemma highFrequency  = buildAbsentLemmaWithPos("run",  "VERB", 100, PriorityLevel.HIGH);
        AbsentLemma midFrequency   = buildAbsentLemmaWithPos("walk", "VERB", 500, PriorityLevel.HIGH);
        AbsentLemma lowFrequency   = buildAbsentLemmaWithPos("amble","VERB", 900, PriorityLevel.MEDIUM);

        // Provide lemmas out of priority order so we can verify the port sorts them
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r010", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(lowFrequency, highFrequency, midFrequency)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(3, lemmas.size());
        // Verify ordering: the first result should have a lower or equal cocaRank than the last
        Integer firstCocaRank = lemmas.get(0).getCocaRank();
        Integer lastCocaRank  = lemmas.get(lemmas.size() - 1).getCocaRank();
        Assertions.assertTrue(firstCocaRank <= lastCocaRank,
                "Results must be ordered by priority (ascending cocaRank): first=" + firstCocaRank + " last=" + lastCocaRank);
    }

    @Test
    @DisplayName("should return more suggested lemmas than the cap of 10 used by LemmaAbsenceContextResolver when the requested limit exceeds it")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R011")
    public void shouldReturnMoreSuggestedLemmasThanTheCapOf10UsedByLemmaAbsenceContextResolverWhenTheRequestedLimitExceedsIt(
            ) {
        String quizId = "quiz-r011";
        // 12 absent lemmas in the milestone diagnosis — more than the static cap of 10
        List<AbsentLemma> twelveLemmas = IntStream.rangeClosed(1, 12)
                .mapToObj(i -> buildAbsentLemma("lemma" + i, "NOUN", i * 100))
                .toList();

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r011", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, twelveLemmas),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        // Request 12 — must get 12 (not capped at 10)
        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.of(12), Optional.empty(), Optional.empty());

        Assertions.assertTrue(result.getSuggestedLemmas().size() > 10,
                "Port must return more than the resolver's static cap of 10; got: " + result.getSuggestedLemmas().size());
    }

    @Test
    @DisplayName("should return an empty suggested lemma list with the effective level when the task has no compatible base for suggesting lemmas")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R012")
    public void shouldReturnAnEmptySuggestedLemmaListWithTheEffectiveLevelWhenTheTaskHasNoCompatibleBaseForSuggestingLemmas(
            ) {
        String quizId = "quiz-r012";

        // Milestone has a LemmaAbsence diagnosis with an empty absent-lemma list
        // (level is inferable but there is no base for suggestions)
        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r012", "B1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.B1, List.of()),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        Assertions.assertNotNull(result);
        Assertions.assertTrue(result.getSuggestedLemmas().isEmpty());
        // The effective level must still be reported for traceability
        Assertions.assertEquals(CefrLevel.B1, result.getCefrLevel());
    }

    @Test
    @DisplayName("should expose each suggested lemma identifiably in the result with the list order representing its relative priority")
    @Tag("FEAT-CSLATDC")
    @Tag("F-CSLATDC-R014")
    public void shouldExposeEachSuggestedLemmaIdentifiablyInTheResultWithTheListOrderRepresentingItsRelativePriority(
            ) {
        String quizId = "quiz-r014";
        AbsentLemma first  = buildAbsentLemma("run",  "VERB", 100);
        AbsentLemma second = buildAbsentLemma("walk", "VERB", 200);

        AuditReport report = buildReport(
                new AuditableMilestone(List.of(), "ms-r014", "A1 Milestone", null),
                buildMilestoneDiagnoses(CefrLevel.A1, List.of(first, second)),
                buildQuiz(quizId),
                new DefaultQuizDiagnoses());
        RefinementTask task = buildLemmaAbsenceTask(quizId);

        SuggestedLemmaQueryResult result = sut.query(
                report, task, Optional.empty(), Optional.empty(), Optional.empty());

        List<SuggestedLemma> lemmas = result.getSuggestedLemmas();
        Assertions.assertEquals(2, lemmas.size());

        // Each lemma is individually identifiable (non-null lemma string)
        lemmas.forEach(l -> Assertions.assertNotNull(l.getLemma()));
        // List order represents relative priority: position 0 is higher priority than position 1
        Assertions.assertNotEquals(lemmas.get(0).getLemma(), lemmas.get(1).getLemma());
    }
}
