package com.learney.contentaudit.auditdomain.quizinstruction;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface QuizInstructionComplianceChecker {
    QuizInstructionComplianceResult check(QuizInstructionSubjectView view);

    QuizInstructionComplianceResult revalidate(QuizInstructionSubjectView view);
}
