package com.learney.contentaudit.auditdomain.quizinstruction;

import com.learney.contentaudit.auditdomain.QuizInstructionVerdictReader;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationBudget;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSessionFactory;
import com.learney.contentaudit.evaluationledgerdomain.Evaluator;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface QuizInstructionComplianceCheckerFactory {
    QuizInstructionComplianceChecker create(EvaluationSessionFactory sessionFactory,
            Evaluator evaluator, QuizInstructionVerdictReader verdictReader,
            EvaluationBudget budget);
}
