package com.learney.contentaudit.revisioninfrastructure.quizinstructionagent;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionGeneratorResponse;
import com.sentinel.agents.framework.state.ArtifactPointer;
import com.sentinel.agents.framework.state.RunState;
import com.sentinel.agents.framework.state.RunStatus;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Handwritten test for {@link DefaultQuizInstructionAgentCandidateParser}.
 *
 * Strategy: mirrors the artifact-backed RunState fixture already used by
 * {@code QuizInstructionAgentJudgeTest} (quiz-instruction-infrastructure) — a real temp file
 * referenced by an {@link ArtifactPointer}, since {@code .sentinel/agents/quiz-instruction-corrector}'s
 * emit node declares {@code correctionCandidate} as a file-backed artifact
 * ({@code completion.produces: [{kind: correctionCandidate, pointer: "{run_dir}/correctionCandidate.json"}]}),
 * not a value living directly in RunState.data(). The JSON shape mirrors what
 * {@code scripts/emit.sh} of that same graph writes: the champion candidate together with what it did
 * NOT meet ({@code unmetCriteria}, F-QICOR-R014) and how many attempts the corrector's own loop spent
 * reaching it ({@code attempts}, F-QICOR-R012).
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultQuizInstructionAgentCandidateParserTest {

    private static final String CANDIDATE_WITH_UNMET_CRITERIA_JSON = """
            {
              "generated": true,
              "quizSentence": "He ____ [goes] to school every day.",
              "translation": "El va a la escuela todos los dias.",
              "rationale": "Se corrigio la concordancia sujeto-verbo que la violacion señalaba.",
              "reason": "",
              "unmetCriteria": [
                { "criterion": "LEVEL_VOCABULARY", "outcome": "FAILED", "detail": "Introduce 'perambulate', ausente en el original y mal ubicado para A1" },
                { "criterion": "DISTINCTNESS", "outcome": "NOT_EVALUABLE", "detail": "No se pudo comparar contra los ejercicios hermanos" }
              ],
              "lengthMeasurement": { "tokens": 7, "targetMin": 4, "targetMax": 9, "inRange": true, "measured": true },
              "attempts": 2,
              "allCriteriaMet": false
            }
            """;

    private RunState runStateWithCandidateArtifact(String candidateJson) throws IOException {
        Path artifactFile = Files.createTempFile("correction-candidate", ".json");
        artifactFile.toFile().deleteOnExit();
        Files.writeString(artifactFile, candidateJson);
        ArtifactPointer pointer = new ArtifactPointer(
                "correctionCandidate",
                "correctionCandidate",
                artifactFile,
                Instant.now(),
                "emit",
                "test-content-hash");
        return RunState.empty()
                .withRunStatus(RunStatus.COMPLETED)
                .putArtifact("correctionCandidate", pointer);
    }

    @Test
    @DisplayName("should read back the verdicts the correction measured for the candidate it hands over and how many attempts it spent")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R012")
    public void shouldReadBackTheVerdictsTheCorrectionMeasuredForTheCandidateItHandsOverAndHowManyAttemptsItSpent(
            ) throws IOException {
        DefaultQuizInstructionAgentCandidateParser parser = new DefaultQuizInstructionAgentCandidateParser();
        RunState runState = runStateWithCandidateArtifact(CANDIDATE_WITH_UNMET_CRITERIA_JSON);

        QuizInstructionGeneratorResponse response = parser.parse(runState, "quiz-node-001");

        // F-QICOR-R012: "el sistema no vuelve a pedir un candidato desde cero... lo que recibe es el
        // resultado del lazo, no cada uno de sus pasos" — the verdicts and the attempt count must be
        // READ BACK from what the correction's own loop reported, not recomputed or defaulted.
        assertEquals(2, response.getAttempts(),
                "the attempts the corrector's own loop spent reaching its champion must be read back "
                        + "verbatim, not recomputed or defaulted to 0/1");
        assertEquals(2, response.getVerdicts().size(),
                "every criterion the champion did not meet must reach the response — not a subset and "
                        + "not silently dropped");
        assertTrue(response.getVerdicts().contains(new CriterionVerdict(CorrectionCriterion.LEVEL_VOCABULARY,
                        CriterionOutcome.FAILED,
                        "Introduce 'perambulate', ausente en el original y mal ubicado para A1")),
                "expected the LEVEL_VOCABULARY FAILED verdict with its own reason to be read back "
                        + "verbatim: " + response.getVerdicts());
        assertTrue(response.getVerdicts().contains(new CriterionVerdict(CorrectionCriterion.DISTINCTNESS,
                        CriterionOutcome.NOT_EVALUABLE,
                        "No se pudo comparar contra los ejercicios hermanos")),
                "expected the DISTINCTNESS NOT_EVALUABLE verdict to be read back distinguished from "
                        + "FAILED (F-QICOR-R014 (e)): " + response.getVerdicts());
    }
}
