package com.learney.contentaudit.revisioninfrastructure.quizinstructionagent;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyMap;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.quizinstruction.InstructionSeverity;
import com.learney.contentaudit.auditdomain.quizinstruction.InstructionViolation;
import com.learney.contentaudit.refinerdomain.QuizInstructionCorrectionContext;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionGenerationRequest;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionGeneratorResponse;
import com.learney.contentaudit.revisioninfrastructure.lagen.LagenConfig;
import com.sentinel.agents.framework.state.RunState;
import com.sentinel.agents.framework.state.RunStatus;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Handwritten test for {@link QuizInstructionAgentGenerator}.
 *
 * Strategy: mirrors the approach used for other agent-runtime adapters in this module (see
 * LemmaAbsenceAgentGeneratorTest / AgentCandidateJudgmentEvaluatorTest) — Mockito doubles for the
 * package-private collaborators (QuizInstructionAgentRuntimeLauncher, QuizInstructionAgentCandidateParser,
 * QuizInstructionAgentErrorClassifier) without importing dev.langchain4j.model.chat.ChatModel directly
 * (version conflict between the explicit langchain4j-core dep and the transitive one pulled by
 * sentinel-agents). {@code null} is passed for the ChatModel constructor arg because the fake launcher
 * never invokes it.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class QuizInstructionAgentGeneratorTest {

    private QuizInstructionCorrectionContext validContext() {
        return new QuizInstructionCorrectionContext(
                "task-001", "quiz-node-001",
                "He ____ [go|goes] to school.", "El va a la escuela.",
                "He go to school.", "Present Simple", "Escribe la forma afirmativa",
                "Verbs", CefrLevel.A1, "A1", null,
                List.of(new InstructionViolation("AGREEMENT", "El verbo debe concordar con el sujeto",
                        "go", "El sujeto es de tercera persona singular")),
                "No cumple: 1 violacion", InstructionSeverity.MAJOR, List.of(), "audit-001", "plan-001");
    }

    private LagenConfig lagenConfig() {
        return new LagenConfig(
                "test-provider", "test-model", "http://localhost:1234/v1", null, null, null, null, null, 3);
    }

    @Test
    @DisplayName("should pass the attempt limit it was given to the agent that drives the correction loop, instead of looping on its own")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R012")
    public void shouldPassTheAttemptLimitItWasGivenToTheAgentThatDrivesTheCorrectionLoopInsteadOfLoopingOnItsOwn(
            ) {
        // Arrange
        RunState successState = RunState.empty().withRunStatus(RunStatus.COMPLETED);

        AtomicReference<Map<String, String>> capturedInputs = new AtomicReference<>();
        QuizInstructionAgentRuntimeLauncher launcher = mock(QuizInstructionAgentRuntimeLauncher.class);
        when(launcher.launch(anyString(), anyMap(), any()))
                .thenAnswer(invocation -> {
                    @SuppressWarnings("unchecked")
                    Map<String, String> inputs = invocation.getArgument(1);
                    capturedInputs.set(inputs);
                    return successState;
                });

        QuizInstructionGeneratorResponse fixedResponse = new QuizInstructionGeneratorResponse(
                "He ____ [goes] to school.", "El va a la escuela.",
                "Corregida la concordancia sujeto-verbo que la violacion señalaba.", List.of(), 1);
        QuizInstructionAgentCandidateParser parser = mock(QuizInstructionAgentCandidateParser.class);
        when(parser.parse(any(), anyString())).thenReturn(fixedResponse);

        QuizInstructionAgentErrorClassifier classifier = mock(QuizInstructionAgentErrorClassifier.class);

        QuizInstructionAgentGenerator generator = new QuizInstructionAgentGenerator(
                launcher, parser, classifier, null, lagenConfig(), Path.of("/placeholder/project"));

        // A maximum of 9 attempts is a property of THIS run (F-QICOR-R012) — distinct from the
        // unrelated LagenConfig.maxEvalRetries (3) used elsewhere for plain LLM-call knobs, and
        // chosen so it cannot coincidentally appear anywhere else in the fixture data below.
        QuizInstructionGenerationRequest request = new QuizInstructionGenerationRequest(validContext(), 9);

        // Act
        generator.generate(request);

        // Assert — F-QICOR-R012: "el sistema no vuelve a pedir un candidato desde cero... el lazo, el
        // champion y la decision de reintentar viven del lado de quien corrige". The generator must
        // launch the agent graph exactly once (no external retry loop of its own) and must hand the
        // configured attempt limit INWARD, under the "maxAttempts" input the quiz-instruction-corrector
        // graph itself declares as a dependency — not consume it in a loop outside the agent.
        verify(launcher, times(1)).launch(anyString(), anyMap(), any());
        Map<String, String> inputs = capturedInputs.get();
        assertNotNull(inputs, "launch() must have been called and the inputs map must not be null");
        assertEquals("9", inputs.get("maxAttempts"),
                "expected the maxAttempts value (9) the request carried to reach the agent's own "
                        + "'maxAttempts' input verbatim: " + inputs);
    }
}
