package com.learney.contentaudit.auditdomain.finding;

import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class Finding {
    private String analyzer;

    private String rule;

    private FindingNodeRef node;

    private FindingSeverity severity;

    private FindingEvidence evidence;

    private FindingResolution resolution;

    private AnalysisCost cost;

    private FindingIdentity identity;

    public Finding() {
    }

    public Finding(String analyzer, String rule, FindingNodeRef node, FindingSeverity severity,
            FindingEvidence evidence, FindingResolution resolution, AnalysisCost cost,
            FindingIdentity identity) {
        this.analyzer = analyzer;
        this.rule = rule;
        this.node = node;
        this.severity = severity;
        this.evidence = evidence;
        this.resolution = resolution;
        this.cost = cost;
        this.identity = identity;
    }

    public String getAnalyzer() {
        return this.analyzer;
    }

    public void setAnalyzer(String analyzer) {
        this.analyzer = analyzer;
    }

    public String getRule() {
        return this.rule;
    }

    public void setRule(String rule) {
        this.rule = rule;
    }

    public FindingNodeRef getNode() {
        return this.node;
    }

    public void setNode(FindingNodeRef node) {
        this.node = node;
    }

    public FindingSeverity getSeverity() {
        return this.severity;
    }

    public void setSeverity(FindingSeverity severity) {
        this.severity = severity;
    }

    public FindingEvidence getEvidence() {
        return this.evidence;
    }

    public void setEvidence(FindingEvidence evidence) {
        this.evidence = evidence;
    }

    public FindingResolution getResolution() {
        return this.resolution;
    }

    public void setResolution(FindingResolution resolution) {
        this.resolution = resolution;
    }

    public AnalysisCost getCost() {
        return this.cost;
    }

    public void setCost(AnalysisCost cost) {
        this.cost = cost;
    }

    public FindingIdentity getIdentity() {
        return this.identity;
    }

    public void setIdentity(FindingIdentity identity) {
        this.identity = identity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Finding that = (Finding) o;
        return Objects.equals(this.analyzer, that.analyzer)
                    && Objects.equals(this.rule, that.rule)
                    && Objects.equals(this.node, that.node)
                    && Objects.equals(this.severity, that.severity)
                    && Objects.equals(this.evidence, that.evidence)
                    && Objects.equals(this.resolution, that.resolution)
                    && Objects.equals(this.cost, that.cost)
                    && Objects.equals(this.identity, that.identity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(analyzer, rule, node, severity, evidence, resolution, cost, identity);
    }
}
