package com.learney.contentaudit.revisioninfrastructure.candidatejudgment;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyMap;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisioninfrastructure.lagen.LagenConfig;
import com.sentinel.agents.framework.state.RunState;
import com.sentinel.agents.framework.state.RunStatus;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Handwritten tests for {@link AgentCandidateJudgmentEvaluator}.
 *
 * Strategy: mirrors the approach used for other agent-runtime adapters in this module
 * (see LemmaAbsenceAgentGeneratorTest) — Mockito doubles for the package-private
 * collaborators (CandidateJudgmentRuntimeLauncher, CandidateJudgmentVerdictParser)
 * without importing dev.langchain4j.model.chat.ChatModel directly (version conflict
 * between the explicit langchain4j-core dep and the transitive one pulled by
 * sentinel-agents). {@code null} is passed for the ChatModel constructor arg because
 * the fake launcher never invokes it.
 *
 * The real judgment (whether a translation is faithful, whether a candidate is still
 * solvable) happens inside the agent prompt, not in this Java class — its only job is
 * to launch the agent and surface whatever verdict the parser produced, without
 * collapsing distinct outcomes (F-QICOR-R004: NOT_EVALUABLE is not FAILED).
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class AgentCandidateJudgmentEvaluatorTest {

    // ------------------------------------------------------------------
    // Fixture helpers
    // ------------------------------------------------------------------

    /**
     * Builds a QuizTemplateEntity whose sentence parts include a scaffolding cue —
     * e.g. "(eat)" — inside a TEXT part: shown to the student as a hint but not part
     * of the finished, graded sentence.
     */
    private static QuizTemplateEntity quizTemplate(String id, String translation,
            List<SentencePartEntity> sentenceParts, List<String> sentences) {
        FormEntity form = new FormEntity("CLOZE", 1.0, "", "", sentenceParts);
        return new QuizTemplateEntity(
                id, id, "CLOZE", "knowledge-1", "Present Perfect", "Complete with present perfect",
                translation, "1.1.theory", "Verb Tenses", form, 0.0, 0.0, 0.0, "", "", "", "", "", "", "",
                sentences);
    }

    private static CourseElementSnapshot quizSnapshot(String quizId, String translation,
            List<SentencePartEntity> sentenceParts, List<String> sentences) {
        return new CourseElementSnapshot(
                AuditTarget.QUIZ, quizId, quizTemplate(quizId, translation, sentenceParts, sentences), null);
    }

    private static LagenConfig lagenConfig() {
        return new LagenConfig(
                "test-provider", "test-model", "http://localhost:1234/v1", null, null, null, null, null, 3);
    }

    private static CandidateAssessmentInput assessmentInput(
            CourseElementSnapshot original, CourseElementSnapshot candidate) {
        return new CandidateAssessmentInput(
                "quiz-1", "audit-1", original, candidate, CefrLevel.B1, "Verb Tenses",
                "Present Perfect", "Complete with present perfect", "B1",
                SentenceMode.FILL, List.of(), List.of("have eaten breakfast already"));
    }

    // ------------------------------------------------------------------
    // Tests
    // ------------------------------------------------------------------

    @Test
    @DisplayName("should fail a candidate whose Spanish translation does not faithfully render the corrected sentence")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldFailACandidateWhoseSpanishTranslationDoesNotFaithfullyRenderTheCorrectedSentence(
            ) {
        CourseElementSnapshot original = quizSnapshot("quiz-1", "Ya he desayunado.",
                List.of(
                        new SentencePartEntity(SentencePartKind.TEXT, "I ", null),
                        new SentencePartEntity(SentencePartKind.CLOZE, null, List.of("have eaten", "'ve eaten")),
                        new SentencePartEntity(SentencePartKind.TEXT, " (eat) breakfast already.", null)),
                List.of("I have eaten breakfast already."));
        // The candidate corrects the sentence but its Spanish translation was left stale,
        // now describing a present-tense habit instead of the corrected sentence.
        CourseElementSnapshot candidate = quizSnapshot("quiz-1", "Como desayuno todos los dias.",
                List.of(
                        new SentencePartEntity(SentencePartKind.TEXT, "I ", null),
                        new SentencePartEntity(SentencePartKind.CLOZE, null, List.of("have already eaten")),
                        new SentencePartEntity(SentencePartKind.TEXT, " (eat) breakfast.", null)),
                List.of("I have already eaten breakfast."));
        CandidateAssessmentInput input = assessmentInput(original, candidate);

        CandidateJudgmentRuntimeLauncher launcher = mock(CandidateJudgmentRuntimeLauncher.class);
        RunState runState = RunState.empty().withRunStatus(RunStatus.COMPLETED);
        when(launcher.launch(anyString(), anyMap(), any())).thenReturn(runState);

        CandidateJudgmentVerdictParser verdictParser = mock(CandidateJudgmentVerdictParser.class);
        CriterionVerdict failedVerdict = new CriterionVerdict(CorrectionCriterion.FAITHFUL_TRANSLATION,
                CriterionOutcome.FAILED,
                "La traduccion 'Como desayuno todos los dias.' no refleja la oracion corregida "
                        + "'I have already eaten breakfast.'");
        when(verdictParser.parse(runState, CorrectionCriterion.FAITHFUL_TRANSLATION)).thenReturn(failedVerdict);

        AgentCandidateJudgmentEvaluator sut = new AgentCandidateJudgmentEvaluator(
                CorrectionCriterion.FAITHFUL_TRANSLATION, launcher, verdictParser, null, lagenConfig());

        CriterionVerdict result = sut.evaluate(input);

        verify(launcher).launch(anyString(), anyMap(), any());
        verify(verdictParser).parse(runState, CorrectionCriterion.FAITHFUL_TRANSLATION);
        assertEquals(failedVerdict, result,
                "R004 criterio 4: un candidato cuya traduccion no es fiel a la oracion corregida debe reprobar, "
                        + "no proponerse como si cumpliera");
        assertEquals(CriterionOutcome.FAILED, result.getOutcome());
    }

    @Test
    @DisplayName("should fail a candidate that stopped being solvable by the student or that changed the exercise kind of the original")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldFailACandidateThatStoppedBeingSolvableByTheStudentOrThatChangedTheExerciseKindOfTheOriginal(
            ) {
        CourseElementSnapshot original = quizSnapshot("quiz-2", "Ya he desayunado.",
                List.of(
                        new SentencePartEntity(SentencePartKind.TEXT, "I ", null),
                        new SentencePartEntity(SentencePartKind.CLOZE, null, List.of("have eaten", "'ve eaten")),
                        new SentencePartEntity(SentencePartKind.TEXT, " (eat) breakfast already.", null)),
                List.of("I have eaten breakfast already."));
        // The candidate "resolves" the instruction violation by removing the gap entirely:
        // there is nothing left for the student to solve, and the exercise kind changed
        // from a fill-in-the-blank CLOZE to a plain, non-solvable statement.
        CourseElementSnapshot candidate = quizSnapshot("quiz-2", "Ya he desayunado.",
                List.of(new SentencePartEntity(SentencePartKind.TEXT, "I have already eaten breakfast.", null)),
                List.of("I have already eaten breakfast."));
        CandidateAssessmentInput input = assessmentInput(original, candidate);

        CandidateJudgmentRuntimeLauncher launcher = mock(CandidateJudgmentRuntimeLauncher.class);
        RunState runState = RunState.empty().withRunStatus(RunStatus.COMPLETED);
        when(launcher.launch(anyString(), anyMap(), any())).thenReturn(runState);

        CandidateJudgmentVerdictParser verdictParser = mock(CandidateJudgmentVerdictParser.class);
        CriterionVerdict failedVerdict = new CriterionVerdict(CorrectionCriterion.SOLVABLE_SAME_KIND,
                CriterionOutcome.FAILED,
                "El candidato no tiene ningun hueco que el alumno deba completar: dejo de ser un ejercicio "
                        + "CLOZE resoluble");
        when(verdictParser.parse(runState, CorrectionCriterion.SOLVABLE_SAME_KIND)).thenReturn(failedVerdict);

        AgentCandidateJudgmentEvaluator sut = new AgentCandidateJudgmentEvaluator(
                CorrectionCriterion.SOLVABLE_SAME_KIND, launcher, verdictParser, null, lagenConfig());

        CriterionVerdict result = sut.evaluate(input);

        verify(launcher).launch(anyString(), anyMap(), any());
        verify(verdictParser).parse(runState, CorrectionCriterion.SOLVABLE_SAME_KIND);
        assertEquals(failedVerdict, result,
                "R004 criterio 5: un candidato que deja de ser resoluble o cambia de tipo de ejercicio debe "
                        + "reprobar");
        assertEquals(CriterionOutcome.FAILED, result.getOutcome());
    }

    @Test
    @DisplayName("should not return a passing verdict when the judgment could not be obtained")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldNotReturnAPassingVerdictWhenTheJudgmentCouldNotBeObtained() {
        CourseElementSnapshot original = quizSnapshot("quiz-3", "Ya he desayunado.",
                List.of(
                        new SentencePartEntity(SentencePartKind.TEXT, "I ", null),
                        new SentencePartEntity(SentencePartKind.CLOZE, null, List.of("have eaten", "'ve eaten")),
                        new SentencePartEntity(SentencePartKind.TEXT, " (eat) breakfast already.", null)),
                List.of("I have eaten breakfast already."));
        CourseElementSnapshot candidate = quizSnapshot("quiz-3", "Ya he desayunado.",
                List.of(
                        new SentencePartEntity(SentencePartKind.TEXT, "I ", null),
                        new SentencePartEntity(SentencePartKind.CLOZE, null, List.of("have already eaten")),
                        new SentencePartEntity(SentencePartKind.TEXT, " (eat) breakfast.", null)),
                List.of("I have already eaten breakfast."));
        CandidateAssessmentInput input = assessmentInput(original, candidate);

        CandidateJudgmentRuntimeLauncher launcher = mock(CandidateJudgmentRuntimeLauncher.class);
        RunState runState = RunState.empty().withRunStatus(RunStatus.COMPLETED);
        when(launcher.launch(anyString(), anyMap(), any())).thenReturn(runState);

        // The judge answered, but its output could not be turned into a usable verdict:
        // an infrastructure failure, not a finding about the candidate.
        CandidateJudgmentVerdictParser verdictParser = mock(CandidateJudgmentVerdictParser.class);
        CriterionVerdict notEvaluableVerdict = new CriterionVerdict(CorrectionCriterion.FAITHFUL_TRANSLATION,
                CriterionOutcome.NOT_EVALUABLE,
                "La respuesta del juez no se pudo interpretar como un veredicto usable");
        when(verdictParser.parse(runState, CorrectionCriterion.FAITHFUL_TRANSLATION)).thenReturn(notEvaluableVerdict);

        AgentCandidateJudgmentEvaluator sut = new AgentCandidateJudgmentEvaluator(
                CorrectionCriterion.FAITHFUL_TRANSLATION, launcher, verdictParser, null, lagenConfig());

        CriterionVerdict result = sut.evaluate(input);

        assertEquals(CriterionOutcome.NOT_EVALUABLE, result.getOutcome(),
                "R004: cuando el juicio no se pudo obtener, el desenlace es NOT_EVALUABLE, no PASSED ni FAILED "
                        + "— una falla de infraestructura no afirma que el candidato empeoro algo");
        assertNotEquals(CriterionOutcome.PASSED, result.getOutcome());
        assertNotEquals(CriterionOutcome.FAILED, result.getOutcome(),
                "R004: no reprobar por una falla del juez — reprobar afirma algo sobre el candidato que aqui no "
                        + "se afirmo, y descartaria un candidato que podria ser bueno");
    }
}
