package com.learney.contentaudit.agentruntimeinfrastructure.graphexecution;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentDefinitionLocator;

import com.learney.contentaudit.agentruntimeinfrastructure.AgentDefinitionFound;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentDefinitionLocation;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentDefinitionUnresolved;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentGraphRunner;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentGraphRunnerConfig;
import com.sentinel.agents.framework.definition.Node;
import com.sentinel.agents.framework.loader.AgentLoader;
import com.sentinel.agents.framework.persistence.RunPersistence;
import com.sentinel.agents.framework.runner.AgentRun;
import com.sentinel.agents.framework.runner.ExecutionContext;
import com.sentinel.agents.framework.runner.NodeRunners;
import com.sentinel.agents.framework.state.RunState;
import dev.langchain4j.model.chat.ChatModel;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import javax.annotation.processing.Generated;

/**
 * Consolidated in-process sentinel-agents runtime launcher. Absorbs the two
 * previously-duplicated launchers that lived in revision-infrastructure
 * (lemmaabsenceagent.DefaultAgentRuntimeLauncher and
 * knowledgetitleagent.DefaultKnowledgeTitleAgentRuntimeLauncher): same
 * algorithm (AgentLoader.loadFromDirectory, AgentRun.runRecording,
 * RunPersistence, run-id format, {@code run_dir} enrichment), unified base-dir
 * resolution.
 *
 * <p><strong>{@code runsBaseDir} resolution:</strong> a three-step chain that is
 * the union — not the intersection — of the two original behaviors, so every
 * existing caller keeps getting exactly the paths it got before:
 * <ol>
 *   <li>{@link AgentGraphRunnerConfig}'s explicit value, when set;</li>
 *   <li>else {@code inputs["project_root"]}, when present and non-blank
 *       (this was knowledge-title's original — and only — resolution);</li>
 *   <li>else the CWD (this was lemma-absence's original — and only —
 *       resolution; it never populates {@code project_root}, so it falls
 *       through to this step exactly as before).</li>
 * </ol>
 *
 * <p><strong>Agent definition directory resolution:</strong> delegated
 * entirely to the injected {@link AgentDefinitionLocator} — the same instance
 * built alongside this runner from the same {@link AgentGraphRunnerConfig} —
 * so the directory this runner loads the graph from and the directory a
 * consumer (e.g. a judge version resolver) digests are the same by
 * construction, never two independently-resolved paths that could diverge.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultAgentGraphRunner implements AgentGraphRunner {

    private static final String RUNS_BASE_DIR = ".sentinel/runs";

    private static final DateTimeFormatter RUN_ID_FMT =
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss").withZone(ZoneOffset.UTC);

    private final AgentGraphRunnerConfig config;

private final AgentDefinitionLocator agentDefinitionLocator;

public DefaultAgentGraphRunner(AgentGraphRunnerConfig config, AgentDefinitionLocator agentDefinitionLocator) {
    this.config = config;
    this.agentDefinitionLocator = agentDefinitionLocator;
}

    @Override
    public RunState run(String agentName, Map<String, String> inputs, ChatModel chatModel,
            Map<String, Object> tools) {
        Path runsBase = resolveBaseDir(
                config != null ? config.getRunsBaseDir() : null, RUNS_BASE_DIR, inputs);

        Path agentDir = resolveAgentDir(agentName, inputs);
        Node entryNode = AgentLoader.loadFromDirectory(agentDir);

        String runId = RUN_ID_FMT.format(Instant.now()) + "-" + UUID.randomUUID().toString().substring(0, 8);
        Path runDir = runsBase.resolve(agentName).resolve(runId).toAbsolutePath();

        RunPersistence persistence = new RunPersistence(
                runDir, runId, agentName, "", null, Map.of());

        Map<String, String> enriched = new LinkedHashMap<>(inputs != null ? inputs : Collections.emptyMap());
        enriched.put("run_dir", runDir.toString());

        ExecutionContext ctx = new ExecutionContext(
                chatModel,
                tools != null ? tools : Collections.emptyMap(),
                Collections.emptyMap(),   // gates  — handled declaratively in the graph
                Collections.emptyMap(),   // scripts — handled declaratively in the graph
                runDir,                   // workDir = run-dir so graph scripts resolve artifacts by abs path
                new NodeRunners());       // default dispatcher (no custom runners)

        RunState state;
        try {
            // Stream both observability channels live to the run log: framework
            // events AND the llm_request/llm_response roundtrip transcripts. The
            // roundtrips never enter RunState, so a plain AgentRun.run + a
            // post-hoc writeEvents(state) would lose every transcript — only
            // this live sink captures them. The ChatModel must carry a
            // FrameworkLlmListener (wired by each caller's own factory).
            state = AgentRun.runRecording(
                    entryNode, enriched, ctx,
                    (event, stateAfter) -> persistence.appendFrameworkEvent(event),
                    persistence::appendEvent);
        } catch (RuntimeException e) {
            persistence.finish("failed", Map.of(
                    "halted", true,
                    "haltReason", String.valueOf(e.getMessage())));
            throw e;
        }
        persistence.writeState(state);
        boolean halted = state.runStatus().name().equals("HALTED");
        persistence.finish(halted ? "failed" : "completed", RunPersistence.outcomeOf(state));
        return state;
    }

    /**
     * Mirrors the union of the two original consumers at the locator boundary:
     * knowledge-title-agent populates {@code inputs["project_root"]}, so its
     * runs resolve {@code locateUnderProjectRoot}; lemma-absence-agent never
     * does, so its runs resolve plain {@code locate} (config, else CWD).
     */
    private Path resolveAgentDir(String agentName, Map<String, String> inputs) {
        String projectRoot = inputs != null ? inputs.get("project_root") : null;
        AgentDefinitionLocation location = (projectRoot != null && !projectRoot.isBlank())
                ? agentDefinitionLocator.locateUnderProjectRoot(projectRoot, agentName)
                : agentDefinitionLocator.locate(agentName);

        if (location instanceof AgentDefinitionFound found) {
            return found.getDirectory();
        }
        if (location instanceof AgentDefinitionUnresolved unresolved) {
            throw new IllegalStateException(
                    "No se encontro la definicion del agente '" + unresolved.getAgentName()
                            + "' buscada en " + unresolved.getSearchedIn());
        }
        throw new IllegalStateException("AgentDefinitionLocation desconocido: " + location);
    }

    private static Path resolveBaseDir(Path configured, String defaultRelative, Map<String, String> inputs) {
        if (configured != null) {
            return configured;
        }
        Path projectRoot = resolveProjectRoot(inputs);
        if (projectRoot != null) {
            return projectRoot.resolve(defaultRelative);
        }
        return Paths.get(defaultRelative);
    }

    private static Path resolveProjectRoot(Map<String, String> inputs) {
        if (inputs != null) {
            String projectRoot = inputs.get("project_root");
            if (projectRoot != null && !projectRoot.isBlank()) {
                return Paths.get(projectRoot);
            }
        }
        return null;
    }
}
