package com.learney.contentaudit.auditdomain.quizinstructionengine;

import com.learney.contentaudit.auditdomain.QuizInstructionConfig;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionVerdict;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultQuizInstructionScorer implements QuizInstructionScorer {
    private final QuizInstructionConfig config;

    public DefaultQuizInstructionScorer(QuizInstructionConfig config) {
        this.config = config;
    }

    @Override
    public double score(QuizInstructionVerdict verdict) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
