package com.learney.contentaudit.auditdomain.quizinstructionengine;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionSubjectView;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSubject;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface QuizInstructionSubjectBuilder {
    EvaluationSubject build(AuditNode quizNode);

    EvaluationSubject buildFromView(QuizInstructionSubjectView view);
}
