package com.learney.contentaudit.auditcli.commands;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessment;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateLengthMeasurement;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisiondomain.quizinstruction.CandidateAssessmentUnavailableException;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionCandidateAssessor;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
public class AssessCandidateCmdTest {

    @Mock
    QuizInstructionCandidateAssessor candidateAssessor;

    AssessCandidateCmd cmd;

    @BeforeEach
    void setUp() {
        cmd = new AssessCandidateCmd(candidateAssessor);
    }

    @Test
    @DisplayName("should return one verdict per criterion of the catalog for the candidate consulted, with its reason when the verdict is negative")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R015")
    public void shouldReturnOneVerdictPerCriterionOfTheCatalogForTheCandidateConsultedWithItsReasonWhenTheVerdictIsNegative(
            ) {
        String planId = "plan-1";
        String taskId = "task-qi-1";
        String candidateSentence = "He ____ [goes] to school.";
        String candidateTranslation = "El va a la escuela.";
        String coursePath = "/placeholder/course";

        // One verdict per catalog criterion — all eight — one of them negative with its own reason,
        // exactly what F-QICOR-R015(a) requires the consultation to hand back.
        List<CriterionVerdict> verdicts = List.of(
                new CriterionVerdict(CorrectionCriterion.SCOPED_EDIT, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.LENGTH_IN_RANGE, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.LEVEL_VOCABULARY, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.DISTINCTNESS, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.FAITHFUL_TRANSLATION, CriterionOutcome.FAILED,
                        "La traduccion sigue diciendo lo que decia la oracion anterior"),
                new CriterionVerdict(CorrectionCriterion.SOLVABLE_SAME_KIND, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.INSTRUCTION_COMPLIANCE, CriterionOutcome.PASSED, ""),
                new CriterionVerdict(CorrectionCriterion.REAL_WORLD_SENSE, CriterionOutcome.PASSED, ""));
        CandidateLengthMeasurement lengthMeasurement = new CandidateLengthMeasurement(8, 6, 10, true, true);
        CandidateAssessment assessment = new CandidateAssessment(verdicts, true, true, 5,
                List.of(verdicts.get(4)), lengthMeasurement, "some-rank-key");
        when(candidateAssessor.assessTask(eq(planId), eq(taskId), any(Path.class), eq(candidateSentence),
                eq(candidateTranslation))).thenReturn(assessment);

        ByteArrayOutputStream outBuf = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outBuf));
        int exit;
        try {
            exit = cmd.assessCandidate(planId, taskId, candidateSentence, candidateTranslation, coursePath,
                    "text");
        } finally {
            System.setOut(originalOut);
        }

        assertEquals(0, exit);
        String output = outBuf.toString();
        for (CorrectionCriterion criterion : CorrectionCriterion.values()) {
            assertTrue(output.contains(criterion.name()),
                    "Expected every catalog criterion in the consult output, missing " + criterion.name()
                            + ": " + output);
        }
        assertTrue(output.contains("La traduccion sigue diciendo lo que decia la oracion anterior"),
                "Expected the reason of the negative FAITHFUL_TRANSLATION verdict in the output: " + output);
    }

    @Test
    @DisplayName("should report the consultation as failed with a non-zero exit status, instead of printing verdicts, when the candidate could not be assessed")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R015")
    public void shouldReportTheConsultationAsFailedWithANonzeroExitStatusInsteadOfPrintingVerdictsWhenTheCandidateCouldNotBeAssessed(
            ) {
        String planId = "plan-1";
        String taskId = "task-qi-1";
        String candidateSentence = "He ____ [goes] to school.";
        String candidateTranslation = "El va a la escuela.";
        String coursePath = "/placeholder/course";

        // The seam could not even reach a verdict — infrastructure failed to resolve the plan, the
        // task, its context or its original, not a candidate that was judged and reproached
        when(candidateAssessor.assessTask(eq(planId), eq(taskId), any(Path.class), eq(candidateSentence),
                eq(candidateTranslation)))
                .thenThrow(new CandidateAssessmentUnavailableException(taskId, "el plan no existe"));

        ByteArrayOutputStream outBuf = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outBuf));
        int exit;
        try {
            exit = cmd.assessCandidate(planId, taskId, candidateSentence, candidateTranslation, coursePath,
                    "text");
        } finally {
            System.setOut(originalOut);
        }

        assertNotEquals(0, exit);
        String output = outBuf.toString();
        for (CorrectionCriterion criterion : CorrectionCriterion.values()) {
            assertFalse(output.contains(criterion.name()),
                    "Expected no verdict to be printed when the candidate could not be assessed, but found "
                            + criterion.name() + " in: " + output);
        }
    }
}
