package com.learney.contentaudit.auditcli.commands;

import com.learney.contentaudit.auditdomain.ActiveAnalysisSelection;
import com.learney.contentaudit.auditdomain.ActiveAnalysisSelectionStore;
import com.learney.contentaudit.auditcli.formatting.ConsolidatedViewFormatter;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedView;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewAvailability;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewBuilder;
import com.learney.contentaudit.revisiondomain.consolidatedview.NodeImpact;
import com.learney.contentaudit.revisiondomain.consolidatedview.StatisticImpact;
import com.learney.contentaudit.auditdomain.AuditTarget;
import java.nio.file.Path;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@ExtendWith(MockitoExtension.class)
@Tag("F-CDIFF")
@Tag("F-CDIFF-J006")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FCdiffJ006JourneyTest {

    @Mock private ConsolidatedViewBuilder consolidatedViewBuilder;
    @Mock private ConsolidatedViewFormatter formatter;
    @Mock private ActiveAnalysisSelectionStore activeAnalysisSelectionStore;

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: Existe un analisis A con pendientes e... → El consumidor pide la estructura cons... → El consumidor invoca la operacion del... → El consumidor pide la estructura cons... → success")
    public void path1_success() {
        // situacion_inicial: existe analisis A con pendientes, analisis B es el activo
        // pedir_salida_b: el consolidado de B (sin pendientes dormidas de A)
        StatisticImpact statB = new StatisticImpact(
                AuditTarget.COURSE, "course-001", "lemma-absence",
                0.70, 0.80, 0.10, null, null);
        ConsolidatedView viewB = new ConsolidatedView(
                "audit-B", "plan-B",
                ConsolidatedViewAvailability.AVAILABLE, null,
                null, List.of(), List.of(statB), List.of());
        // Gate R001, R017: activeAuditId=B, solo propuestas del plan de B
        when(consolidatedViewBuilder.build(any(Path.class)))
                .thenReturn(viewB)
                // pedir_salida_a (segunda llamada): consolidado de A con pendientes dormidas
                .thenReturn(buildViewA());
        when(formatter.format(any(), any())).thenReturn("{}");

        DefaultGetConsolidatedCommand getCommand = new DefaultGetConsolidatedCommand(consolidatedViewBuilder, formatter);
        DefaultSetActiveAnalysisCommand setCommand = new DefaultSetActiveAnalysisCommand(activeAnalysisSelectionStore);

        // Paso 1: pedir_salida_b — Gate R001, R017
        getCommand.getConsolidated("/course", "json");
        verify(formatter).format(eq(viewB), any());

        // Paso 2: cambiar_activo_a_a — Gate R002 (no destructivo: solo modifica store activo)
        setCommand.setActive("audit-A", "plan-A");
        ArgumentCaptor<ActiveAnalysisSelection> captor = ArgumentCaptor.forClass(ActiveAnalysisSelection.class);
        verify(activeAnalysisSelectionStore).write(captor.capture());
        assertEquals("audit-A", captor.getValue().getAuditId(), "El store activo debe apuntar a audit-A");
        assertEquals("plan-A", captor.getValue().getPlanId(), "El store activo debe apuntar a plan-A");

        // Paso 3: pedir_salida_a — Gate R001, R004, R006, R009: las pendientes dormidas de A aparecen
        getCommand.getConsolidated("/course", "json");
        // El formatter fue llamado dos veces en total: una para B y otra para A
        verify(formatter, times(2)).format(any(ConsolidatedView.class), any());
    }

    private ConsolidatedView buildViewA() {
        // A tiene pendientes dormidas: statisticImpact con pendingDelta no nulo
        StatisticImpact statA = new StatisticImpact(
                AuditTarget.COURSE, "course-001", "lemma-absence",
                0.65, 0.65, 0.0,
                0.78, 0.13);
        return new ConsolidatedView(
                "audit-A", "plan-A",
                ConsolidatedViewAvailability.AVAILABLE, null,
                null, List.of(), List.of(statA), List.of());
    }
}
