package com.learney.contentaudit.auditcli.commands;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditcli.formatting.ConsolidatedViewFormatter;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedView;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewAvailability;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewBuilder;
import com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange;
import com.learney.contentaudit.revisiondomain.consolidatedview.NodeImpact;
import com.learney.contentaudit.auditdomain.AuditTarget;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
@Tag("F-CDIFF")
@Tag("F-CDIFF-J006")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FCdiffJ006JourneyTest {

    @Mock private ConsolidatedViewBuilder consolidatedViewBuilder;
    @Mock private ConsolidatedViewFormatter formatter;

    private static final String COURSE_PATH = "/courses/english";

    // ─────────────────────────────────────────────────────────────────────────
    // Helper: build ConsolidatedView fixtures
    // ─────────────────────────────────────────────────────────────────────────

    private ConsolidatedView availableViewFor(String auditId, String planId,
            List<NodeImpact> nodeImpacts) {
        return new ConsolidatedView(auditId, planId,
                ConsolidatedViewAvailability.AVAILABLE, null,
                Instant.now(), nodeImpacts, Collections.emptyList());
    }

    private NodeImpact nodeImpact(String nodeId, FieldChange fc,
            List<String> acceptedIds, List<String> pendingIds) {
        return new NodeImpact(AuditTarget.QUIZ, nodeId, acceptedIds,
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc), pendingIds);
    }

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: Existe un analisis A con pendientes e... → El consumidor pide la estructura cons... → El consumidor invoca la operacion del... → El consumidor pide la estructura cons... → success")
    public void path1_success() {
        // situacion_inicial: Analisis B es el activo; A es viejo con pendientes dormidas.
        // El consumidor tiene dos pares distintos: B y A.

        // pedir_salida_b: Gate R001, R017
        // El consolidado del par activo B se construye sin incluir pendientes de A.
        ConsolidatedView viewB = availableViewFor("audit-B", "plan-B", Collections.emptyList());
        String outputB = "{\"activeAuditId\":\"audit-B\",\"activePlanId\":\"plan-B\",\"availability\":\"AVAILABLE\"}";
        when(consolidatedViewBuilder.build(any(Path.class))).thenReturn(viewB);
        when(formatter.format(eq(viewB), any())).thenReturn(outputB);

        DefaultGetConsolidatedCommand command = new DefaultGetConsolidatedCommand(
                consolidatedViewBuilder, formatter);
        Integer exitB = command.getConsolidated(COURSE_PATH, "json");

        // Gate R001: activeAuditId y activePlanId de B aparecen en la salida formateada
        assertEquals(0, exitB, "El comando debe retornar exit code 0 para B (R001)");
        assertTrue(outputB.contains("audit-B"),
                "activeAuditId de B debe aparecer en la salida (R001)");
        // Gate R017: el consolidado de B solo usa propuestas del plan-B
        assertFalse(outputB.contains("plan-A"),
                "La salida de B NO debe incluir references al plan de A (R017)");

        // cambiar_activo_a_a: Gate R002
        // El operador cambia el par activo a A. La operacion set-active no destruye nada.
        // (El DefaultSetActiveAnalysisCommand se testa en DefaultSetActiveAnalysisCommandTest;
        //  aqui verificamos el cambio observable via el siguiente build.)
        // Simulamos el cambio: el proximo build() retorna la vista de A con sus pendientes dormidas.

        // pedir_salida_a: Gate R001, R004, R006, R007
        // Ahora el consolidado es el de A; sus pendientes dormidas aparecen.
        FieldChange tokenCountChange = new FieldChange(8, 8, 10); // pendiente mueve de 8 a 10
        NodeImpact quizAfectado = nodeImpact("quiz-dormida",
                tokenCountChange,
                Collections.emptyList(), // sin aceptadas (son del plan de A, no se ven en B)
                List.of("prop-dormida-A"));
        ConsolidatedView viewA = availableViewFor("audit-A", "plan-A",
                List.of(quizAfectado));
        String outputA = "{\"activeAuditId\":\"audit-A\",\"activePlanId\":\"plan-A\","
                + "\"pendingProposalIds\":[\"prop-dormida-A\"]}";

        // El builder ahora devuelve la vista de A (par activo cambiado)
        when(consolidatedViewBuilder.build(any(Path.class))).thenReturn(viewA);
        when(formatter.format(eq(viewA), any())).thenReturn(outputA);

        Integer exitA = command.getConsolidated(COURSE_PATH, "json");

        // Gate R001: activeAuditId de A aparece en la salida formateada
        assertEquals(0, exitA, "El comando debe retornar exit code 0 para A (R001)");
        assertTrue(outputA.contains("audit-A"),
                "activeAuditId de A debe aparecer en la salida (R001)");

        // Gate R004: las pendientes dormidas de A aparecen en la salida
        assertTrue(outputA.contains("prop-dormida-A"),
                "Las pendientes dormidas de A deben aparecer en la salida (R004)");

        // Gate R006, R007: el nodo afectado aparece con su tripleta
        NodeImpact ni = viewA.getNodeImpacts().get(0);
        assertEquals("quiz-dormida", ni.getNodeId(),
                "El nodo afectado por la pendiente dormida debe aparecer (R006)");
        FieldChange fc = ni.getFieldChanges().values().iterator().next();
        assertEquals(8, fc.getOriginal(), "original = 8 (baseline, R007.1)");
        assertEquals(8, fc.getConsolidated(), "consolidated = 8 (sin aceptadas, R007.2)");
        assertEquals(10, fc.getPendingProjection(), "pendingProjection = 10 (con pendiente, R007.3)");

        // El formatter fue invocado dos veces: una para B y una para A
        verify(formatter, times(2)).format(any(), any());
    }
}
