package com.learney.contentaudit.auditcli.commands;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableKnowledge;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.AuditableTopic;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.DefaultKnowledgeDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultTopicDiagnoses;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.LemmaPlacementDiagnosis;
import com.learney.contentaudit.auditdomain.labs.MisplacedLemma;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import com.learney.contentaudit.auditdomain.lemmacount.LemmaCountLevelDiagnosis;
import com.learney.contentaudit.auditdomain.lemmacount.LemmaCountStats;
import com.learney.contentaudit.auditdomain.lemmacount.LevelLemmaCountResult;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceContextResolver;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-SLEM")
@Tag("F-SLEM-J001")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FSlemJ001JourneyTest {

    // -------------------------------------------------------------------------
    // Tree-building helpers (mirrors LemmaAbsenceContextResolverTest pattern)
    // -------------------------------------------------------------------------

    private AuditNode buildCourseNode() {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.COURSE);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        return node;
    }

    private AuditNode buildMilestoneNode(AuditNode parent, AuditableMilestone milestone,
            DefaultLevelDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.MILESTONE);
        node.setEntity(milestone);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildTopicNode(AuditNode parent, AuditableTopic topic) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.TOPIC);
        node.setEntity(topic);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(new DefaultTopicDiagnoses());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildKnowledgeNode(AuditNode parent, AuditableKnowledge knowledge) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.KNOWLEDGE);
        node.setEntity(knowledge);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(new DefaultKnowledgeDiagnoses());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildQuizNode(AuditNode parent, AuditableQuiz quiz,
            DefaultQuizDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setEntity(quiz);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El cliente ejecuta AuditRunner.runDet... → La auditoría queda disponible para pl... → El cliente ejecuta PlanCommand.plan(a... [La auditoría incluyó lemma-count y diagnósticos LEMMA_ABSENCE] → Las tareas LEMMA_ABSENCE del plan exp... → success")
    public void path1_laAuditoraIncluyLemmacountYDiagnsticosLEMMAABSENCE_success() {
        // Journey J001 — path-1: audit with lemma-count + LEMMA_ABSENCE
        //
        // STEP 1: audit_course — the audit result carries both LEMMA_ABSENCE and lemma-count
        // diagnoses (gate: R001 — lemma-count signal is available)
        //
        // STEP 2: audit_has_lemma_count [La auditoría incluyó lemma-count y diagnósticos LEMMA_ABSENCE]
        // → plan_with_context (gate: R001, R002)
        //
        // STEP 3: assert_ranked_suggestions
        // (gate: R003, R004, R005, R006, R007, R013)

        // --- Step 1: Build AuditReport with lemma-count + LEMMA_ABSENCE ---
        // Milestone A1 has:
        //   - LemmaAbsenceLevelDiagnosis: 2 absent lemmas (APPEARS_TOO_LATE + COMPLETELY_ABSENT)
        //   - LemmaCountLevelDiagnosis: "cat" underexposed (count=1 < threshold=3)

        AuditableQuiz quiz = new AuditableQuiz(
                List.of(), "quiz-j001-p1", null, null,
                "El gato corre.", List.of("The cat runs."), null);
        AuditableKnowledge knowledge = new AuditableKnowledge(
                List.of(), "Animals", "Complete.", true, "know-j001-p1", null, null);
        AuditableTopic topic = new AuditableTopic(List.of(), "topic-j001-p1", "Nature", null);
        AuditableMilestone milestone = new AuditableMilestone(List.of(), "ms-j001-p1", "A1", null);

        // LEMMA_ABSENCE: "cat" APPEARS_TOO_LATE (underexposed at A1), "dog" COMPLETELY_ABSENT
        AbsentLemma absentCat = new AbsentLemma(
                new LemmaAndPos("cat", "NOUN"), CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE, List.of(), PriorityLevel.HIGH, 200, null);
        AbsentLemma absentDog = new AbsentLemma(
                new LemmaAndPos("dog", "NOUN"), CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT, List.of(), PriorityLevel.HIGH, 300, null);

        LemmaAbsenceLevelDiagnosis absenceDiag = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A1, 100, 2, 10.0, 90.0,
                0.8, 0.7, 0.5, null,
                List.of(absentCat, absentDog), List.of(), 2, 3, 5);

        // Lemma-count: "cat" count=1 < threshold=3 → underexposed
        LemmaCountStats catStats = new LemmaCountStats(
                new LemmaAndPos("cat", "NOUN"), 1, 0.33, Optional.of(CefrLevel.A1));
        LevelLemmaCountResult levelResult = new LevelLemmaCountResult(
                CefrLevel.A1, 0.33, 1, List.of(catStats));
        LemmaCountLevelDiagnosis lemmaCountDiag = new LemmaCountLevelDiagnosis(levelResult);

        DefaultLevelDiagnoses milestoneDiag = new DefaultLevelDiagnoses();
        milestoneDiag.setLemmaAbsenceDiagnosis(absenceDiag);
        milestoneDiag.setLemmaCountDiagnosis(lemmaCountDiag); // R001: lemma-count signal available

        MisplacedLemma ml = new MisplacedLemma(
                new LemmaAndPos("run", "VERB"), CefrLevel.A2, CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE, 400, null);
        DefaultQuizDiagnoses quizDiag = new DefaultQuizDiagnoses();
        quizDiag.setLemmaAbsenceDiagnosis(new LemmaPlacementDiagnosis(1, List.of(ml)));

        AuditNode courseNode = buildCourseNode();
        AuditNode milestoneNode = buildMilestoneNode(courseNode, milestone, milestoneDiag);
        AuditNode topicNode = buildTopicNode(milestoneNode, topic);
        AuditNode knowledgeNode = buildKnowledgeNode(topicNode, knowledge);
        buildQuizNode(knowledgeNode, quiz, quizDiag);

        AuditReport report = new AuditReport(courseNode);

        // --- Step 2: plan_with_context — resolve correctionContext (gate: R001, R002) ---
        LemmaAbsenceContextResolver resolver = new LemmaAbsenceContextResolver();
        RefinementTask task = new RefinementTask(
                "task-j001-p1", AuditTarget.QUIZ, "quiz-j001-p1",
                "Quiz label", DiagnosisKind.LEMMA_ABSENCE, 1, RefinementTaskStatus.PENDING);

        Optional<LemmaAbsenceCorrectionContext> ctx = resolver.resolve(report, task);

        // Gate R001: correctionContext is available (lemma-count signal was present in audit)
        assertTrue(ctx.isPresent(),
                "J001-path-1 gate R001: correctionContext must be resolvable when audit includes lemma-count");

        // Gate R002: suggestedLemmas carries lemma-count signal for underexposed lemmas
        List<SuggestedLemma> lemmas = ctx.get().getSuggestedLemmas();
        assertFalse(lemmas.isEmpty(),
                "J001-path-1 gate R002: suggestedLemmas must not be empty");

        // "cat" is APPEARS_TOO_LATE + underexposed → triple must be informed (R002)
        Optional<SuggestedLemma> catEntry = lemmas.stream()
                .filter(l -> "cat".equals(l.getLemma()))
                .findFirst();
        assertTrue(catEntry.isPresent(),
                "J001-path-1 gate R002: 'cat' (underexposed APPEARS_TOO_LATE) must be in suggestedLemmas");
        assertNotNull(catEntry.get().getLemmaCount(),
                "J001-path-1 gate R002: lemmaCount must be informed for underexposed 'cat'");
        assertNotNull(catEntry.get().getLemmaCountThreshold(),
                "J001-path-1 gate R002: lemmaCountThreshold must be informed for underexposed 'cat'");
        assertNotNull(catEntry.get().getIsUnderexposed(),
                "J001-path-1 gate R002: isUnderexposed must be informed for underexposed 'cat'");
        assertTrue(catEntry.get().getIsUnderexposed(),
                "J001-path-1 gate R002: 'cat' must be flagged as underexposed (count=1 < threshold=3)");

        // --- Step 3: assert_ranked_suggestions ---
        // Gate R003: underexposed APPEARS_TOO_LATE ("cat", group 1) must come before COMPLETELY_ABSENT ("dog", group 5)
        int catIndex = -1, dogIndex = -1;
        for (int i = 0; i < lemmas.size(); i++) {
            if ("cat".equals(lemmas.get(i).getLemma())) catIndex = i;
            if ("dog".equals(lemmas.get(i).getLemma())) dogIndex = i;
        }
        assertTrue(catIndex >= 0, "J001-path-1 gate R003: 'cat' must be in suggestedLemmas");
        assertTrue(dogIndex >= 0, "J001-path-1 gate R003: 'dog' must be in suggestedLemmas");
        assertTrue(catIndex < dogIndex,
                "J001-path-1 gate R003: underexposed 'cat' (group 1) must precede COMPLETELY_ABSENT 'dog' (group 5, last)");

        // Gate R007: "dog" (COMPLETELY_ABSENT) triple must be all null
        SuggestedLemma dogEntry = lemmas.get(dogIndex);
        assertNull(dogEntry.getLemmaCount(),
                "J001-path-1 gate R007: COMPLETELY_ABSENT 'dog' lemmaCount must be null");
        assertNull(dogEntry.getLemmaCountThreshold(),
                "J001-path-1 gate R007: COMPLETELY_ABSENT 'dog' lemmaCountThreshold must be null");
        assertNull(dogEntry.getIsUnderexposed(),
                "J001-path-1 gate R007: COMPLETELY_ABSENT 'dog' isUnderexposed must be null");

        // Gate R013: all elements are either all-informed or all-uninformed (no mixed state)
        for (SuggestedLemma sl : lemmas) {
            boolean allInformed = sl.getLemmaCount() != null
                    && sl.getLemmaCountThreshold() != null
                    && sl.getIsUnderexposed() != null;
            boolean allUninformed = sl.getLemmaCount() == null
                    && sl.getLemmaCountThreshold() == null
                    && sl.getIsUnderexposed() == null;
            assertTrue(allInformed || allUninformed,
                    "J001-path-1 gate R013: all-or-nothing triple violated for lemma: " + sl.getLemma());
        }
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El cliente ejecuta AuditRunner.runDet... → La auditoría queda disponible para pl... → El cliente ejecuta PlanCommand.plan(a... [La auditoría incluyó diagnósticos LEMMA_ABSENCE pero no incluyó lemma-count] → Las tareas LEMMA_ABSENCE conservan su... → success")
    public void path2_laAuditoraIncluyDiagnsticosLEMMAABSENCEPeroNoIncluyLemmacount_success() {
        // Journey J001 — path-2: audit with LEMMA_ABSENCE but WITHOUT lemma-count
        //
        // STEP 1: audit_course — audit result has LEMMA_ABSENCE but no lemma-count signal
        // STEP 2: audit_has_lemma_count [La auditoría incluyó LEMMA_ABSENCE pero NO lemma-count]
        // → plan_without_lemma_count_signal (gate: R012)
        // STEP 3: assert_suggestions_without_signal (gate: R013 — triple all null)

        // --- Step 1: Build AuditReport with LEMMA_ABSENCE but NO lemma-count signal ---
        AuditableQuiz quiz = new AuditableQuiz(
                List.of(), "quiz-j001-p2", null, null,
                "El perro ladra.", List.of("The dog barks."), null);
        AuditableKnowledge knowledge = new AuditableKnowledge(
                List.of(), "Animals", "Complete.", true, "know-j001-p2", null, null);
        AuditableTopic topic = new AuditableTopic(List.of(), "topic-j001-p2", "Nature", null);
        AuditableMilestone milestone = new AuditableMilestone(List.of(), "ms-j001-p2", "A1", null);

        AbsentLemma absentBark = new AbsentLemma(
                new LemmaAndPos("bark", "VERB"), CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT, List.of(), PriorityLevel.HIGH, 500, null);

        LemmaAbsenceLevelDiagnosis absenceDiag = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A1, 100, 1, 10.0, 90.0,
                0.8, 0.7, 0.5, null,
                List.of(absentBark), List.of(), 2, 3, 5);

        // NO lemma-count diagnosis set → signal unavailable
        DefaultLevelDiagnoses milestoneDiag = new DefaultLevelDiagnoses();
        milestoneDiag.setLemmaAbsenceDiagnosis(absenceDiag);
        // intentionally: milestoneDiag.setLemmaCountDiagnosis(...) NOT called

        MisplacedLemma ml = new MisplacedLemma(
                new LemmaAndPos("dog", "NOUN"), CefrLevel.A2, CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE, 300, null);
        DefaultQuizDiagnoses quizDiag = new DefaultQuizDiagnoses();
        quizDiag.setLemmaAbsenceDiagnosis(new LemmaPlacementDiagnosis(1, List.of(ml)));

        AuditNode courseNode = buildCourseNode();
        AuditNode milestoneNode = buildMilestoneNode(courseNode, milestone, milestoneDiag);
        AuditNode topicNode = buildTopicNode(milestoneNode, topic);
        AuditNode knowledgeNode = buildKnowledgeNode(topicNode, knowledge);
        buildQuizNode(knowledgeNode, quiz, quizDiag);

        AuditReport report = new AuditReport(courseNode);

        // --- Step 2: plan_without_lemma_count_signal — resolve correctionContext (gate: R012) ---
        LemmaAbsenceContextResolver resolver = new LemmaAbsenceContextResolver();
        RefinementTask task = new RefinementTask(
                "task-j001-p2", AuditTarget.QUIZ, "quiz-j001-p2",
                "Quiz label", DiagnosisKind.LEMMA_ABSENCE, 1, RefinementTaskStatus.PENDING);

        // Gate R012: must NOT throw even without lemma-count signal
        Optional<LemmaAbsenceCorrectionContext> ctx = resolver.resolve(report, task);
        assertTrue(ctx.isPresent(),
                "J001-path-2 gate R012: correctionContext must be returned even without lemma-count signal");

        List<SuggestedLemma> lemmas = ctx.get().getSuggestedLemmas();
        assertFalse(lemmas.isEmpty(),
                "J001-path-2 gate R012: suggestedLemmas must not be empty when LEMMA_ABSENCE is present");

        // --- Step 3: assert_suggestions_without_signal ---
        // Gate R013: when no lemma-count signal, all three triple values must be null for ALL elements
        for (SuggestedLemma sl : lemmas) {
            assertNull(sl.getLemmaCount(),
                    "J001-path-2 gate R013: lemmaCount must be null when no lemma-count signal (lemma: " + sl.getLemma() + ")");
            assertNull(sl.getLemmaCountThreshold(),
                    "J001-path-2 gate R013: lemmaCountThreshold must be null when no lemma-count signal (lemma: " + sl.getLemma() + ")");
            assertNull(sl.getIsUnderexposed(),
                    "J001-path-2 gate R013: isUnderexposed must be null when no lemma-count signal (lemma: " + sl.getLemma() + ")");
        }
    }
}
