package com.learney.contentaudit.auditcli.commands;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.revisiondomain.RevisionEngine;
import com.learney.contentaudit.revisiondomain.RevisionOutcome;
import com.learney.contentaudit.revisiondomain.RevisionOutcomeKind;
import java.nio.file.Path;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class RefinerReviseCmdTest {
    @Test
    @DisplayName("Given a RevisionEngine that returns APPROVED_APPLIED, when revise is invoked with planId and taskId, then it delegates to engine.revise and returns exit code 0")
    @Tag("FEAT-REVBYP")
    @Tag("F-REVBYP-R013")
    public void givenARevisionEngineThatReturnsAPPROVEDAPPLIEDWhenReviseIsInvokedWithPlanIdAndTaskIdThenItDelegatesToEnginereviseAndReturnsExitCode0(
            ) {
        // Arrange
        RevisionEngine revisionEngine = mock(RevisionEngine.class);
        RevisionOutcome approvedOutcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        when(revisionEngine.revise(eq("plan-001"), eq("task-001"), any(Path.class)))
                .thenReturn(approvedOutcome);

        RefinerReviseCmd cmd = new RefinerReviseCmd(revisionEngine);

        // Act
        int exitCode = cmd.revise("plan-001", "task-001");

        // Assert — R013: when proposal is approved and applied, task reaches DONE state;
        // the CLI exit code 0 signals successful completion to the operator.
        assertEquals(0, exitCode, "exit code must be 0 when engine returns APPROVED_APPLIED");
        verify(revisionEngine).revise(eq("plan-001"), eq("task-001"), any(Path.class));
    }
}
