package com.learney.contentaudit.auditcli.commands;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.*;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.revisiondomain.CorrectionContextSource;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionEngine;
import com.learney.contentaudit.revisiondomain.RevisionOutcome;
import com.learney.contentaudit.revisiondomain.RevisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
public class ReviseCmdTest {

    @Mock
    RevisionEngine revisionEngine;

    @Mock
    RefinementPlanStore refinementPlanStore;

    @InjectMocks
    ReviseCmd reviseCmd;

    /**
     * ReviseCmd has a picocli @Option for the course path (--course-path / CONTENT_AUDIT_CONTENT_FOLDER).
     * When this field is null and the env var is not set, ReviseCmd exits early with an error
     * before the business logic runs. We use reflection to set any null String field to a
     * placeholder path so the command can proceed past the course-path validation and exercise
     * the actual plan/task resolution logic under test.
     *
     * The path value itself does not matter for these unit tests because revisionEngine is mocked
     * and never actually reads the file system.
     */
    @BeforeEach
    void initPicocliOptionDefaults() throws Exception {
        for (Field f : reviseCmd.getClass().getDeclaredFields()) {
            f.setAccessible(true);
            if (f.getType() == String.class && f.get(reviseCmd) == null) {
                // Provide a non-blank placeholder so CoursePathResolver returns a value
                f.set(reviseCmd, "/placeholder/course");
            }
        }
    }

    // --- Helpers ---

    private RefinementTask task(String taskId) {
        return new RefinementTask(
                taskId,
                AuditTarget.QUIZ,
                "quiz-001",
                "Sample Quiz",
                DiagnosisKind.SENTENCE_LENGTH,
                1,
                RefinementTaskStatus.PENDING
        );
    }

    private RefinementPlan plan(String planId, String auditId, List<RefinementTask> tasks) {
        return new RefinementPlan(planId, auditId, Instant.parse("2026-04-19T10:00:00Z"), tasks);
    }

    // --- Happy paths ---

    @Test
    @DisplayName("should resolve the task in the most recent plan when 'revise task <id>' is invoked without --plan")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldResolveTheTaskInTheMostRecentPlanWhenReviseTaskIdIsInvokedWithoutPlan() {
        // Arrange — planId == null → use loadLatest()
        String taskId = "task-001";
        String planId = "plan-latest";
        RefinementTask task = task(taskId);
        RefinementPlan latestPlan = plan(planId, "audit-001", List.of(task));

        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(latestPlan));

        RevisionOutcome outcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), isNull())).thenReturn(outcome);

        // Act
        int exit = reviseCmd.revise(taskId, null, null, null);

        // Assert — R015: default plan resolution uses loadLatest(); APPROVED_APPLIED maps to exit 0
        assertEquals(0, exit,
                "revise(taskId, null) with APPROVED_APPLIED outcome should exit 0");
        verify(refinementPlanStore).loadLatest();
        verify(revisionEngine).revise(eq(planId), eq(taskId), any(Path.class), isNull());
    }

    @Test
    @DisplayName("should resolve the task in the named plan when 'revise task <id> --plan <plan-id>' is invoked with an existing plan id")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldResolveTheTaskInTheNamedPlanWhenReviseTaskIdPlanPlanidIsInvokedWithAnExistingPlanId(
            ) {
        // Arrange — planId != null → use load(planId)
        String taskId = "task-002";
        String planId = "plan-explicit";
        RefinementTask task = task(taskId);
        RefinementPlan namedPlan = plan(planId, "audit-002", List.of(task));

        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(namedPlan));

        RevisionOutcome outcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), isNull())).thenReturn(outcome);

        // Act
        int exit = reviseCmd.revise(taskId, planId, null, null);

        // Assert — R015: explicit --plan uses load(planId); APPROVED_APPLIED maps to exit 0
        assertEquals(0, exit,
                "revise(taskId, planId) with APPROVED_APPLIED outcome should exit 0");
        verify(refinementPlanStore).load(planId);
        verify(revisionEngine).revise(eq(planId), eq(taskId), any(Path.class), isNull());
    }

    // --- Failure modes ---

    @Test
    @DisplayName("should report 'No plans available' and exit non-zero when no plans exist regardless of --plan")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldReportNoPlansAvailableAndExitNonzeroWhenNoPlansExistRegardlessOfPlan() {
        // Arrange — no plans at all; planId == null → loadLatest() returns empty
        when(refinementPlanStore.loadLatest()).thenReturn(Optional.empty());

        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));
        try {
            // Act
            int exit = reviseCmd.revise("task-001", null, null, null);

            // Assert — R015: "No plans available. Run 'content-audit plan' first."
            assertNotEquals(0, exit, "revise with no plans must exit non-zero");
            String errOutput = errBuf.toString();
            assertTrue(errOutput.contains("No plans available"),
                    "stderr must contain 'No plans available', got: " + errOutput);
        } finally {
            System.setErr(originalErr);
        }
    }

    @Test
    @DisplayName("should report 'Plan <id> not found' and exit non-zero when --plan references an unknown plan id")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldReportPlanIdNotFoundAndExitNonzeroWhenPlanReferencesAnUnknownPlanId() {
        // Arrange — named plan does not exist; planId != null → load(planId) returns empty
        String unknownPlanId = "plan-ghost";
        when(refinementPlanStore.load(unknownPlanId)).thenReturn(Optional.empty());

        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));
        try {
            // Act
            int exit = reviseCmd.revise("task-001", unknownPlanId, null, null);

            // Assert — R015: "Plan '<id>' not found"
            assertNotEquals(0, exit, "revise with unknown planId must exit non-zero");
            String errOutput = errBuf.toString();
            assertTrue(errOutput.contains("not found"),
                    "stderr must contain 'not found', got: " + errOutput);
            assertTrue(errOutput.contains(unknownPlanId),
                    "stderr must name the unknown plan id, got: " + errOutput);
        } finally {
            System.setErr(originalErr);
        }
    }

    @Test
    @DisplayName("should report 'Task <task-id> not found in plan <plan-id>' naming the resolved plan when the task id is absent from the resolved plan")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldReportTaskTaskidNotFoundInPlanPlanidNamingTheResolvedPlanWhenTheTaskIdIsAbsentFromTheResolvedPlan(
            ) {
        // Arrange — plan exists but does NOT contain the requested task; planId == null → loadLatest()
        String missingTaskId = "task-999";
        String planId = "plan-recent";
        RefinementTask existingTask = task("task-001"); // different task id
        RefinementPlan recentPlan = plan(planId, "audit-003", List.of(existingTask));

        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(recentPlan));

        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));
        try {
            // Act
            int exit = reviseCmd.revise(missingTaskId, null, null, null);

            // Assert — R015: "Task '<task-id>' not found in plan '<plan-id>'"
            // The plan-id in the message is the resolved plan (default = most recent)
            assertNotEquals(0, exit, "revise with absent taskId must exit non-zero");
            String errOutput = errBuf.toString();
            assertTrue(errOutput.contains("not found"),
                    "stderr must contain 'not found', got: " + errOutput);
            assertTrue(errOutput.contains(missingTaskId),
                    "stderr must name the missing task id, got: " + errOutput);
            assertTrue(errOutput.contains(planId),
                    "stderr must name the resolved plan id, got: " + errOutput);
        } finally {
            System.setErr(originalErr);
        }
    }

    @Test
    @DisplayName("should report 'Task <task-id> not found in plan <plan-id>' naming the explicitly supplied plan when --plan was used and the task is absent")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R015")
    public void shouldReportTaskTaskidNotFoundInPlanPlanidNamingTheExplicitlySuppliedPlanWhenPlanWasUsedAndTheTaskIsAbsent(
            ) {
        // Arrange — explicit planId supplied; plan exists but does NOT contain the task
        String missingTaskId = "task-888";
        String explicitPlanId = "plan-explicit-no-task";
        RefinementTask existingTask = task("task-001"); // different task id
        RefinementPlan explicitPlan = plan(explicitPlanId, "audit-004", List.of(existingTask));

        when(refinementPlanStore.load(explicitPlanId)).thenReturn(Optional.of(explicitPlan));

        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));
        try {
            // Act
            int exit = reviseCmd.revise(missingTaskId, explicitPlanId, null, null);

            // Assert — R015: error message names the explicitly supplied plan id
            assertNotEquals(0, exit, "revise with absent taskId must exit non-zero");
            String errOutput = errBuf.toString();
            assertTrue(errOutput.contains("not found"),
                    "stderr must contain 'not found', got: " + errOutput);
            assertTrue(errOutput.contains(missingTaskId),
                    "stderr must name the missing task id, got: " + errOutput);
            assertTrue(errOutput.contains(explicitPlanId),
                    "stderr must name the explicitly supplied plan id, got: " + errOutput);
        } finally {
            System.setErr(originalErr);
        }
    }

    @Test
    @DisplayName("Given revise runs in human mode and the engine returns PENDING_APPROVAL_PERSISTED, when the command finishes, then stdout contains the assigned proposalId in a form suitable for copy-paste to 'approve proposal <id>' / 'reject proposal <id>'")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R016")
    public void givenReviseRunsInHumanModeAndTheEngineReturnsPENDINGAPPROVALPERSISTEDWhenTheCommandFinishesThenStdoutContainsTheAssignedProposalIdInAFormSuitableForCopypasteToApproveProposalIdRejectProposalId() {
        // Arrange — a plan with a single task exists
        String taskId = "task-007";
        String planId = "plan-human-001";
        String proposalId = "task-007-20260420T123000Z";

        RefinementTask task = task(taskId);
        RefinementPlan latestPlan = plan(planId, "audit-007", List.of(task));
        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(latestPlan));

        // Build a RevisionProposal carrying the known proposalId
        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionProposal proposal = new RevisionProposal(
                proposalId,
                taskId,
                planId,
                "audit-007",
                DiagnosisKind.SENTENCE_LENGTH,
                AuditTarget.QUIZ,
                "quiz-001",
                snapshot,
                snapshot,
                "human approval pending",
                "bypass",
                Instant.parse("2026-04-20T12:30:00Z"),
                null);

        // Build the artifact with verdict PENDING_APPROVAL (course untouched)
        RevisionArtifact artifact = new RevisionArtifact(
                proposal,
                RevisionVerdict.PENDING_APPROVAL,
                null,   // rejectionReason: null when PENDING_APPROVAL
                RevisionOutcomeKind.PENDING_APPROVAL_PERSISTED,
                null,   // decidedAt: null — not yet decided
                null,   // decisionNote: null — not yet decided
                CorrectionContextSource.DERIVED,
                null    // contextOverridePayload: null — no override
        );

        RevisionOutcome outcome = new RevisionOutcome(
                RevisionOutcomeKind.PENDING_APPROVAL_PERSISTED,
                artifact,
                null
        );
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), isNull())).thenReturn(outcome);

        // Capture stdout
        ByteArrayOutputStream outBuf = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outBuf));
        int exit;
        try {
            // Act — invoke revise without --plan (uses loadLatest)
            exit = reviseCmd.revise(taskId, null, null, null);
        } finally {
            System.setOut(originalOut);
        }

        // Assert — R016: stdout must contain the proposalId so the operator can copy-paste it
        // to "approve proposal <id>" or "reject proposal <id>"
        String stdoutOutput = outBuf.toString();
        assertEquals(0, exit,
                "PENDING_APPROVAL_PERSISTED outcome should exit 0 (propose phase succeeded)");
        assertTrue(stdoutOutput.contains(proposalId),
                "stdout must contain the proposalId '" + proposalId + "' for copy-paste, got: " + stdoutOutput);
    }

    @Test
    @DisplayName("should reject the invocation with a clear error before invoking the engine when both --correction-context and --correction-context-file are provided")
    @Tag("FEAT-REVCTX")
    @Tag("F-REVCTX-R001")
    public void shouldRejectTheInvocationWithAClearErrorBeforeInvokingTheEngineWhenBothCorrectioncontextAndCorrectioncontextfileAreProvided() {
        // R001: if the operator passes both --correction-context and --correction-context-file
        // in the same invocation, the command must fail with a clear error BEFORE reading either
        // payload, without invoking the engine, without persisting an artifact, without modifying
        // the task or the course.
        String inlineJson = """
                {"taskId":"task-001","nodeId":"quiz-001","diagnosisKind":"LEMMA_ABSENCE"}
                """;
        String filePath = "/tmp/ctx.json";

        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));
        int exit;
        try {
            // Act — both flags provided simultaneously
            exit = reviseCmd.revise("task-001", null, inlineJson, filePath);
        } finally {
            System.setErr(originalErr);
        }

        // Assert — R001: exit non-zero, clear error message about mutual exclusion
        assertNotEquals(0, exit, "Command must exit non-zero when both override flags are provided");
        String errOutput = errBuf.toString();
        assertTrue(
                errOutput.contains("mutuamente excluyentes") || errOutput.contains("mutually exclusive")
                        || errOutput.contains("correction-context"),
                "stderr must contain a clear message about mutual exclusion, got: " + errOutput
        );
        // Assert — R001: engine must NOT be invoked (no side effects)
        verify(revisionEngine, never()).revise(anyString(), anyString(), any(Path.class), any());
    }

    @Test
    @DisplayName("should invoke the engine overload with the inline JSON payload when --correction-context is provided")
    @Tag("FEAT-REVCTX")
    @Tag("F-REVCTX-R001")
    public void shouldInvokeTheEngineOverloadWithTheInlineJSONPayloadWhenCorrectioncontextIsProvided() {
        // R001: when --correction-context=<json> is provided (and --correction-context-file is
        // absent), the command must resolve the plan normally and invoke the engine's 4-arg
        // revise() with the inline JSON string as the overridePayload.
        String taskId = "task-ctx-inline";
        String planId = "plan-ctx-inline";
        String inlineJson = """
                {"taskId":"task-ctx-inline","nodeId":"quiz-inline","diagnosisKind":"LEMMA_ABSENCE","sentence":"I read."}
                """;

        RefinementTask task = task(taskId);
        RefinementPlan latestPlan = plan(planId, "audit-ctx-inline", List.of(task));
        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(latestPlan));

        RevisionOutcome outcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), eq(inlineJson)))
                .thenReturn(outcome);

        // Act — --correction-context provided, --correction-context-file absent (null)
        int exit = reviseCmd.revise(taskId, null, inlineJson, null);

        // Assert — R001: engine invoked with the inline JSON as overridePayload; exit 0
        assertEquals(0, exit, "APPROVED_APPLIED outcome with inline override should exit 0");
        verify(revisionEngine).revise(eq(planId), eq(taskId), any(Path.class), eq(inlineJson));
    }

    @Test
    @DisplayName("should invoke the engine overload with the JSON payload read from disk when --correction-context-file is provided")
    @Tag("FEAT-REVCTX")
    @Tag("F-REVCTX-R001")
    public void shouldInvokeTheEngineOverloadWithTheJSONPayloadReadFromDiskWhenCorrectioncontextfileIsProvided() throws Exception {
        // R001: when --correction-context-file=<path> is provided (and --correction-context is
        // absent), the command must read the file and invoke the engine's 4-arg revise() with the
        // file's content as the overridePayload.
        String taskId = "task-ctx-file";
        String planId = "plan-ctx-file";
        String fileContent = """
                {"taskId":"task-ctx-file","nodeId":"quiz-file","diagnosisKind":"LEMMA_ABSENCE","sentence":"You write."}
                """;

        // Write the override payload to a temp file
        java.io.File tempFile = java.io.File.createTempFile("correction-context-", ".json");
        tempFile.deleteOnExit();
        java.nio.file.Files.writeString(tempFile.toPath(), fileContent);

        RefinementTask task = task(taskId);
        RefinementPlan latestPlan = plan(planId, "audit-ctx-file", List.of(task));
        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(latestPlan));

        RevisionOutcome outcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        // The engine receives the file content as overridePayload
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), eq(fileContent)))
                .thenReturn(outcome);

        // Act — --correction-context-file provided, --correction-context absent (null)
        int exit = reviseCmd.revise(taskId, null, null, tempFile.getAbsolutePath());

        // Assert — R001: engine invoked with the file content as overridePayload; exit 0
        assertEquals(0, exit, "APPROVED_APPLIED outcome with file override should exit 0");
        verify(revisionEngine).revise(eq(planId), eq(taskId), any(Path.class), eq(fileContent));
    }

    @Test
    @DisplayName("should invoke the engine without overridePayload and preserve the historical revise behavior when neither override flag is provided")
    @Tag("FEAT-REVCTX")
    @Tag("F-REVCTX-R001")
    public void shouldInvokeTheEngineWithoutOverridePayloadAndPreserveTheHistoricalReviseBehaviorWhenNeitherOverrideFlagIsProvided() {
        // R001: when neither --correction-context nor --correction-context-file is provided,
        // the command must preserve the historical behavior: invoke the engine with null as
        // overridePayload so the engine derives context from the plan/AuditReport as before.
        // A client that does not use the override observes no change.
        String taskId = "task-no-override";
        String planId = "plan-no-override";

        RefinementTask task = task(taskId);
        RefinementPlan latestPlan = plan(planId, "audit-no-override", List.of(task));
        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(latestPlan));

        RevisionOutcome outcome = new RevisionOutcome(RevisionOutcomeKind.APPROVED_APPLIED, null, null);
        when(revisionEngine.revise(eq(planId), eq(taskId), any(Path.class), isNull()))
                .thenReturn(outcome);

        // Act — neither override flag provided
        int exit = reviseCmd.revise(taskId, null, null, null);

        // Assert — R001: engine invoked with null overridePayload (historical path); exit 0
        assertEquals(0, exit, "APPROVED_APPLIED outcome without override should exit 0");
        verify(revisionEngine).revise(eq(planId), eq(taskId), any(Path.class), isNull());
    }
}
