package com.learney.contentaudit.auditcli.commands;

import com.learney.contentaudit.auditapplication.AnalyzerRegistry;
import com.learney.contentaudit.auditapplication.AuditRunner;
import com.learney.contentaudit.auditcli.formatting.AnalyzerStatsTransformer;
import com.learney.contentaudit.auditcli.formatting.AnalyzerStatsView;
import com.learney.contentaudit.auditdomain.AnalyzerDescriptor;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.ArgumentMatchers;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.when;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.learney.contentaudit.auditapplication.AuditRunRequest;
import com.learney.contentaudit.auditapplication.DefaultAnalyzerRegistry;
import com.learney.contentaudit.auditapplication.DefaultAuditRunner;
import com.learney.contentaudit.auditcli.commands.AnalyzeCmdTest.Base299;
import com.learney.contentaudit.auditcli.formatting.DefaultAnalyzerStatsTransformer;
import com.learney.contentaudit.auditdomain.AnalyzerCatalog;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.contextnumbers.AnalyzerScore;
import com.learney.contentaudit.auditdomain.contextnumbers.ContextNumbers;
import com.learney.contentaudit.auditdomain.contextnumbers.SubMetricScore;
import com.learney.contentaudit.evaluationledgerinfrastructure.FileSystemEvaluationLedger;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class StatsAnalyzerCmdTest {

    @Mock
    AnalyzerRegistry analyzerRegistry;

    @Mock
    AnalyzerStatsTransformer analyzerStatsTransformer;

    @Mock
    AuditRunner auditRunner;

    @Mock
    AuditNode mockAuditNode;

    @Test
    @DisplayName("should run the analyzer over the supplied course path and render the stats view when invoked with a known analyzer")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R021")
    public void shouldRunTheAnalyzerOverTheSuppliedCoursePathAndRenderTheStatsViewWhenInvokedWithAKnownAnalyzer(
            ) {
        // Arrange — known analyzer, explicit course path supplied
        String analyzerName = "sentence-length";
        String coursePath = "/tmp/fixture-course";

        // The impl may check registry via listAnalyzers() or getAnalyzerConfig(); stub both
        AnalyzerDescriptor descriptor = new AnalyzerDescriptor(analyzerName,
                "Checks sentence length", AuditTarget.KNOWLEDGE, null, null, null, null, null, null, null, null);
        when(analyzerRegistry.listAnalyzers()).thenReturn(List.of(descriptor));
        when(analyzerRegistry.getAnalyzerConfig(analyzerName))
                .thenReturn(java.util.Optional.of(Map.of("maxSentenceLength", 25)));

        // The impl may call runAudit or runDetailedAudit; stub both with a minimal result
        AuditReport minimalReport = new AuditReport(mockAuditNode);
        when(auditRunner.runAudit(any(Path.class), ArgumentMatchers.<Set<String>>any())).thenReturn(minimalReport);
        when(auditRunner.runDetailedAudit(any(), anyString())).thenReturn(mockAuditNode);

        // Stub the transformer to return a valid (non-null) stats view
        AnalyzerStatsView statsView = new AnalyzerStatsView(analyzerName,
                "Checks sentence length", 0.85,
                Collections.emptyMap(), Collections.emptyList(),
                Collections.emptyMap(), Collections.emptyMap(), 10);
        when(analyzerStatsTransformer.transform(any(), anyString(), any())).thenReturn(statsView);

        StatsAnalyzerCmd cmd = new StatsAnalyzerCmd(analyzerRegistry, analyzerStatsTransformer, auditRunner);

        // Act
        int exitCode = cmd.showStats(analyzerName, coursePath);

        // Assert — R021: known analyzer + valid course path → exit 0
        assertEquals(0, exitCode,
                "stats analyzer <known-name> <course-path> must exit 0 when the analyzer is registered and a course path is supplied");
    }

    @Test
    @DisplayName("should report 'Analyzer <name> not found' and exit non-zero when invoked with an unknown analyzer")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R021")
    public void shouldReportAnalyzerNameNotFoundAndExitNonzeroWhenInvokedWithAnUnknownAnalyzer() {
        // Arrange — unknown analyzer: listAnalyzers returns an empty list (no match)
        when(analyzerRegistry.listAnalyzers()).thenReturn(Collections.emptyList());
        when(analyzerRegistry.getAnalyzerConfig(anyString()))
                .thenReturn(java.util.Optional.empty());

        StatsAnalyzerCmd cmd = new StatsAnalyzerCmd(analyzerRegistry, analyzerStatsTransformer, auditRunner);

        // Act
        int exitCode = cmd.showStats("no-such-analyzer", "/tmp/fixture-course");

        // Assert — R021 / R016: "Analyzer '<name>' not found" → non-zero exit
        assertNotEquals(0, exitCode,
                "stats analyzer <unknown-name> must exit non-zero when the analyzer is not registered");
    }

    @Test
    @DisplayName("should fall back to CONTENT_AUDIT_CONTENT_FOLDER env var when no course-path argument is supplied")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R021")
    public void shouldFallBackToCONTENTAUDITCONTENTFOLDEREnvVarWhenNoCoursepathArgumentIsSupplied(
            @TempDir Path workdir) throws IOException, InterruptedException {
        // Cannot mutate System.getenv() inside the JVM, so spawn the launcher as a sub-process
        // with CONTENT_AUDIT_CONTENT_FOLDER set and no positional course-path argument.
        // If the env fallback is consulted, the analyzer runs over the fixture and exits 0.
        Path projectRoot = Path.of("/Users/josecullen/projects/learney/content-audit");
        Path fixtureCourse = projectRoot.resolve(
                "audit-cli/src/test/resources/fixtures/tiny-course/english-course");

        ProcessBuilder pb = new ProcessBuilder(
                projectRoot.resolve("audit-cli.sh").toString(),
                "--workdir", workdir.toString(),
                "stats", "analyzer", "sentence-length");  // no positional course path
        pb.directory(projectRoot.toFile());
        pb.environment().put("CONTENT_AUDIT_CONTENT_FOLDER", fixtureCourse.toString());
        pb.redirectErrorStream(true);

        Process p = pb.start();
        int exit = p.waitFor();
        String output = new String(p.getInputStream().readAllBytes());

        assertEquals(0, exit,
                "stats analyzer must exit 0 when CONTENT_AUDIT_CONTENT_FOLDER provides the course path. "
                + "Output:\n" + output);
        // Non-empty output proves the env path was consulted and the analyzer ran (produced a stats view).
        // If the env fallback hadn't worked, the cmd would have errored on missing course path before any view was produced.
        assertTrue(output.contains("AnalyzerStatsView") || output.toLowerCase().contains("sentence-length")
                        || output.contains("score"),
                "Output should reflect that the analyzer ran (env fallback consulted); got:\n" + output);
    }

    @Test
    @DisplayName("should report a missing-course-path error and exit non-zero when neither argument nor CONTENT_AUDIT_CONTENT_FOLDER is set")
    @Tag("FEAT-CLIRV")
    @Tag("F-CLIRV-R021")
    public void shouldReportAMissingcoursepathErrorAndExitNonzeroWhenNeitherArgumentNorCONTENTAUDITCONTENTFOLDERIsSet(
            @TempDir Path workdir) throws IOException, InterruptedException {
        // Arrange — spawn the CLI with CONTENT_AUDIT_CONTENT_FOLDER explicitly removed.
        // Java cannot unset env vars from its own process, so an in-process test that
        // relied on the absence of CONTENT_AUDIT_CONTENT_FOLDER would be fragile in
        // developer shells that export the variable. Subprocess + env.remove() is
        // the same pattern the env-fallback test nearby uses, inverted.
        Path projectRoot = Path.of("/Users/josecullen/projects/learney/content-audit");

        ProcessBuilder pb = new ProcessBuilder(
                projectRoot.resolve("audit-cli.sh").toString(),
                "--workdir", workdir.toString(),
                "stats", "analyzer", "sentence-length");  // no positional course path
        pb.directory(projectRoot.toFile());
        pb.environment().remove("CONTENT_AUDIT_CONTENT_FOLDER");
        pb.redirectErrorStream(true);

        // Act
        Process p = pb.start();
        int exit = p.waitFor();
        String output = new String(p.getInputStream().readAllBytes());

        // Assert — R021: no resolvable course path must exit non-zero
        assertNotEquals(0, exit,
                "stats analyzer <name> with no resolved course path must exit non-zero. Output:\n"
                        + output);
        assertTrue(
                output.toLowerCase().contains("missing course path")
                        || output.toLowerCase().contains("content_audit_content_folder"),
                "Output should explain the missing course path; got:\n" + output);
    }

    @Test
    @DisplayName("should show the stats of quiz-instruction from the verdicts already recorded, with no new judge query, and declare how many quizzes lack a verdict")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R005")
    public void shouldShowTheStatsOfQuizinstructionFromTheVerdictsAlreadyRecordedWithNoNewJudgeQueryAndDeclareHowManyQuizzesLackAVerdict(
            @TempDir Path workdir) throws IOException {
        // R005 (DOUBT-STATS-DE-LOS-JUECES, A): stats of the judge over the 29/9 course uses the verdicts
        // already recorded -- the three an earlier analyze paid for -- makes no new query, and declares
        // how many quizzes lack a verdict.
        Base299.FakeJudge judge = new Base299.FakeJudge(Base299.FIRST_QUIZ);
        AnalyzerCatalog catalog = Base299.mainCatalog(judge, new FileSystemEvaluationLedger(workdir));
        DefaultAuditRunner runner = Base299.runner(catalog);
        Base299.Captured analyzed = Base299.run(Base299.analyzeCmd(runner, mock(AuditReportStore.class)),
                Base299.COURSE.toString(), "--analyzers", "quiz-instruction", "--budget", "quiz-instruction=3",
                "-f", "raw");
        assertEquals(0, analyzed.exit(), analyzed.err());
        assertEquals(3, judge.asked().size(), "the three verdicts analyze paid for");
        StatsAnalyzerCmd stats = new StatsAnalyzerCmd(new DefaultAnalyzerRegistry(catalog),
                new DefaultAnalyzerStatsTransformer(), runner);

        Base299.Captured run = Base299.run(stats, "analyzer", "quiz-instruction", Base299.COURSE.toString(), "-f", "json");

        assertEquals(0, run.exit(), run.err());
        assertEquals(3, judge.asked().size(), "R005: stats asked the judge nothing new");
        assertTrue(run.err().contains("Sin veredicto registrado: 11284 de 11287 ejercicios (stats sólo usa los "
                + "veredictos ya registrados: 0 consultas nuevas)"), "R005: how many lack a verdict: " + run.err());
        JsonNode view = new ObjectMapper().readTree(run.out());
        assertEquals("quiz-instruction", view.get("analyzerName").asText());
        assertEquals(3, view.get("itemCount").asInt(), "R005: the stats of the three recorded verdicts");
        assertEquals(Base299.FIRST_QUIZ, view.get("worstItems").get(0).get("quizId").asText(),
                "the breach recorded for the first quiz");
        assertEquals(0.3, view.get("worstItems").get(0).get("score").asDouble(), "a major breach scores 0,3");
    }

    @Test
    @DisplayName("should show in stats analyzer coca-buckets-distribution the course score 72,5 % published for it, with its quarters Q1 to Q4 as sub-metrics outside any average")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R010")
    public void shouldShowInStatsAnalyzerCocabucketsdistributionTheCourseScore725PublishedForItWithItsQuartersQ1ToQ4AsSubmetricsOutsideAnyAverage() throws IOException {
        // R010: stats of coca-buckets-distribution over the 29/9 course shows the course score the engine
        // published for it, 72,5 %, with its quarters Q1 to Q4 nested under it as sub-metrics -- never
        // as analyzers of their own, so no average takes them.
        AnalyzerCatalog catalog = Base299.mainCatalog(new Base299.FakeJudge(), new Base299.MapLedger());
        DefaultAuditRunner runner = spy(Base299.runner(catalog));
        List<AuditReport> reports = new java.util.ArrayList<>();
        doAnswer(invocation -> {
            AuditReport report = (AuditReport) invocation.callRealMethod();
            reports.add(report);
            return report;
        }).when(runner).runAudit(any(Path.class), any(AuditRunRequest.class));
        StatsAnalyzerCmd stats = new StatsAnalyzerCmd(new DefaultAnalyzerRegistry(catalog),
                new DefaultAnalyzerStatsTransformer(), runner);

        Base299.Captured run = Base299.run(stats, "analyzer", "coca-buckets-distribution", Base299.COURSE.toString(),
                "-f", "json");

        assertEquals(0, run.exit(), run.err());
        JsonNode view = new ObjectMapper().readTree(run.out());
        assertEquals(0.7253788624322802, view.get("courseScore").asDouble(),
                "R010: the course score published for it in the 29/9 base");
        assertEquals("72,5 %", GetCmd.scoreText(view.get("courseScore").asDouble()));
        Map<String, Double> levels = new java.util.LinkedHashMap<>();
        view.get("levelScores").fields().forEachRemaining(level -> levels.put(level.getKey(), level.getValue().asDouble()));
        assertEquals(Map.of(Base299.LEVELS.get(0), 1.0, Base299.LEVELS.get(1), 1.0,
                Base299.LEVELS.get(2), 0.5792869389091038, Base299.LEVELS.get(3), 0.3222285108200172), levels,
                "its score on each level, and no quarter among them");
        for (String level : Base299.LEVELS) {
            List<String> quarters = new java.util.ArrayList<>();
            view.get("subMetricsByLevel").get(level).fieldNames().forEachRemaining(quarters::add);
            assertEquals(List.of("Q1", "Q2", "Q3", "Q4"), quarters, "R010: its quarters, as sub-metrics of " + level);
        }
        ContextNumbers course = reports.get(0).getRoot().getNumbers();
        assertEquals(1, course.getAnalyzerScores().size(), "R010: the quarters are not analyzers of their own");
        AnalyzerScore coca = course.getAnalyzerScores().get(0);
        assertEquals("coca-buckets-distribution", coca.getAnalyzer());
        assertEquals(Map.of("Q1", 0.7673328547283127, "Q2", 0.7684543932356559, "Q3", 0.6915373831741857,
                "Q4", 0.6741908185909666), coca.getSubMetrics().stream()
                .collect(java.util.stream.Collectors.toMap(SubMetricScore::getName, SubMetricScore::getScore)),
                "R010: nested under it, the quarters of the 29/9 base");
        assertEquals(0.7253788624322802, course.getVocabularyScore(), "R009: the average of one analyzer, not of five keys");
    }
}
