package com.learney.contentaudit.revisioninfrastructure.lemmaabsenceagent;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyMap;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.LengthDirection;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQuerySessionFactory;
import com.learney.contentaudit.revisiondomain.lemmaabsence.LemmaAbsenceGeneratorResponse;
import com.learney.contentaudit.revisioninfrastructure.lagen.LagenConfig;
import com.sentinel.agents.framework.state.RunState;
import com.sentinel.agents.framework.state.RunStatus;
import java.util.Collections;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-LASAG")
@Tag("F-LASAG-J005")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FLasagJ005JourneyTest {

    // ---------------------------------------------------------------------------
    // Shared fixture helpers (same pattern as LemmaAbsenceAgentGeneratorTest)
    // ---------------------------------------------------------------------------

    private LemmaAbsenceCorrectionContext validContext() {
        return new LemmaAbsenceCorrectionContext(
                "task-j005",
                "She goes to school every day.",
                "Ella va a la escuela todos los días.",
                "Daily Routines",
                "Fill in the blank with the correct verb.",
                "Everyday Activities",
                CefrLevel.A1,
                Collections.emptyList(),
                Collections.emptyList(),
                "She [[goes]] to school every day.",
                12,
                10,
                15,
                0,
                LengthDirection.KEEP_SAME,
                null
        );
    }

    /** maxEvalRetries = 3, maxSuggestedLemmaRequests = 5. */
    private LagenConfig lagenConfig() {
        return new LagenConfig(
                "test-provider",
                "test-model",
                "http://localhost:1234/v1",
                null, null, null, null,
                5,
                3
        );
    }

    // ---------------------------------------------------------------------------
    // Tests
    // ---------------------------------------------------------------------------

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: Se configura maxEvalRetries y se fuer... → El agente genera y evalúa candidatos ... → Se emite sin excepción el mejor candi... [se agotan los reintentos sin candidato que pase todos los bloqueantes] → success")
    public void path1_seAgotanLosReintentosSinCandidatoQuePaseTodosLosBloqueantes_success() {
        // Arrange
        // Scenario: all candidates across every attempt fail at least one blocking eval;
        // maxEvalRetries is exhausted. The best-effort selection (F-LASAG-R009) and the
        // retry loop (F-LASAG-R008) are entirely internal to the agent graph — the seam
        // observable is that generate() returns a QuizCandidate without throwing
        // (exhaustion is not a failure per F-LASAG-R009).
        // The launcher fake returns COMPLETED + a candidate (the "best seen" is chosen by
        // the agent graph, not by the Java adapter).
        RunState completedBestEffort = RunState.empty().withRunStatus(RunStatus.COMPLETED);
        AgentRuntimeLauncher launcher = mock(AgentRuntimeLauncher.class);
        when(launcher.launch(anyString(), anyMap(), any(), anyMap()))
                .thenReturn(completedBestEffort);

        // The best-effort candidate: passed the most blocking evals among all attempts
        LemmaAbsenceGeneratorResponse bestSeenCandidate = new LemmaAbsenceGeneratorResponse(
                "She [[reads]] books at home every night.",
                "Ella lee libros en casa todas las noches.");
        AgentCandidateParser parser = mock(AgentCandidateParser.class);
        when(parser.parse(any(), anyString(), anyString())).thenReturn(bestSeenCandidate);

        AgentRuntimeErrorClassifier classifier = mock(AgentRuntimeErrorClassifier.class);
        SuggestedLemmaQuerySessionFactory sessionFactory =
                mock(SuggestedLemmaQuerySessionFactory.class);

        LemmaAbsenceAgentGenerator generator = new LemmaAbsenceAgentGenerator(
                lagenConfig(),
                launcher,
                sessionFactory,
                classifier,
                parser,
                null,
                "lemma-absence-llm"
        );

        // Act — F-LASAG-J005 path-1: retries exhausted, best-effort emits the best candidate.
        LemmaAbsenceGeneratorResponse result = generator.generate(validContext());

        // Assert — outcome: QuizCandidate emitted without exception (F-LASAG-R009).
        // The "best seen" selection is graph-internal; the seam asserts no failure and a
        // non-null candidate with both fields present (F-LASAG-R003).
        assertNotNull(result,
                "J005-path-1: se debe emitir un QuizCandidate sin excepción al agotar los reintentos (F-LASAG-R009)");
        assertNotNull(result.getQuizSentence(),
                "J005-path-1: quizSentence no debe ser nulo en el candidato best-effort (F-LASAG-R003)");
        assertNotNull(result.getTranslation(),
                "J005-path-1: translation no debe ser nula en el candidato best-effort (F-LASAG-R003)");
    }
}
