package com.learney.contentaudit.revisiondomain.preservation;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import java.util.Set;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface CorrectionScope {
    Set<ScopedField> changeableFields(DiagnosisKind kind, AuditTarget target);
}
