package com.learney.contentaudit.auditapplication;

import com.learney.contentaudit.auditdomain.AuditReport;
import java.nio.file.Path;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface AuditRunner {
    AuditReport runAudit(Path coursePath);
}
