package com.learney.contentaudit.auditapplication;

import com.learney.contentaudit.auditdomain.LemmaRecurrenceConfig;
import java.util.Map;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultLemmaRecurrenceConfig implements LemmaRecurrenceConfig {
    @Override
    public int getTop() {
        return 2000;
    }

    @Override
    public double getSubExposedThreshold() {
        return 1000.0;
    }

    @Override
    public double getOverExposedThreshold() {
        return 50.0;
    }
    @Override
    public Map<String, Object> describe() {
        return Map.of(
                "analyzerName", "lemma-recurrence",
                "top", getTop(),
                "subExposedThreshold", getSubExposedThreshold(),
                "overExposedThreshold", getOverExposedThreshold());
    }
}
