package com.learney.contentaudit.auditdomain.lrec;

import com.learney.contentaudit.auditdomain.LemmaRecurrenceConfig;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface ExposureClassifier {
    ExposureStatus classify(double meanInterval, LemmaRecurrenceConfig config);
}
