package com.learney.contentaudit.auditdomain.lrec;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public enum ExposureStatus {
    NORMAL,

    SUB_EXPOSED,

    OVER_EXPOSED
}
