package com.learney.contentaudit.revisiondomain.quizinstruction;

import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class QuizInstructionCorrectionConfig {
    private Integer maxAttempts;

    private Integer maxCorrectionsPerRun;

    public QuizInstructionCorrectionConfig() {
    }

    public QuizInstructionCorrectionConfig(Integer maxAttempts, Integer maxCorrectionsPerRun) {
        this.maxAttempts = maxAttempts;
        this.maxCorrectionsPerRun = maxCorrectionsPerRun;
    }

    public Integer getMaxAttempts() {
        return this.maxAttempts;
    }

    public void setMaxAttempts(Integer maxAttempts) {
        this.maxAttempts = maxAttempts;
    }

    public Integer getMaxCorrectionsPerRun() {
        return this.maxCorrectionsPerRun;
    }

    public void setMaxCorrectionsPerRun(Integer maxCorrectionsPerRun) {
        this.maxCorrectionsPerRun = maxCorrectionsPerRun;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        QuizInstructionCorrectionConfig that = (QuizInstructionCorrectionConfig) o;
        return Objects.equals(this.maxAttempts, that.maxAttempts)
                    && Objects.equals(this.maxCorrectionsPerRun, that.maxCorrectionsPerRun);
    }

    @Override
    public int hashCode() {
        return Objects.hash(maxAttempts, maxCorrectionsPerRun);
    }
}
