package com.learney.contentaudit.auditcli.journeys;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditapplication.AnalyzerRegistry;
import com.learney.contentaudit.auditcli.GetCommand;
import com.learney.contentaudit.auditcli.GetTasksFilter;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

/**
 * Journey J005: Listar propuestas por plan y por estado (F-REVAPR-R002, R003).
 *
 * In-memory test: constructs GetCmd via reflection (it is package-private in
 * com.learney.contentaudit.auditcli.commands), injects a mock RevisionArtifactStore
 * pre-populated with artifacts of three verdicts (PENDING_APPROVAL, APPROVED, REJECTED).
 *
 * Path-1: valid --status filter → devolver_lista (exit 0, only matching proposals shown).
 * Path-2: invalid --status value → rechazar_status_invalido (exit non-zero, error lists allowed values).
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-REVAPR")
@Tag("F-REVAPR-J005")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FRevaprJ005JourneyTest {

    private static final String PLAN_ID           = "plan-j005";
    private static final String PENDING_PROPOSAL  = "task-j005-pending";
    private static final String APPROVED_PROPOSAL = "task-j005-approved";
    private static final String REJECTED_PROPOSAL = "task-j005-rejected";

    // GetCmd instance accessed via the GetCommand interface (constructed via reflection)
    private GetCommand cmd;
    private RevisionArtifactStore revisionArtifactStore;

    // -------------------------------------------------------------------------
    // Fixture builders
    // -------------------------------------------------------------------------

    private RevisionProposal buildProposal(String proposalId, String planId) {
        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-j005", null);
        return new RevisionProposal(
                proposalId, "task-j005", planId, "audit-j005",
                DiagnosisKind.SENTENCE_LENGTH, AuditTarget.QUIZ, "quiz-j005",
                snapshot, snapshot, "bypass: identity revision", "bypass", Instant.now(), null);
    }

    private RevisionArtifact buildArtifact(String proposalId, String planId, RevisionVerdict verdict) {
        return new RevisionArtifact(buildProposal(proposalId, planId), verdict, null, null, null, null);
    }

    // -------------------------------------------------------------------------
    // Setup — build GetCmd via reflection to cross the package-private boundary
    // -------------------------------------------------------------------------

    @BeforeEach
    void setUp() throws Exception {
        AuditReportStore auditReportStore       = mock(AuditReportStore.class);
        RefinementPlanStore refinementPlanStore  = mock(RefinementPlanStore.class);
        AnalyzerRegistry analyzerRegistry        = mock(AnalyzerRegistry.class);
        CorrectionContextResolver contextResolver = mock(CorrectionContextResolver.class);
        revisionArtifactStore                    = mock(RevisionArtifactStore.class);

        // GetCmd is package-private; instantiate via reflection
        Class<?> getCmdClass = Class.forName(
                "com.learney.contentaudit.auditcli.commands.GetCmd");
        Constructor<?> ctor = getCmdClass.getDeclaredConstructor(
                AuditReportStore.class,
                RefinementPlanStore.class,
                AnalyzerRegistry.class,
                CorrectionContextResolver.class);
        ctor.setAccessible(true);
        Object getCmdInstance = ctor.newInstance(
                auditReportStore, refinementPlanStore, analyzerRegistry, contextResolver);

        // Inject formatName (picocli @Option default)
        try {
            Field formatField = getCmdClass.getDeclaredField("formatName");
            formatField.setAccessible(true);
            formatField.set(getCmdInstance, "text");
        } catch (NoSuchFieldException ignored) {
            // If the field name changes, tests will fail with NPE; update fix-log
        }

        // Inject the RevisionArtifactStore via setRevisionArtifactStore setter
        Method setStoreSetter = getCmdClass.getDeclaredMethod(
                "setRevisionArtifactStore", RevisionArtifactStore.class);
        setStoreSetter.setAccessible(true);
        setStoreSetter.invoke(getCmdInstance, revisionArtifactStore);

        cmd = (GetCommand) getCmdInstance;

        // Seed the store with three artifacts — one per verdict
        RevisionArtifact pendingArtifact  = buildArtifact(PENDING_PROPOSAL, PLAN_ID, RevisionVerdict.PENDING_APPROVAL);
        RevisionArtifact approvedArtifact = buildArtifact(APPROVED_PROPOSAL, PLAN_ID, RevisionVerdict.APPROVED);
        RevisionArtifact rejectedArtifact = buildArtifact(REJECTED_PROPOSAL, PLAN_ID, RevisionVerdict.REJECTED);

        when(revisionArtifactStore.list()).thenReturn(
                List.of(pendingArtifact, approvedArtifact, rejectedArtifact));
    }

    // -------------------------------------------------------------------------
    // path-1: Los filtros son válidos → devolver_lista → success
    // Gates: R002 (proposals is a first-class resource), R003 (--status filter works conjunctively)
    // -------------------------------------------------------------------------

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El operador invoca 'content-audit get... → El sistema devuelve la lista de propu... [Los filtros son validos (si hay --status, el valor es pending, approved o rejected)] → success")
    public void path1_losFiltrosSonValidosSiHayStatusElValorEsPendingApprovedORejected_success() {
        // ── Act / Assert 1: get proposals --status pending ───────────────────────
        // Gate R002: 'proposals' is a recognised resource.
        // Gate R003: --status pending maps to PENDING_APPROVAL verdict.
        ByteArrayOutputStream outBuf = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outBuf));
        int exit1;
        try {
            GetTasksFilter pendingFilter = new GetTasksFilter(
                    Optional.empty(), Optional.of("pending"), false, Optional.empty(),
                    Optional.empty(), Optional.empty());
            exit1 = cmd.get("proposals", null, pendingFilter);
        } finally {
            System.setOut(originalOut);
        }
        String pendingOutput = outBuf.toString();
        assertEquals(0, exit1, "get proposals --status pending must exit 0 (R003), stderr not captured here");
        assertTrue(pendingOutput.contains(PENDING_PROPOSAL),
                "get proposals --status pending must include the pending proposal '" + PENDING_PROPOSAL + "', got: " + pendingOutput);
        assertTrue(!pendingOutput.contains(APPROVED_PROPOSAL),
                "get proposals --status pending must NOT include the approved proposal, got: " + pendingOutput);
        assertTrue(!pendingOutput.contains(REJECTED_PROPOSAL),
                "get proposals --status pending must NOT include the rejected proposal, got: " + pendingOutput);

        // ── Act / Assert 2: get proposals --status approved ──────────────────────
        // Gate R003: --status approved maps to APPROVED verdict.
        outBuf.reset();
        System.setOut(new PrintStream(outBuf));
        int exit2;
        try {
            GetTasksFilter approvedFilter = new GetTasksFilter(
                    Optional.empty(), Optional.of("approved"), false, Optional.empty(),
                    Optional.empty(), Optional.empty());
            exit2 = cmd.get("proposals", null, approvedFilter);
        } finally {
            System.setOut(originalOut);
        }
        String approvedOutput = outBuf.toString();
        assertEquals(0, exit2, "get proposals --status approved must exit 0 (R003)");
        assertTrue(approvedOutput.contains(APPROVED_PROPOSAL),
                "get proposals --status approved must include the approved proposal '" + APPROVED_PROPOSAL + "', got: " + approvedOutput);
        assertTrue(!approvedOutput.contains(PENDING_PROPOSAL),
                "get proposals --status approved must NOT include the pending proposal, got: " + approvedOutput);
        assertTrue(!approvedOutput.contains(REJECTED_PROPOSAL),
                "get proposals --status approved must NOT include the rejected proposal, got: " + approvedOutput);

        // ── Act / Assert 3: get proposals --status rejected ──────────────────────
        // Gate R003: --status rejected maps to REJECTED verdict; exit 0 even if list is non-empty.
        outBuf.reset();
        System.setOut(new PrintStream(outBuf));
        int exit3;
        try {
            GetTasksFilter rejectedFilter = new GetTasksFilter(
                    Optional.empty(), Optional.of("rejected"), false, Optional.empty(),
                    Optional.empty(), Optional.empty());
            exit3 = cmd.get("proposals", null, rejectedFilter);
        } finally {
            System.setOut(originalOut);
        }
        String rejectedOutput = outBuf.toString();
        assertEquals(0, exit3, "get proposals --status rejected must exit 0 (R003)");
        assertTrue(rejectedOutput.contains(REJECTED_PROPOSAL),
                "get proposals --status rejected must include the rejected proposal '" + REJECTED_PROPOSAL + "', got: " + rejectedOutput);
        assertTrue(!rejectedOutput.contains(APPROVED_PROPOSAL),
                "get proposals --status rejected must NOT include the approved proposal, got: " + rejectedOutput);
    }

    // -------------------------------------------------------------------------
    // path-2: El valor de --status no es válido → rechazar_status_invalido → failure
    // Gate: R003 error: "Invalid value for --status: '<value>'. Allowed: pending, approved, rejected"
    // -------------------------------------------------------------------------

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El operador invoca 'content-audit get... → El sistema reporta que el valor de --... [El valor de --status no es uno de los tres permitidos] → failure")
    public void path2_elValorDeStatusNoEsUnoDeLosTresPermitidos_failure() {
        // ── Arrange / Act ────────────────────────────────────────────────────────
        // Gate R003: 'bogus' is not in {pending, approved, rejected} → non-zero exit + error message.
        ByteArrayOutputStream errBuf = new ByteArrayOutputStream();
        PrintStream originalErr = System.err;
        System.setErr(new PrintStream(errBuf));

        int exit;
        try {
            GetTasksFilter badFilter = new GetTasksFilter(
                    Optional.empty(), Optional.of("bogus"), false, Optional.empty(),
                    Optional.empty(), Optional.empty());
            exit = cmd.get("proposals", null, badFilter);
        } finally {
            System.setErr(originalErr);
        }

        // ── Assert: failure ──────────────────────────────────────────────────────
        // Gate R003: non-zero exit on invalid --status value
        assertNotEquals(0, exit,
                "get proposals --status bogus must exit non-zero (R003)");

        // Gate R003: error message names the allowed values (pending, approved, rejected)
        String errorOutput = errBuf.toString();
        assertTrue(errorOutput.toLowerCase().contains("pending"),
                "R003 error must mention 'pending' among allowed values, got: " + errorOutput);
        assertTrue(errorOutput.toLowerCase().contains("approved"),
                "R003 error must mention 'approved' among allowed values, got: " + errorOutput);
        assertTrue(errorOutput.toLowerCase().contains("rejected"),
                "R003 error must mention 'rejected' among allowed values, got: " + errorOutput);
    }
}
