package com.learney.contentaudit.auditcli.journeys;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.CorrectionContext;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.revisiondomain.ApprovalMode;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.ProposalDecisionOutcome;
import com.learney.contentaudit.revisiondomain.ProposalDecisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.ProposalDecisionService;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionEngine;
import com.learney.contentaudit.revisiondomain.RevisionEngineConfig;
import com.learney.contentaudit.revisiondomain.RevisionOutcome;
import com.learney.contentaudit.revisiondomain.RevisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.RevisionValidator;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.engine.DefaultProposalDecisionServiceFactory;
import com.learney.contentaudit.revisiondomain.engine.DefaultRevisionEngineFactory;
import com.learney.contentaudit.revisiondomain.engine.DefaultRevisionValidatorFactory;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.mockito.ArgumentCaptor;

/**
 * Journey J002: Human-mode end-to-end reject path — proposal → rejection → task back to PENDING.
 *
 * In-memory test: instantiates RevisionEngine (human mode) for the propose phase and
 * ProposalDecisionService for the reject phase. No subprocess, no filesystem fixture.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-REVAPR")
@Tag("F-REVAPR-J002")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FRevaprJ002JourneyTest {

    private static final String PLAN_ID     = "plan-j002";
    private static final String AUDIT_ID    = "audit-j002";
    private static final String TASK_ID     = "task-j002";
    private static final String QUIZ_ID     = "quiz-j002";
    private static final Path   COURSE_PATH = Path.of("./db/english-course");

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private RefinementPlan buildPlan() {
        RefinementTask task = new RefinementTask(
                TASK_ID, AuditTarget.QUIZ, QUIZ_ID, "Quiz about sentence length",
                DiagnosisKind.SENTENCE_LENGTH, 1, RefinementTaskStatus.PENDING);
        return new RefinementPlan(PLAN_ID, AUDIT_ID, Instant.now(), List.of(task));
    }

    /** Minimal AuditReport — only used to pass the engine's "report not found" guard. */
    private AuditReport buildMinimalAuditReport() {
        AuditNode root = new AuditNode();
        root.setTarget(AuditTarget.COURSE);
        root.setChildren(new ArrayList<>());
        root.setScores(new LinkedHashMap<>());
        root.setMetadata(new LinkedHashMap<>());
        return new AuditReport(root);
    }

    private RevisionEngineConfig buildHumanConfig(
            RefinementPlanStore planStore,
            AuditReportStore auditReportStore,
            RevisionArtifactStore artifactStore,
            CourseRepository courseRepository,
            CourseElementLocator elementLocator) {

        CorrectionContext stubContext = mock(CorrectionContext.class);
        CorrectionContextResolver<CorrectionContext> contextResolver =
                (report, task) -> Optional.of(stubContext);

        RevisionValidator humanValidator = new DefaultRevisionValidatorFactory().create(ApprovalMode.HUMAN);
        RevisionEngineConfig config = new RevisionEngineConfig();
        config.setRevisers(Map.of());
        config.setValidator(humanValidator);
        config.setArtifactStore(artifactStore);
        config.setCourseRepository(courseRepository);
        config.setElementLocator(elementLocator);
        config.setRefinementPlanStore(planStore);
        config.setAuditReportStore(auditReportStore);
        config.setContextResolver(contextResolver);
        config.setLemmaAbsenceStrategyRegistry(null);
        config.setLemmaAbsenceProposalDeriver(null);
        return config;
    }

    // -------------------------------------------------------------------------
    // path-1: configurar_modo_humano → iniciar_revision → emitir_pendiente → operador_rechaza
    //         → transicionar_a_rechazado → tarea_vuelve_pending → success
    // Gates: R005, R007/R008/R009, R012/R013, R012, R014
    // -------------------------------------------------------------------------

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: La CLI arranca con CONTENT_AUDIT_APPR... → El operador invoca 'content-audit rev... → El validator humano emite PENDING_APPR... → El operador invoca 'content-audit rej... → El sistema transiciona el veredicto a... → La RefinementTask vuelve a su estado ... → success")
    public void path1_success() {
        // ── Arrange ─────────────────────────────────────────────────────────────
        RefinementPlanStore planStore       = mock(RefinementPlanStore.class);
        AuditReportStore auditReportStore   = mock(AuditReportStore.class);
        RevisionArtifactStore artifactStore = mock(RevisionArtifactStore.class);
        CourseRepository courseRepository   = mock(CourseRepository.class);
        CourseElementLocator elementLocator = mock(CourseElementLocator.class);

        RefinementPlan plan = buildPlan();
        AuditReport auditReport = buildMinimalAuditReport();
        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, QUIZ_ID, null);
        CourseEntity course = mock(CourseEntity.class);

        when(planStore.load(PLAN_ID)).thenReturn(Optional.of(plan));
        when(auditReportStore.load(AUDIT_ID)).thenReturn(Optional.of(auditReport));
        when(artifactStore.hasPendingProposalForTask(PLAN_ID, TASK_ID)).thenReturn(false);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(elementLocator.snapshot(course, AuditTarget.QUIZ, QUIZ_ID)).thenReturn(Optional.of(snapshot));
        when(artifactStore.save(any(RevisionArtifact.class))).thenAnswer(inv -> {
            RevisionArtifact art = inv.getArgument(0);
            return ".content-audit/revisions/" + PLAN_ID + "/" + art.getProposal().getProposalId();
        });

        // ── Phase 1: iniciar_revision / emitir_pendiente ─────────────────────────
        // Gate R007/R008/R009: human validator emits PENDING_APPROVAL; artifact persisted; course untouched.
        RevisionEngineConfig config = buildHumanConfig(
                planStore, auditReportStore, artifactStore, courseRepository, elementLocator);
        RevisionEngine engine = new DefaultRevisionEngineFactory().create(config);
        RevisionOutcome proposeOutcome = engine.revise(PLAN_ID, TASK_ID, COURSE_PATH);

        assertEquals(RevisionOutcomeKind.PENDING_APPROVAL_PERSISTED, proposeOutcome.getKind(),
                "path-1 propose: human validator must yield PENDING_APPROVAL_PERSISTED (R007, R008, R009)");
        assertEquals(RevisionVerdict.PENDING_APPROVAL, proposeOutcome.getArtifact().getVerdict(),
                "artifact verdict must be PENDING_APPROVAL after propose (R007/R008)");

        // Gate R008: course NOT written during propose phase
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));

        // Gate R009: task stays PENDING — engine saves plan unchanged (DOUBT-AWAITING-STATE Option B);
        // plan.save IS called once but the task status is still PENDING (not DONE).
        // We do not assert never() here since the engine always persists the plan on PENDING_APPROVAL.

        String proposalId = proposeOutcome.getArtifact().getProposal().getProposalId();

        // Reset course-repository invocation counts so we can assert the reject phase independently.
        // The propose phase calls courseRepository.load() to snapshot the element — that is expected.
        // Gate R012 is about the REJECT phase not touching the course.
        org.mockito.Mockito.clearInvocations(courseRepository);

        // ── Phase 2: operador_rechaza / transicionar_a_rechazado / tarea_vuelve_pending ──
        // Gate R012/R013: reject only if PENDING_APPROVAL; course NOT touched on reject.
        // Gate R014: task returns to PENDING.
        RevisionArtifact pendingArtifact = proposeOutcome.getArtifact();
        when(artifactStore.findByProposalId(eq(proposalId), any()))
                .thenReturn(Optional.of(pendingArtifact));
        RefinementPlan freshPlan = buildPlan();
        when(planStore.load(PLAN_ID)).thenReturn(Optional.of(freshPlan));

        RevisionEngineConfig decideConfig = new RevisionEngineConfig();
        decideConfig.setArtifactStore(artifactStore);
        decideConfig.setCourseRepository(courseRepository);
        decideConfig.setElementLocator(elementLocator);
        decideConfig.setRefinementPlanStore(planStore);
        ProposalDecisionService decisionService = new DefaultProposalDecisionServiceFactory().create(decideConfig);

        String reason = "Content quality insufficient for this level";
        ProposalDecisionOutcome rejectOutcome = decisionService.reject(
                proposalId, Optional.of(PLAN_ID), Optional.of(reason));

        // Gate R012: outcome is REJECTED; course NOT loaded or saved
        assertEquals(ProposalDecisionOutcomeKind.REJECTED, rejectOutcome.getKind(),
                "path-1 reject: outcome must be REJECTED (R012)");
        verify(courseRepository, never()).load(any(Path.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));

        // Gate R012: artifact rewritten with REJECTED verdict
        assertNotNull(rejectOutcome.getArtifact(), "artifact must be present after reject");
        assertEquals(RevisionVerdict.REJECTED, rejectOutcome.getArtifact().getVerdict(),
                "artifact verdict must be REJECTED (R012)");

        // Gate R012: decisionNote carries the --reason text
        assertEquals(reason, rejectOutcome.getArtifact().getDecisionNote(),
                "artifact decisionNote must carry the --reason text (R012)");

        // Gate R014: task returns to PENDING — plan was saved at least twice:
        //   1st time during propose phase (engine saves plan unchanged, Option B of DOUBT-AWAITING-STATE)
        //   2nd time during reject phase (decisionService saves plan with task still PENDING)
        // We capture all saves and verify the last one carries the task in PENDING state.
        ArgumentCaptor<RefinementPlan> planCaptor = ArgumentCaptor.forClass(RefinementPlan.class);
        verify(planStore, org.mockito.Mockito.atLeast(1)).save(planCaptor.capture());
        RefinementPlan lastSavedPlan = planCaptor.getAllValues().get(planCaptor.getAllValues().size() - 1);
        RefinementTask savedTask = lastSavedPlan.getTasks().stream()
                .filter(t -> TASK_ID.equals(t.getId())).findFirst()
                .orElseThrow(() -> new AssertionError("Task " + TASK_ID + " not found in saved plan"));
        assertEquals(RefinementTaskStatus.PENDING, savedTask.getStatus(),
                "R014: task must return to PENDING after reject");
    }
}
