package com.learney.contentaudit.revisiondomain;

import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreview;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface ImpactPreviewStore {
    void save(ImpactPreview preview);

    Optional<ImpactPreview> findByProposalId(String proposalId);
}
