package com.learney.contentaudit.revisiondomain;

import com.learney.contentaudit.revisiondomain.preservation.PreservationCheck;
import com.learney.contentaudit.revisiondomain.preservation.PreservationRepair;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface PreservationFactory {
    PreservationCheck createCheck();

    PreservationRepair createRepair(RevisionArtifactStore artifactStore);
}
