package com.learney.contentaudit.revisiondomain;

import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.CourseMapper;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionComplianceChecker;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionSubjectViewFactory;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.CorrectionContext;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessor;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionCorrectionConfig;
import java.util.Map;
import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class RevisionEngineConfig {
    private Map<DiagnosisKind, Reviser> revisers;

    private RevisionValidator validator;

    private RevisionArtifactStore artifactStore;

    private CourseRepository courseRepository;

    private CourseElementLocator elementLocator;

    private RefinementPlanStore refinementPlanStore;

    private AuditReportStore auditReportStore;

    private CorrectionContextResolver<CorrectionContext> contextResolver;

    private LemmaAbsenceProposalStrategyRegistry lemmaAbsenceStrategyRegistry;

    private LemmaAbsenceProposalDeriver lemmaAbsenceProposalDeriver;

    private CourseMapper courseMapper;

    private AuditEngine auditEngine;

    private ImpactPreviewStore impactPreviewStore;

    private CorrectionContextOverrideParser correctionContextOverrideParser;

    private KnowledgeTitleProposalStrategyRegistry knowledgeTitleStrategyRegistry;

    private KnowledgeTitleProposalDeriver knowledgeTitleProposalDeriver;

    private QuizInstructionProposalStrategyRegistry quizInstructionStrategyRegistry;

    private CandidateAssessor candidateAssessor;

    private QuizInstructionComplianceChecker quizInstructionComplianceChecker;

    private QuizInstructionSubjectViewFactory quizInstructionSubjectViewFactory;

    private QuizInstructionCorrectionConfig quizInstructionCorrectionConfig;

    public RevisionEngineConfig() {
    }

    public RevisionEngineConfig(Map<DiagnosisKind, Reviser> revisers, RevisionValidator validator,
            RevisionArtifactStore artifactStore, CourseRepository courseRepository,
            CourseElementLocator elementLocator, RefinementPlanStore refinementPlanStore,
            AuditReportStore auditReportStore,
            CorrectionContextResolver<CorrectionContext> contextResolver,
            LemmaAbsenceProposalStrategyRegistry lemmaAbsenceStrategyRegistry,
            LemmaAbsenceProposalDeriver lemmaAbsenceProposalDeriver, CourseMapper courseMapper,
            AuditEngine auditEngine, ImpactPreviewStore impactPreviewStore,
            CorrectionContextOverrideParser correctionContextOverrideParser,
            KnowledgeTitleProposalStrategyRegistry knowledgeTitleStrategyRegistry,
            KnowledgeTitleProposalDeriver knowledgeTitleProposalDeriver,
            QuizInstructionProposalStrategyRegistry quizInstructionStrategyRegistry,
            CandidateAssessor candidateAssessor,
            QuizInstructionComplianceChecker quizInstructionComplianceChecker,
            QuizInstructionSubjectViewFactory quizInstructionSubjectViewFactory,
            QuizInstructionCorrectionConfig quizInstructionCorrectionConfig) {
        this.revisers = revisers;
        this.validator = validator;
        this.artifactStore = artifactStore;
        this.courseRepository = courseRepository;
        this.elementLocator = elementLocator;
        this.refinementPlanStore = refinementPlanStore;
        this.auditReportStore = auditReportStore;
        this.contextResolver = contextResolver;
        this.lemmaAbsenceStrategyRegistry = lemmaAbsenceStrategyRegistry;
        this.lemmaAbsenceProposalDeriver = lemmaAbsenceProposalDeriver;
        this.courseMapper = courseMapper;
        this.auditEngine = auditEngine;
        this.impactPreviewStore = impactPreviewStore;
        this.correctionContextOverrideParser = correctionContextOverrideParser;
        this.knowledgeTitleStrategyRegistry = knowledgeTitleStrategyRegistry;
        this.knowledgeTitleProposalDeriver = knowledgeTitleProposalDeriver;
        this.quizInstructionStrategyRegistry = quizInstructionStrategyRegistry;
        this.candidateAssessor = candidateAssessor;
        this.quizInstructionComplianceChecker = quizInstructionComplianceChecker;
        this.quizInstructionSubjectViewFactory = quizInstructionSubjectViewFactory;
        this.quizInstructionCorrectionConfig = quizInstructionCorrectionConfig;
    }

    public Map<DiagnosisKind, Reviser> getRevisers() {
        return this.revisers;
    }

    public void setRevisers(Map<DiagnosisKind, Reviser> revisers) {
        this.revisers = revisers;
    }

    public RevisionValidator getValidator() {
        return this.validator;
    }

    public void setValidator(RevisionValidator validator) {
        this.validator = validator;
    }

    public RevisionArtifactStore getArtifactStore() {
        return this.artifactStore;
    }

    public void setArtifactStore(RevisionArtifactStore artifactStore) {
        this.artifactStore = artifactStore;
    }

    public CourseRepository getCourseRepository() {
        return this.courseRepository;
    }

    public void setCourseRepository(CourseRepository courseRepository) {
        this.courseRepository = courseRepository;
    }

    public CourseElementLocator getElementLocator() {
        return this.elementLocator;
    }

    public void setElementLocator(CourseElementLocator elementLocator) {
        this.elementLocator = elementLocator;
    }

    public RefinementPlanStore getRefinementPlanStore() {
        return this.refinementPlanStore;
    }

    public void setRefinementPlanStore(RefinementPlanStore refinementPlanStore) {
        this.refinementPlanStore = refinementPlanStore;
    }

    public AuditReportStore getAuditReportStore() {
        return this.auditReportStore;
    }

    public void setAuditReportStore(AuditReportStore auditReportStore) {
        this.auditReportStore = auditReportStore;
    }

    public CorrectionContextResolver<CorrectionContext> getContextResolver() {
        return this.contextResolver;
    }

    public void setContextResolver(CorrectionContextResolver<CorrectionContext> contextResolver) {
        this.contextResolver = contextResolver;
    }

    public LemmaAbsenceProposalStrategyRegistry getLemmaAbsenceStrategyRegistry() {
        return this.lemmaAbsenceStrategyRegistry;
    }

    public void setLemmaAbsenceStrategyRegistry(
            LemmaAbsenceProposalStrategyRegistry lemmaAbsenceStrategyRegistry) {
        this.lemmaAbsenceStrategyRegistry = lemmaAbsenceStrategyRegistry;
    }

    public LemmaAbsenceProposalDeriver getLemmaAbsenceProposalDeriver() {
        return this.lemmaAbsenceProposalDeriver;
    }

    public void setLemmaAbsenceProposalDeriver(
            LemmaAbsenceProposalDeriver lemmaAbsenceProposalDeriver) {
        this.lemmaAbsenceProposalDeriver = lemmaAbsenceProposalDeriver;
    }

    public CourseMapper getCourseMapper() {
        return this.courseMapper;
    }

    public void setCourseMapper(CourseMapper courseMapper) {
        this.courseMapper = courseMapper;
    }

    public AuditEngine getAuditEngine() {
        return this.auditEngine;
    }

    public void setAuditEngine(AuditEngine auditEngine) {
        this.auditEngine = auditEngine;
    }

    public ImpactPreviewStore getImpactPreviewStore() {
        return this.impactPreviewStore;
    }

    public void setImpactPreviewStore(ImpactPreviewStore impactPreviewStore) {
        this.impactPreviewStore = impactPreviewStore;
    }

    public CorrectionContextOverrideParser getCorrectionContextOverrideParser() {
        return this.correctionContextOverrideParser;
    }

    public void setCorrectionContextOverrideParser(
            CorrectionContextOverrideParser correctionContextOverrideParser) {
        this.correctionContextOverrideParser = correctionContextOverrideParser;
    }

    public KnowledgeTitleProposalStrategyRegistry getKnowledgeTitleStrategyRegistry() {
        return this.knowledgeTitleStrategyRegistry;
    }

    public void setKnowledgeTitleStrategyRegistry(
            KnowledgeTitleProposalStrategyRegistry knowledgeTitleStrategyRegistry) {
        this.knowledgeTitleStrategyRegistry = knowledgeTitleStrategyRegistry;
    }

    public KnowledgeTitleProposalDeriver getKnowledgeTitleProposalDeriver() {
        return this.knowledgeTitleProposalDeriver;
    }

    public void setKnowledgeTitleProposalDeriver(
            KnowledgeTitleProposalDeriver knowledgeTitleProposalDeriver) {
        this.knowledgeTitleProposalDeriver = knowledgeTitleProposalDeriver;
    }

    public QuizInstructionProposalStrategyRegistry getQuizInstructionStrategyRegistry() {
        return this.quizInstructionStrategyRegistry;
    }

    public void setQuizInstructionStrategyRegistry(
            QuizInstructionProposalStrategyRegistry quizInstructionStrategyRegistry) {
        this.quizInstructionStrategyRegistry = quizInstructionStrategyRegistry;
    }

    public CandidateAssessor getCandidateAssessor() {
        return this.candidateAssessor;
    }

    public void setCandidateAssessor(CandidateAssessor candidateAssessor) {
        this.candidateAssessor = candidateAssessor;
    }

    public QuizInstructionComplianceChecker getQuizInstructionComplianceChecker() {
        return this.quizInstructionComplianceChecker;
    }

    public void setQuizInstructionComplianceChecker(
            QuizInstructionComplianceChecker quizInstructionComplianceChecker) {
        this.quizInstructionComplianceChecker = quizInstructionComplianceChecker;
    }

    public QuizInstructionSubjectViewFactory getQuizInstructionSubjectViewFactory() {
        return this.quizInstructionSubjectViewFactory;
    }

    public void setQuizInstructionSubjectViewFactory(
            QuizInstructionSubjectViewFactory quizInstructionSubjectViewFactory) {
        this.quizInstructionSubjectViewFactory = quizInstructionSubjectViewFactory;
    }

    public QuizInstructionCorrectionConfig getQuizInstructionCorrectionConfig() {
        return this.quizInstructionCorrectionConfig;
    }

    public void setQuizInstructionCorrectionConfig(
            QuizInstructionCorrectionConfig quizInstructionCorrectionConfig) {
        this.quizInstructionCorrectionConfig = quizInstructionCorrectionConfig;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RevisionEngineConfig that = (RevisionEngineConfig) o;
        return Objects.equals(this.revisers, that.revisers)
                    && Objects.equals(this.validator, that.validator)
                    && Objects.equals(this.artifactStore, that.artifactStore)
                    && Objects.equals(this.courseRepository, that.courseRepository)
                    && Objects.equals(this.elementLocator, that.elementLocator)
                    && Objects.equals(this.refinementPlanStore, that.refinementPlanStore)
                    && Objects.equals(this.auditReportStore, that.auditReportStore)
                    && Objects.equals(this.contextResolver, that.contextResolver)
                    && Objects.equals(this.lemmaAbsenceStrategyRegistry, that.lemmaAbsenceStrategyRegistry)
                    && Objects.equals(this.lemmaAbsenceProposalDeriver, that.lemmaAbsenceProposalDeriver)
                    && Objects.equals(this.courseMapper, that.courseMapper)
                    && Objects.equals(this.auditEngine, that.auditEngine)
                    && Objects.equals(this.impactPreviewStore, that.impactPreviewStore)
                    && Objects.equals(this.correctionContextOverrideParser, that.correctionContextOverrideParser)
                    && Objects.equals(this.knowledgeTitleStrategyRegistry, that.knowledgeTitleStrategyRegistry)
                    && Objects.equals(this.knowledgeTitleProposalDeriver, that.knowledgeTitleProposalDeriver)
                    && Objects.equals(this.quizInstructionStrategyRegistry, that.quizInstructionStrategyRegistry)
                    && Objects.equals(this.candidateAssessor, that.candidateAssessor)
                    && Objects.equals(this.quizInstructionComplianceChecker, that.quizInstructionComplianceChecker)
                    && Objects.equals(this.quizInstructionSubjectViewFactory, that.quizInstructionSubjectViewFactory)
                    && Objects.equals(this.quizInstructionCorrectionConfig, that.quizInstructionCorrectionConfig);
    }

    @Override
    public int hashCode() {
        return Objects.hash(revisers, validator, artifactStore, courseRepository, elementLocator, refinementPlanStore, auditReportStore, contextResolver, lemmaAbsenceStrategyRegistry, lemmaAbsenceProposalDeriver, courseMapper, auditEngine, impactPreviewStore, correctionContextOverrideParser, knowledgeTitleStrategyRegistry, knowledgeTitleProposalDeriver, quizInstructionStrategyRegistry, candidateAssessor, quizInstructionComplianceChecker, quizInstructionSubjectViewFactory, quizInstructionCorrectionConfig);
    }
}
