package com.learney.contentaudit.revisiondomain.candidatecriteria;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class AbsoluteCriterionEvaluatorMissingException extends RuntimeException {
    private final CorrectionCriterion criterion;

    public AbsoluteCriterionEvaluatorMissingException(CorrectionCriterion criterion) {
        super(String.format("No se puede construir el catalogo de criterios: falta el evaluador del criterio absoluto '%s'", criterion));
        this.criterion = criterion;
    }

    public CorrectionCriterion getCriterion() {
        return this.criterion;
    }
}
