package com.learney.contentaudit.revisiondomain.candidatecriteria;

import java.util.List;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface CandidateAssessor {
    CandidateAssessment assess(CandidateAssessmentInput input);

    List<CorrectionCriterion> catalog();
}
