package com.learney.contentaudit.nlpinfrastructure.spacy;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.NlpToken;
import com.learney.contentaudit.auditdomain.NlpTokenizer;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class CachedNlpTokenizerTest {

    @Test
    @DisplayName("should serve repeated analyzeTokens calls for the same sentence text from an in-memory cache so that the delegate NlpTokenizer is invoked only on the first call")
    @Tag("FEAT-NLP")
    @Tag("F-NLP-R023")
    public void shouldServeRepeatedAnalyzeTokensCallsForTheSameSentenceTextFromAnInmemoryCacheSoThatTheDelegateNlpTokenizerIsInvokedOnlyOnTheFirstCall(
            ) {
        // R023: second call for the same sentence must be served from cache — delegate not invoked again
        NlpTokenizer delegate = mock(NlpTokenizer.class);
        NlpToken token = new NlpToken("cat", "cat", "NOUN", 300, false, false);
        when(delegate.analyzeTokens("cats")).thenReturn(List.of(token));

        CachedNlpTokenizer sut = new CachedNlpTokenizer(delegate);

        List<NlpToken> first = sut.analyzeTokens("cats");
        List<NlpToken> second = sut.analyzeTokens("cats");

        // Delegate must be invoked exactly once — second call is served from cache
        verify(delegate, times(1)).analyzeTokens("cats");
        assertEquals(first, second, "R023: cached result must equal the first call's result");
        assertNotNull(second, "R023: cached result must not be null");
    }

    @Test
    @DisplayName("should treat two sentences differing in any single character (case spacing punctuation) as distinct cache entries triggering a fresh delegate invocation for each variant")
    @Tag("FEAT-NLP")
    @Tag("F-NLP-R024")
    public void shouldTreatTwoSentencesDifferingInAnySingleCharacterCaseSpacingPunctuationAsDistinctCacheEntriesTriggeringAFreshDelegateInvocationForEachVariant(
            ) {
        // R024: exact text is the cache key — any character difference means a cache miss
        NlpTokenizer delegate = mock(NlpTokenizer.class);
        NlpToken lowerToken = new NlpToken("cat", "cat", "NOUN", 300, false, false);
        NlpToken upperToken = new NlpToken("Cat", "cat", "NOUN", 300, false, false);
        NlpToken spacedToken = new NlpToken("cat", "cat", "NOUN", 300, false, false);
        when(delegate.analyzeTokens("cat")).thenReturn(List.of(lowerToken));
        when(delegate.analyzeTokens("Cat")).thenReturn(List.of(upperToken));
        when(delegate.analyzeTokens("cat ")).thenReturn(List.of(spacedToken));

        CachedNlpTokenizer sut = new CachedNlpTokenizer(delegate);

        sut.analyzeTokens("cat");    // miss — delegates
        sut.analyzeTokens("Cat");    // miss — different case, delegates again
        sut.analyzeTokens("cat ");   // miss — trailing space, delegates again
        sut.analyzeTokens("cat");    // hit — served from cache

        // Each distinct key triggers exactly one delegate call
        verify(delegate, times(1)).analyzeTokens("cat");
        verify(delegate, times(1)).analyzeTokens("Cat");
        verify(delegate, times(1)).analyzeTokens("cat ");
    }

    @Test
    @DisplayName("should cache List<NlpToken> produced by analyzeTokens with the same decorator pattern previously used for tokenize String results so cached entries match the enriched signature")
    @Tag("FEAT-NLP")
    @Tag("F-NLP-R026")
    public void shouldCacheListNlpTokenProducedByAnalyzeTokensWithTheSameDecoratorPatternPreviouslyUsedForTokenizeStringResultsSoCachedEntriesMatchTheEnrichedSignature(
            ) {
        // R026: CachedNlpTokenizer wraps the enriched analyzeTokens result in its cache,
        // using the same decorator pattern previously used for List<String> tokenize.
        NlpTokenizer delegate = mock(NlpTokenizer.class);
        NlpToken runToken = new NlpToken("running", "run", "VERB", 245, false, false);
        NlpToken sheToken = new NlpToken("She", "she", "PRON", 12, true, false);
        String sentence = "She running";
        when(delegate.analyzeTokens(sentence)).thenReturn(List.of(sheToken, runToken));

        CachedNlpTokenizer sut = new CachedNlpTokenizer(delegate);

        // First call — delegate invoked, result stored in cache
        List<NlpToken> result = sut.analyzeTokens(sentence);
        // Second call — served from cache with full NlpToken list
        List<NlpToken> cached = sut.analyzeTokens(sentence);

        verify(delegate, times(1)).analyzeTokens(sentence);
        assertEquals(2, cached.size(), "R026: cached result must contain all enriched tokens");
        // Verify the cached entries are the full NlpToken objects (not degraded to plain strings)
        assertEquals("run", cached.get(1).getLemma(),
                "R026: cached NlpToken must preserve enriched fields (lemma)");
        assertEquals("VERB", cached.get(1).getPosTag(),
                "R026: cached NlpToken must preserve enriched fields (posTag)");
        assertEquals(245, cached.get(1).getFrequencyRank(),
                "R026: cached NlpToken must preserve enriched fields (frequencyRank)");
    }
}
