package com.learney.contentaudit.auditdomain.quizinstructionengine;

import com.learney.contentaudit.auditdomain.AmbiguousReevaluationScopeException;
import com.learney.contentaudit.auditdomain.ContentAnalyzer;
import com.learney.contentaudit.auditdomain.EmptyReevaluationSetException;
import com.learney.contentaudit.auditdomain.EvaluationRunPolicy;
import com.learney.contentaudit.auditdomain.QuizInstructionConfig;
import com.learney.contentaudit.auditdomain.QuizInstructionVerdictReader;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationBudget;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSession;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSessionFactory;
import com.learney.contentaudit.evaluationledgerdomain.Evaluator;
import java.util.Set;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
public class DefaultQuizInstructionAnalyzerFactoryTest {

    @Mock
    private EvaluationSessionFactory sessionFactory;

    @Mock
    private Evaluator evaluator;

    @Mock
    private QuizInstructionVerdictReader verdictReader;

    @Mock
    private QuizInstructionConfig config;

    @Mock
    private EvaluationSession session;

    @InjectMocks
    private DefaultQuizInstructionAnalyzerFactory sut;

    @Test
    @DisplayName("should build the analyzer with the configured default budget when the run declares no policy for the judge")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R006")
    public void shouldBuildTheAnalyzerWithTheConfiguredDefaultBudgetWhenTheRunDeclaresNoPolicyForTheJudge(
            ) {
        Mockito.when(config.getDefaultMaxNewEvaluations()).thenReturn(500);
        Mockito.when(sessionFactory.open(Mockito.any(), Mockito.eq(evaluator))).thenReturn(session);

        // The run declares no policy for this evaluator: DefaultAuditRunner would pass null here
        // when its per-evaluator policy map has no entry for this factory's evaluatorId.
        ContentAnalyzer analyzer = sut.create(null);

        Assertions.assertNotNull(analyzer,
                "R006: the factory must still build a usable analyzer without an explicit run policy");

        ArgumentCaptor<EvaluationBudget> policyCaptor = ArgumentCaptor.forClass(EvaluationBudget.class);
        Mockito.verify(sessionFactory).open(policyCaptor.capture(), Mockito.eq(evaluator));
        EvaluationBudget usedPolicy = policyCaptor.getValue();

        Assertions.assertNotNull(usedPolicy,
                "R006: a session must be opened with a concrete policy even absent an explicit one");
        Assertions.assertEquals(500, usedPolicy.getMaxNewEvaluations(),
                "R006: absent a per-run policy, the configured default budget must be used");
    }

    @Test
    @DisplayName("should publish for selection exactly the name under which the analyzer it builds reports its score")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R015")
    public void shouldPublishForSelectionExactlyTheNameUnderWhichTheAnalyzerItBuildsReportsItsScore() {
        // R015: the name under which this analysis is selected/excluded/budgeted --
        // analyzerName(), read by DefaultAuditRunner -- must be exactly the name under
        // which the analyzer this same factory builds reports its own score in the audit
        // report (ContentAnalyzer.getName()). These are two methods on two different
        // objects (the factory and the analyzer it assembles); nothing in the contract
        // keeps them equal by construction except the factory's own coherence.
        Mockito.when(config.getDefaultMaxNewEvaluations()).thenReturn(500);
        Mockito.when(sessionFactory.open(Mockito.any(), Mockito.eq(evaluator))).thenReturn(session);

        ContentAnalyzer analyzer = sut.create(null);

        Assertions.assertEquals(sut.analyzerName(), analyzer.getName(),
                "R015: the factory's published analyzerName() must be exactly the name the analyzer it builds "
                + "reports via getName() -- a single name, the one read is the one written");
    }

    @Test
    @DisplayName("should reject the run request that declares an empty set of quizzes, before opening the evaluation session")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R018")
    public void shouldRejectTheRunRequestThatDeclaresAnEmptySetOfQuizzesBeforeOpeningTheEvaluationSession() {
        // Conjunto declarado y vacio: NO equivale a "todo el curso" -- se rechaza (R018 inv.3)
        EvaluationRunPolicy policy = new EvaluationRunPolicy(500, false, null, Set.of());

        Assertions.assertThrows(EmptyReevaluationSetException.class, () -> sut.create(policy),
                "R018: a run request that declares an empty set of quizzes must be rejected, not read as the whole course");

        Mockito.verifyNoInteractions(sessionFactory);
    }

    @Test
    @DisplayName("should reject the run request that declares a set of quizzes together with a course area, before opening the evaluation session")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R018")
    public void shouldRejectTheRunRequestThatDeclaresASetOfQuizzesTogetherWithACourseAreaBeforeOpeningTheEvaluationSession() {
        // Conjunto declarado Y area del curso a la vez: dos lecturas posibles (interseccion/union)
        // que difieren en ordenes de magnitud de gasto -- se rechaza sin adivinar (R018 inv.3)
        EvaluationRunPolicy policy = new EvaluationRunPolicy(500, true, "knowledge-a", Set.of("quiz-a1"));

        Assertions.assertThrows(AmbiguousReevaluationScopeException.class, () -> sut.create(policy),
                "R018: a run request that declares both a set of quizzes and a course area at once must be rejected, "
                + "since neither intersection nor union can be chosen without guessing");

        Mockito.verifyNoInteractions(sessionFactory);
    }
}
