package com.learney.contentaudit.auditdomain.quizinstructionengine;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableKnowledge;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultQuizInstructionScopeMatcherTest {

    private DefaultQuizInstructionScopeMatcher sut;

    @BeforeEach
    public void setUp() {
        sut = new DefaultQuizInstructionScopeMatcher();
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private static AuditNode buildKnowledgeNode(String knowledgeId) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.KNOWLEDGE);
        node.setEntity(new AuditableKnowledge(
                List.of(), "K", "Instructions", true, knowledgeId, "K label", "K", null, "Topic"));
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        return node;
    }

    private static AuditNode buildQuizNodeUnder(AuditNode knowledgeNode, String quizId) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setEntity(new AuditableQuiz(
                List.of(), quizId, "Q", "Q", null, List.of("s"), null, "Instructions", List.of()));
        node.setParent(knowledgeNode);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        knowledgeNode.getChildren().add(node);
        return node;
    }

    @Test
    @DisplayName("should match only the quizzes selected by the requested re evaluation scope")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R012")
    public void shouldMatchOnlyTheQuizzesSelectedByTheRequestedReEvaluationScope() {
        AuditNode knowledgeA = buildKnowledgeNode("knowledge-a");
        AuditNode quizUnderA = buildQuizNodeUnder(knowledgeA, "quiz-a1");

        AuditNode knowledgeB = buildKnowledgeNode("knowledge-b");
        AuditNode quizUnderB = buildQuizNodeUnder(knowledgeB, "quiz-b1");

        Assertions.assertTrue(sut.matches(quizUnderA, "knowledge-a"),
                "R012: a quiz within the requested scope must match");
        Assertions.assertFalse(sut.matches(quizUnderB, "knowledge-a"),
                "R012: a quiz outside the requested scope must not match, so the re-evaluation stays acotable");
    }

    @Test
    @DisplayName("should match every reached quiz when the re evaluation request declares no scope")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R012")
    public void shouldMatchEveryReachedQuizWhenTheReEvaluationRequestDeclaresNoScope() {
        AuditNode knowledgeA = buildKnowledgeNode("knowledge-a");
        AuditNode quizUnderA = buildQuizNodeUnder(knowledgeA, "quiz-a1");

        AuditNode knowledgeB = buildKnowledgeNode("knowledge-b");
        AuditNode quizUnderB = buildQuizNodeUnder(knowledgeB, "quiz-b1");

        Assertions.assertTrue(sut.matches(quizUnderA, null),
                "R012: a re-evaluation request without a declared scope must reach the whole course");
        Assertions.assertTrue(sut.matches(quizUnderB, null),
                "R012: a re-evaluation request without a declared scope must reach the whole course");
    }
}
