package com.learney.contentaudit.auditcli.bootstrap;

import com.learney.contentaudit.quizinstructioninfrastructure.QuizInstructionJudgeConfig;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultQuizInstructionJudgeConfigResolver implements QuizInstructionJudgeConfigResolver {
    @Override
    public QuizInstructionJudgeConfig resolve() {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
