package com.learney.contentaudit.auditcli.bootstrap;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class InvalidApprovalModeException extends RuntimeException {
    private final String value;

    public InvalidApprovalModeException(String value) {
        super(String.format("Invalid value for CONTENT_AUDIT_APPROVAL_MODE: '%s'. Allowed: auto, human", value));
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }
}
