package com.learney.contentaudit.auditcli.bootstrap;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class InvalidProposalStrategyException extends RuntimeException {
    private final String value;

    private final String registered;

    public InvalidProposalStrategyException(String value, String registered) {
        super(String.format("Invalid value for CONTENT_AUDIT_LAPS_STRATEGY: '%s'. Registered: %s", value, registered));
        this.value = value;
        this.registered = registered;
    }

    public String getValue() {
        return this.value;
    }

    public String getRegistered() {
        return this.registered;
    }
}
