package com.learney.contentaudit.coursedomain.quizsentenceengine;

import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.coursedomain.quizsentence.QuizSentenceSerializationException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;
import javax.annotation.processing.Generated;

/**
 * Derives the ordered list of plain sentences from a {@code FormEntity.sentenceParts}.
 *
 * <p>Rules applied:
 * <ul>
 *   <li>R017 – One sentence per variant combination; canonical (index 0) uses the first
 *              sub-variant of the first entry of each CLOZE.</li>
 *   <li>R018 – Canonical variant = first sub-variant (before first {@code |}) of first entry.</li>
 *   <li>R019 – Hints (parenthesized scaffolding) are stripped; whitespace normalized.</li>
 *   <li>R024 – Any invalid input triggers atomic failure.</li>
 * </ul>
 *
 * <p>Multi-CLOZE combinatorics: the list contains one sentence per combination of one
 * variant from each CLOZE. The ordering is lexicographic on (CLOZE position, variant index).
 * Index 0 is always the all-canonical combination.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class PlainSentenceDeriver {

    /** Matches a parenthesized hint block anywhere in TEXT (R007, R019). */
    private static final Pattern HINT_PATTERN = Pattern.compile("\\([^)]*\\)");

    private final WhitespaceNormalizer whitespaceNormalizer;

public PlainSentenceDeriver(WhitespaceNormalizer whitespaceNormalizer) {
    this.whitespaceNormalizer = whitespaceNormalizer;
}


    /** Pattern that matches a sentence-terminal punctuation at end of a string. */
    private static final Pattern SENTENCE_END_PATTERN = Pattern.compile(".*[.?!]\\s*$");

    /**
     * Post-processes a derived sentence list by removing spurious spaces that appear
     * immediately before sentence-ending punctuation ({@code .?!}) left over after
     * hint-stripping (e.g. {@code "She dances well ."} → {@code "She dances well."}).
     */
    private List<String> removeSpaceBeforePunctuation(List<String> sentences) {
        if (sentences == null || sentences.isEmpty()) {
            return sentences;
        }
        List<String> result = new ArrayList<>(sentences.size());
        for (String s : sentences) {
            result.add(s == null ? null : s.replaceAll("\\s+([.?!])", "$1"));
        }
        return result;
    }

    /**
     * Derives all plain sentences from {@code form.sentenceParts} using the given mode
     * (F-SMODE-R003, R004).
     *
     * <ul>
     *   <li>FILL or null — delegates to {@link #derive(FormEntity)} (full-sentence, mode-blind),
     *       then removes any space that appears immediately before sentence-ending punctuation
     *       (artifact of hint-stripping inside TEXT parts).</li>
     *   <li>REWRITE — derives only the segment(s) that contain at least one CLOZE part,
     *       excluding any TEXT-only scaffold sentence that precedes the first CLOZE and ends
     *       with sentence-terminal punctuation ({@code .?!}).</li>
     * </ul>
     *
     * @param form the form to derive sentences from
     * @param mode the sentence mode; null is treated as FILL
     * @return ordered list; index 0 is the canonical variant
     */
    List<String> derive(FormEntity form, SentenceMode mode) {
        if (mode != SentenceMode.REWRITE) {
            // FILL or null → full-sentence, mode-blind derivation (legacy behaviour)
            // Apply post-processing to remove spaces before punctuation that arise from hint-stripping
            return removeSpaceBeforePunctuation(derive(form));
        }

        // REWRITE: exclude TEXT-andamio scaffold sentences that precede the first CLOZE
        // and end with sentence-terminal punctuation.
        if (form == null || form.getSentenceParts() == null || form.getSentenceParts().isEmpty()) {
            return List.of();
        }

        List<SentencePartEntity> original = form.getSentenceParts();

        // Identify the index of the first CLOZE part
        int firstClozeIndex = -1;
        for (int i = 0; i < original.size(); i++) {
            if (original.get(i).getKind() == SentencePartKind.CLOZE) {
                firstClozeIndex = i;
                break;
            }
        }

        if (firstClozeIndex < 0) {
            // No CLOZE at all — nothing to exclude; derive as normal (degenerate case)
            return derive(form);
        }

        // Build filtered parts: skip TEXT-scaffold parts that precede the first CLOZE
        // and form a complete sentence (end with . ? !)
        List<SentencePartEntity> filtered = new ArrayList<>();
        for (int i = 0; i < original.size(); i++) {
            SentencePartEntity part = original.get(i);
            if (i < firstClozeIndex
                    && part.getKind() == SentencePartKind.TEXT
                    && isScaffoldSentence(part.getText())) {
                // Skip: this is the source/prompt scaffold TEXT sentence
                continue;
            }
            filtered.add(part);
        }

        if (filtered.isEmpty()) {
            return List.of();
        }

        // Derive from the filtered parts using a temporary FormEntity
        FormEntity rewriteForm = new FormEntity(
                form.getKind(),
                form.getIncidence(),
                form.getLabel(),
                form.getName(),
                filtered);
        return removeSpaceBeforePunctuation(derive(rewriteForm));
    }

    /**
     * Returns true when {@code text} is a scaffold sentence: non-blank text that ends with
     * sentence-terminal punctuation (., ?, !), possibly followed by whitespace.
     */
    private boolean isScaffoldSentence(String text) {
        if (text == null || text.isBlank()) {
            return false;
        }
        return SENTENCE_END_PATTERN.matcher(text).matches();
    }

    /**
     * Derives all plain sentences from {@code form.sentenceParts}.
     *
     * @param form the form to derive sentences from
     * @return ordered list; index 0 is the canonical variant
     * @throws QuizSentenceSerializationException if the sentenceParts violate the convention
     */
    List<String> derive(FormEntity form) {
        if (form == null || form.getSentenceParts() == null || form.getSentenceParts().isEmpty()) {
            return List.of();
        }

        List<SentencePartEntity> parts = form.getSentenceParts();

        // Collect TEXT segments (with hints stripped) and CLOZE variant lists in order
        List<String> textSegments = new ArrayList<>();    // interleaved with clozeVariants
        List<List<String>> clozeVariants = new ArrayList<>();
        // We build a "template" as alternating text/cloze indices.
        // Strategy: build a flat structure as (text | cloze-placeholder)* and then expand.

        // Validate and collect
        for (int i = 0; i < parts.size(); i++) {
            SentencePartEntity part = parts.get(i);
            if (part.getKind() == SentencePartKind.TEXT) {
                // R003 – TEXT must not have options
                if (part.getOptions() != null && !part.getOptions().isEmpty()) {
                    throw new QuizSentenceSerializationException(
                            "El TEXT de indice " + i + " trae options; los TEXT no pueden tener options",
                            String.valueOf(i));
                }
            } else if (part.getKind() == SentencePartKind.CLOZE) {
                // R004 – CLOZE must have at least one option
                if (part.getOptions() == null || part.getOptions().isEmpty()) {
                    throw new QuizSentenceSerializationException(
                            "El CLOZE de indice " + i
                                    + " no tiene options; un CLOZE requiere al menos una respuesta aceptada",
                            String.valueOf(i));
                }
                clozeVariants.add(flattenVariants(part.getOptions()));
            }
        }

        // Build the combinatorial set.
        // We iterate over all combinations of one variant per CLOZE.
        if (clozeVariants.isEmpty()) {
            // Pure-text form: one sentence, no CLOZE
            String sentence = buildSentenceFromParts(parts, new int[0]);
            return List.of(sentence);
        }

        // Compute total combinations
        int total = 1;
        for (List<String> variants : clozeVariants) {
            total *= variants.size();
        }

        List<String> result = new ArrayList<>(total);
        int[] indices = new int[clozeVariants.size()]; // all zeros → canonical combination

        for (int combo = 0; combo < total; combo++) {
            String sentence = buildSentenceFromParts(parts, indices);
            result.add(sentence);
            // Advance indices (least-significant = last CLOZE, like odometer)
            advanceIndices(indices, clozeVariants);
        }

        return result;
    }

    // -------------------------------------------------------------------------
    // Combinatorics helpers
    // -------------------------------------------------------------------------

    /**
     * Flattens all entries (and their pipe-splits) into an ordered flat list of variants.
     * Canonical variant is at index 0.
     */
    private List<String> flattenVariants(List<String> options) {
        List<String> flat = new ArrayList<>();
        for (String entry : options) {
            String[] splits = entry.split("\\|", -1);
            flat.addAll(Arrays.asList(splits));
        }
        return flat;
    }

    /**
     * Advances the odometer indices for the next combination.
     * The rightmost (last CLOZE) advances first; carries propagate left.
     */
    private void advanceIndices(int[] indices, List<List<String>> clozeVariants) {
        for (int i = indices.length - 1; i >= 0; i--) {
            indices[i]++;
            if (indices[i] < clozeVariants.get(i).size()) {
                break;
            }
            indices[i] = 0;
        }
    }

    // -------------------------------------------------------------------------
    // Sentence assembly
    // -------------------------------------------------------------------------

    /**
     * Builds one plain sentence by substituting CLOZE parts with their chosen variant and
     * stripping hints from TEXT parts.
     *
     * @param parts    the sentenceParts of the form
     * @param indices  for each CLOZE (in order of appearance), the chosen variant index
     */
    private String buildSentenceFromParts(List<SentencePartEntity> parts, int[] indices) {
        StringBuilder sb = new StringBuilder();
        int clozeIdx = 0;
        boolean firstTokenEmitted = false;

        for (SentencePartEntity part : parts) {
            String token;
            if (part.getKind() == SentencePartKind.TEXT) {
                String text = part.getText();
                if (text == null || text.isEmpty()) {
                    continue;
                }
                // Strip hints (R019)
                token = HINT_PATTERN.matcher(text).replaceAll("");
            } else if (part.getKind() == SentencePartKind.CLOZE) {
                List<String> flat = flattenVariants(part.getOptions());
                token = flat.get(indices[clozeIdx]);
                clozeIdx++;
            } else {
                continue;
            }

            // Insert canonical single space between emitted tokens; the final
            // whitespace-normalize step collapses any duplicates the raw TEXT
            // may have contributed at the boundary.
            if (firstTokenEmitted) {
                sb.append(' ');
            }
            sb.append(token);
            firstTokenEmitted = true;
        }

        // Normalize whitespace (R019): collapse runs, trim
        return whitespaceNormalizer.normalize(sb.toString());
    }
}
