package com.learney.contentaudit.vocabularyinfrastructure.evp;

import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.EvpCatalogPort;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import java.util.Optional;
import java.util.Set;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class FileSystemEvpCatalog implements EvpCatalogPort {
    @Override
    public Set<LemmaAndPos> getExpectedLemmas(CefrLevel level) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public boolean isPhrase(String lemma) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public Optional<Integer> getCocaRank(LemmaAndPos lemmaAndPos) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public Optional<String> getSemanticCategory(LemmaAndPos lemmaAndPos) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
