package com.learney.contentaudit.revisioninfrastructure.lagenopenai;

import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
interface LemmaAbsencePromptBuilder {
    String buildSystemPrompt();

    String buildUserPrompt(LemmaAbsenceCorrectionContext context);
}
