package com.learney.contentaudit.refinerdomain.lemmasuggestion;

import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryPort;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQuerySession;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQuerySessionFactory;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultSuggestedLemmaQuerySessionFactory implements SuggestedLemmaQuerySessionFactory {
    private final SuggestedLemmaQueryPort queryPort;

    private final AuditReportStore auditReportStore;

    public DefaultSuggestedLemmaQuerySessionFactory(SuggestedLemmaQueryPort queryPort,
            AuditReportStore auditReportStore) {
        this.queryPort = queryPort;
        this.auditReportStore = auditReportStore;
    }

    @Override
    public SuggestedLemmaQuerySession bindForTask(String sourceAuditId, RefinementTask task) {
        // R015: load the AuditReport identified by the explicit sourceAuditId that was stamped
        // on the task's context at derivation time. Never call loadLatest() — the task must
        // always be evaluated against the same analysis from which its context was derived.
        AuditReport report = auditReportStore.load(sourceAuditId).orElse(null);
        return new BoundSuggestedLemmaQuerySession(queryPort, report, task);
    }
}
