package com.learney.contentaudit.refinerdomain.lemmasuggestion;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryCriteria;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.EvpCatalogPort;
import com.learney.contentaudit.auditdomain.LemmaCountConfig;
import com.learney.contentaudit.auditdomain.LevelDiagnoses;
import com.learney.contentaudit.auditdomain.NodeDiagnoses;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryPort;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryRejectedException;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryResult;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaTierRanker;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import java.util.stream.Collectors;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaAbsenceContextSuggestedLemmaQueryPort implements SuggestedLemmaQueryPort {
    private final CorrectionContextResolver<LemmaAbsenceCorrectionContext> lemmaAbsenceContextResolver;

    private final LeveledLemmaInventory underexposedLemmaInventory;

    private final LeveledLemmaInventory levelWideLemmaInventory;

    public LemmaAbsenceContextSuggestedLemmaQueryPort(
            CorrectionContextResolver<LemmaAbsenceCorrectionContext> lemmaAbsenceContextResolver,
            LeveledLemmaInventory underexposedLemmaInventory,
            LeveledLemmaInventory levelWideLemmaInventory) {
        this.lemmaAbsenceContextResolver = lemmaAbsenceContextResolver;
        this.underexposedLemmaInventory = underexposedLemmaInventory;
        this.levelWideLemmaInventory = levelWideLemmaInventory;
    }

    /**
     * Static factory for use by the composition root. Wires the two default inventory
     * implementations (internal to this package) without exposing LeveledLemmaInventory
     * to callers outside the package.
     */
    public static LemmaAbsenceContextSuggestedLemmaQueryPort create(
            CorrectionContextResolver<LemmaAbsenceCorrectionContext> lemmaAbsenceContextResolver,
            EvpCatalogPort evpCatalogPort,
            LemmaCountConfig lemmaCountConfig) {
        return new LemmaAbsenceContextSuggestedLemmaQueryPort(
                lemmaAbsenceContextResolver,
                new UnderexposedLemmaInventory(lemmaAbsenceContextResolver),
                new LevelWideLemmaInventory(evpCatalogPort, lemmaCountConfig));
    }

    @Override
    public SuggestedLemmaQueryResult query(AuditReport report, RefinementTask task,
            SuggestedLemmaQueryCriteria criteria) {

        Optional<Integer> limit = criteria.getLimit();
        Optional<String> partOfSpeech = criteria.getPartOfSpeech();
        Optional<CefrLevel> explicitLevel = criteria.getExplicitLevel();
        boolean includeExposed = criteria.isIncludeExposed();

        // Step 1: Locate the quiz AuditNode in the report tree (R001, R012)
        AuditNode root = report.getRoot();
        Optional<AuditNode> maybeQuizNode = findNode(root, task.getNodeId(), task.getNodeTarget());

        // Step 2: Resolve the effective CefrLevel (R003, R004, R005, R006)
        CefrLevel effectiveLevel;
        if (maybeQuizNode.isPresent()) {
            AuditNode quizNode = maybeQuizNode.get();
            Optional<AuditNode> milestoneAncestor = quizNode.ancestor(AuditTarget.MILESTONE);
            CefrLevel inferredLevel = inferLevelFromMilestone(milestoneAncestor);
            effectiveLevel = resolveEffectiveLevel(task.getId(), inferredLevel, explicitLevel);
        } else {
            // Quiz node not found: no ancestor inference available (R012)
            effectiveLevel = resolveEffectiveLevel(task.getId(), null, explicitLevel);
        }

        // Step 3: Build candidate list.
        //
        // OFF mode (includeExposed=false, F-INCEXP-R001):
        //   Delegates entirely to underexposedLemmaInventory — identical to previous behaviour.
        //
        // ON mode (includeExposed=true, F-INCEXP-R002, R003, R007):
        //   The ON result is a SUPERSET of OFF by construction:
        //   (a) "needs-exposure" block = exactly what underexposedLemmaInventory returns
        //       (absent + sub-exposed; preserves OFF order and all fields).
        //   (b) "already-exposed" tail = lemmas from levelWideLemmaInventory that are
        //       genuinely exposed (isUnderexposed==false) AND not already in block (a).
        //       These are appended after the needs-exposure block.
        //   Dedup key: (lemma, pos) — OFF entries always win.
        //
        // This guarantees: limit cuts from already-exposed first, never from absent/sub-exposed.

        List<SuggestedLemma> candidates;

        if (!includeExposed) {
            // OFF path: absent + sub-exposed candidates from the underexposed inventory
            candidates = new ArrayList<>(underexposedLemmaInventory.lemmasFor(
                    report, task, effectiveLevel, partOfSpeech));
        } else {
            // ON path: OFF block + genuinely-exposed tail (deduped)
            List<SuggestedLemma> needsExposure = underexposedLemmaInventory.lemmasFor(
                    report, task, effectiveLevel, partOfSpeech);

            // Build dedup key set from needs-exposure block
            Set<String> seenKeys = new HashSet<>();
            for (SuggestedLemma sl : needsExposure) {
                seenKeys.add(lemmaKey(sl));
            }

            // Collect genuinely-exposed entries from the level-wide inventory, excluding dupes
            List<SuggestedLemma> alreadyExposedTail = new ArrayList<>();
            List<SuggestedLemma> levelWideAll = levelWideLemmaInventory.lemmasFor(
                    report, task, effectiveLevel, partOfSpeech);
            for (SuggestedLemma sl : levelWideAll) {
                if (Boolean.FALSE.equals(sl.getIsUnderexposed())
                        && seenKeys.add(lemmaKey(sl))) {
                    alreadyExposedTail.add(sl);
                }
            }

            candidates = new ArrayList<>(needsExposure.size() + alreadyExposedTail.size());
            candidates.addAll(needsExposure);
            candidates.addAll(alreadyExposedTail);
        }

        // Step 5: Apply 6-tier ranking (F-SLEM-R003, R014, R015).
        // Bands are looked up by effectiveLevel (= explicitLevel if present, else inferred — R014 key).
        // tierComparator degrades gracefully to COCA-ascending when no bands are available (R015).
        List<int[]> enrichBands = SuggestedLemmaTierRanker.extractEnrichBands(root, effectiveLevel);
        candidates.sort(SuggestedLemmaTierRanker.tierComparator(enrichBands));

        // Step 5b: Apply regex filter if present (F-SLREGEX-R002, R003, R004, R005, R006, R009).
        // Executed after all other filters (level, pos, exposure) and BEFORE the limit cut (R007).
        Optional<String> regex = criteria.getRegex();
        if (regex != null && regex.isPresent()) {
            String raw = regex.get();
            Pattern pattern;
            try {
                pattern = Pattern.compile(raw, Pattern.CASE_INSENSITIVE);
            } catch (PatternSyntaxException e) {
                // R008: reject with clear validation, not a raw exception or empty list
                throw new SuggestedLemmaQueryRejectedException(task.getId(),
                        "El patrón de búsqueda informado en --regex no es válido.");
            }
            // R002: match only against lemma text (not pos or other fields)
            // R003: partial/grep-like match via find() — no implicit anchoring
            // R006: filter preserves encounter order (stream filter maintains order)
            candidates = candidates.stream()
                    .filter(sl -> sl.getLemma() != null && pattern.matcher(sl.getLemma()).find())
                    .collect(Collectors.toList());
        }

        // Step 6: Apply limit as last step (R008, R009)
        if (limit.isPresent()) {
            int n = limit.get();
            if (candidates.size() > n) {
                candidates = candidates.subList(0, n);
            }
        }

        // Step 7: Return result (R001, R003, R012, R014)
        return new SuggestedLemmaQueryResult(task.getId(), effectiveLevel, candidates);
    }

    /**
     * Dedup key for a SuggestedLemma: (lemma, pos) pair.
     * Null-safe — uses empty string for missing parts.
     */
    private static String lemmaKey(SuggestedLemma sl) {
        return (sl.getLemma() != null ? sl.getLemma() : "")
                + "\0"
                + (sl.getPos() != null ? sl.getPos() : "");
    }

    /**
     * Resolves the effective CefrLevel. Throws SuggestedLemmaQueryRejectedException (R005) when
     * neither inference nor an explicit override is available.
     */
    private CefrLevel resolveEffectiveLevel(String taskId, CefrLevel inferred,
            Optional<CefrLevel> explicitLevel) {
        // Explicit level always wins when present (R006)
        if (explicitLevel.isPresent()) {
            return explicitLevel.get();
        }
        // Inferred from milestone ancestor (R004)
        if (inferred != null) {
            return inferred;
        }
        // No level available — reject (R005)
        throw new SuggestedLemmaQueryRejectedException(taskId,
                "No se pueden sugerir lemas porque falta el nivel necesario para filtrar.");
    }

    /**
     * Infers the CefrLevel from the milestone ancestor's LemmaAbsenceLevelDiagnosis.
     * Falls back to parsing the milestone label as a CefrLevel enum constant.
     * Returns null if no level can be inferred.
     */
    private CefrLevel inferLevelFromMilestone(Optional<AuditNode> milestoneAncestor) {
        if (milestoneAncestor.isEmpty()) {
            return null;
        }
        AuditNode milestoneNode = milestoneAncestor.get();

        // Primary: level from LemmaAbsenceLevelDiagnosis
        NodeDiagnoses diagnoses = milestoneNode.getDiagnoses();
        if (diagnoses instanceof LevelDiagnoses) {
            Optional<LemmaAbsenceLevelDiagnosis> maybeAbsence =
                    ((LevelDiagnoses) diagnoses).getLemmaAbsenceDiagnosis();
            if (maybeAbsence.isPresent()) {
                return maybeAbsence.get().getLevel();
            }
        }

        // Fallback: parse milestone entity label as CefrLevel
        AuditableEntity entity = milestoneNode.getEntity();
        if (entity instanceof AuditableMilestone) {
            String label = ((AuditableMilestone) entity).getLabel();
            if (label != null) {
                try {
                    return CefrLevel.valueOf(label);
                } catch (IllegalArgumentException ignored) {
                    // label is not a valid CefrLevel
                }
            }
        }
        return null;
    }

    /**
     * Finds the AuditNode matching the given nodeId and nodeTarget by recursive tree walk.
     */
    private Optional<AuditNode> findNode(AuditNode node, String nodeId, AuditTarget nodeTarget) {
        if (node == null) {
            return Optional.empty();
        }
        AuditableEntity entity = node.getEntity();
        if (node.getTarget() == nodeTarget
                && entity != null
                && nodeId != null
                && nodeId.equals(entity.getId())) {
            return Optional.of(node);
        }
        List<AuditNode> children = node.getChildren();
        if (children != null) {
            for (AuditNode child : children) {
                Optional<AuditNode> found = findNode(child, nodeId, nodeTarget);
                if (found.isPresent()) {
                    return found;
                }
            }
        }
        return Optional.empty();
    }
}
