package com.learney.contentaudit.refinerdomain.lemmasuggestion;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.LevelDiagnoses;
import com.learney.contentaudit.auditdomain.NodeDiagnoses;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.annotation.processing.Generated;

/**
 * Inventario de lemas sub-expuestos/ausentes para el modo OFF de FEAT-INCEXP.
 *
 * Reproduce el comportamiento actual de LemmaAbsenceContextSuggestedLemmaQueryPort
 * antes de la migración: obtiene los lemas candidatos únicamente a partir del
 * LemmaAbsenceLevelDiagnosis del ancestro milestone (lemas faltantes o sub-expuestos).
 * No incluye lemas ya suficientemente expuestos.
 *
 * Delega en LemmaAbsenceContextResolver para el enriquecimiento con la señal de
 * lemma-count cuando está disponible.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class UnderexposedLemmaInventory implements LeveledLemmaInventory {
    private final CorrectionContextResolver<LemmaAbsenceCorrectionContext> lemmaAbsenceContextResolver;

    public UnderexposedLemmaInventory(
            CorrectionContextResolver<LemmaAbsenceCorrectionContext> lemmaAbsenceContextResolver) {
        this.lemmaAbsenceContextResolver = lemmaAbsenceContextResolver;
    }

    /**
     * Returns the list of sub-exposed/absent lemmas for the given level and optional POS filter.
     *
     * The logic mirrors what LemmaAbsenceContextSuggestedLemmaQueryPort did prior to
     * FEAT-INCEXP: extract absent lemmas from the quiz node's milestone ancestor for the
     * effective level, and map them to SuggestedLemma with COCA-ascending order and
     * no isUnderexposed filtering (all candidates are by definition sub-exposed or absent).
     *
     * POS filtering is applied here so the inventory contract is fully self-contained.
     */
    @Override
    public List<SuggestedLemma> lemmasFor(AuditReport report, RefinementTask task,
            CefrLevel level, Optional<String> partOfSpeech) {

        // Locate quiz node to navigate to milestone ancestor
        AuditNode root = report.getRoot();
        Optional<AuditNode> maybeQuizNode = findNode(root, task.getNodeId(), task.getNodeTarget());

        List<AbsentLemma> absentLemmas;
        if (maybeQuizNode.isPresent()) {
            Optional<AuditNode> milestoneAncestor = maybeQuizNode.get().ancestor(AuditTarget.MILESTONE);
            absentLemmas = extractAbsentLemmas(milestoneAncestor, level);
        } else {
            absentLemmas = Collections.emptyList();
        }

        // Map to SuggestedLemma preserving COCA-ascending order; POS filter applied here
        List<SuggestedLemma> candidates = absentLemmas.stream()
                .sorted(Comparator.comparingInt(
                        (AbsentLemma al) -> al.getCocaRank() == null || al.getCocaRank() == 0
                                ? Integer.MAX_VALUE : al.getCocaRank()))
                .map(al -> new SuggestedLemma(
                        al.getLemmaAndPos() != null ? al.getLemmaAndPos().getLemma() : null,
                        al.getLemmaAndPos() != null ? al.getLemmaAndPos().getPos() : null,
                        al.getAbsenceType() != null ? al.getAbsenceType().name() : null,
                        al.getCocaRank(),
                        null, null, null))
                .collect(Collectors.toList());

        // POS filter (R007)
        if (partOfSpeech.isPresent()) {
            String pos = partOfSpeech.get();
            candidates = candidates.stream()
                    .filter(sl -> pos.equals(sl.getPos()))
                    .collect(Collectors.toList());
        }

        return candidates;
    }

    /**
     * Extracts absent lemmas from the milestone ancestor's LemmaAbsenceLevelDiagnosis.
     * Returns an empty list when the diagnosis is not present.
     */
    private List<AbsentLemma> extractAbsentLemmas(Optional<AuditNode> milestoneAncestor,
            CefrLevel level) {
        if (milestoneAncestor.isEmpty()) {
            return Collections.emptyList();
        }
        NodeDiagnoses diagnoses = milestoneAncestor.get().getDiagnoses();
        if (!(diagnoses instanceof LevelDiagnoses)) {
            return Collections.emptyList();
        }
        Optional<LemmaAbsenceLevelDiagnosis> maybeAbsence =
                ((LevelDiagnoses) diagnoses).getLemmaAbsenceDiagnosis();
        if (maybeAbsence.isEmpty()) {
            return Collections.emptyList();
        }
        List<AbsentLemma> lemmas = maybeAbsence.get().getAbsentLemmas();
        return lemmas != null ? lemmas : Collections.emptyList();
    }

    /**
     * Finds the AuditNode matching the given nodeId and nodeTarget by recursive tree walk.
     */
    private Optional<AuditNode> findNode(AuditNode node, String nodeId, AuditTarget nodeTarget) {
        if (node == null) {
            return Optional.empty();
        }
        AuditableEntity entity = node.getEntity();
        if (node.getTarget() == nodeTarget
                && entity != null
                && nodeId != null
                && nodeId.equals(entity.getId())) {
            return Optional.of(node);
        }
        List<AuditNode> children = node.getChildren();
        if (children != null) {
            for (AuditNode child : children) {
                Optional<AuditNode> found = findNode(child, nodeId, nodeTarget);
                if (found.isPresent()) {
                    return found;
                }
            }
        }
        return Optional.empty();
    }
}
