package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.auditdomain.ActiveAnalysisSelection;
import com.learney.contentaudit.auditdomain.ActiveAnalysisSelectionStore;
import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableCourse;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.CourseMapper;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedView;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewAvailability;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewUnavailabilityReason;
import com.learney.contentaudit.revisiondomain.consolidatedview.NodeImpact;
import com.learney.contentaudit.revisiondomain.consolidatedview.NonApplicablePendingReason;
import com.learney.contentaudit.revisiondomain.consolidatedview.StatisticImpact;
import java.nio.file.Path;
import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
public class DefaultConsolidatedViewBuilderTest {

    @Mock private RevisionArtifactStore revisionArtifactStore;
    @Mock private ActiveAnalysisSelectionStore activeAnalysisSelectionStore;
    @Mock private AuditReportStore auditReportStore;
    @Mock private RefinementPlanStore refinementPlanStore;
    @Mock private CourseRepository courseRepository;
    @Mock private CourseElementLocator courseElementLocator;
    @Mock private CourseMapper courseMapper;
    @Mock private AuditEngine auditEngine;

    private static final Path COURSE_PATH = Path.of("./db/english-course");

    private DefaultConsolidatedViewBuilder builder() {
        return new DefaultConsolidatedViewBuilder(
                revisionArtifactStore, activeAnalysisSelectionStore, auditReportStore,
                refinementPlanStore, courseRepository, courseElementLocator,
                courseMapper, auditEngine);
    }

    private RevisionArtifact approvedArtifact(String proposalId, String planId, String auditId,
            String nodeId, CourseElementSnapshot elementBefore, CourseElementSnapshot elementAfter,
            Instant createdAt) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-001", planId, auditId,
                DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, nodeId,
                elementBefore, elementAfter, "rationale", "lemma-mvp", createdAt, null);
        return new RevisionArtifact(proposal, RevisionVerdict.APPROVED, null, null, null, null);
    }

    private RevisionArtifact pendingArtifact(String proposalId, String planId, String auditId,
            String nodeId, CourseElementSnapshot elementBefore, CourseElementSnapshot elementAfter,
            Instant createdAt) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-001", planId, auditId,
                DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, nodeId,
                elementBefore, elementAfter, "rationale", "lemma-mvp", createdAt, null);
        return new RevisionArtifact(proposal, RevisionVerdict.PENDING_APPROVAL, null, null, null, null);
    }

    private RevisionArtifact rejectedArtifact(String proposalId, String planId, String auditId,
            String nodeId, CourseElementSnapshot snap) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-001", planId, auditId,
                DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, nodeId,
                snap, snap, "rationale", "lemma-mvp", Instant.parse("2026-01-01T00:00:00Z"), null);
        return new RevisionArtifact(proposal, RevisionVerdict.REJECTED, "rechazada", null, null, null);
    }

    private static class FakeEntity implements AuditableEntity {
        private final String id;
        FakeEntity(String id) { this.id = id; }
        @Override public String getId() { return id; }
        @Override public String getLabel() { return id; }
        @Override public String getCode() { return null; }
    }

    private AuditNode quizNode(String nodeId, Map<String, Double> scores) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setScores(scores);
        node.setEntity(new FakeEntity(nodeId));
        node.setChildren(List.of());
        return node;
    }

    private AuditReport report(AuditNode root) {
        return new AuditReport(root);
    }

    private void stubActive(String auditId, String planId) {
        when(activeAnalysisSelectionStore.read())
                .thenReturn(Optional.of(new ActiveAnalysisSelection(auditId, planId)));
    }

    private RefinementPlan plan(String planId, String auditId) {
        return new RefinementPlan(planId, auditId, Instant.parse("2026-01-01T00:00:00Z"), List.of());
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dada una seleccion activa con auditId y planId resolubles, cuando build corre, entonces ConsolidatedView.activeAuditId y activePlanId coinciden con los identificadores leidos del ActiveAnalysisSelectionStore")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R001")
    public void dadaUnaSeleccionActivaConAuditIdYPlanIdResolublesCuandoBuildCorreEntoncesConsolidatedViewactiveAuditIdYActivePlanIdCoincidenConLosIdentificadoresLeidosDelActiveAnalysisSelectionStore() {
        stubActive("audit-r001", "plan-r001");
        when(refinementPlanStore.load("plan-r001")).thenReturn(Optional.of(plan("plan-r001", "audit-r001")));
        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.80));
        when(auditReportStore.load("audit-r001")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r001")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals("audit-r001", view.getActiveAuditId());
        assertEquals("plan-r001", view.getActivePlanId());
        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability());
    }

    @Test
    @DisplayName("Dado un AuditReport recien creado cuyo plan activo no tiene propuestas aceptadas ni pendientes, cuando build corre, entonces nodeImpacts y statisticImpacts quedan vacios y los valores consolidados coinciden con el baseline del analisis")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R003")
    public void dadoUnAuditReportRecienCreadoCuyoPlanActivoNoTienePropuestasAceptadasNiPendientesCuandoBuildCorreEntoncesNodeImpactsYStatisticImpactsQuedanVaciosYLosValoresConsolidadosCoincidenConElBaselineDelAnalisis() {
        stubActive("audit-r003", "plan-r003");
        when(refinementPlanStore.load("plan-r003")).thenReturn(Optional.of(plan("plan-r003", "audit-r003")));
        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.75));
        when(auditReportStore.load("audit-r003")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r003")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability());
        assertTrue(view.getNodeImpacts().isEmpty(), "No debe haber nodeImpacts sin propuestas");
        assertTrue(view.getStatisticImpacts().isEmpty(), "No debe haber statisticImpacts sin propuestas");
    }

    @Test
    @DisplayName("Dado un plan activo de un analisis viejo con propuestas pendientes y un analisis mas nuevo cuyo plan no las contiene, cuando build corre apuntando al analisis viejo, entonces sus pendientes dormidas aparecen en nodeImpacts/statisticImpacts del consolidado")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R004")
    public void dadoUnPlanActivoDeUnAnalisisViejoConPropuestasPendientesYUnAnalisisMasNuevoCuyoPlanNoLasContieneCuandoBuildCorreApuntandoAlAnalisisViejoEntoncesSusPendientesDormidasAparecenEnNodeImpactsstatisticImpactsDelConsolidado() {
        stubActive("audit-old", "plan-old");
        when(refinementPlanStore.load("plan-old")).thenReturn(Optional.of(plan("plan-old", "audit-old")));

        CourseElementSnapshot snapBefore = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfter = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact dormant = pendingArtifact("proposal-dormant", "plan-old", "audit-old",
                "quiz-001", snapBefore, snapAfter, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-old")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-old")).thenReturn(List.of(dormant));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseWithPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapBefore));
        when(courseElementLocator.replace(eq(course), eq(snapAfter))).thenReturn(courseWithPend);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseWithPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        AuditNode rootPend = quizNode("quiz-001", Map.of("lemma-absence", 0.75));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(rootPend));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability());
        assertFalse(view.getNodeImpacts().isEmpty(),
                "Las pendientes dormidas del plan viejo deben aparecer en nodeImpacts");
    }

    @Test
    @DisplayName("Dado un RevisionArtifact con verdict REJECTED en el plan activo, cuando build corre, entonces ese proposalId no aparece en nodeImpacts, statisticImpacts ni nonApplicablePendings y no contribuye a consolidated, acceptedDelta, pendingProjection ni pendingDelta")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R005")
    public void dadoUnRevisionArtifactConVerdictREJECTEDEnElPlanActivoCuandoBuildCorreEntoncesEseProposalIdNoApareceEnNodeImpactsStatisticImpactsNiNonApplicablePendingsYNoContribuyeAConsolidatedAcceptedDeltaPendingProjectionNiPendingDelta() {
        stubActive("audit-r005", "plan-r005");
        when(refinementPlanStore.load("plan-r005")).thenReturn(Optional.of(plan("plan-r005", "audit-r005")));

        CourseElementSnapshot snap = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact rejected = rejectedArtifact("proposal-rejected", "plan-r005", "audit-r005", "quiz-001", snap);

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.70));
        when(auditReportStore.load("audit-r005")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r005")).thenReturn(List.of(rejected));
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertTrue(view.getNodeImpacts().isEmpty(), "REJECTED no debe aparecer en nodeImpacts");
        assertTrue(view.getStatisticImpacts().isEmpty(), "REJECTED no debe aparecer en statisticImpacts");
        assertTrue(view.getNonApplicablePendings().isEmpty(), "REJECTED no debe aparecer en nonApplicablePendings");
    }

    @Test
    @DisplayName("Dado un nodo hoja sin aceptadas ni pendientes en el plan activo, cuando build corre, entonces ese nodo no aparece en nodeImpacts (la salida solo emite nodos afectados)")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoHojaSinAceptadasNiPendientesEnElPlanActivoCuandoBuildCorreEntoncesEseNodoNoApareceEnNodeImpactsLaSalidaSoloEmiteNodosAfectados() {
        stubActive("audit-r006a", "plan-r006a");
        when(refinementPlanStore.load("plan-r006a")).thenReturn(Optional.of(plan("plan-r006a", "audit-r006a")));
        AuditNode root = quizNode("quiz-unaffected", Map.of("lemma-absence", 0.80));
        when(auditReportStore.load("audit-r006a")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r006a")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertTrue(view.getNodeImpacts().isEmpty(), "Un nodo sin propuestas no debe aparecer en nodeImpacts");
    }

    @Test
    @DisplayName("Dado un nodo hoja con una pendiente en el plan activo y sin aceptadas, cuando build corre, entonces NodeImpact.consolidated coincide con el snapshot del baseline y pendingProjection coincide con el snapshot resultante de aplicar la pendiente sobre ese baseline")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoHojaConUnaPendienteEnElPlanActivoYSinAceptadasCuandoBuildCorreEntoncesNodeImpactconsolidatedCoincideConElSnapshotDelBaselineYPendingProjectionCoincideConElSnapshotResultanteDeAplicarLaPendienteSobreEseBaseline() {
        stubActive("audit-r006b", "plan-r006b");
        when(refinementPlanStore.load("plan-r006b")).thenReturn(Optional.of(plan("plan-r006b", "audit-r006b")));

        CourseElementSnapshot snapBase = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapPend = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact pending = pendingArtifact("proposal-pend", "plan-r006b", "audit-r006b",
                "quiz-001", snapBase, snapPend, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r006b")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r006b")).thenReturn(List.of(pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseWithPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapBase));
        when(courseElementLocator.replace(eq(course), eq(snapPend))).thenReturn(courseWithPend);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseWithPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        AuditNode rootPend = quizNode("quiz-001", Map.of("lemma-absence", 0.75));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(rootPend));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> "quiz-001".equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para quiz-001 no encontrado"));

        assertEquals(snapBase, ni.getConsolidated(),
                "consolidated debe ser el snapshot del baseline cuando no hay aceptadas");
        assertNotNull(ni.getPendingProjection(), "pendingProjection debe estar presente");
        assertEquals("proposal-pend", ni.getPendingProposalId());
    }

    @Test
    @DisplayName("Dado un nodo hoja con una propuesta aceptada y sin pendientes, cuando build corre, entonces NodeImpact.consolidated coincide con el elementAfter de la aceptada y pendingProjection es null")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoHojaConUnaPropuestaAceptadaYSinPendientesCuandoBuildCorreEntoncesNodeImpactconsolidatedCoincideConElElementAfterDeLaAceptadaYPendingProjectionEsNull() {
        stubActive("audit-r006c", "plan-r006c");
        when(refinementPlanStore.load("plan-r006c")).thenReturn(Optional.of(plan("plan-r006c", "audit-r006c")));

        CourseElementSnapshot snapBefore = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfter = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-acc", "plan-r006c", "audit-r006c",
                "quiz-001", snapBefore, snapAfter, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r006c")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r006c")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snapAfter))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        AuditNode rootAfter = quizNode("quiz-001", Map.of("lemma-absence", 0.80));
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(rootAfter));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> "quiz-001".equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para quiz-001 no encontrado"));

        assertEquals(snapAfter, ni.getConsolidated(),
                "consolidated debe coincidir con el elementAfter de la aceptada");
        assertNull(ni.getPendingProjection(), "pendingProjection debe ser null cuando no hay pendientes");
    }

    @Test
    @DisplayName("Dado un nodo hoja con una aceptada y una pendiente sobre el mismo nodeId, cuando build corre, entonces pendingProjection se calcula aplicando la pendiente sobre consolidated (es decir sobre el elementAfter de la aceptada) y no sobre el snapshot original del baseline")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoHojaConUnaAceptadaYUnaPendienteSobreElMismoNodeIdCuandoBuildCorreEntoncesPendingProjectionSeCalculaAplicandoLaPendienteSobreConsolidatedEsDecirSobreElElementAfterDeLaAceptadaYNoSobreElSnapshotOriginalDelBaseline() {
        stubActive("audit-r006d", "plan-r006d");
        when(refinementPlanStore.load("plan-r006d")).thenReturn(Optional.of(plan("plan-r006d", "audit-r006d")));

        CourseElementSnapshot snapBase = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfterAcc = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfterPend = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);

        RevisionArtifact approved = approvedArtifact("proposal-acc", "plan-r006d", "audit-r006d",
                "quiz-001", snapBase, snapAfterAcc, Instant.parse("2026-01-01T00:00:00Z"));
        // Pendiente usa snapAfterAcc como elementBefore — se aplica sobre el consolidated
        RevisionArtifact pending = pendingArtifact("proposal-pend", "plan-r006d", "audit-r006d",
                "quiz-001", snapAfterAcc, snapAfterPend, Instant.parse("2026-01-02T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.50));
        when(auditReportStore.load("audit-r006d")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r006d")).thenReturn(List.of(approved, pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfterAcc = mock(CourseEntity.class);
        CourseEntity courseAfterPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snapAfterAcc))).thenReturn(courseAfterAcc);
        when(courseElementLocator.snapshot(eq(courseAfterAcc), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapAfterAcc));
        when(courseElementLocator.replace(eq(courseAfterAcc), eq(snapAfterPend))).thenReturn(courseAfterPend);

        AuditableCourse audAcc = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfterAcc)).thenReturn(audAcc);
        when(courseMapper.map(courseAfterPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audAcc))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.70))));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.85))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> "quiz-001".equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para quiz-001 no encontrado"));

        assertEquals(snapAfterAcc, ni.getConsolidated(),
                "consolidated = elementAfter de la aceptada");
        assertNotNull(ni.getPendingProjection(),
                "pendingProjection debe reflejar la pendiente aplicada sobre el consolidated");
    }

    @Test
    @DisplayName("Dado un nodo hoja con dos propuestas aceptadas que lo afectaron en orden createdAt ascendente, cuando build corre, entonces NodeImpact.acceptedProposalIds contiene ambos proposalId en orden createdAt ascendente")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnNodoHojaConDosPropuestasAceptadasQueLoAfectaronEnOrdenCreatedAtAscendenteCuandoBuildCorreEntoncesNodeImpactacceptedProposalIdsContieneAmbosProposalIdEnOrdenCreatedAtAscendente() {
        stubActive("audit-r007a", "plan-r007a");
        when(refinementPlanStore.load("plan-r007a")).thenReturn(Optional.of(plan("plan-r007a", "audit-r007a")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap3 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);

        RevisionArtifact acc1 = approvedArtifact("proposal-first", "plan-r007a", "audit-r007a",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));
        RevisionArtifact acc2 = approvedArtifact("proposal-second", "plan-r007a", "audit-r007a",
                "quiz-001", snap2, snap3, Instant.parse("2026-01-02T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.50));
        when(auditReportStore.load("audit-r007a")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r007a")).thenReturn(List.of(acc1, acc2));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity course2 = mock(CourseEntity.class);
        CourseEntity course3 = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(course2);
        when(courseElementLocator.replace(eq(course2), eq(snap3))).thenReturn(course3);
        AuditableCourse audFinal = mock(AuditableCourse.class);
        when(courseMapper.map(course3)).thenReturn(audFinal);
        when(auditEngine.runAudit(eq(audFinal))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.90))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> "quiz-001".equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para quiz-001 no encontrado"));

        List<String> ids = ni.getAcceptedProposalIds();
        assertEquals(2, ids.size());
        assertEquals("proposal-first", ids.get(0));
        assertEquals("proposal-second", ids.get(1));
    }

    @Test
    @DisplayName("Dado un nodo hoja con una pendiente aplicable, cuando build corre, entonces NodeImpact.pendingProposalId equivale al proposalId de la pendiente que produjo pendingProjection")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnNodoHojaConUnaPendienteAplicableCuandoBuildCorreEntoncesNodeImpactpendingProposalIdEquivaleAlProposalIdDeLaPendienteQueProdujoPendingProjection() {
        stubActive("audit-r007b", "plan-r007b");
        when(refinementPlanStore.load("plan-r007b")).thenReturn(Optional.of(plan("plan-r007b", "audit-r007b")));

        CourseElementSnapshot snapBefore = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfter = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact pending = pendingArtifact("proposal-pend-r007", "plan-r007b", "audit-r007b",
                "quiz-001", snapBefore, snapAfter, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r007b")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r007b")).thenReturn(List.of(pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseWithPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapBefore));
        when(courseElementLocator.replace(eq(course), eq(snapAfter))).thenReturn(courseWithPend);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseWithPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.75))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> "quiz-001".equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para quiz-001 no encontrado"));

        assertEquals("proposal-pend-r007", ni.getPendingProposalId());
    }

    @Test
    @DisplayName("Dado un nodo padre cuyo subarbol contiene un quiz afectado por una aceptada, cuando build corre, entonces aparece un NodeImpact para ese padre y los valores consolidados de sus estadisticas resultan de re-agregar el subarbol con la estrategia del analizador (no de sumar deltas individuales)")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R008")
    public void dadoUnNodoPadreCuyoSubarbolContieneUnQuizAfectadoPorUnaAceptadaCuandoBuildCorreEntoncesApareceUnNodeImpactParaEsePadreYLosValoresConsolidadosDeSusEstadisticasResultanDeReagregarElSubarbolConLaEstrategiaDelAnalizadorNoDeSumarDeltasIndividuales() {
        stubActive("audit-r008a", "plan-r008a");
        when(refinementPlanStore.load("plan-r008a")).thenReturn(Optional.of(plan("plan-r008a", "audit-r008a")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-r008", "plan-r008a", "audit-r008a",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode quizChild = quizNode("quiz-001", Map.of("lemma-absence", 0.50));
        AuditNode topicRoot = new AuditNode();
        topicRoot.setTarget(AuditTarget.TOPIC);
        FakeEntity topicEnt = new FakeEntity("topic-001");
        topicRoot.setEntity(topicEnt);
        topicRoot.setScores(Map.of("lemma-absence", 0.50));
        topicRoot.setChildren(List.of(quizChild));

        when(auditReportStore.load("audit-r008a")).thenReturn(Optional.of(report(topicRoot)));
        when(revisionArtifactStore.listByPlan("plan-r008a")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);

        AuditNode quizAfter = quizNode("quiz-001", Map.of("lemma-absence", 0.80));
        AuditNode topicAfter = new AuditNode();
        topicAfter.setTarget(AuditTarget.TOPIC);
        topicAfter.setEntity(topicEnt);
        topicAfter.setScores(Map.of("lemma-absence", 0.80));
        topicAfter.setChildren(List.of(quizAfter));
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(topicAfter));

        ConsolidatedView view = builder().build(COURSE_PATH);

        boolean topicInStats = view.getStatisticImpacts().stream()
                .anyMatch(s -> "topic-001".equals(s.getNodeId()));
        assertTrue(topicInStats, "El padre (topic) debe aparecer en statisticImpacts con valores re-agregados");

        StatisticImpact topicStat = view.getStatisticImpacts().stream()
                .filter(s -> "topic-001".equals(s.getNodeId()) && "lemma-absence".equals(s.getDimension()))
                .findFirst().orElseThrow();
        assertEquals(0.80, topicStat.getConsolidated(), 0.001,
                "consolidated del padre debe venir de re-agregar via AuditEngine, no de sumar deltas");
    }

    @Test
    @DisplayName("Dado un nodo padre cuyo subarbol no contiene aceptadas ni pendientes, cuando build corre, entonces ese padre no aparece en nodeImpacts ni en statisticImpacts")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R008")
    public void dadoUnNodoPadreCuyoSubarbolNoContieneAceptadasNiPendientesCuandoBuildCorreEntoncesEsePadreNoApareceEnNodeImpactsNiEnStatisticImpacts() {
        stubActive("audit-r008b", "plan-r008b");
        when(refinementPlanStore.load("plan-r008b")).thenReturn(Optional.of(plan("plan-r008b", "audit-r008b")));

        AuditNode quizChild = quizNode("quiz-unaffected", Map.of("lemma-absence", 0.70));
        AuditNode topicRoot = new AuditNode();
        topicRoot.setTarget(AuditTarget.TOPIC);
        topicRoot.setEntity(new FakeEntity("topic-unaffected"));
        topicRoot.setScores(Map.of("lemma-absence", 0.70));
        topicRoot.setChildren(List.of(quizChild));

        when(auditReportStore.load("audit-r008b")).thenReturn(Optional.of(report(topicRoot)));
        when(revisionArtifactStore.listByPlan("plan-r008b")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(topicRoot));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertTrue(view.getNodeImpacts().isEmpty());
        assertTrue(view.getStatisticImpacts().isEmpty());
    }

    @Test
    @DisplayName("Dada una estadistica tocada solo por una aceptada en el plan activo, cuando build corre, entonces el StatisticImpact correspondiente expone original y consolidated distintos, acceptedDelta no nulo, y pendingProjection y pendingDelta nulos")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R009")
    public void dadaUnaEstadisticaTocadaSoloPorUnaAceptadaEnElPlanActivoCuandoBuildCorreEntoncesElStatisticImpactCorrespondienteExponeOriginalYConsolidatedDistintosAcceptedDeltaNoNuloYPendingProjectionYPendingDeltaNulos() {
        stubActive("audit-r009a", "plan-r009a");
        when(refinementPlanStore.load("plan-r009a")).thenReturn(Optional.of(plan("plan-r009a", "audit-r009a")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-acc-r009a", "plan-r009a", "audit-r009a",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r009a")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r009a")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.80))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        StatisticImpact stat = view.getStatisticImpacts().stream()
                .filter(s -> "quiz-001".equals(s.getNodeId()) && "lemma-absence".equals(s.getDimension()))
                .findFirst().orElseThrow(() -> new AssertionError("StatisticImpact no encontrado"));

        assertEquals(0.60, stat.getOriginal(), 0.001);
        assertEquals(0.80, stat.getConsolidated(), 0.001);
        assertFalse(stat.getAcceptedDelta() == 0.0, "acceptedDelta debe ser no cero");
        assertNull(stat.getPendingProjection());
        assertNull(stat.getPendingDelta());
    }

    @Test
    @DisplayName("Dada una estadistica tocada solo por una pendiente en el plan activo, cuando build corre, entonces el StatisticImpact correspondiente expone consolidated igual a original, acceptedDelta cero, y pendingProjection con pendingDelta no nulos")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R009")
    public void dadaUnaEstadisticaTocadaSoloPorUnaPendienteEnElPlanActivoCuandoBuildCorreEntoncesElStatisticImpactCorrespondienteExponeConsolidatedIgualAOriginalAcceptedDeltaCeroYPendingProjectionConPendingDeltaNoNulos() {
        stubActive("audit-r009b", "plan-r009b");
        when(refinementPlanStore.load("plan-r009b")).thenReturn(Optional.of(plan("plan-r009b", "audit-r009b")));

        CourseElementSnapshot snapBefore = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfter = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact pending = pendingArtifact("proposal-pend-r009b", "plan-r009b", "audit-r009b",
                "quiz-001", snapBefore, snapAfter, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r009b")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r009b")).thenReturn(List.of(pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseWithPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapBefore));
        when(courseElementLocator.replace(eq(course), eq(snapAfter))).thenReturn(courseWithPend);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseWithPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.80))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        StatisticImpact stat = view.getStatisticImpacts().stream()
                .filter(s -> "quiz-001".equals(s.getNodeId()) && "lemma-absence".equals(s.getDimension()))
                .findFirst().orElseThrow(() -> new AssertionError("StatisticImpact no encontrado"));

        assertEquals(0.60, stat.getOriginal(), 0.001);
        assertEquals(0.60, stat.getConsolidated(), 0.001,
                "consolidated == original cuando solo hay pendientes");
        assertEquals(0.0, stat.getAcceptedDelta(), 0.001);
        assertNotNull(stat.getPendingProjection());
        assertNotNull(stat.getPendingDelta());
    }

    @Test
    @DisplayName("Dada una estadistica del baseline no tocada por ninguna decision del plan activo, cuando build corre, entonces ese par (nivel, dimension) no aparece en statisticImpacts")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R009")
    public void dadaUnaEstadisticaDelBaselineNoTocadaPorNingunaDecisionDelPlanActivoCuandoBuildCorreEntoncesEseParNivelDimensionNoApareceEnStatisticImpacts() {
        stubActive("audit-r009c", "plan-r009c");
        when(refinementPlanStore.load("plan-r009c")).thenReturn(Optional.of(plan("plan-r009c", "audit-r009c")));

        Map<String, Double> scores = new HashMap<>();
        scores.put("lemma-absence", 0.70);
        scores.put("sentence-length", 0.80);
        AuditNode root = quizNode("quiz-001", scores);
        when(auditReportStore.load("audit-r009c")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r009c")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertTrue(view.getStatisticImpacts().isEmpty(),
                "Estadisticas no tocadas no deben aparecer en statisticImpacts");
    }

    @Test
    @DisplayName("Dado cualquier StatisticImpact emitido por build, entonces acceptedDelta es exactamente consolidated menos original, sin escalado relativo")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R010")
    public void dadoCualquierStatisticImpactEmitidoPorBuildEntoncesAcceptedDeltaEsExactamenteConsolidatedMenosOriginalSinEscaladoRelativo() {
        stubActive("audit-r010a", "plan-r010a");
        when(refinementPlanStore.load("plan-r010a")).thenReturn(Optional.of(plan("plan-r010a", "audit-r010a")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-r010a", "plan-r010a", "audit-r010a",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.50));
        when(auditReportStore.load("audit-r010a")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r010a")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.75))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        for (StatisticImpact stat : view.getStatisticImpacts()) {
            assertEquals(stat.getConsolidated() - stat.getOriginal(), stat.getAcceptedDelta(), 0.0001,
                    "acceptedDelta debe ser exactamente consolidated - original (puntos absolutos)");
        }
    }

    @Test
    @DisplayName("Dado un StatisticImpact con pendingProjection no nulo, entonces pendingDelta es exactamente pendingProjection menos consolidated, sin escalado relativo")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R010")
    public void dadoUnStatisticImpactConPendingProjectionNoNuloEntoncesPendingDeltaEsExactamentePendingProjectionMenosConsolidatedSinEscaladoRelativo() {
        stubActive("audit-r010b", "plan-r010b");
        when(refinementPlanStore.load("plan-r010b")).thenReturn(Optional.of(plan("plan-r010b", "audit-r010b")));

        CourseElementSnapshot snapBase = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapPend = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact pending = pendingArtifact("proposal-pend-r010b", "plan-r010b", "audit-r010b",
                "quiz-001", snapBase, snapPend, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r010b")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r010b")).thenReturn(List.of(pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseWithPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapBase));
        when(courseElementLocator.replace(eq(course), eq(snapPend))).thenReturn(courseWithPend);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseWithPend)).thenReturn(audPend);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.85))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        for (StatisticImpact stat : view.getStatisticImpacts()) {
            if (stat.getPendingProjection() != null) {
                assertEquals(stat.getPendingProjection() - stat.getConsolidated(), stat.getPendingDelta(), 0.0001,
                        "pendingDelta debe ser exactamente pendingProjection - consolidated (puntos absolutos)");
            }
        }
    }

    @Test
    @DisplayName("Dado un AuditReport con pares (nivel, dimension) reportados por el motor en el baseline, cuando build corre, entonces statisticImpacts solo contiene pares presentes en el baseline (la salida no inventa pares ausentes ni reordena la granularidad)")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R011")
    public void dadoUnAuditReportConParesNivelDimensionReportadosPorElMotorEnElBaselineCuandoBuildCorreEntoncesStatisticImpactsSoloContieneParesPresentesEnElBaselineLaSalidaNoInventaParesAusentesNiReordenaLaGranularidad() {
        stubActive("audit-r011", "plan-r011");
        when(refinementPlanStore.load("plan-r011")).thenReturn(Optional.of(plan("plan-r011", "audit-r011")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-r011", "plan-r011", "audit-r011",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        // Baseline only has "lemma-absence" — no "coca-buckets"
        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r011")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r011")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(quizNode("quiz-001", Map.of("lemma-absence", 0.80))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        for (StatisticImpact stat : view.getStatisticImpacts()) {
            assertTrue(root.getScores().containsKey(stat.getDimension()),
                    "statisticImpact contiene dimension '" + stat.getDimension() +
                    "' que no estaba en el baseline del AuditReport");
        }
        assertTrue(view.getStatisticImpacts().stream().noneMatch(s -> "coca-buckets".equals(s.getDimension())),
                "La salida no debe inventar pares de dimension ausentes del baseline");
    }

    @Test
    @DisplayName("Dada una pendiente cuyo nodeId no se encuentra en el subarbol vigente, cuando build corre, entonces aparece en nonApplicablePendings con reason NODE_ABSENT y detail no vacio, y no contribuye a pendingProjection ni pendingDelta de ningun nodo o estadistica")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R012")
    public void dadaUnaPendienteCuyoNodeIdNoSeEncuentraEnElSubarbolVigenteCuandoBuildCorreEntoncesApareceEnNonApplicablePendingsConReasonNODEABSENTYDetailNoVacioYNoContribuyeAPendingProjectionNiPendingDeltaDeNingunNodoOEstadistica() {
        stubActive("audit-r012a", "plan-r012a");
        when(refinementPlanStore.load("plan-r012a")).thenReturn(Optional.of(plan("plan-r012a", "audit-r012a")));

        CourseElementSnapshot snapGhost = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-ghost", null);
        RevisionArtifact pending = pendingArtifact("proposal-absent", "plan-r012a", "audit-r012a",
                "quiz-ghost", snapGhost, snapGhost, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-other", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r012a")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r012a")).thenReturn(List.of(pending));

        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-ghost")))
                .thenReturn(Optional.empty());
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(1, view.getNonApplicablePendings().size());
        assertEquals("proposal-absent", view.getNonApplicablePendings().get(0).getProposalId());
        assertEquals(NonApplicablePendingReason.NODE_ABSENT,
                view.getNonApplicablePendings().get(0).getReason());
        assertFalse(view.getNonApplicablePendings().get(0).getDetail().isBlank());
        assertTrue(view.getNodeImpacts().stream().noneMatch(n -> n.getPendingProjection() != null));
    }

    @Test
    @DisplayName("Dadas dos pendientes sobre el mismo nodeId aplicadas en orden createdAt ascendente cuyo elementBefore de la segunda no coincide con el consolidated tras aplicar la primera, cuando build corre, entonces la segunda aparece en nonApplicablePendings con reason ELEMENT_BEFORE_MISMATCH y no contribuye a pendingProjection ni pendingDelta")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R012")
    public void dadasDosPendientesSobreElMismoNodeIdAplicadasEnOrdenCreatedAtAscendenteCuyoElementBeforeDeLaSegundaNoCoincideConElConsolidatedTrasAplicarLaPrimeraCuandoBuildCorreEntoncesLaSegundaApareceEnNonApplicablePendingsConReasonELEMENTBEFOREMISMATCHYNoContribuyeAPendingProjectionNiPendingDelta() {
        stubActive("audit-r012b", "plan-r012b");
        when(refinementPlanStore.load("plan-r012b")).thenReturn(Optional.of(plan("plan-r012b", "audit-r012b")));

        CourseElementSnapshot snapOrig    = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapAfter1  = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001-v2", null);
        // snapMismatch simulates pend2's stale elementBefore — differs from snapAfter1 so equals() returns false
        CourseElementSnapshot snapMismatch = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001-stale", null);
        CourseElementSnapshot snapAfter2  = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001-v3", null);

        RevisionArtifact pend1 = pendingArtifact("proposal-pend1", "plan-r012b", "audit-r012b",
                "quiz-001", snapOrig, snapAfter1, Instant.parse("2026-01-01T00:00:00Z"));
        // pend2 expects snapMismatch as elementBefore, but after pend1 the consolidated is snapAfter1
        RevisionArtifact pend2 = pendingArtifact("proposal-pend2", "plan-r012b", "audit-r012b",
                "quiz-001", snapMismatch, snapAfter2, Instant.parse("2026-01-02T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r012b")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r012b")).thenReturn(List.of(pend1, pend2));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter1 = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapOrig));
        when(courseElementLocator.replace(eq(course), eq(snapAfter1))).thenReturn(courseAfter1);
        // After applying pend1, consolidated of node is snapAfter1
        when(courseElementLocator.snapshot(eq(courseAfter1), eq(AuditTarget.QUIZ), eq("quiz-001")))
                .thenReturn(Optional.of(snapAfter1));
        // pend2 elementBefore=snapMismatch != snapAfter1 → ELEMENT_BEFORE_MISMATCH

        AuditableCourse audPend1 = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter1)).thenReturn(audPend1);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertTrue(view.getNonApplicablePendings().stream()
                .anyMatch(n -> "proposal-pend2".equals(n.getProposalId()) &&
                               NonApplicablePendingReason.ELEMENT_BEFORE_MISMATCH == n.getReason()),
                "La segunda pendiente debe aparecer con ELEMENT_BEFORE_MISMATCH");
    }

    @Test
    @DisplayName("Dada una pendiente marcada como NOT_APPLICABLE y otras pendientes aplicables en el mismo plan activo, cuando build corre, entonces el resto del consolidado se entrega normalmente y solo la pendiente no aplicable queda excluida del calculo de proyeccion")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R012")
    public void dadaUnaPendienteMarcadaComoNOTAPPLICABLEYOtrasPendientesAplicablesEnElMismoPlanActivoCuandoBuildCorreEntoncesElRestoDelConsolidadoSeEntregaNormalmenteYSoloLaPendienteNoAplicableQuedaExcluidaDelCalculoDeProyeccion() {
        stubActive("audit-r012c", "plan-r012c");
        when(refinementPlanStore.load("plan-r012c")).thenReturn(Optional.of(plan("plan-r012c", "audit-r012c")));

        CourseElementSnapshot snapAbsent = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-absent", null);
        RevisionArtifact notApplicable = pendingArtifact("proposal-absent", "plan-r012c", "audit-r012c",
                "quiz-absent", snapAbsent, snapAbsent, Instant.parse("2026-01-01T00:00:00Z"));

        CourseElementSnapshot snapOk = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-ok", null);
        CourseElementSnapshot snapOkAfter = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-ok", null);
        RevisionArtifact applicable = pendingArtifact("proposal-ok", "plan-r012c", "audit-r012c",
                "quiz-ok", snapOk, snapOkAfter, Instant.parse("2026-01-02T00:00:00Z"));

        AuditNode root = quizNode("quiz-ok", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r012c")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r012c")).thenReturn(List.of(notApplicable, applicable));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfterOk = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-absent")))
                .thenReturn(Optional.empty());
        when(courseElementLocator.snapshot(eq(course), eq(AuditTarget.QUIZ), eq("quiz-ok")))
                .thenReturn(Optional.of(snapOk));
        when(courseElementLocator.replace(eq(course), eq(snapOkAfter))).thenReturn(courseAfterOk);
        AuditableCourse audBase = mock(AuditableCourse.class);
        AuditableCourse audOk = mock(AuditableCourse.class);
        when(courseMapper.map(course)).thenReturn(audBase);
        when(courseMapper.map(courseAfterOk)).thenReturn(audOk);
        when(auditEngine.runAudit(eq(audBase))).thenReturn(report(root));
        when(auditEngine.runAudit(eq(audOk))).thenReturn(report(quizNode("quiz-ok", Map.of("lemma-absence", 0.80))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability(),
                "El consolidado debe entregarse normalmente con pendiente no aplicable");
        assertEquals(1, view.getNonApplicablePendings().size());
        assertEquals("proposal-absent", view.getNonApplicablePendings().get(0).getProposalId());
        assertTrue(view.getNodeImpacts().stream()
                .anyMatch(n -> "quiz-ok".equals(n.getNodeId()) && n.getPendingProjection() != null),
                "La pendiente aplicable debe contribuir a pendingProjection de quiz-ok");
    }

    @Test
    @DisplayName("Dado que el ActiveAnalysisSelectionStore retorna Optional.empty, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason NO_ACTIVE_ANALYSIS y nodeImpacts/statisticImpacts quedan vacios")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoQueElActiveAnalysisSelectionStoreRetornaOptionalemptyCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonNOACTIVEANALYSISYNodeImpactsstatisticImpactsQuedanVacios() {
        when(activeAnalysisSelectionStore.read()).thenReturn(Optional.empty());

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability());
        assertEquals(ConsolidatedViewUnavailabilityReason.NO_ACTIVE_ANALYSIS,
                view.getUnavailability().getReason());
        assertTrue(view.getNodeImpacts().isEmpty());
        assertTrue(view.getStatisticImpacts().isEmpty());
    }

    @Test
    @DisplayName("Dado un par activo cuyo planId no se puede ubicar dentro del analisis (RefinementPlanStore retorna empty), cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason ACTIVE_PLAN_UNAVAILABLE")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoUnParActivoCuyoPlanIdNoSePuedeUbicarDentroDelAnalisisRefinementPlanStoreRetornaEmptyCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonACTIVEPLANUNAVAILABLE() {
        stubActive("audit-r013b", "plan-missing");
        when(refinementPlanStore.load("plan-missing")).thenReturn(Optional.empty());

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability());
        assertEquals(ConsolidatedViewUnavailabilityReason.ACTIVE_PLAN_UNAVAILABLE,
                view.getUnavailability().getReason());
    }

    @Test
    @DisplayName("Dada una propuesta aceptada que referencia un nodeId no encontrado por CourseElementLocator al re-agregar, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason INCONSISTENT_PROPOSAL")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadaUnaPropuestaAceptadaQueReferenciaUnNodeIdNoEncontradoPorCourseElementLocatorAlReagregarCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonINCONSISTENTPROPOSAL() {
        stubActive("audit-r013c", "plan-r013c");
        when(refinementPlanStore.load("plan-r013c")).thenReturn(Optional.of(plan("plan-r013c", "audit-r013c")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-ghost", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-ghost", null);
        RevisionArtifact approved = approvedArtifact("proposal-ghost", "plan-r013c", "audit-r013c",
                "quiz-ghost", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-other", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r013c")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r013c")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(any(), any()))
                .thenThrow(new IllegalArgumentException("nodeId quiz-ghost not found in course tree"));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability());
        assertEquals(ConsolidatedViewUnavailabilityReason.INCONSISTENT_PROPOSAL,
                view.getUnavailability().getReason());
    }

    @Test
    @DisplayName("Dado que AuditEngine falla al recomputar agregaciones sobre el subarbol modificado, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason REAGGREGATION_FAILED")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoQueAuditEngineFallaAlRecomputarAgregacionesSobreElSubarbolModificadoCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonREAGGREGATIONFAILED() {
        stubActive("audit-r013d", "plan-r013d");
        when(refinementPlanStore.load("plan-r013d")).thenReturn(Optional.of(plan("plan-r013d", "audit-r013d")));

        CourseElementSnapshot snap1 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snap2 = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        RevisionArtifact approved = approvedArtifact("proposal-r013d", "plan-r013d", "audit-r013d",
                "quiz-001", snap1, snap2, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r013d")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r013d")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snap2))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        when(auditEngine.runAudit(eq(audAfter)))
                .thenThrow(new RuntimeException("Motor de auditoria fallo al re-agregar"));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability());
        assertEquals(ConsolidatedViewUnavailabilityReason.REAGGREGATION_FAILED,
                view.getUnavailability().getReason());
    }

    @Test
    @DisplayName("Dada cualquier invocacion de build (exitosa, UNAVAILABLE o con pendientes no aplicables), entonces no se invoca AuditReportStore.save, RefinementPlanStore.save ni RevisionArtifactStore.save sobre los stores inyectados")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R015")
    public void dadaCualquierInvocacionDeBuildExitosaUNAVAILABLEOConPendientesNoAplicablesEntoncesNoSeInvocaAuditReportStoresaveRefinementPlanStoresaveNiRevisionArtifactStoresaveSobreLosStoresInyectados() {
        stubActive("audit-r015", "plan-r015");
        when(refinementPlanStore.load("plan-r015")).thenReturn(Optional.of(plan("plan-r015", "audit-r015")));
        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.70));
        when(auditReportStore.load("audit-r015")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r015")).thenReturn(List.of());
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        builder().build(COURSE_PATH);

        verify(auditReportStore, never()).save(any());
        verify(refinementPlanStore, never()).save(any());
        verify(revisionArtifactStore, never()).save(any());
    }

    @Test
    @DisplayName("Dado un plan activo asociado a un AuditReport y un plan ajeno con propuestas distintas asociadas a otro analisis, cuando build corre, entonces solo se consultan los RevisionArtifact via listByPlan(activePlanId) y las propuestas del plan ajeno no aparecen en nodeImpacts ni statisticImpacts")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R017")
    public void dadoUnPlanActivoAsociadoAUnAuditReportYUnPlanAjenoConPropuestasDistintasAsociadasAOtroAnalisisCuandoBuildCorreEntoncesSoloSeConsultanLosRevisionArtifactViaListByPlanactivePlanIdYLasPropuestasDelPlanAjenoNoAparecenEnNodeImpactsNiStatisticImpacts() {
        String activePlanId = "plan-active";
        String foreignPlanId = "plan-foreign";
        stubActive("audit-active", activePlanId);
        when(refinementPlanStore.load(activePlanId)).thenReturn(Optional.of(plan(activePlanId, "audit-active")));
        when(revisionArtifactStore.listByPlan(activePlanId)).thenReturn(List.of());

        AuditNode root = quizNode("quiz-001", Map.of("lemma-absence", 0.70));
        when(auditReportStore.load("audit-active")).thenReturn(Optional.of(report(root)));
        CourseEntity course = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseMapper.map(course)).thenReturn(mock(AuditableCourse.class));
        when(auditEngine.runAudit(any())).thenReturn(report(root));

        builder().build(COURSE_PATH);

        verify(revisionArtifactStore).listByPlan(activePlanId);
        verify(revisionArtifactStore, never()).listByPlan(foreignPlanId);
    }

    @Test
    @DisplayName("Dada una RevisionProposal cuyo elementBefore y elementAfter referencian el mismo nodeId estable, cuando build corre, entonces el NodeImpact resultante conserva ese nodeId en consolidated y pendingProjection sin modelar renombres ni reubicaciones")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R018")
    public void dadaUnaRevisionProposalCuyoElementBeforeYElementAfterReferencianElMismoNodeIdEstableCuandoBuildCorreEntoncesElNodeImpactResultanteConservaEseNodeIdEnConsolidatedYPendingProjectionSinModelarRenombresNiReubicaciones() {
        stubActive("audit-r018", "plan-r018");
        when(refinementPlanStore.load("plan-r018")).thenReturn(Optional.of(plan("plan-r018", "audit-r018")));

        String stableNodeId = "quiz-stable-id";
        CourseElementSnapshot snapBefore = new CourseElementSnapshot(AuditTarget.QUIZ, stableNodeId, null);
        CourseElementSnapshot snapAfter = new CourseElementSnapshot(AuditTarget.QUIZ, stableNodeId, null);
        RevisionArtifact approved = approvedArtifact("proposal-r018", "plan-r018", "audit-r018",
                stableNodeId, snapBefore, snapAfter, Instant.parse("2026-01-01T00:00:00Z"));

        AuditNode root = quizNode(stableNodeId, Map.of("lemma-absence", 0.60));
        when(auditReportStore.load("audit-r018")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r018")).thenReturn(List.of(approved));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfter = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snapAfter))).thenReturn(courseAfter);
        AuditableCourse audAfter = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfter)).thenReturn(audAfter);
        when(auditEngine.runAudit(eq(audAfter))).thenReturn(report(quizNode(stableNodeId, Map.of("lemma-absence", 0.80))));

        ConsolidatedView view = builder().build(COURSE_PATH);

        NodeImpact ni = view.getNodeImpacts().stream()
                .filter(n -> stableNodeId.equals(n.getNodeId())).findFirst()
                .orElseThrow(() -> new AssertionError("NodeImpact para " + stableNodeId + " no encontrado"));

        assertEquals(stableNodeId, ni.getConsolidated().getNodeId(),
                "consolidated deve conservar el nodeId estable sin modelar renombres");
    }

    @Test
    @DisplayName("Dado un plan activo con varias aceptadas y varias pendientes que tocan distintos nodos del curso, cuando build corre, entonces el ConsolidatedView retornado combina baseline + aceptadas + pendientes en una unica estructura con nodeImpacts y statisticImpacts agregados")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R016")
    public void dadoUnPlanActivoConVariasAceptadasYVariasPendientesQueTocanDistintosNodosDelCursoCuandoBuildCorreEntoncesElConsolidatedViewRetornadoCombinaBaselineAceptadasPendientesEnUnaUnicaEstructuraConNodeImpactsYStatisticImpactsAgregados() {
        stubActive("audit-r016", "plan-r016");
        when(refinementPlanStore.load("plan-r016")).thenReturn(Optional.of(plan("plan-r016", "audit-r016")));

        CourseElementSnapshot snapQ1B = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapQ1A = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapQ2B = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-002", null);
        CourseElementSnapshot snapQ2A = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-002", null);

        RevisionArtifact approved = approvedArtifact("proposal-acc", "plan-r016", "audit-r016",
                "quiz-001", snapQ1B, snapQ1A, Instant.parse("2026-01-01T00:00:00Z"));
        RevisionArtifact pending = pendingArtifact("proposal-pend", "plan-r016", "audit-r016",
                "quiz-002", snapQ2B, snapQ2A, Instant.parse("2026-01-02T00:00:00Z"));

        AuditNode quiz1 = quizNode("quiz-001", Map.of("lemma-absence", 0.60));
        AuditNode quiz2 = quizNode("quiz-002", Map.of("lemma-absence", 0.55));
        AuditNode root = new AuditNode();
        root.setTarget(AuditTarget.COURSE);
        FakeEntity courseEnt = new FakeEntity("course-001");
        root.setEntity(courseEnt);
        root.setScores(Map.of("lemma-absence", 0.575));
        root.setChildren(List.of(quiz1, quiz2));

        when(auditReportStore.load("audit-r016")).thenReturn(Optional.of(report(root)));
        when(revisionArtifactStore.listByPlan("plan-r016")).thenReturn(List.of(approved, pending));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAfterAcc = mock(CourseEntity.class);
        CourseEntity courseAfterPend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snapQ1A))).thenReturn(courseAfterAcc);
        when(courseElementLocator.snapshot(eq(courseAfterAcc), eq(AuditTarget.QUIZ), eq("quiz-002")))
                .thenReturn(Optional.of(snapQ2B));
        when(courseElementLocator.replace(eq(courseAfterAcc), eq(snapQ2A))).thenReturn(courseAfterPend);

        AuditableCourse audAcc = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(courseAfterAcc)).thenReturn(audAcc);
        when(courseMapper.map(courseAfterPend)).thenReturn(audPend);

        AuditNode rootAfterAcc = new AuditNode();
        rootAfterAcc.setTarget(AuditTarget.COURSE);
        rootAfterAcc.setEntity(courseEnt);
        rootAfterAcc.setScores(Map.of("lemma-absence", 0.675));
        rootAfterAcc.setChildren(List.of(quizNode("quiz-001", Map.of("lemma-absence", 0.80)),
                                         quizNode("quiz-002", Map.of("lemma-absence", 0.55))));
        when(auditEngine.runAudit(eq(audAcc))).thenReturn(report(rootAfterAcc));

        AuditNode rootAfterPend = new AuditNode();
        rootAfterPend.setTarget(AuditTarget.COURSE);
        rootAfterPend.setEntity(courseEnt);
        rootAfterPend.setScores(Map.of("lemma-absence", 0.775));
        rootAfterPend.setChildren(List.of(quizNode("quiz-001", Map.of("lemma-absence", 0.80)),
                                          quizNode("quiz-002", Map.of("lemma-absence", 0.75))));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(report(rootAfterPend));

        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability());
        assertFalse(view.getNodeImpacts().isEmpty());
        assertFalse(view.getStatisticImpacts().isEmpty());
        assertTrue(view.getNodeImpacts().stream().anyMatch(n -> "quiz-001".equals(n.getNodeId())));
        assertTrue(view.getNodeImpacts().stream().anyMatch(n -> "quiz-002".equals(n.getNodeId())));
    }
}
