package com.learney.contentaudit.revisiondomain.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.ActiveAnalysisSelection;
import com.learney.contentaudit.auditdomain.ActiveAnalysisSelectionStore;
import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableCourse;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.CourseMapper;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.SentenceLengthDiagnosis;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedView;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewAvailability;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewUnavailabilityReason;
import com.learney.contentaudit.revisiondomain.consolidatedview.NodeFieldDiffer;
import com.learney.contentaudit.revisiondomain.fielddiff.DefaultNodeFieldDifferFactory;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class DefaultConsolidatedViewBuilderTest {

    @Mock RevisionArtifactStore revisionArtifactStore;
    @Mock ActiveAnalysisSelectionStore activeAnalysisSelectionStore;
    @Mock AuditReportStore auditReportStore;
    @Mock RefinementPlanStore refinementPlanStore;
    @Mock CourseRepository courseRepository;
    @Mock CourseElementLocator courseElementLocator;
    @Mock CourseMapper courseMapper;
    @Mock AuditEngine auditEngine;
    @Mock NodeFieldDiffer nodeFieldDiffer;

    private static final String AUDIT_ID   = "audit-001";
    private static final String PLAN_ID    = "plan-001";
    private static final Path   COURSE_PATH = Path.of("/courses/english");

    private DefaultConsolidatedViewBuilder builder;

    @BeforeEach
    void setUp() {
        builder = new DefaultConsolidatedViewBuilder(
                revisionArtifactStore,
                activeAnalysisSelectionStore,
                auditReportStore,
                refinementPlanStore,
                courseRepository,
                courseElementLocator,
                courseMapper,
                auditEngine,
                nodeFieldDiffer);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private ActiveAnalysisSelection activeSelection() {
        return new ActiveAnalysisSelection(AUDIT_ID, PLAN_ID);
    }

    private RefinementPlan emptyPlan() {
        return new RefinementPlan(PLAN_ID, AUDIT_ID, Instant.now(), Collections.emptyList());
    }

    private AuditNode quizNode(String id, int tokenCount, int delta) {
        AuditableEntity entity = org.mockito.Mockito.mock(AuditableEntity.class);
        org.mockito.Mockito.when(entity.getId()).thenReturn(id);
        SentenceLengthDiagnosis diag = new SentenceLengthDiagnosis(
                tokenCount, 6, 12, CefrLevel.A1, delta, 1);
        DefaultQuizDiagnoses diagnoses = new DefaultQuizDiagnoses();
        diagnoses.setSentenceLengthDiagnosis(diag);
        return new AuditNode(entity, AuditTarget.QUIZ, null,
                Collections.emptyList(), Collections.emptyMap(), Collections.emptyMap(), diagnoses);
    }

    private AuditReport reportWith(AuditNode root) {
        return new AuditReport(root);
    }

    private RevisionArtifact approvedArtifact(String proposalId, String nodeId) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-" + proposalId, PLAN_ID, AUDIT_ID,
                null, AuditTarget.QUIZ, nodeId,
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                "rationale", "auto", Instant.now(), null);
        return new RevisionArtifact(proposal, RevisionVerdict.APPROVED, null, null, Instant.now(), null);
    }

    private RevisionArtifact pendingArtifact(String proposalId, String nodeId) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-" + proposalId, PLAN_ID, AUDIT_ID,
                null, AuditTarget.QUIZ, nodeId,
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                "rationale", "auto", Instant.now(), null);
        return new RevisionArtifact(proposal, RevisionVerdict.PENDING_APPROVAL, null, null, Instant.now(), null);
    }

    private RevisionArtifact rejectedArtifact(String proposalId, String nodeId) {
        RevisionProposal proposal = new RevisionProposal(
                proposalId, "task-" + proposalId, PLAN_ID, AUDIT_ID,
                null, AuditTarget.QUIZ, nodeId,
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                new CourseElementSnapshot(AuditTarget.QUIZ, nodeId, null),
                "rationale", "auto", Instant.now(), null);
        return new RevisionArtifact(proposal, RevisionVerdict.REJECTED, "no sirve", null, Instant.now(), null);
    }

    /** Stub the "happy path" up to the point where AuditEngine runs. */
    private void stubActive(AuditNode baselineRoot) {
        when(activeAnalysisSelectionStore.read())
                .thenReturn(Optional.of(activeSelection()));
        when(auditReportStore.load(AUDIT_ID))
                .thenReturn(Optional.of(reportWith(baselineRoot)));
        when(refinementPlanStore.load(PLAN_ID))
                .thenReturn(Optional.of(emptyPlan()));
        CourseEntity courseEntity = new CourseEntity("cid", "English", Collections.emptyList(), null, "english");
        when(courseRepository.load(COURSE_PATH))
                .thenReturn(courseEntity);
        AuditableCourse auditableCourse = new AuditableCourse(Collections.emptyList());
        when(courseMapper.map(any())).thenReturn(auditableCourse);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R001
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dada una seleccion activa con auditId y planId resolubles, cuando build corre, entonces ConsolidatedView.activeAuditId y activePlanId coinciden con los identificadores leidos del ActiveAnalysisSelectionStore")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R001")
    public void dadaUnaSeleccionActivaConAuditIdYPlanIdResolublesCuandoBuildCorreEntoncesConsolidatedViewactiveAuditIdYActivePlanIdCoincidenConLosIdentificadoresLeidosDelActiveAnalysisSelectionStore(
            ) {
        // Arrange
        AuditNode root = quizNode("quiz-r001", 10, 0);
        stubActive(root);
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        AuditReport baselineReport = reportWith(root);
        when(auditReportStore.load(AUDIT_ID)).thenReturn(Optional.of(baselineReport));
        when(auditEngine.runAudit(any())).thenReturn(reportWith(root));
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R001: activeAuditId y activePlanId deben coincidir con los del store
        assertEquals(AUDIT_ID, view.getActiveAuditId(),
                "activeAuditId debe coincidir con el leido del ActiveAnalysisSelectionStore (R001)");
        assertEquals(PLAN_ID, view.getActivePlanId(),
                "activePlanId debe coincidir con el leido del ActiveAnalysisSelectionStore (R001)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R013 (4 razones de UNAVAILABLE)
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado que el ActiveAnalysisSelectionStore retorna Optional.empty, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason NO_ACTIVE_ANALYSIS y nodeImpacts queda vacio — R013")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoQueElActiveAnalysisSelectionStoreRetornaOptionalemptyCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonNOACTIVEANALYSISYNodeImpactsQuedaVacioR013(
            ) {
        // Arrange: no hay seleccion activa
        when(activeAnalysisSelectionStore.read()).thenReturn(Optional.empty());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R013 / NO_ACTIVE_ANALYSIS
        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability(),
                "La availability debe ser UNAVAILABLE cuando no hay par activo (R013)");
        assertNotNull(view.getUnavailability(),
                "El campo unavailability debe estar poblado");
        assertEquals(ConsolidatedViewUnavailabilityReason.NO_ACTIVE_ANALYSIS,
                view.getUnavailability().getReason(),
                "La razon debe ser NO_ACTIVE_ANALYSIS (R013)");
        assertTrue(view.getNodeImpacts().isEmpty(),
                "nodeImpacts debe estar vacio cuando UNAVAILABLE (R013)");
    }

    @Test
    @DisplayName("Dado un par activo cuyo planId no se puede ubicar dentro del analisis (RefinementPlanStore retorna empty), cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason ACTIVE_PLAN_UNAVAILABLE")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoUnParActivoCuyoPlanIdNoSePuedeUbicarDentroDelAnalisisRefinementPlanStoreRetornaEmptyCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonACTIVEPLANUNAVAILABLE(
            ) {
        // Arrange: hay par activo pero el plan no se puede cargar
        AuditNode node013b = quizNode("quiz-r013b", 10, 0);
        when(activeAnalysisSelectionStore.read())
                .thenReturn(Optional.of(activeSelection()));
        when(auditReportStore.load(AUDIT_ID))
                .thenReturn(Optional.of(reportWith(node013b)));
        when(refinementPlanStore.load(PLAN_ID)).thenReturn(Optional.empty());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R013 / ACTIVE_PLAN_UNAVAILABLE
        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability(),
                "La availability debe ser UNAVAILABLE cuando el plan no se encuentra (R013)");
        assertEquals(ConsolidatedViewUnavailabilityReason.ACTIVE_PLAN_UNAVAILABLE,
                view.getUnavailability().getReason(),
                "La razon debe ser ACTIVE_PLAN_UNAVAILABLE (R013)");
    }

    @Test
    @DisplayName("Dada una propuesta aceptada que referencia un nodeId no encontrado por CourseElementLocator al re-agregar, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason INCONSISTENT_PROPOSAL")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadaUnaPropuestaAceptadaQueReferenciaUnNodeIdNoEncontradoPorCourseElementLocatorAlReagregarCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonINCONSISTENTPROPOSAL(
            ) {
        // Arrange: hay una propuesta APPROVED pero su aplicacion (replace) falla
        // porque el elemento referenciado es inconsistente con el estado actual del curso.
        AuditNode baseRoot = quizNode("quiz-absent", 10, 0);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-absent", "quiz-absent");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));
        // El replace de la propuesta APPROVED lanza excepcion (nodeId inconsistente)
        when(courseElementLocator.replace(any(), any()))
                .thenThrow(new IllegalArgumentException("nodeId no encontrado en el curso"));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R013 / INCONSISTENT_PROPOSAL
        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability(),
                "La availability debe ser UNAVAILABLE cuando la propuesta APPROVED no se puede aplicar (R013)");
        assertEquals(ConsolidatedViewUnavailabilityReason.INCONSISTENT_PROPOSAL,
                view.getUnavailability().getReason(),
                "La razon debe ser INCONSISTENT_PROPOSAL cuando replace falla por nodeId inconsistente (R013)");
    }

    @Test
    @DisplayName("Dado que AuditEngine falla al recomputar agregaciones sobre el subarbol modificado, cuando build corre, entonces ConsolidatedView.availability es UNAVAILABLE con reason REAGGREGATION_FAILED")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R013")
    public void dadoQueAuditEngineFallaAlRecomputarAgregacionesSobreElSubarbolModificadoCuandoBuildCorreEntoncesConsolidatedViewavailabilityEsUNAVAILABLEConReasonREAGGREGATIONFAILED(
            ) {
        // Arrange: el AuditEngine lanza excepcion al re-correr
        AuditNode root = quizNode("quiz-fail", 10, 0);
        stubActive(root);
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        when(auditEngine.runAudit(any()))
                .thenThrow(new RuntimeException("motor fallo"));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R013 / REAGGREGATION_FAILED
        assertEquals(ConsolidatedViewAvailability.UNAVAILABLE, view.getAvailability(),
                "La availability debe ser UNAVAILABLE cuando el auditEngine falla (R013)");
        assertEquals(ConsolidatedViewUnavailabilityReason.REAGGREGATION_FAILED,
                view.getUnavailability().getReason(),
                "La razon debe ser REAGGREGATION_FAILED cuando el motor lanza excepcion (R013)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R015
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dada cualquier invocacion de build (exitosa, UNAVAILABLE o con pendientes no aplicables), entonces no se invoca AuditReportStore.save, RefinementPlanStore.save ni RevisionArtifactStore.save sobre los stores inyectados")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R015")
    public void dadaCualquierInvocacionDeBuildExitosaUNAVAILABLEOConPendientesNoAplicablesEntoncesNoSeInvocaAuditReportStoresaveRefinementPlanStoresaveNiRevisionArtifactStoresaveSobreLosStoresInyectados(
            ) {
        // Arrange: caso exitoso con un plan sin propuestas
        AuditNode root = quizNode("quiz-r015", 10, 0);
        stubActive(root);
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        when(auditEngine.runAudit(any())).thenReturn(reportWith(root));
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        builder.build(COURSE_PATH);

        // Assert R015: NUNCA se invoca .save en ninguno de los tres stores
        verify(auditReportStore, never()).save(any());
        verify(refinementPlanStore, never()).save(any());
        verify(revisionArtifactStore, never()).save(any());

        // Verificamos tambien para el caso UNAVAILABLE (no hay seleccion activa)
        org.mockito.Mockito.reset(activeAnalysisSelectionStore, auditReportStore,
                refinementPlanStore, revisionArtifactStore);
        when(activeAnalysisSelectionStore.read()).thenReturn(Optional.empty());
        builder.build(COURSE_PATH);
        verify(auditReportStore, never()).save(any());
        verify(refinementPlanStore, never()).save(any());
        verify(revisionArtifactStore, never()).save(any());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R003
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un AuditReport cuyo plan activo no tiene propuestas aceptadas ni pendientes, cuando build corre, entonces nodeImpacts queda vacio (no hay nodos afectados que reportar) — R003")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R003")
    public void dadoUnAuditReportCuyoPlanActivoNoTienePropuestasAceptadasNiPendientesCuandoBuildCorreEntoncesNodeImpactsQuedaVacioNoHayNodosAfectadosQueReportarR003(
            ) {
        // Arrange: plan sin propuestas — no hay APPROVED ni PENDING_APPROVAL
        AuditNode root = quizNode("quiz-r003", 10, 0);
        stubActive(root);
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        when(auditEngine.runAudit(any())).thenReturn(reportWith(root));
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R003: lista de afectados vacia
        assertNotNull(view.getNodeImpacts(),
                "nodeImpacts no debe ser null (R003)");
        assertTrue(view.getNodeImpacts().isEmpty(),
                "nodeImpacts debe estar vacio cuando no hay propuestas APPROVED/PENDING (R003)");
        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability(),
                "La availability debe ser AVAILABLE aunque nodeImpacts este vacio (R003)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R004
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un plan activo de un analisis viejo con propuestas pendientes y un analisis mas nuevo cuyo plan no las contiene, cuando build corre apuntando al analisis viejo, entonces sus pendientes dormidas aparecen como pendingProposalIds y como contribuciones a la foto pendingProjection de los fields tocados en nodeImpacts — R004")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R004")
    public void dadoUnPlanActivoDeUnAnalisisViejoConPropuestasPendientesYUnAnalisisMasNuevoCuyoPlanNoLasContieneCuandoBuildCorreApuntandoAlAnalisisViejoEntoncesSusPendientesDormidasAparecenComoPendingProposalIdsYComoContribucionesALaFotoPendingProjectionDeLosFieldsTocadosEnNodeImpactsR004(
            ) {
        // Arrange: plan viejo con una PENDING_APPROVAL
        AuditNode baseRoot = quizNode("quiz-r004", 8, -2);
        stubActive(baseRoot);

        RevisionArtifact pending = pendingArtifact("prop-dormida", "quiz-r004");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(pending));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r004", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        // El engine produce distintos reportes para consolidated y pendingProjection
        AuditNode consRoot = quizNode("quiz-r004", 8, -2); // sin cambio (no hay approved)
        AuditNode pendRoot = quizNode("quiz-r004", 10, 0); // con pendiente aplicada
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        // El differ detecta el cambio entre consRoot y pendRoot en tokenCount
        when(nodeFieldDiffer.diff(any(), any(), any()))
                .thenReturn(Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount",
                        new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 8, 10)));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R004: la pendiente dormida aparece en pendingProposalIds del nodo afectado
        assertNotNull(view.getNodeImpacts(),
                "nodeImpacts no debe ser null (R004)");
        assertEquals(1, view.getNodeImpacts().size(),
                "Debe haber un NodeImpact para el nodo afectado por la pendiente dormida (R004)");
        assertTrue(view.getNodeImpacts().get(0).getPendingProposalIds().contains("prop-dormida"),
                "La pendiente dormida debe aparecer en pendingProposalIds del NodeImpact (R004)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R005
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un RevisionArtifact con verdict REJECTED en el plan activo, cuando build corre, entonces ese proposalId no aparece en nodeImpacts (ni en acceptedProposalIds ni en pendingProposalIds de ningun nodo) ni en nonApplicablePendings, y no contribuye a las fotos original/consolidated/pendingProjection de ningun field — R005")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R005")
    public void dadoUnRevisionArtifactConVerdictREJECTEDEnElPlanActivoCuandoBuildCorreEntoncesEseProposalIdNoApareceEnNodeImpactsNiEnAcceptedProposalIdsNiEnPendingProposalIdsDeNingunNodoNiEnNonApplicablePendingsYNoContribuyeALasFotosOriginalconsolidatedpendingProjectionDeNingunFieldR005(
            ) {
        // Arrange: un REJECTED y ningun otro artefacto
        AuditNode root = quizNode("quiz-r005", 10, 0);
        stubActive(root);
        RevisionArtifact rejected = rejectedArtifact("prop-rejected", "quiz-r005");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(rejected));
        when(auditEngine.runAudit(any())).thenReturn(reportWith(root));
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R005: el proposalId del REJECTED no aparece en ningun NodeImpact
        boolean aparecioEnAccepted = view.getNodeImpacts().stream()
                .anyMatch(ni -> ni.getAcceptedProposalIds() != null
                        && ni.getAcceptedProposalIds().contains("prop-rejected"));
        boolean aparecioEnPending = view.getNodeImpacts().stream()
                .anyMatch(ni -> ni.getPendingProposalIds() != null
                        && ni.getPendingProposalIds().contains("prop-rejected"));
        boolean aparecioEnNonApplicable = view.getNonApplicablePendings() != null
                && view.getNonApplicablePendings().stream()
                        .anyMatch(nap -> "prop-rejected".equals(nap.getProposalId()));

        assertTrue(!aparecioEnAccepted && !aparecioEnPending && !aparecioEnNonApplicable,
                "La propuesta REJECTED no debe aparecer en ningun campo de la salida (R005)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R017
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un plan activo asociado a un AuditReport y un plan ajeno con propuestas distintas asociadas a otro analisis, cuando build corre, entonces solo se consultan los RevisionArtifact via listByPlan(activePlanId) y las propuestas del plan ajeno no aparecen en nodeImpacts (ni como acceptedProposalIds, pendingProposalIds, ni como contribuciones a las fotos de fields) — R017")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R017")
    public void dadoUnPlanActivoAsociadoAUnAuditReportYUnPlanAjenoConPropuestasDistintasAsociadasAOtroAnalisisCuandoBuildCorreEntoncesSoloSeConsultanLosRevisionArtifactViaListByPlanactivePlanIdYLasPropuestasDelPlanAjenoNoAparecenEnNodeImpactsNiComoAcceptedProposalIdsPendingProposalIdsNiComoContribucionesALasFotosDeFieldsR017(
            ) {
        // Arrange: el plan activo no tiene propuestas; verificamos que listByPlan se llama con
        // el planId activo y no con otro planId
        AuditNode root = quizNode("quiz-r017", 10, 0);
        stubActive(root);
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        when(auditEngine.runAudit(any())).thenReturn(reportWith(root));
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R017: listByPlan fue invocado con el planId activo (no con otro plan)
        verify(revisionArtifactStore).listByPlan(PLAN_ID);
        // Y no fue invocado con ningun otro planId
        verify(revisionArtifactStore, never()).listByPlan(org.mockito.AdditionalMatchers.not(org.mockito.ArgumentMatchers.eq(PLAN_ID)));

        // Assert: ningun NodeImpact contiene propuestas de plans ajenos
        assertTrue(view.getNodeImpacts().isEmpty(),
                "No debe haber NodeImpacts cuando el plan activo no tiene propuestas (R017)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R006 (3 invariantes)
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un nodo hoja con un field cuyas tres fotos son identicas y otro field cuya foto consolidated difiere de original, cuando build corre, entonces el mapa fieldChanges del NodeImpact contiene SOLO la entrada del segundo field — R006 invariante 1: solo fields con cambio")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoHojaConUnFieldCuyasTresFotosSonIdenticasYOtroFieldCuyaFotoConsolidatedDifiereDeOriginalCuandoBuildCorreEntoncesElMapaFieldChangesDelNodeImpactContieneSOLOLaEntradaDelSegundoFieldR006Invariante1SoloFieldsConCambio(
            ) {
        // Arrange: APPROVED que cambia el nodo. El differ retorna solo el field que cambio
        AuditNode baseRoot = quizNode("quiz-r006", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r006", "quiz-r006");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r006", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r006", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        // El differ retorna UN SOLO field cambiado (tokenCount); el targetMin no difiere
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange tokenCountChange =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any()))
                .thenReturn(Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", tokenCountChange));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R006.1: el mapa solo tiene el field que cambia (tokenCount), no targetMin
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null");
        assertEquals(1, view.getNodeImpacts().size(), "Debe haber un NodeImpact");
        Map<String, com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange> fieldChanges =
                view.getNodeImpacts().get(0).getFieldChanges();
        assertEquals(1, fieldChanges.size(),
                "Solo debe haber UN field cambiado en el mapa (R006.1)");
        assertTrue(fieldChanges.containsKey("diagnoses.sentenceLengthDiagnosis.tokenCount"),
                "El field cambiado debe ser tokenCount (R006.1)");
    }

    @Test
    @DisplayName("Dado un NodeImpact con varios fields cambiados de origenes distintos (componente de diagnostico tipado, contenido del nodo, score escalar), cuando build corre, entonces todas las entradas del mapa fieldChanges siguen la misma forma clave-valor con FieldChange(original, consolidated, pendingProjection) sin ramas separadas por origen del field — R006 invariante 2: forma uniforme")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodeImpactConVariosFieldsCambiadosDeOrigenesDistintosComponenteDeDiagnosticoTipadoContenidoDelNodoScoreEscalarCuandoBuildCorreEntoncesTodasLasEntradasDelMapaFieldChangesSiguenLaMismaFormaClavevalorConFieldChangeoriginalConsolidatedPendingProjectionSinRamasSeparadasPorOrigenDelFieldR006Invariante2FormaUniforme(
            ) {
        // Arrange: APPROVED que cambia el nodo; el differ retorna 2 fields de origenes distintos
        AuditNode baseRoot = quizNode("quiz-r006b", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r006b", "quiz-r006b");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r006b", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r006b", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        // El differ retorna dos fields de origenes distintos: diagnostico + score
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange diagChange =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange scoreChange =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(0.65, 0.85, 0.85);
        when(nodeFieldDiffer.diff(any(), any(), any()))
                .thenReturn(Map.of(
                        "diagnoses.sentenceLengthDiagnosis.tokenCount", diagChange,
                        "scores.sentenceLength", scoreChange));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R006.2: ambas entradas tienen la forma uniforme FieldChange(orig, cons, pend)
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null");
        assertEquals(1, view.getNodeImpacts().size(), "Debe haber un NodeImpact");
        Map<String, com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange> fieldChanges =
                view.getNodeImpacts().get(0).getFieldChanges();
        assertEquals(2, fieldChanges.size(),
                "Deben aparecer los 2 fields cambiados de origenes distintos (R006.2)");
        // Verificamos que todos los valores son FieldChange (forma uniforme)
        for (com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc : fieldChanges.values()) {
            assertNotNull(fc.getOriginal(),    "original no debe ser null en forma uniforme");
            assertNotNull(fc.getConsolidated(),"consolidated no debe ser null en forma uniforme");
            // pendingProjection puede ser null o igual a consolidated cuando no hay pendiente
        }
    }

    @Test
    @DisplayName("Dado un nodo cuyo subarbol no produce ningun field cambiado entre las tres fotos, cuando build corre, entonces ese nodo NO aparece en ConsolidatedView.nodeImpacts — R006 invariante 3: nodo sin cambios no aparece")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R006")
    public void dadoUnNodoCuyoSubarbolNoProduceNingunFieldCambiadoEntreLasTresFotosCuandoBuildCorreEntoncesEseNodoNOApareceEnConsolidatedViewnodeImpactsR006Invariante3NodoSinCambiosNoAparece(
            ) {
        // Arrange: plan sin propuestas — ningun nodo esta en acceptedProposalIds ni pendingProposalIds.
        // Sin propuestas que afecten el nodo, el differ retorna mapa vacio y el nodo no aparece.
        // Esta es la invariante R006.3: nodo sin fields cambiados no aparece en nodeImpacts.
        AuditNode baseRoot = quizNode("quiz-r006c", 10, 0);
        stubActive(baseRoot);
        // Sin propuestas: el plan esta vacio
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(Collections.emptyList());
        AuditNode consRoot = quizNode("quiz-r006c", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));
        // El differ indica que no hay campos cambiados (las tres fotos son identicas)
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Collections.emptyMap());

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R006.3: el nodo sin cambios no aparece (lista vacia = R003 y R006.3)
        assertTrue(view.getNodeImpacts().isEmpty(),
                "El nodo sin fields cambiados NO debe aparecer en nodeImpacts (R006.3 = R003 sin propuestas)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R007 (5 invariantes)
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un field cambiado de un nodo hoja, cuando build corre, entonces FieldChange.original es identico al valor que el AuditReport baseline expone para ese field y ese nodo (sin recomputar, sin redondear, sin derivar) — R007 invariante 1: fidelidad de original")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnFieldCambiadoDeUnNodoHojaCuandoBuildCorreEntoncesFieldChangeoriginalEsIdenticoAlValorQueElAuditReportBaselineExponeParaEseFieldYEseNodoSinRecomputarSinRedondearSinDerivarR007Invariante1FidelidadDeOriginal(
            ) {
        // Arrange: el differ retorna un FieldChange con original=8 (el valor del baseline)
        AuditNode baseRoot = quizNode("quiz-r007a", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r007a", "quiz-r007a");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r007a", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r007a", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        // El differ recibe (baseRoot, consRoot, pendRoot) y el original viene del baseRoot (8)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R007.1: el FieldChange.original en la salida es 8 (el valor del baseline)
        assertEquals(1, view.getNodeImpacts().size());
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                view.getNodeImpacts().get(0).getFieldChanges()
                        .get("diagnoses.sentenceLengthDiagnosis.tokenCount");
        assertNotNull(emitted, "El field cambiado debe estar en el mapa");
        assertEquals(8, emitted.getOriginal(),
                "FieldChange.original debe ser el valor del baseline (8), sin recomputo (R007.1)");
    }

    @Test
    @DisplayName("Dado un escenario donde el AuditEngine es invocado dos veces (una sobre el arbol con-aceptadas y otra sobre el arbol con-aceptadas-y-pendientes), cuando build corre, entonces FieldChange.consolidated coincide identicamente con el valor que el AuditReport del primer runAudit dejo en el AuditNode correspondiente, sin que el builder lo recompute o transforme — R007 invariante 2: determinacion de consolidated")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnEscenarioDondeElAuditEngineEsInvocadoDosVecesUnaSobreElArbolConaceptadasYOtraSobreElArbolConaceptadasypendientesCuandoBuildCorreEntoncesFieldChangeconsolidatedCoincideIdenticamenteConElValorQueElAuditReportDelPrimerRunAuditDejoEnElAuditNodeCorrespondienteSinQueElBuilderLoRecomputeOTransformeR007Invariante2DeterminacionDeConsolidated(
            ) {
        // Arrange: una APPROVED genera un AuditReport donde tokenCount=10 (consolidated)
        AuditNode baseRoot = quizNode("quiz-r007b", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r007b", "quiz-r007b");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r007b", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r007b", 10, 0); // primer runAudit: tokenCount=10
        AuditNode pendRoot = quizNode("quiz-r007b", 10, 0); // sin pendientes: igual
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R007.2: FieldChange.consolidated es 10 (del primer runAudit)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                view.getNodeImpacts().get(0).getFieldChanges()
                        .get("diagnoses.sentenceLengthDiagnosis.tokenCount");
        assertEquals(10, emitted.getConsolidated(),
                "FieldChange.consolidated debe ser el valor del primer runAudit (10) (R007.2)");
    }

    @Test
    @DisplayName("Dado un escenario donde el AuditEngine es invocado dos veces (una sobre el arbol con-aceptadas y otra sobre el arbol con-aceptadas-y-pendientes), cuando build corre, entonces FieldChange.pendingProjection coincide identicamente con el valor que el AuditReport del segundo runAudit dejo en el AuditNode correspondiente, sin que el builder lo recompute o derive desde consolidated — R007 invariante 3: determinacion de pendingProjection")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnEscenarioDondeElAuditEngineEsInvocadoDosVecesUnaSobreElArbolConaceptadasYOtraSobreElArbolConaceptadasypendientesCuandoBuildCorreEntoncesFieldChangependingProjectionCoincideIdenticamenteConElValorQueElAuditReportDelSegundoRunAuditDejoEnElAuditNodeCorrespondienteSinQueElBuilderLoRecomputeODeriveDesdeConsolidatedR007Invariante3DeterminacionDePendingProjection(
            ) {
        // Arrange: APPROVED + PENDING. El segundo runAudit produce tokenCount=11
        AuditNode baseRoot = quizNode("quiz-r007c", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r007c-app", "quiz-r007c");
        RevisionArtifact pending  = pendingArtifact("prop-r007c-pend", "quiz-r007c");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved, pending));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r007c", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r007c", 10, 0); // primer runAudit
        AuditNode pendRoot = quizNode("quiz-r007c", 11, 1); // segundo runAudit: tokenCount=11
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 11);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R007.3: FieldChange.pendingProjection es 11 (del segundo runAudit)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                view.getNodeImpacts().get(0).getFieldChanges()
                        .get("diagnoses.sentenceLengthDiagnosis.tokenCount");
        assertEquals(11, emitted.getPendingProjection(),
                "FieldChange.pendingProjection debe ser el valor del segundo runAudit (11) (R007.3)");
    }

    @Test
    @DisplayName("Dado un nodo hoja con una aceptada (que cambia el field) y una pendiente sobre el mismo nodeId (que lo cambia de nuevo), cuando build corre, entonces el AuditEngine es invocado para pendingProjection sobre el arbol que YA tiene la aceptada aplicada (no sobre el original) — R007 invariante 4: orden de stacking, pendientes sobre consolidated, no sobre original")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnNodoHojaConUnaAceptadaQueCambiaElFieldYUnaPendienteSobreElMismoNodeIdQueLoCambiaDeNuevoCuandoBuildCorreEntoncesElAuditEngineEsInvocadoParaPendingProjectionSobreElArbolQueYATieneLaAceptadaAplicadaNoSobreElOriginalR007Invariante4OrdenDeStackingPendientesSobreConsolidatedNoSobreOriginal(
            ) {
        // Arrange: APPROVED + PENDING sobre el mismo nodeId
        AuditNode baseRoot = quizNode("quiz-r007d", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r007d-app", "quiz-r007d");
        RevisionArtifact pending  = pendingArtifact("prop-r007d-pend", "quiz-r007d");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved, pending));

        CourseElementSnapshot snapshotOrig = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r007d", null);
        CourseElementSnapshot snapshotCons = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r007d", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshotOrig));
        CourseEntity courseAfterApproved = new CourseEntity("cid", "English", Collections.emptyList(), null, "english");
        CourseEntity courseAfterPending  = new CourseEntity("cid", "English", Collections.emptyList(), null, "english");
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(courseAfterApproved)
                .thenReturn(courseAfterPending);

        AuditNode consRoot = quizNode("quiz-r007d", 10, 0);
        AuditNode pendRoot = quizNode("quiz-r007d", 11, 1);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 11);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R007.4: el AuditEngine fue invocado exactamente 2 veces
        // (una para consolidated = arbol con APPROVED, otra para pendingProjection = arbol con APPROVED+PENDING)
        org.mockito.Mockito.verify(auditEngine, org.mockito.Mockito.times(2)).runAudit(any());
        // El resultado final tiene pendingProjection=11 (no el original 8)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                view.getNodeImpacts().get(0).getFieldChanges()
                        .get("diagnoses.sentenceLengthDiagnosis.tokenCount");
        assertEquals(11, emitted.getPendingProjection(),
                "pendingProjection debe provenir del segundo runAudit (sobre el arbol con APPROVED+PENDING) (R007.4)");
    }

    @Test
    @DisplayName("Dado un nodo padre cuyo subarbol contiene cambios y para el cual el AuditEngine produjo un valor agregado en el AuditReport del arbol con-aceptadas, cuando build corre, entonces FieldChange.consolidated del field del padre es identico a ese valor leido del AuditReport y NO el resultado de re-agregar deltas de hijos en el builder — R007 invariante 5: las tres fotos provienen del motor")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R007")
    public void dadoUnNodoPadreCuyoSubarbolContieneCambiosYParaElCualElAuditEngineProdujoUnValorAgregadoEnElAuditReportDelArbolConaceptadasCuandoBuildCorreEntoncesFieldChangeconsolidatedDelFieldDelPadreEsIdenticoAEseValorLeidoDelAuditReportYNOElResultadoDeReagregarDeltasDeHijosEnElBuilderR007Invariante5LasTresFotosProvienenDelMotor(
            ) {
        // Arrange: APPROVED sobre el nodo hijo. El builder no re-agrega —
        // lee el valor del padre del AuditReport devuelto por el motor.
        // El differ retorna un FieldChange para un score del padre.
        AuditNode baseRoot = quizNode("quiz-parent", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r007e", "quiz-parent");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-parent", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        // El motor produce un score del padre = 0.85 en el consolidated
        AuditNode consRoot = quizNode("quiz-parent", 10, 0);
        consRoot.setScores(Map.of("sentenceLength", 0.85));
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        // El differ reporta el score del padre como un field cambiado con consolidated=0.85
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange parentScore =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(0.65, 0.85, 0.85);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("scores.sentenceLength", parentScore));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R007.5: el consolidated del score del padre es 0.85 (el que el motor produjo)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                view.getNodeImpacts().get(0).getFieldChanges().get("scores.sentenceLength");
        assertNotNull(emitted, "El score del padre debe aparecer en el mapa (R007.5)");
        assertEquals(0.85, emitted.getConsolidated(),
                "El consolidated del padre debe ser el valor del motor (0.85), no un re-calculo (R007.5)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R009
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un escenario donde varias dimensiones de score cambian por aceptadas o pendientes, cuando build corre, entonces ConsolidatedView devuelto NO expone ningun campo statisticImpacts ni ninguna lista paralela de estadisticas afectadas; los scores cambiados solo aparecen como entradas del mapa fieldChanges del nodo correspondiente — R009")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R009")
    public void dadoUnEscenarioDondeVariasDimensionesDeScoreCambianPorAceptadasOPendientesCuandoBuildCorreEntoncesConsolidatedViewDevueltoNOExponeNingunCampoStatisticImpactsNiNingunaListaParalelaDeEstadisticasAfectadasLosScoresCambiadosSoloAparecenComoEntradasDelMapaFieldChangesDelNodoCorrespondienteR009(
            ) {
        // Arrange: APPROVED, el differ reporta scores cambiados en fieldChanges
        AuditNode baseRoot = quizNode("quiz-r009", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r009", "quiz-r009");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r009", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r009", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange scoreChange =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(0.65, 0.85, 0.85);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("scores.sentenceLength", scoreChange));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R009: ConsolidatedView NO tiene campo statisticImpacts (v2 eliminado)
        // El contrato actual solo expone nodeImpacts y nonApplicablePendings
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null");
        // Verificamos via reflection que NO existe el metodo getStatisticImpacts
        boolean tieneStatisticImpacts;
        try {
            view.getClass().getMethod("getStatisticImpacts");
            tieneStatisticImpacts = true;
        } catch (NoSuchMethodException e) {
            tieneStatisticImpacts = false;
        }
        assertTrue(!tieneStatisticImpacts,
                "ConsolidatedView NO debe exponer getStatisticImpacts (R009 — seccion paralela eliminada)");
        // Los scores cambiados aparecen dentro de fieldChanges del NodeImpact
        assertEquals(1, view.getNodeImpacts().size(), "Debe haber un NodeImpact");
        assertTrue(view.getNodeImpacts().get(0).getFieldChanges().containsKey("scores.sentenceLength"),
                "El score cambiado debe aparecer en fieldChanges, no en una seccion paralela (R009)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R010
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado cualquier ConsolidatedView producido por build, entonces ningun NodeImpact expone campos acceptedDelta o pendingDelta precomputados; el contrato emitido contiene exclusivamente las tripletas (original, consolidated, pendingProjection) por field — R010")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R010")
    public void dadoCualquierConsolidatedViewProducidoPorBuildEntoncesNingunNodeImpactExponeCamposAcceptedDeltaOPendingDeltaPrecomputadosElContratoEmitidoContieneExclusivamenteLasTripletasOriginalConsolidatedPendingProjectionPorFieldR010(
            ) {
        // Arrange: cualquier scenario con un NodeImpact
        AuditNode baseRoot = quizNode("quiz-r010", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r010", "quiz-r010");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved));

        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r010", null);
        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(snapshot));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r010", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R010: NodeImpact NO tiene getAcceptedDelta ni getPendingDelta
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null");
        assertEquals(1, view.getNodeImpacts().size());
        com.learney.contentaudit.revisiondomain.consolidatedview.NodeImpact ni =
                view.getNodeImpacts().get(0);
        boolean tieneAcceptedDelta;
        boolean tienePendingDelta;
        try { ni.getClass().getMethod("getAcceptedDelta"); tieneAcceptedDelta = true; }
        catch (NoSuchMethodException e) { tieneAcceptedDelta = false; }
        try { ni.getClass().getMethod("getPendingDelta"); tienePendingDelta = true; }
        catch (NoSuchMethodException e) { tienePendingDelta = false; }
        assertTrue(!tieneAcceptedDelta,
                "NodeImpact NO debe exponer getAcceptedDelta (R010 — deltas fuera del contrato)");
        assertTrue(!tienePendingDelta,
                "NodeImpact NO debe exponer getPendingDelta (R010 — deltas fuera del contrato)");
        // El FieldChange tiene las tres fotos
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange emitted =
                ni.getFieldChanges().get("diagnoses.sentenceLengthDiagnosis.tokenCount");
        assertNotNull(emitted.getOriginal(), "original presente (R010)");
        assertNotNull(emitted.getConsolidated(), "consolidated presente (R010)");
        assertNotNull(emitted.getPendingProjection(), "pendingProjection presente (R010)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R011 (4 invariantes)
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dada una propuesta APPROVED del plan activo que cambia el contenido de un nodo y otra APPROVED del plan activo que NO afecta a ese nodo, cuando build corre, entonces NodeImpact.acceptedProposalIds del nodo afectado contiene SOLO el proposalId de la primera (R011 invariante 1: cobertura accepted, recíproca incluida)")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R011")
    public void dadaUnaPropuestaAPPROVEDDelPlanActivoQueCambiaElContenidoDeUnNodoYOtraAPPROVEDDelPlanActivoQueNOAfectaAEseNodoCuandoBuildCorreEntoncesNodeImpactacceptedProposalIdsDelNodoAfectadoContieneSOLOElProposalIdDeLaPrimeraR011Invariante1CoberturaAcceptedRecprocaIncluida(
            ) {
        // Arrange: prop1 afecta "quiz-r011a", prop2 afecta "quiz-r011b"
        // Solo "quiz-r011a" aparece en el AuditReport, no "quiz-r011b"
        AuditNode root = quizNode("quiz-r011a", 8, -2);
        stubActive(root);
        RevisionArtifact prop1 = approvedArtifact("prop-r011-1", "quiz-r011a"); // afecta
        RevisionArtifact prop2 = approvedArtifact("prop-r011-2", "quiz-r011b"); // NO afecta (nodo diferente)
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(prop1, prop2));

        // El locator encuentra quiz-r011a pero NO quiz-r011b (empty para r011b)
        when(courseElementLocator.snapshot(any(), any(), org.mockito.ArgumentMatchers.eq("quiz-r011a")))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011a", null)));
        when(courseElementLocator.snapshot(any(), any(), org.mockito.ArgumentMatchers.eq("quiz-r011b")))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011b", null)));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r011a", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any()))
                // Para quiz-r011a hay cambio, para quiz-r011b no hay cambio
                .thenReturn(Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R011.1: solo prop-r011-1 aparece en acceptedProposalIds de quiz-r011a
        // (puede haber un NodeImpact por cada nodo que tuvo cambios)
        boolean prop1enAccepted = view.getNodeImpacts().stream()
                .anyMatch(ni -> ni.getAcceptedProposalIds() != null
                        && ni.getAcceptedProposalIds().contains("prop-r011-1"));
        assertTrue(prop1enAccepted,
                "prop-r011-1 debe aparecer en acceptedProposalIds del nodo afectado (R011.1)");
    }

    @Test
    @DisplayName("Dada una propuesta PENDING_APPROVAL aplicable del plan activo que cambia un nodo y otra PENDING_APPROVAL aplicable que NO afecta a ese nodo, cuando build corre, entonces NodeImpact.pendingProposalIds del nodo afectado contiene SOLO el proposalId de la primera (R011 invariante 2: cobertura pending, recíproca incluida)")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R011")
    public void dadaUnaPropuestaPENDINGAPPROVALAplicableDelPlanActivoQueCambiaUnNodoYOtraPENDINGAPPROVALAplicableQueNOAfectaAEseNodoCuandoBuildCorreEntoncesNodeImpactpendingProposalIdsDelNodoAfectadoContieneSOLOElProposalIdDeLaPrimeraR011Invariante2CoberturaPendingRecprocaIncluida(
            ) {
        // Arrange: pend1 afecta "quiz-r011c" (tiene cambio), pend2 afecta "quiz-r011d" (sin cambio)
        AuditNode root = quizNode("quiz-r011c", 8, -2);
        stubActive(root);
        RevisionArtifact pend1 = pendingArtifact("prop-r011-pend1", "quiz-r011c");
        RevisionArtifact pend2 = pendingArtifact("prop-r011-pend2", "quiz-r011d");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(pend1, pend2));

        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011c", null)));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r011c", 8, -2); // sin APPROVED, igual al baseline
        AuditNode pendRoot = quizNode("quiz-r011c", 10, 0); // con pendiente
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 8, 10);
        when(nodeFieldDiffer.diff(any(), any(), any()))
                .thenReturn(Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R011.2: pend1 aparece en pendingProposalIds, pend2 no
        boolean pend1enPending = view.getNodeImpacts().stream()
                .anyMatch(ni -> ni.getPendingProposalIds() != null
                        && ni.getPendingProposalIds().contains("prop-r011-pend1"));
        boolean pend2enPending = view.getNodeImpacts().stream()
                .anyMatch(ni -> ni.getPendingProposalIds() != null
                        && ni.getPendingProposalIds().contains("prop-r011-pend2"));
        assertTrue(pend1enPending,
                "prop-r011-pend1 debe aparecer en pendingProposalIds (R011.2)");
        assertTrue(!pend2enPending,
                "prop-r011-pend2 NO debe aparecer en el mismo nodo si no lo afecta (R011.2)");
    }

    @Test
    @DisplayName("Dado un nodo hoja con dos propuestas aceptadas que lo afectaron en orden createdAt ascendente, cuando build corre, entonces NodeImpact.acceptedProposalIds contiene ambos proposalId en orden createdAt ascendente — R011 invariante 3: orden estable")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R011")
    public void dadoUnNodoHojaConDosPropuestasAceptadasQueLoAfectaronEnOrdenCreatedAtAscendenteCuandoBuildCorreEntoncesNodeImpactacceptedProposalIdsContieneAmbosProposalIdEnOrdenCreatedAtAscendenteR011Invariante3OrdenEstable(
            ) {
        // Arrange: dos APPROVED con createdAt distintos (prop-mas-vieja < prop-mas-nueva)
        AuditNode baseRoot = quizNode("quiz-r011e", 6, -4);
        stubActive(baseRoot);

        Instant t1 = Instant.parse("2026-01-01T00:00:00Z");
        Instant t2 = Instant.parse("2026-01-02T00:00:00Z");

        RevisionProposal proposal1 = new RevisionProposal(
                "prop-r011-vieja", "task-v", PLAN_ID, AUDIT_ID,
                null, AuditTarget.QUIZ, "quiz-r011e",
                new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011e", null),
                new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011e", null),
                "r1", "auto", t1, null);
        RevisionArtifact approved1 = new RevisionArtifact(proposal1, RevisionVerdict.APPROVED,
                null, null, t1, null);

        RevisionProposal proposal2 = new RevisionProposal(
                "prop-r011-nueva", "task-n", PLAN_ID, AUDIT_ID,
                null, AuditTarget.QUIZ, "quiz-r011e",
                new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011e", null),
                new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011e", null),
                "r2", "auto", t2, null);
        RevisionArtifact approved2 = new RevisionArtifact(proposal2, RevisionVerdict.APPROVED,
                null, null, t2, null);

        // Se pasa en orden: vieja luego nueva — el builder debe ordenar por createdAt ascendente
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved1, approved2));

        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011e", null)));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r011e", 10, 0);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(consRoot));

        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(6, 10, 10);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R011.3: ambas propuestas en acceptedProposalIds en orden createdAt ascendente
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null");
        assertEquals(1, view.getNodeImpacts().size());
        List<String> acceptedIds = view.getNodeImpacts().get(0).getAcceptedProposalIds();
        assertTrue(acceptedIds.contains("prop-r011-vieja"),
                "La propuesta mas vieja debe estar en acceptedProposalIds (R011.3)");
        assertTrue(acceptedIds.contains("prop-r011-nueva"),
                "La propuesta mas nueva debe estar en acceptedProposalIds (R011.3)");
        // El orden debe ser vieja antes que nueva
        assertTrue(acceptedIds.indexOf("prop-r011-vieja") < acceptedIds.indexOf("prop-r011-nueva"),
                "El orden en acceptedProposalIds debe ser createdAt ascendente: vieja antes que nueva (R011.3)");
    }

    @Test
    @DisplayName("Dado un nodo afectado con varias aceptadas y varias pendientes que tocan distintos fields, cuando build corre, entonces NodeImpact expone acceptedProposalIds y pendingProposalIds a nivel del NODO (no asocia un proposalId a un field especifico dentro de fieldChanges) — R011 invariante 4: trazabilidad por nodo, no por field")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R011")
    public void dadoUnNodoAfectadoConVariasAceptadasYVariasPendientesQueTocanDistintosFieldsCuandoBuildCorreEntoncesNodeImpactExponeAcceptedProposalIdsYPendingProposalIdsANivelDelNODONoAsociaUnProposalIdAUnFieldEspecificoDentroDeFieldChangesR011Invariante4TrazabilidadPorNodoNoPorField(
            ) {
        // Arrange: APPROVED + PENDING sobre el mismo nodo con distintos fields
        AuditNode baseRoot = quizNode("quiz-r011f", 8, -2);
        stubActive(baseRoot);
        RevisionArtifact approved = approvedArtifact("prop-r011-acc", "quiz-r011f");
        RevisionArtifact pending  = pendingArtifact("prop-r011-pen", "quiz-r011f");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(approved, pending));

        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r011f", null)));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r011f", 10, 0);
        AuditNode pendRoot = quizNode("quiz-r011f", 11, 1);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        // El differ retorna dos fields distintos (uno por aceptada y uno por pendiente)
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc1 =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 10);
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc2 =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(-2, 0, 1);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(Map.of(
                "diagnoses.sentenceLengthDiagnosis.tokenCount", fc1,
                "diagnoses.sentenceLengthDiagnosis.delta", fc2));

        // Act
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R011.4: los proposalIds estan en el NodeImpact a nivel de nodo
        // NO dentro de los FieldChange individuales
        assertEquals(1, view.getNodeImpacts().size());
        com.learney.contentaudit.revisiondomain.consolidatedview.NodeImpact ni =
                view.getNodeImpacts().get(0);

        // acceptedProposalIds y pendingProposalIds son LISTAS a nivel de NodeImpact
        assertNotNull(ni.getAcceptedProposalIds(), "acceptedProposalIds debe estar en NodeImpact (R011.4)");
        assertNotNull(ni.getPendingProposalIds(), "pendingProposalIds debe estar en NodeImpact (R011.4)");
        assertTrue(ni.getAcceptedProposalIds().contains("prop-r011-acc"), "R011.4: accepted presente");
        assertTrue(ni.getPendingProposalIds().contains("prop-r011-pen"), "R011.4: pending presente");

        // Los FieldChange no tienen proposalId dentro (la trazabilidad es solo a nivel de nodo)
        boolean tieneProposalIdEnFieldChange;
        try {
            com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange.class
                    .getMethod("getProposalId");
            tieneProposalIdEnFieldChange = true;
        } catch (NoSuchMethodException e) {
            tieneProposalIdEnFieldChange = false;
        }
        assertTrue(!tieneProposalIdEnFieldChange,
                "FieldChange NO debe exponer getProposalId (trazabilidad es a nivel del nodo) (R011.4)");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // R016
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("Dado un plan activo con multiples propuestas (varias APPROVED y varias PENDING_APPROVAL) que tocan distintos nodos, cuando build corre una sola vez, entonces ConsolidatedView retornado expone los efectos de TODAS esas propuestas en una unica salida (acceptadas en las fotos consolidated y pendientes aplicables en las fotos pendingProjection) sin requerir invocaciones adicionales del builder — R016 invariante 1: combinacion en un documento")
    @Tag("FEAT-CDIFF")
    @Tag("F-CDIFF-R016")
    public void dadoUnPlanActivoConMultiplesPropuestasVariasAPPROVEDYVariasPENDINGAPPROVALQueTocanDistintosNodosCuandoBuildCorreUnaSolaVezEntoncesConsolidatedViewRetornadoExponeLosEfectosDeTODASEsasPropuestasEnUnaUnicaSalidaAcceptadasEnLasFotosConsolidatedYPendientesAplicablesEnLasFotosPendingProjectionSinRequerirInvocacionesAdicionalesDelBuilderR016Invariante1CombinacionEnUnDocumento(
            ) {
        // Arrange: 2 APPROVED y 1 PENDING en distintos nodos
        AuditNode baseRoot = quizNode("quiz-r016a", 8, -2);
        stubActive(baseRoot);

        RevisionArtifact app1 = approvedArtifact("prop-r016-app1", "quiz-r016a");
        RevisionArtifact app2 = approvedArtifact("prop-r016-app2", "quiz-r016b");
        RevisionArtifact pend = pendingArtifact("prop-r016-pend", "quiz-r016c");
        when(revisionArtifactStore.listByPlan(PLAN_ID)).thenReturn(List.of(app1, app2, pend));

        when(courseElementLocator.snapshot(any(), any(), anyString()))
                .thenReturn(Optional.of(new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-r016a", null)));
        when(courseElementLocator.replace(any(), any()))
                .thenReturn(new CourseEntity("cid", "English", Collections.emptyList(), null, "english"));

        AuditNode consRoot = quizNode("quiz-r016a", 10, 0);
        AuditNode pendRoot = quizNode("quiz-r016a", 11, 1);
        when(auditEngine.runAudit(any()))
                .thenReturn(reportWith(consRoot))
                .thenReturn(reportWith(pendRoot));

        // El differ retorna un field cambiado por la invocacion para el nodo afectado
        com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange fc =
                new com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange(8, 10, 11);
        when(nodeFieldDiffer.diff(any(), any(), any())).thenReturn(
                Map.of("diagnoses.sentenceLengthDiagnosis.tokenCount", fc));

        // Act: una SOLA invocacion al builder
        ConsolidatedView view = builder.build(COURSE_PATH);

        // Assert R016: la salida contiene efectos de TODAS las propuestas en un solo documento
        assertNotNull(view, "ConsolidatedView no debe ser null (R016)");
        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability(),
                "La vista debe estar disponible (R016)");
        // Los IDs del par activo estan en la raiz
        assertEquals(AUDIT_ID, view.getActiveAuditId(), "activeAuditId correcto (R016)");
        assertEquals(PLAN_ID, view.getActivePlanId(), "activePlanId correcto (R016)");
        // La lista de nodeImpacts fue poblada en una sola pasada del builder
        assertNotNull(view.getNodeImpacts(), "nodeImpacts no debe ser null (R016)");
    }
}
