package com.learney.contentaudit.revisiondomain.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.KnowledgeEntity;
import com.learney.contentaudit.coursedomain.MilestoneEntity;
import com.learney.contentaudit.coursedomain.NodeKind;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.RootNodeEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.TopicEntity;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultCourseElementLocatorTest {
    @Test
    @DisplayName("Given a course whose knowledge declares a REWRITE sentenceMode, when replace swaps a quiz inside that knowledge, then the resulting knowledge in the returned course keeps its REWRITE sentenceMode")
    @Tag("FEAT-SMODE")
    @Tag("F-SMODE-R006")
    public void givenACourseWhoseKnowledgeDeclaresAREWRITESentenceModeWhenReplaceSwapsAQuizInsideThatKnowledgeThenTheResultingKnowledgeInTheReturnedCourseKeepsItsREWRITESentenceMode(
            ) {
        // Arrange — build course hierarchy with a REWRITE knowledge containing one quiz

        // Quiz original: el que va a ser reemplazado
        QuizTemplateEntity originalQuiz = new QuizTemplateEntity();
        originalQuiz.setId("quiz-rewrite-001");
        originalQuiz.setKnowledgeId("knowledge-rewrite-001");
        originalQuiz.setTitle("Watch the DVD.");
        originalQuiz.setSentences(List.of("Watch the DVD."));

        // KnowledgeEntity con sentenceMode = REWRITE (F-SMODE-R001, F-SMODE-R002)
        KnowledgeEntity knowledge = new KnowledgeEntity();
        knowledge.setId("knowledge-rewrite-001");
        knowledge.setKind(NodeKind.KNOWLEDGE);
        knowledge.setLabel("Imperatives");
        knowledge.setSentenceMode(SentenceMode.REWRITE);
        knowledge.setQuizTemplates(List.of(originalQuiz));

        TopicEntity topic = new TopicEntity();
        topic.setId("topic-001");
        topic.setKind(NodeKind.TOPIC);
        topic.setLabel("Present Simple");
        topic.setKnowledges(List.of(knowledge));

        MilestoneEntity milestone = new MilestoneEntity();
        milestone.setId("milestone-001");
        milestone.setKind(NodeKind.MILESTONE);
        milestone.setLabel("A1");
        milestone.setTopics(List.of(topic));

        RootNodeEntity root = new RootNodeEntity();
        root.setId("root-001");
        root.setKind(NodeKind.ROOT);
        root.setMilestones(List.of(milestone));

        CourseEntity course = new CourseEntity();
        course.setId("course-001");
        course.setTitle("english-course");
        course.setRoot(root);

        // Quiz revisado: misma id, nuevo contenido (estructura preservada — F-SMODE-R006)
        QuizTemplateEntity revisedQuiz = new QuizTemplateEntity();
        revisedQuiz.setId("quiz-rewrite-001");
        revisedQuiz.setKnowledgeId("knowledge-rewrite-001");
        revisedQuiz.setTitle("Watch the film.");
        revisedQuiz.setSentences(List.of("Watch the film."));

        // elementAfter: snapshot del quiz revisado con el mismo nodeId
        CourseElementSnapshot elementAfter = new CourseElementSnapshot(
                AuditTarget.QUIZ, "quiz-rewrite-001", revisedQuiz);

        // Act — replace swaps the quiz inside the knowledge
        CourseElementLocator locator = new DefaultCourseElementLocator();
        CourseEntity result = locator.replace(course, elementAfter);

        // Assert — the knowledge in the returned course keeps its REWRITE sentenceMode (F-SMODE-R006)
        KnowledgeEntity resultKnowledge = result.getRoot()
                .getMilestones().get(0)
                .getTopics().get(0)
                .getKnowledges().get(0);

        assertEquals(SentenceMode.REWRITE, resultKnowledge.getSentenceMode(),
                "La revision que preserva la estructura debe conservar el sentenceMode del knowledge (F-SMODE-R006): " +
                "el knowledge resultante no debe tener sentenceMode null sino REWRITE");
    }
}
