package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.ProposalDecisionOutcome;
import com.learney.contentaudit.revisiondomain.ProposalDecisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultProposalDecisionServiceTest {

    @Mock private RevisionArtifactStore artifactStore;
    @Mock private CourseRepository courseRepository;
    @Mock private CourseElementLocator elementLocator;
    @Mock private RefinementPlanStore refinementPlanStore;

    private DefaultProposalDecisionService buildService() {
        return new DefaultProposalDecisionService(
                artifactStore,
                courseRepository,
                elementLocator,
                refinementPlanStore
        );
    }

    // ---------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------

    private RevisionProposal buildProposal(String proposalId, String taskId, String planId) {
        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        return new RevisionProposal(
                proposalId, taskId, planId, "audit-001",
                DiagnosisKind.SENTENCE_LENGTH, AuditTarget.QUIZ, "quiz-001",
                snapshot, snapshot, "bypass: identity revision", "bypass", Instant.now()
        );
    }

    private RevisionArtifact buildArtifact(String proposalId, String taskId, String planId,
                                           RevisionVerdict verdict) {
        RevisionProposal proposal = buildProposal(proposalId, taskId, planId);
        return new RevisionArtifact(proposal, verdict, null, null, null, null);
    }

    private RefinementPlan buildPlanWithTask(String planId, String taskId,
                                             RefinementTaskStatus status) {
        RefinementTask task = new RefinementTask(
                taskId, AuditTarget.QUIZ, "quiz-001", "Quiz about verbs",
                DiagnosisKind.SENTENCE_LENGTH, 1, status
        );
        return new RefinementPlan(planId, "audit-001", Instant.now(), List.of(task));
    }

    // ---------------------------------------------------------------------------
    // R011 — approve flow
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Given a PENDING_APPROVAL artifact, when approve is called, then the artifact is rewritten with verdict APPROVED and decidedAt set")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R011")
    public void givenAPENDINGAPPROVALArtifactWhenApproveIsCalledThenTheArtifactIsRewrittenWithVerdictAPPROVEDAndDecidedAtSet(
            ) {
        // Arrange
        String proposalId = "task-011a-100001";
        String taskId     = "task-011a";
        String planId     = "plan-011a";
        Path coursePath   = Path.of("./db/english-course");

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        CourseEntity course = mock(CourseEntity.class);
        CourseElementSnapshot snapshot = artifact.getProposal().getElementAfter();

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(courseRepository.load(coursePath)).thenReturn(course);
        when(elementLocator.replace(eq(course), eq(snapshot))).thenReturn(course);
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — artifact rewritten with APPROVED and decidedAt set
        ArgumentCaptor<RevisionArtifact> captor = ArgumentCaptor.forClass(RevisionArtifact.class);
        verify(artifactStore).save(captor.capture());
        RevisionArtifact saved = captor.getValue();
        assertEquals(RevisionVerdict.APPROVED, saved.getVerdict(),
                "Artifact must be rewritten with verdict APPROVED");
        assertNotNull(saved.getDecidedAt(),
                "Artifact must have decidedAt set after approve");
    }

    @Test
    @DisplayName("Given a PENDING_APPROVAL artifact, when approve is called, then the course is loaded and saved with elementAfter applied via CourseRepository")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R011")
    public void givenAPENDINGAPPROVALArtifactWhenApproveIsCalledThenTheCourseIsLoadedAndSavedWithElementAfterAppliedViaCourseRepository(
            ) {
        // Arrange
        String proposalId = "task-011b-100002";
        String taskId     = "task-011b";
        String planId     = "plan-011b";
        Path coursePath   = Path.of("./db/english-course");

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity updatedCourse = mock(CourseEntity.class);
        CourseElementSnapshot elementAfter = artifact.getProposal().getElementAfter();

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(courseRepository.load(coursePath)).thenReturn(course);
        when(elementLocator.replace(eq(course), eq(elementAfter))).thenReturn(updatedCourse);
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — R011: course loaded and saved with the updated course
        verify(courseRepository).load(coursePath);
        verify(courseRepository).save(eq(updatedCourse), eq(coursePath));
    }

    @Test
    @DisplayName("Given approve succeeds and the course is applied, then the associated RefinementTask transitions to DONE")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R014")
    public void givenApproveSucceedsAndTheCourseIsAppliedThenTheAssociatedRefinementTaskTransitionsToDONE(
            ) {
        // Arrange
        String proposalId = "task-014a-100003";
        String taskId     = "task-014a";
        String planId     = "plan-014a";
        Path coursePath   = Path.of("./db/english-course");

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        CourseEntity course = mock(CourseEntity.class);
        CourseElementSnapshot snapshot = artifact.getProposal().getElementAfter();

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(courseRepository.load(coursePath)).thenReturn(course);
        when(elementLocator.replace(eq(course), eq(snapshot))).thenReturn(course);
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — R014: refinementPlanStore.save called with task in COMPLETED (DONE) state
        ArgumentCaptor<RefinementPlan> planCaptor = ArgumentCaptor.forClass(RefinementPlan.class);
        verify(refinementPlanStore).save(planCaptor.capture());
        RefinementPlan savedPlan = planCaptor.getValue();
        RefinementTask savedTask = savedPlan.getTasks().stream()
                .filter(t -> taskId.equals(t.getId()))
                .findFirst()
                .orElseThrow(() -> new AssertionError("Task " + taskId + " not found in saved plan"));
        assertEquals(RefinementTaskStatus.COMPLETED, savedTask.getStatus(),
                "Task must be COMPLETED (DONE) after approve + course applied");
        assertEquals(ProposalDecisionOutcomeKind.APPROVED_APPLIED, outcome.getKind());
    }

    @Test
    @DisplayName("Given approve is called with a --note, then the persisted artifact's decisionNote carries that note")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R011")
    public void givenApproveIsCalledWithANoteThenThePersistedArtifactsDecisionNoteCarriesThatNote(
            ) {
        // Arrange
        String proposalId  = "task-011c-100004";
        String taskId      = "task-011c";
        String planId      = "plan-011c";
        Path coursePath    = Path.of("./db/english-course");
        String operatorNote = "Approved after manual review of quiz X";

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        CourseEntity course = mock(CourseEntity.class);
        CourseElementSnapshot snapshot = artifact.getProposal().getElementAfter();

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(courseRepository.load(coursePath)).thenReturn(course);
        when(elementLocator.replace(eq(course), eq(snapshot))).thenReturn(course);
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        service.approve(proposalId, Optional.of(planId), Optional.of(operatorNote), coursePath);

        // Assert — --note is stored in decisionNote on the persisted artifact
        ArgumentCaptor<RevisionArtifact> captor = ArgumentCaptor.forClass(RevisionArtifact.class);
        verify(artifactStore).save(captor.capture());
        assertEquals(operatorNote, captor.getValue().getDecisionNote(),
                "Persisted artifact's decisionNote must carry the --note text");
    }

    @Test
    @DisplayName("Given no proposal matches the supplied id, when approve is called, then the outcome is NOT_FOUND and no artifact or course is written")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R011")
    public void givenNoProposalMatchesTheSuppliedIdWhenApproveIsCalledThenTheOutcomeIsNOTFOUNDAndNoArtifactOrCourseIsWritten(
            ) {
        // Arrange
        String proposalId = "nonexistent-proposal-id";
        Path coursePath   = Path.of("./db/english-course");

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.empty());

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.empty(), Optional.empty(), coursePath);

        // Assert — outcome is NOT_FOUND, no artifact saved, no course written
        assertEquals(ProposalDecisionOutcomeKind.NOT_FOUND, outcome.getKind(),
                "Outcome must be NOT_FOUND when no proposal matches the id");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
    }

    // ---------------------------------------------------------------------------
    // R013 — already-decided: approve on already-decided proposal
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Given a proposal whose verdict is already APPROVED, when approve is called again, then the outcome is ALREADY_DECIDED and no side effects occur")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R013")
    public void givenAProposalWhoseVerdictIsAlreadyAPPROVEDWhenApproveIsCalledAgainThenTheOutcomeIsALREADYDECIDEDAndNoSideEffectsOccur(
            ) {
        // Arrange
        String proposalId = "task-013a-100006";
        String taskId     = "task-013a";
        String planId     = "plan-013a";
        Path coursePath   = Path.of("./db/english-course");

        // Already-decided artifact: verdict is APPROVED
        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.APPROVED);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — R013: outcome is ALREADY_DECIDED, no write side effects
        assertEquals(ProposalDecisionOutcomeKind.ALREADY_DECIDED, outcome.getKind(),
                "Approving an already-APPROVED proposal must return ALREADY_DECIDED");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
        verify(refinementPlanStore, never()).save(any(RefinementPlan.class));
    }

    @Test
    @DisplayName("Given a proposal whose verdict is already REJECTED, when approve is called, then the outcome is ALREADY_DECIDED and no side effects occur")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R013")
    public void givenAProposalWhoseVerdictIsAlreadyREJECTEDWhenApproveIsCalledThenTheOutcomeIsALREADYDECIDEDAndNoSideEffectsOccur(
            ) {
        // Arrange
        String proposalId = "task-013b-100007";
        String taskId     = "task-013b";
        String planId     = "plan-013b";
        Path coursePath   = Path.of("./db/english-course");

        // Already-decided artifact: verdict is REJECTED
        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.REJECTED);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — R013: outcome is ALREADY_DECIDED, no write side effects
        assertEquals(ProposalDecisionOutcomeKind.ALREADY_DECIDED, outcome.getKind(),
                "Approving an already-REJECTED proposal must return ALREADY_DECIDED");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
        verify(refinementPlanStore, never()).save(any(RefinementPlan.class));
    }

    // ---------------------------------------------------------------------------
    // R014 — course write failure after APPROVED decision
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Given approve rewrites the artifact to APPROVED but the course write fails, then the artifact keeps APPROVED with decidedAt and the task does not advance to DONE")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R014")
    public void givenApproveRewritesTheArtifactToAPPROVEDButTheCourseWriteFailsThenTheArtifactKeepsAPPROVEDWithDecidedAtAndTheTaskDoesNotAdvanceToDONE(
            ) {
        // Arrange
        String proposalId = "task-014b-100008";
        String taskId     = "task-014b";
        String planId     = "plan-014b";
        Path coursePath   = Path.of("./db/english-course");

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        CourseEntity course = mock(CourseEntity.class);
        CourseElementSnapshot snapshot = artifact.getProposal().getElementAfter();

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(courseRepository.load(coursePath)).thenReturn(course);
        when(elementLocator.replace(eq(course), eq(snapshot))).thenReturn(course);
        // Artifact is saved (APPROVED) but then course write throws
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);
        org.mockito.Mockito.doThrow(new RuntimeException("Disk full"))
                .when(courseRepository).save(any(CourseEntity.class), eq(coursePath));

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.approve(proposalId, Optional.of(planId), Optional.empty(), coursePath);

        // Assert — R014: outcome is APPROVED_APPLY_FAILED; artifact was saved as APPROVED; task NOT advanced to DONE
        assertEquals(ProposalDecisionOutcomeKind.APPROVED_APPLY_FAILED, outcome.getKind(),
                "When course write fails after APPROVED, outcome must be APPROVED_APPLY_FAILED");

        // Artifact was rewritten to APPROVED before the failure
        ArgumentCaptor<RevisionArtifact> artifactCaptor = ArgumentCaptor.forClass(RevisionArtifact.class);
        verify(artifactStore).save(artifactCaptor.capture());
        assertEquals(RevisionVerdict.APPROVED, artifactCaptor.getValue().getVerdict(),
                "Artifact must carry APPROVED verdict even when course write fails");
        assertNotNull(artifactCaptor.getValue().getDecidedAt(),
                "Artifact must have decidedAt set");

        // Task must NOT be advanced to DONE (refinementPlanStore.save not called with COMPLETED task)
        verify(refinementPlanStore, never()).save(any(RefinementPlan.class));
    }

    // ---------------------------------------------------------------------------
    // R012 — reject flow
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Given a PENDING_APPROVAL artifact, when reject is called, then the artifact is rewritten with verdict REJECTED and decisionNote carrying the --reason")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R012")
    public void givenAPENDINGAPPROVALArtifactWhenRejectIsCalledThenTheArtifactIsRewrittenWithVerdictREJECTEDAndDecisionNoteCarryingTheReason(
            ) {
        // Arrange
        String proposalId = "task-012a-100009";
        String taskId     = "task-012a";
        String planId     = "plan-012a";
        String reason     = "Content quality insufficient for this level";

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.reject(proposalId, Optional.of(planId), Optional.of(reason));

        // Assert — artifact rewritten with REJECTED and decisionNote carries the --reason
        ArgumentCaptor<RevisionArtifact> captor = ArgumentCaptor.forClass(RevisionArtifact.class);
        verify(artifactStore).save(captor.capture());
        RevisionArtifact saved = captor.getValue();
        assertEquals(RevisionVerdict.REJECTED, saved.getVerdict(),
                "Artifact must be rewritten with verdict REJECTED");
        assertEquals(reason, saved.getDecisionNote(),
                "Persisted artifact's decisionNote must carry the --reason text");
    }

    @Test
    @DisplayName("Given a PENDING_APPROVAL artifact, when reject is called, then CourseRepository is never asked to load or save the course")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R012")
    public void givenAPENDINGAPPROVALArtifactWhenRejectIsCalledThenCourseRepositoryIsNeverAskedToLoadOrSaveTheCourse(
            ) {
        // Arrange
        String proposalId = "task-012b-100010";
        String taskId     = "task-012b";
        String planId     = "plan-012b";

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        service.reject(proposalId, Optional.of(planId), Optional.empty());

        // Assert — R012: CourseRepository never loaded or saved
        verify(courseRepository, never()).load(any(Path.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
    }

    @Test
    @DisplayName("Given reject succeeds, then the associated RefinementTask returns to its previous state (typically PENDING)")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R014")
    public void givenRejectSucceedsThenTheAssociatedRefinementTaskReturnsToItsPreviousStateTypicallyPENDING(
            ) {
        // Arrange
        String proposalId = "task-014c-100011";
        String taskId     = "task-014c";
        String planId     = "plan-014c";

        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.PENDING_APPROVAL);
        // Task was PENDING before the proposal was emitted; state was preserved (DOUBT-AWAITING-STATE Option B)
        RefinementPlan plan = buildPlanWithTask(planId, taskId, RefinementTaskStatus.PENDING);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));
        when(refinementPlanStore.load(planId)).thenReturn(Optional.of(plan));
        when(artifactStore.save(any(RevisionArtifact.class))).thenReturn(
                ".content-audit/revisions/" + planId + "/" + proposalId);

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.reject(proposalId, Optional.of(planId), Optional.empty());

        // Assert — R014: task returns to PENDING; outcome is REJECTED
        assertEquals(ProposalDecisionOutcomeKind.REJECTED, outcome.getKind(),
                "Outcome must be REJECTED after a successful reject");
        // refinementPlanStore.save called with the task still in PENDING state
        ArgumentCaptor<RefinementPlan> planCaptor = ArgumentCaptor.forClass(RefinementPlan.class);
        verify(refinementPlanStore).save(planCaptor.capture());
        RefinementPlan savedPlan = planCaptor.getValue();
        RefinementTask savedTask = savedPlan.getTasks().stream()
                .filter(t -> taskId.equals(t.getId()))
                .findFirst()
                .orElseThrow(() -> new AssertionError("Task " + taskId + " not found in saved plan"));
        assertEquals(RefinementTaskStatus.PENDING, savedTask.getStatus(),
                "Task must remain PENDING after reject (returns to previous state)");
    }

    @Test
    @DisplayName("Given no proposal matches the supplied id, when reject is called, then the outcome is NOT_FOUND and no artifact or course is written")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R012")
    public void givenNoProposalMatchesTheSuppliedIdWhenRejectIsCalledThenTheOutcomeIsNOTFOUNDAndNoArtifactOrCourseIsWritten(
            ) {
        // Arrange
        String proposalId = "nonexistent-proposal-id-reject";

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.empty());

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.reject(proposalId, Optional.empty(), Optional.empty());

        // Assert — outcome is NOT_FOUND, no artifact saved, no course written
        assertEquals(ProposalDecisionOutcomeKind.NOT_FOUND, outcome.getKind(),
                "Outcome must be NOT_FOUND when no proposal matches the id");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
    }

    // ---------------------------------------------------------------------------
    // R013 — already-decided: reject on already-decided proposal
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Given a proposal whose verdict is already APPROVED, when reject is called, then the outcome is ALREADY_DECIDED and no side effects occur")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R013")
    public void givenAProposalWhoseVerdictIsAlreadyAPPROVEDWhenRejectIsCalledThenTheOutcomeIsALREADYDECIDEDAndNoSideEffectsOccur(
            ) {
        // Arrange
        String proposalId = "task-013c-100013";
        String taskId     = "task-013c";
        String planId     = "plan-013c";

        // Already-decided artifact: verdict is APPROVED
        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.APPROVED);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.reject(proposalId, Optional.of(planId), Optional.empty());

        // Assert — R013: outcome is ALREADY_DECIDED, no write side effects
        assertEquals(ProposalDecisionOutcomeKind.ALREADY_DECIDED, outcome.getKind(),
                "Rejecting an already-APPROVED proposal must return ALREADY_DECIDED");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
        verify(refinementPlanStore, never()).save(any(RefinementPlan.class));
    }

    @Test
    @DisplayName("Given a proposal whose verdict is already REJECTED, when reject is called, then the outcome is ALREADY_DECIDED and no side effects occur")
    @Tag("FEAT-REVAPR")
    @Tag("F-REVAPR-R013")
    public void givenAProposalWhoseVerdictIsAlreadyREJECTEDWhenRejectIsCalledThenTheOutcomeIsALREADYDECIDEDAndNoSideEffectsOccur(
            ) {
        // Arrange
        String proposalId = "task-013d-100014";
        String taskId     = "task-013d";
        String planId     = "plan-013d";

        // Already-decided artifact: verdict is REJECTED
        RevisionArtifact artifact = buildArtifact(proposalId, taskId, planId, RevisionVerdict.REJECTED);

        when(artifactStore.findByProposalId(eq(proposalId), any())).thenReturn(Optional.of(artifact));

        DefaultProposalDecisionService service = buildService();

        // Act
        ProposalDecisionOutcome outcome = service.reject(proposalId, Optional.of(planId), Optional.empty());

        // Assert — R013: outcome is ALREADY_DECIDED, no write side effects
        assertEquals(ProposalDecisionOutcomeKind.ALREADY_DECIDED, outcome.getKind(),
                "Rejecting an already-REJECTED proposal must return ALREADY_DECIDED");
        verify(artifactStore, never()).save(any(RevisionArtifact.class));
        verify(courseRepository, never()).save(any(CourseEntity.class), any(Path.class));
        verify(refinementPlanStore, never()).save(any(RefinementPlan.class));
    }
}
