package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.auditdomain.ActiveAnalysisSelection;
import com.learney.contentaudit.auditdomain.ActiveAnalysisSelectionStore;
import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableCourse;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.CourseMapper;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedView;
import com.learney.contentaudit.revisiondomain.consolidatedview.ConsolidatedViewAvailability;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@ExtendWith(MockitoExtension.class)
@Tag("F-CDIFF")
@Tag("F-CDIFF-J008")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FCdiffJ008JourneyTest {

    @Mock private RevisionArtifactStore revisionArtifactStore;
    @Mock private ActiveAnalysisSelectionStore activeAnalysisSelectionStore;
    @Mock private AuditReportStore auditReportStore;
    @Mock private RefinementPlanStore refinementPlanStore;
    @Mock private CourseRepository courseRepository;
    @Mock private CourseElementLocator courseElementLocator;
    @Mock private CourseMapper courseMapper;
    @Mock private AuditEngine auditEngine;

    private static final Path COURSE_PATH = Path.of("./db/english-course");

    private static class FakeEntity implements AuditableEntity {
        private final String id;
        FakeEntity(String id) { this.id = id; }
        @Override public String getId() { return id; }
        @Override public String getLabel() { return id; }
        @Override public String getCode() { return null; }
    }

    private DefaultConsolidatedViewBuilder builder() {
        return new DefaultConsolidatedViewBuilder(
                revisionArtifactStore, activeAnalysisSelectionStore, auditReportStore,
                refinementPlanStore, courseRepository, courseElementLocator, courseMapper, auditEngine);
    }

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: Existen varias propuestas (aceptadas ... → El consumidor que querria 'ver el imp... → El CLI emite una unica salida que com... → success")
    public void path1_success() {
        // situacion_inicial: varias propuestas (aceptadas + pendientes) en el plan activo.
        // Cada una tiene su preview eager por-propuesta de FEAT-PIPRE (no la tocamos aqui).
        // El consumidor quiere "ver el impacto combinado" -> pide el consolidado (no un preview combinado).
        String auditId = "audit-j008";
        String planId = "plan-j008";

        when(activeAnalysisSelectionStore.read())
                .thenReturn(Optional.of(new ActiveAnalysisSelection(auditId, planId)));
        when(refinementPlanStore.load(planId))
                .thenReturn(Optional.of(new RefinementPlan(planId, auditId,
                        Instant.parse("2026-01-01T00:00:00Z"), List.of())));

        // Dos aceptadas sobre nodos distintos
        CourseElementSnapshot snapQ1B = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapQ1A = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-001", null);
        CourseElementSnapshot snapQ2B = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-002", null);
        CourseElementSnapshot snapQ2A = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-002", null);
        // Una pendiente sobre un tercer nodo
        CourseElementSnapshot snapQ3B = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-003", null);
        CourseElementSnapshot snapQ3A = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-003", null);

        RevisionArtifact acc1 = new RevisionArtifact(
                new RevisionProposal("proposal-acc1", "task-001", planId, auditId,
                        DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, "quiz-001",
                        snapQ1B, snapQ1A, "acc1", "lemma-mvp",
                        Instant.parse("2026-01-01T00:00:00Z"), null),
                RevisionVerdict.APPROVED, null, null, null, null);
        RevisionArtifact acc2 = new RevisionArtifact(
                new RevisionProposal("proposal-acc2", "task-002", planId, auditId,
                        DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, "quiz-002",
                        snapQ2B, snapQ2A, "acc2", "lemma-mvp",
                        Instant.parse("2026-01-02T00:00:00Z"), null),
                RevisionVerdict.APPROVED, null, null, null, null);
        RevisionArtifact pend = new RevisionArtifact(
                new RevisionProposal("proposal-pend", "task-003", planId, auditId,
                        DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, "quiz-003",
                        snapQ3B, snapQ3A, "pend", "lemma-mvp",
                        Instant.parse("2026-01-03T00:00:00Z"), null),
                RevisionVerdict.PENDING_APPROVAL, null, null, null, null);

        FakeEntity q1Ent = new FakeEntity("quiz-001");
        FakeEntity q2Ent = new FakeEntity("quiz-002");
        FakeEntity q3Ent = new FakeEntity("quiz-003");

        AuditNode quiz1 = new AuditNode(); quiz1.setTarget(AuditTarget.QUIZ); quiz1.setEntity(q1Ent);
        quiz1.setScores(Map.of("lemma-absence", 0.50)); quiz1.setChildren(List.of());
        AuditNode quiz2 = new AuditNode(); quiz2.setTarget(AuditTarget.QUIZ); quiz2.setEntity(q2Ent);
        quiz2.setScores(Map.of("lemma-absence", 0.55)); quiz2.setChildren(List.of());
        AuditNode quiz3 = new AuditNode(); quiz3.setTarget(AuditTarget.QUIZ); quiz3.setEntity(q3Ent);
        quiz3.setScores(Map.of("lemma-absence", 0.60)); quiz3.setChildren(List.of());

        FakeEntity courseEnt = new FakeEntity("course-001");
        AuditNode root = new AuditNode(); root.setTarget(AuditTarget.COURSE); root.setEntity(courseEnt);
        root.setScores(Map.of("lemma-absence", 0.55)); root.setChildren(List.of(quiz1, quiz2, quiz3));

        when(auditReportStore.load(auditId)).thenReturn(Optional.of(new AuditReport(root)));
        when(revisionArtifactStore.listByPlan(planId)).thenReturn(List.of(acc1, acc2, pend));

        CourseEntity course = mock(CourseEntity.class);
        CourseEntity courseAcc1 = mock(CourseEntity.class);
        CourseEntity courseAcc2 = mock(CourseEntity.class);
        CourseEntity coursePend = mock(CourseEntity.class);
        when(courseRepository.load(COURSE_PATH)).thenReturn(course);
        when(courseElementLocator.replace(eq(course), eq(snapQ1A))).thenReturn(courseAcc1);
        when(courseElementLocator.replace(eq(courseAcc1), eq(snapQ2A))).thenReturn(courseAcc2);
        when(courseElementLocator.snapshot(eq(courseAcc2), eq(AuditTarget.QUIZ), eq("quiz-003")))
                .thenReturn(Optional.of(snapQ3B));
        when(courseElementLocator.replace(eq(courseAcc2), eq(snapQ3A))).thenReturn(coursePend);

        AuditableCourse audAcc2 = mock(AuditableCourse.class);
        AuditableCourse audPend = mock(AuditableCourse.class);
        when(courseMapper.map(courseAcc2)).thenReturn(audAcc2);
        when(courseMapper.map(coursePend)).thenReturn(audPend);

        // consolidated: baseline + ambas aceptadas aplicadas
        AuditNode rootAfterAcc = new AuditNode(); rootAfterAcc.setTarget(AuditTarget.COURSE);
        rootAfterAcc.setEntity(courseEnt); rootAfterAcc.setScores(Map.of("lemma-absence", 0.72));
        rootAfterAcc.setChildren(List.of(
                mkQuiz(q1Ent, 0.80), mkQuiz(q2Ent, 0.78), mkQuiz(q3Ent, 0.60)));
        when(auditEngine.runAudit(eq(audAcc2))).thenReturn(new AuditReport(rootAfterAcc));

        // pendingProjection: consolidated + pendiente
        AuditNode rootAfterPend = new AuditNode(); rootAfterPend.setTarget(AuditTarget.COURSE);
        rootAfterPend.setEntity(courseEnt); rootAfterPend.setScores(Map.of("lemma-absence", 0.79));
        rootAfterPend.setChildren(List.of(
                mkQuiz(q1Ent, 0.80), mkQuiz(q2Ent, 0.78), mkQuiz(q3Ent, 0.80)));
        when(auditEngine.runAudit(eq(audPend))).thenReturn(new AuditReport(rootAfterPend));

        // pedir_salida_consolidada → emitir_combinacion: Gate R015, R016
        ConsolidatedView view = builder().build(COURSE_PATH);

        assertEquals(ConsolidatedViewAvailability.AVAILABLE, view.getAvailability());
        assertFalse(view.getNodeImpacts().isEmpty(),
                "El consolidado debe combinar baseline + aceptadas + pendientes en nodeImpacts (Gate R016)");
        assertFalse(view.getStatisticImpacts().isEmpty(),
                "El consolidado debe combinar baseline + aceptadas + pendientes en statisticImpacts (Gate R016)");

        // Los previews por-propuesta de FEAT-PIPRE siguen disponibles e intactos (R015, R016)
        // (no los tocamos — estan en ImpactPreviewStore que no es responsabilidad de este builder)
        assertTrue(view.getNonApplicablePendings().isEmpty(),
                "No debe haber pendientes no aplicables en este scenario");

        // quiz-001 y quiz-002 afectados por aceptadas
        assertTrue(view.getNodeImpacts().stream().anyMatch(n -> "quiz-001".equals(n.getNodeId())),
                "quiz-001 afectado por aceptada debe aparecer en nodeImpacts");
        assertTrue(view.getNodeImpacts().stream().anyMatch(n -> "quiz-002".equals(n.getNodeId())),
                "quiz-002 afectado por aceptada debe aparecer en nodeImpacts");
        // quiz-003 afectado por pendiente
        assertTrue(view.getNodeImpacts().stream().anyMatch(n -> "quiz-003".equals(n.getNodeId())),
                "quiz-003 afectado por pendiente debe aparecer en nodeImpacts");
    }

    private AuditNode mkQuiz(AuditableEntity ent, double score) {
        AuditNode n = new AuditNode(); n.setTarget(AuditTarget.QUIZ); n.setEntity(ent);
        n.setScores(Map.of("lemma-absence", score)); n.setChildren(List.of());
        return n;
    }
}
