package com.learney.contentaudit.auditdomain;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface ContentWordFilter {
    boolean isContentWord(NlpToken token);
}
