package com.learney.contentaudit.auditdomain;

import java.util.Objects;
import java.util.Set;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class EvaluationRunPolicy {
    private int maxNewEvaluations;

    private boolean reevaluate;

    private String reevaluationScope;

    private Set<String> reevaluationSubjectIds;

    public EvaluationRunPolicy() {
    }

    public EvaluationRunPolicy(int maxNewEvaluations, boolean reevaluate, String reevaluationScope,
            Set<String> reevaluationSubjectIds) {
        this.maxNewEvaluations = maxNewEvaluations;
        this.reevaluate = reevaluate;
        this.reevaluationScope = reevaluationScope;
        this.reevaluationSubjectIds = reevaluationSubjectIds;
    }

    public int getMaxNewEvaluations() {
        return this.maxNewEvaluations;
    }

    public void setMaxNewEvaluations(int maxNewEvaluations) {
        this.maxNewEvaluations = maxNewEvaluations;
    }

    public boolean isReevaluate() {
        return this.reevaluate;
    }

    public void setReevaluate(boolean reevaluate) {
        this.reevaluate = reevaluate;
    }

    public String getReevaluationScope() {
        return this.reevaluationScope;
    }

    public void setReevaluationScope(String reevaluationScope) {
        this.reevaluationScope = reevaluationScope;
    }

    public Set<String> getReevaluationSubjectIds() {
        return this.reevaluationSubjectIds;
    }

    public void setReevaluationSubjectIds(Set<String> reevaluationSubjectIds) {
        this.reevaluationSubjectIds = reevaluationSubjectIds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EvaluationRunPolicy that = (EvaluationRunPolicy) o;
        return Objects.equals(this.maxNewEvaluations, that.maxNewEvaluations)
                    && Objects.equals(this.reevaluate, that.reevaluate)
                    && Objects.equals(this.reevaluationScope, that.reevaluationScope)
                    && Objects.equals(this.reevaluationSubjectIds, that.reevaluationSubjectIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(maxNewEvaluations, reevaluate, reevaluationScope, reevaluationSubjectIds);
    }
}
