package com.learney.contentaudit.auditdomain;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class IContentAudit implements ContentAudit {
    private final AuditEngine auditEngine;

    public IContentAudit(AuditEngine auditEngine) {
        this.auditEngine = auditEngine;
    }

    @Override
    public AuditReport audit(AuditableCourse auditableCourse) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
