package com.learney.contentaudit.revisiondomain.fielddiff;

import com.learney.contentaudit.revisiondomain.consolidatedview.FieldExclusionRole;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultFieldExclusionRegistry implements FieldExclusionRegistry {

    // Key: "declaringTypeName::fieldName" → role
    private final Map<String, FieldExclusionRole> rules = new HashMap<>();

    DefaultFieldExclusionRegistry() {
        seedRules();
    }

    @Override
    public boolean isExcluded(String declaringTypeName, String fieldName) {
        return rules.containsKey(key(declaringTypeName, fieldName))
                || rules.containsKey(key("*", fieldName));
    }

    @Override
    public Optional<FieldExclusionRole> getRole(String declaringTypeName, String fieldName) {
        FieldExclusionRole role = rules.get(key(declaringTypeName, fieldName));
        if (role == null) {
            role = rules.get(key("*", fieldName));
        }
        return Optional.ofNullable(role);
    }

    private static String key(String typeName, String fieldName) {
        return typeName + "::" + fieldName;
    }

    private void exclude(String typeName, String fieldName, FieldExclusionRole role) {
        rules.put(key(typeName, fieldName), role);
    }

    // Wildcard exclusion — applies regardless of declaring type
    private void excludeGlobal(String fieldName, FieldExclusionRole role) {
        rules.put(key("*", fieldName), role);
    }

    private void seedRules() {
        // ── OPAQUE_PERSISTENCE_ID ──────────────────────────────────────────
        // MongoDB/Jackson persistence identifiers that are implementation details,
        // not semantic content.
        excludeGlobal("_id",  FieldExclusionRole.OPAQUE_PERSISTENCE_ID);
        excludeGlobal("oid",  FieldExclusionRole.OPAQUE_PERSISTENCE_ID);
        excludeGlobal("$oid", FieldExclusionRole.OPAQUE_PERSISTENCE_ID);

        // ── STRUCTURAL_REFERENCE ───────────────────────────────────────────
        // Foreign-key references that encode course tree topology, not content.
        // These are references *inside* a node pointing to its context; they
        // are not the node's own identity (which is `id` / `getId()`).
        excludeGlobal("parentId",    FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("childId",     FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("courseId",    FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("milestoneId", FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("topicId",     FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("knowledgeId", FieldExclusionRole.STRUCTURAL_REFERENCE);
        excludeGlobal("quizId",      FieldExclusionRole.STRUCTURAL_REFERENCE);

        // ── TIMESTAMP ─────────────────────────────────────────────────────
        // Wall-clock fields that change with every write, not with semantic edits.
        excludeGlobal("createdAt",      FieldExclusionRole.TIMESTAMP);
        excludeGlobal("updatedAt",      FieldExclusionRole.TIMESTAMP);
        excludeGlobal("lastModifiedAt", FieldExclusionRole.TIMESTAMP);
        excludeGlobal("timestamp",      FieldExclusionRole.TIMESTAMP);

        // ── INTERNAL_ORDER ────────────────────────────────────────────────
        // Ordering counters / positional indices that encode list layout,
        // not semantic meaning.  Array indices are handled by the walker itself.
        excludeGlobal("index",    FieldExclusionRole.INTERNAL_ORDER);
        excludeGlobal("position", FieldExclusionRole.INTERNAL_ORDER);

        // ── NON_SEMANTIC ──────────────────────────────────────────────────
        // Escape hatch for per-node quirks discovered later.
        // (currently empty — populated on demand by future patches)
    }
}
