package com.learney.contentaudit.revisiondomain.fielddiff;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.revisiondomain.consolidatedview.FieldChange;
import com.learney.contentaudit.revisiondomain.consolidatedview.NodeFieldDiffer;
import java.util.Map;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class RecursiveNodeFieldDiffer implements NodeFieldDiffer {
    private final FieldExclusionRegistry exclusionRegistry;

    private final ListIdentityRegistry identityRegistry;

    public RecursiveNodeFieldDiffer(FieldExclusionRegistry exclusionRegistry,
            ListIdentityRegistry identityRegistry) {
        this.exclusionRegistry = exclusionRegistry;
        this.identityRegistry = identityRegistry;
    }

    @Override
    public Map<String, FieldChange> diff(AuditNode original, AuditNode consolidated,
            AuditNode pendingProjection) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
