# Complete configuration for MongoManager
mongo.container.name=pipeline-container
mongo.image.name=mongo:7.0
mongo.port=27017
mongo.db.name=learney
mongo.restore.path=/Users/josecullen/projects/learney/pipeline/02-no-sentence-marker
mongo.force.restart=true
mongo.timeout.seconds=20

# Strategy levels or quarters.
# Levels means A1, A2, B1, B2
# Quarters subdivides the levels into quarters (e.g., A1.1, A1.2, etc.)
analyzer.frequency.bands.strategy=quarters
analyzer.frequency.bands.bands=1000,2000,3000,4000