package com.learney.contentaudit.auditapplication;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AmbiguousReevaluationScopeException;
import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableCourse;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.CourseDiagnoses;
import com.learney.contentaudit.auditdomain.EmptyReevaluationSetException;
import com.learney.contentaudit.auditdomain.EvaluationAnalyzerFactory;
import com.learney.contentaudit.auditdomain.EvaluationRunPolicy;
import com.learney.contentaudit.auditdomain.NlpToken;
import com.learney.contentaudit.auditdomain.QuizInstructionVerdictReader;
import com.learney.contentaudit.auditdomain.ScoreAggregator;
import com.learney.contentaudit.auditdomain.quizinstruction.InstructionSeverity;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionCoverageDiagnosis;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionVerdict;
import com.learney.contentaudit.auditdomain.quizinstructionengine.DefaultQuizInstructionAnalyzerFactory;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseRepository;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.evaluationledgerdomain.ContentFingerprinter;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationEmitted;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationKey;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationLedger;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationOutcome;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationRecord;
import com.learney.contentaudit.evaluationledgerdomain.EvaluationSubject;
import com.learney.contentaudit.evaluationledgerdomain.Evaluator;
import com.learney.contentaudit.evaluationledgerdomain.evaluationsession.DefaultEvaluationSessionFactory;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-QINST")
@Tag("F-QINST-J004")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FQinstJ004JourneyTest {

    // R018 lives on EvaluationRunPolicy.reevaluationSubjectIds: a declared set of quiz ids the
    // run must re-judge, mutually exclusive with reevaluate/reevaluationScope (F-QINST-R012).
    // Its rejection (empty set / set + area at once) is raised by
    // DefaultQuizInstructionAnalyzerFactory.create(policy) -- the only call of the whole audit
    // that DefaultAuditRunner does NOT wrap in catch(RuntimeException) (F-QINST-R007 wraps every
    // per-node analyzer call). A rejection raised anywhere else would be swallowed silently
    // instead of surfacing as a failed run -- exactly the bug this journey exists to keep out.
    // That is why every path below builds the REAL DefaultQuizInstructionAnalyzerFactory and
    // drives it through the REAL DefaultAuditRunner: faking the factory the way
    // FQinstJ003JourneyTest does for R001/R011/R012 would still pass even if the rejection lived
    // in the wrong place (e.g. inside onQuiz).
    //
    // Only the two true external boundaries are faked: the judge (Evaluator) and the ledger
    // (EvaluationLedger). The verdict reader is also faked, but for a different reason: its only
    // real implementation (JacksonQuizInstructionVerdictReader) lives in
    // quiz-instruction-infrastructure, a module audit-application does not depend on -- and
    // verdict parsing is not what R018 constrains (that is QuizInstructionAnalyzerTest's job).

    private static final String EVALUATOR_ID = "quiz-instruction-validator";
    private static final String JUDGE_VERSION = "v1";

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El usuario pide la auditoria de un cu... → El juez vuelve a juzgar exactamente l... [El conjunto declara ejercicios del curso y el tope de consultas de la corrida alcanza para todos] → success")
    public void path1_elConjuntoDeclaraEjerciciosDelCursoYElTopeDeConsultasDeLaCorridaAlcanzaParaTodos_success(
            ) {
        // R018 inv.1 + R008: with a set declared and budget enough for all of it, the judge must
        // re-judge exactly the quizzes of the set -- a quiz with a current verdict outside the
        // set is reused without a query, and its previous verdict stays untouched in the ledger.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path1.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        AuditReport primingReport = freshReportFor("quiz-in-set", "quiz-outside-set");
        AuditReport report = freshReportFor("quiz-in-set", "quiz-outside-set");

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(primingReport, report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();

        // Prime the course: an ordinary run gives every quiz a current verdict.
        DefaultAuditRunner primingRunner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper,
                auditEngine, List.of(), scoreAggregator, List.of(realQuizInstructionFactory(ledger, fingerprinter,
                        new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION))));
        primingRunner.runAudit(coursePath, new AuditRunRequest(null, null, null));
        assertEquals(1, ledger.historyBySubjectRef("quiz-in-set").size(),
                "setup: quiz-in-set must start with a current verdict");
        assertEquals(1, ledger.historyBySubjectRef("quiz-outside-set").size(),
                "setup: quiz-outside-set must start with a current verdict");

        // The tested run: declare a set with only "quiz-in-set", budget enough for it.
        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        EvaluationRunPolicy setPolicy = new EvaluationRunPolicy(10, false, null, Set.of("quiz-in-set"));
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), setPolicy));
        runner.runAudit(coursePath, request);

        // R018 inv.1: exactly the declared set was consulted, nothing else.
        assertEquals(Set.of("quiz-in-set"), new HashSet<>(evaluator.getEvaluatedSubjectRefs()),
                "R018: the judge must be consulted for every quiz of the declared set and for no quiz outside it");
        // R018 inv.1: the previous verdict coexists with the new one -- nothing was destroyed.
        assertEquals(2, ledger.historyBySubjectRef("quiz-in-set").size(),
                "R018: the previous verdict of a re-judged quiz must stay consultable alongside the new one");
        // R008: the quiz outside the set is reused without a query -- its ledger history is untouched.
        assertEquals(1, ledger.historyBySubjectRef("quiz-outside-set").size(),
                "R008: a quiz outside the declared set must be reused without any new query");
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El usuario pide la auditoria de un cu... → La corrida gasta el tope de consultas... [El conjunto declara mas ejercicios que el tope de consultas de la corrida] → success")
    public void path2_elConjuntoDeclaraMasEjerciciosQueElTopeDeConsultasDeLaCorrida_success() {
        // R018 inv.2 + R006: when the declared set is bigger than the run's budget, the run
        // spends the budget on the set and finishes without error; the set members the budget
        // did not reach keep their previous verdict, keep scoring, and do not end up pending.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path2.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        Set<String> declaredSet = Set.of("quiz-a", "quiz-b", "quiz-c");
        AuditReport primingReport = freshReportFor("quiz-a", "quiz-b", "quiz-c");
        AuditReport report = freshReportFor("quiz-a", "quiz-b", "quiz-c");
        AuditNode rootNode = report.getRoot();

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(primingReport, report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();

        DefaultAuditRunner primingRunner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper,
                auditEngine, List.of(), scoreAggregator, List.of(realQuizInstructionFactory(ledger, fingerprinter,
                        new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION))));
        primingRunner.runAudit(coursePath, new AuditRunRequest(null, null, null));

        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        // Budget of 2, smaller than the declared set of 3.
        EvaluationRunPolicy setPolicy = new EvaluationRunPolicy(2, false, null, declaredSet);
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), setPolicy));
        runner.runAudit(coursePath, request);

        List<String> consulted = evaluator.getEvaluatedSubjectRefs();
        // R006: the run must not exceed its budget of new queries...
        assertEquals(2, consulted.size(), "R006: the run must not exceed its budget of new queries");
        // R018 inv.1: ...and every one of them must be for a quiz that belongs to the declared set.
        assertTrue(declaredSet.containsAll(consulted),
                "R018: every query spent on the set must be for a quiz that belongs to it");

        String analyzerName = quizInstructionFactory.analyzerName();
        for (String quizId : declaredSet) {
            boolean reachedByBudget = consulted.contains(quizId);
            assertEquals(reachedByBudget ? 2 : 1, ledger.historyBySubjectRef(quizId).size(),
                    reachedByBudget
                            ? "R018: a quiz the budget reached must have a new verdict alongside the previous one"
                            : "R018 inv.2: a quiz the budget did not reach must keep its previous verdict untouched");
            // R018 inv.2: whether reached or not, no declared-set quiz is left without a score.
            assertNotNull(findChild(rootNode, quizId).getScores().get(analyzerName),
                    "R018 inv.2: a quiz the budget did not reach must keep scoring instead of turning pending");
        }
    }

    @Test
    @Order(3)
    @Tag("path-3")
    @DisplayName("path-3: El usuario pide la auditoria de un cu... → La corrida vuelve a juzgar los ejerci... [Parte de los identificadores declarados no corresponde a ningun ejercicio del curso] → success")
    public void path3_parteDeLosIdentificadoresDeclaradosNoCorrespondeANingunEjercicioDelCurso_success(
            ) {
        // R018 inv.3 (first half) + R005: identifiers that match no quiz of the course must not
        // invalidate the request -- the rest of the declared set is judged normally, the run
        // finishes without error, informs those identifiers, and no coverage count includes them.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path3.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        AuditReport primingReport = freshReportFor("quiz-1");
        AuditReport report = freshReportFor("quiz-1");
        AuditNode rootNode = report.getRoot();

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(primingReport, report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();

        DefaultAuditRunner primingRunner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper,
                auditEngine, List.of(), scoreAggregator, List.of(realQuizInstructionFactory(ledger, fingerprinter,
                        new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION))));
        primingRunner.runAudit(coursePath, new AuditRunRequest(null, null, null));

        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        Set<String> declaredSet = Set.of("quiz-1", "quiz-ghost-1", "quiz-ghost-2");
        EvaluationRunPolicy setPolicy = new EvaluationRunPolicy(10, false, null, declaredSet);
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), setPolicy));
        runner.runAudit(coursePath, request);

        // R018: only the identifier that corresponds to a real quiz reaches the judge; the run
        // finishes without error.
        assertEquals(Set.of("quiz-1"), new HashSet<>(evaluator.getEvaluatedSubjectRefs()),
                "R018: an identifier with no matching quiz must never reach the judge");

        assertTrue(rootNode.getDiagnoses() instanceof CourseDiagnoses,
                "the root node's diagnoses must be the course-level container the analyzer declares its coverage on");
        CourseDiagnoses courseDiagnoses = (CourseDiagnoses) rootNode.getDiagnoses();
        QuizInstructionCoverageDiagnosis coverageDiagnosis = courseDiagnoses.getQuizInstructionCoverage()
                .orElseThrow(() -> new AssertionError("R005: the report must declare the quiz-instruction coverage"));

        // R018: the identifiers that matched no quiz are informed explicitly, and only those.
        assertEquals(Set.of("quiz-ghost-1", "quiz-ghost-2"),
                new HashSet<>(coverageDiagnosis.getUnmatchedReevaluationIds()),
                "R018: every identifier of the declared set with no matching quiz must be reported, and only those");
        // R018 + R005: unmatched identifiers never enter any coverage count -- reached still
        // counts only the real quiz the course has.
        assertEquals(1, coverageDiagnosis.getCoverage().getReached(),
                "R018: identifiers with no matching quiz are not quizzes of the course and cannot inflate reached");
    }

    @Test
    @Order(4)
    @Tag("path-4")
    @DisplayName("path-4: El usuario pide la auditoria de un cu... → El ejercicio se consulta al juez y re... [El conjunto declara un ejercicio que existe y nunca fue juzgado] → success")
    public void path4_elConjuntoDeclaraUnEjercicioQueExisteYNuncaFueJuzgado_success() {
        // R018: a quiz of the declared set that exists but was never judged before is simply
        // consulted and scored like any evaluated quiz -- no error, no special treatment.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path4.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        AuditReport report = freshReportFor("quiz-never-judged");
        AuditNode rootNode = report.getRoot();

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();
        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        EvaluationRunPolicy setPolicy = new EvaluationRunPolicy(10, false, null, Set.of("quiz-never-judged"));
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), setPolicy));
        runner.runAudit(coursePath, request);

        // R018: the never-judged quiz of the set is consulted just like any other member of it.
        assertEquals(Set.of("quiz-never-judged"), new HashSet<>(evaluator.getEvaluatedSubjectRefs()),
                "R018: a declared-set quiz without a previous verdict must still be consulted");
        // No special treatment: a single, brand-new record...
        assertEquals(1, ledger.historyBySubjectRef("quiz-never-judged").size(),
                "R018: a never-judged quiz gets an ordinary first verdict, nothing special");
        // ...and a score, exactly like any evaluated quiz.
        assertNotNull(
                findChild(rootNode, "quiz-never-judged").getScores().get(quizInstructionFactory.analyzerName()),
                "R018: the never-judged quiz must receive a score like any evaluated quiz");
    }

    @Test
    @Order(5)
    @Tag("path-5")
    @DisplayName("path-5: El usuario pide la auditoria de un cu... → El pedido se rechaza de forma visible... [El conjunto declarado esta vacio] → failure")
    public void path5_elConjuntoDeclaradoEstaVacio_failure() {
        // R018 inv.3: an empty declared set is rejected visibly, before a single query, and
        // without redoing any recorded verdict. See the class comment for why this must be
        // observed through the real DefaultAuditRunner + the real factory.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path5.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        AuditReport primingReport = freshReportFor("quiz-1");
        AuditReport report = freshReportFor("quiz-1");

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(primingReport, report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();

        DefaultAuditRunner primingRunner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper,
                auditEngine, List.of(), scoreAggregator, List.of(realQuizInstructionFactory(ledger, fingerprinter,
                        new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION))));
        primingRunner.runAudit(coursePath, new AuditRunRequest(null, null, null));
        assertEquals(1, ledger.historyBySubjectRef("quiz-1").size(),
                "setup: quiz-1 must start with a current verdict");

        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        // An explicitly empty set -- declared, and empty, which R018 never reads as "the whole course".
        EvaluationRunPolicy emptySetPolicy = new EvaluationRunPolicy(10, false, null, Set.of());
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), emptySetPolicy));

        assertThrows(EmptyReevaluationSetException.class, () -> runner.runAudit(coursePath, request),
                "R018 inv.3: an empty declared set must reject the request visibly instead of running an ordinary audit");

        // R018 inv.3: rejected before emitting a single query, and no recorded verdict was redone.
        assertTrue(evaluator.getEvaluatedSubjectRefs().isEmpty(),
                "R018: a rejected request must not let the judge be consulted at all");
        assertEquals(1, ledger.historyBySubjectRef("quiz-1").size(),
                "R018: a rejected request must not redo any recorded verdict");
    }

    @Test
    @Order(6)
    @Tag("path-6")
    @DisplayName("path-6: El usuario pide la auditoria de un cu... → El pedido se rechaza de forma visible... [El pedido declara a la vez un conjunto de ejercicios y un area del curso] → failure")
    public void path6_elPedidoDeclaraALaVezUnConjuntoDeEjerciciosYUnAreaDelCurso_failure() {
        // R018 inv.3: declaring a set of quizzes together with a course area at the same time is
        // unreadable -- rejected visibly, before a single query, with no recorded verdict redone.
        // Same reason as path-5 for going through the real runner + the real factory.
        CourseRepository courseRepository = mock(CourseRepository.class);
        CourseToAuditableMapper courseToAuditableMapper = mock(CourseToAuditableMapper.class);
        AuditEngine auditEngine = mock(AuditEngine.class);
        ScoreAggregator scoreAggregator = mock(ScoreAggregator.class);

        Path coursePath = Path.of("/test/course-j004-path6.json");
        CourseEntity courseEntity = new CourseEntity();
        AuditableCourse auditableCourse = new AuditableCourse(List.of());

        AuditReport primingReport = freshReportFor("quiz-1");
        AuditReport report = freshReportFor("quiz-1");

        when(courseRepository.load(coursePath)).thenReturn(courseEntity);
        when(courseToAuditableMapper.map(courseEntity)).thenReturn(auditableCourse);
        when(auditEngine.runAudit(auditableCourse)).thenReturn(primingReport, report);

        FakeEvaluationLedger ledger = new FakeEvaluationLedger();
        FakeContentFingerprinter fingerprinter = new FakeContentFingerprinter();

        DefaultAuditRunner primingRunner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper,
                auditEngine, List.of(), scoreAggregator, List.of(realQuizInstructionFactory(ledger, fingerprinter,
                        new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION))));
        primingRunner.runAudit(coursePath, new AuditRunRequest(null, null, null));
        assertEquals(1, ledger.historyBySubjectRef("quiz-1").size(),
                "setup: quiz-1 must start with a current verdict");

        FakeEvaluator evaluator = new FakeEvaluator(EVALUATOR_ID, JUDGE_VERSION);
        EvaluationAnalyzerFactory quizInstructionFactory = realQuizInstructionFactory(ledger, fingerprinter,
                evaluator);
        DefaultAuditRunner runner = new DefaultAuditRunner(courseRepository, courseToAuditableMapper, auditEngine,
                List.of(), scoreAggregator, List.of(quizInstructionFactory));

        // A declared set of quizzes AND a course area (reevaluationScope) at the same time.
        EvaluationRunPolicy ambiguousPolicy = new EvaluationRunPolicy(10, true, "knowledge-99", Set.of("quiz-1"));
        AuditRunRequest request = new AuditRunRequest(null, null,
                Map.of(quizInstructionFactory.analyzerName(), ambiguousPolicy));

        assertThrows(AmbiguousReevaluationScopeException.class, () -> runner.runAudit(coursePath, request),
                "R018 inv.3: declaring a set of quizzes together with a course area must reject the request visibly");

        assertTrue(evaluator.getEvaluatedSubjectRefs().isEmpty(),
                "R018: a rejected request must not let the judge be consulted at all");
        assertEquals(1, ledger.historyBySubjectRef("quiz-1").size(),
                "R018: a rejected request must not redo any recorded verdict");
    }

    // -----------------------------------------------------------------------
    // Fixtures shared across paths
    // -----------------------------------------------------------------------

    /**
     * F-QINST-R009 keeps the quiz id itself out of the judged content on purpose -- identity is
     * content, not element -- so two quizzes built with the same literal content collapse onto a
     * single ledger entry (F-EVCOST-R001 intentionally reuses across different course elements
     * when their content is identical). Empirically (verified by printing the resolved
     * EvaluationKey.contentFingerprint), the real QuizInstructionSubjectBuilder keys its content
     * map on {@code quiz, instructions, title, topic, cefrLevel}, where {@code quiz} is built from
     * sentenceParts -- NOT from AuditableQuiz's flat label/code/translation/sentences/quizSentence
     * fields, which never showed up in the fingerprint at all. A fixture that leaves
     * sentenceParts empty for every quiz -- as this one used to -- makes every quiz resolve to the
     * SAME {@code quiz=} (empty) entry, so several distinct quiz ids in the same tree collapse
     * onto one fingerprint, silently merging their ledger history and hiding exactly the per-quiz
     * selection this journey exists to verify. Giving each quiz its own sentencePart is therefore
     * the field that actually has to vary; the other AuditableQuiz fields are still populated
     * (non-null, non-empty) so the fixture stays realistic, but they are not what disambiguates.
     */
    private static AuditNode quizNode(String quizId) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        List<NlpToken> tokens = List.of(new NlpToken(quizId, quizId, "NOUN", null, false, false));
        List<SentencePartEntity> sentenceParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "Text unique to " + quizId, null));
        node.setEntity(new AuditableQuiz(tokens, quizId, "Label " + quizId, "code-" + quizId,
                "Translation for " + quizId, List.of("Sentence unique to " + quizId + "."),
                "Quiz sentence for " + quizId, "Instructions unique to " + quizId, sentenceParts));
        return node;
    }

    private static AuditNode rootWithChildren(AuditNode... children) {
        AuditNode root = new AuditNode();
        root.setTarget(AuditTarget.COURSE);
        List<AuditNode> childList = new ArrayList<>(List.of(children));
        root.setChildren(childList);
        root.setScores(new LinkedHashMap<>());
        root.setMetadata(new LinkedHashMap<>());
        for (AuditNode child : children) {
            child.setParent(root);
        }
        return root;
    }

    /**
     * Builds a fresh AuditReport over brand-new quiz nodes (same ids, new objects) so a report
     * used for the tested run never carries over scores/diagnoses mutated by an earlier priming
     * run on the same quiz -- a stale leftover score would otherwise hide a run that incorrectly
     * leaves a declared-set quiz pending instead of falling back to its reused verdict.
     */
    private static AuditReport freshReportFor(String... quizIds) {
        AuditNode[] children = new AuditNode[quizIds.length];
        for (int i = 0; i < quizIds.length; i++) {
            children[i] = quizNode(quizIds[i]);
        }
        return new AuditReport(rootWithChildren(children));
    }

    private static AuditNode findChild(AuditNode root, String quizId) {
        return root.getChildren().stream()
                .filter(child -> quizId.equals(child.getEntity().getId()))
                .findFirst()
                .orElseThrow(() -> new AssertionError("fixture error: no quiz node with id " + quizId));
    }

    /**
     * Builds the REAL DefaultQuizInstructionAnalyzerFactory (audit-domain.quizinstructionengine,
     * public in a public package) wired to a real DefaultEvaluationSessionFactory and the real
     * DefaultQuizInstructionConfig -- see the class comment for why R018's rejection must be
     * exercised through the real factory instead of a mock.
     */
    private static EvaluationAnalyzerFactory realQuizInstructionFactory(EvaluationLedger ledger,
            ContentFingerprinter fingerprinter, Evaluator evaluator) {
        return new DefaultQuizInstructionAnalyzerFactory(
                new DefaultEvaluationSessionFactory(ledger, fingerprinter), evaluator,
                new FakeQuizInstructionVerdictReader(), new DefaultQuizInstructionConfig());
    }

    /** Deterministic fake fingerprinter: same content map always yields the same fingerprint. */
    private static final class FakeContentFingerprinter implements ContentFingerprinter {
        @Override
        public String fingerprint(Map<String, String> content) {
            return new TreeMap<>(content).toString();
        }
    }

    /**
     * In-memory fake ledger -- the real FileSystemEvaluationLedger lives in a module this one
     * does not depend on, and a journey test must not touch disk anyway. historyBySubjectRef is a
     * test-only lookup: without it, observing a quiz's verdict history would require reproducing
     * the real subject builder's content map (and therefore its fingerprint) by hand.
     */
    private static final class FakeEvaluationLedger implements EvaluationLedger {
        private final List<EvaluationRecord> records = new ArrayList<>();

        @Override
        public Optional<EvaluationRecord> findLatest(EvaluationKey key) {
            return records.stream().filter(r -> r.getKey().equals(key)).reduce((first, second) -> second);
        }

        @Override
        public void append(EvaluationRecord record) {
            records.add(record);
        }

        @Override
        public List<EvaluationRecord> history(EvaluationKey key) {
            List<EvaluationRecord> result = new ArrayList<>();
            for (EvaluationRecord record : records) {
                if (record.getKey().equals(key)) {
                    result.add(record);
                }
            }
            return result;
        }

        private List<EvaluationRecord> historyBySubjectRef(String subjectRef) {
            List<EvaluationRecord> result = new ArrayList<>();
            for (EvaluationRecord record : records) {
                if (subjectRef.equals(record.getSubjectRef())) {
                    result.add(record);
                }
            }
            return result;
        }
    }

    /** Fake judge -- never calls a real LLM. Records every subject it was asked to judge. */
    private static final class FakeEvaluator implements Evaluator {
        private final String id;
        private final String version;
        private final List<EvaluationSubject> evaluatedSubjects = new ArrayList<>();

        private FakeEvaluator(String id, String version) {
            this.id = id;
            this.version = version;
        }

        @Override
        public String evaluatorId() {
            return id;
        }

        @Override
        public Optional<String> evaluatorVersion() {
            return Optional.of(version);
        }

        @Override
        public EvaluationOutcome evaluate(EvaluationSubject subject) {
            evaluatedSubjects.add(subject);
            return new EvaluationEmitted("{\"compliant\":true}");
        }

        private List<String> getEvaluatedSubjectRefs() {
            return evaluatedSubjects.stream().map(EvaluationSubject::getSubjectRef).toList();
        }
    }

    /**
     * Fake verdict reader -- the real JacksonQuizInstructionVerdictReader lives in
     * quiz-instruction-infrastructure, a module audit-application does not depend on. This
     * journey exercises R018's set-selection machinery, not verdict parsing (covered elsewhere by
     * QuizInstructionAnalyzerTest), so every payload maps to the same compliant verdict.
     */
    private static final class FakeQuizInstructionVerdictReader implements QuizInstructionVerdictReader {
        @Override
        public QuizInstructionVerdict read(String payload) {
            return new QuizInstructionVerdict(true, 1.0, InstructionSeverity.NONE, "compliant", List.of(),
                    List.of());
        }
    }
}
