package com.learney.contentaudit.refinerdomain;
import com.learney.contentaudit.auditdomain.AnalyzerDescriptor;
import com.learney.contentaudit.auditdomain.AnalyzerProvider;
import com.learney.contentaudit.auditdomain.ContentAnalyzer;
import com.learney.contentaudit.auditdomain.EvaluationRunPolicy;
import com.learney.contentaudit.auditdomain.SelfDescribingConfig;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerFamily;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerPlanBinding;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerRuleCard;
import com.learney.contentaudit.auditdomain.finding.AnalysisCost;
import com.learney.contentaudit.auditdomain.finding.FindingResolution;
import com.learney.contentaudit.auditdomain.findingengine.DefaultAnalyzerCatalog;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.Optional;
import java.util.TreeMap;
import java.util.zip.GZIPInputStream;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditableEntity;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultRefinerEngineTest {

    private DefaultRefinerEngine sut;

    @BeforeEach
    void setUp() {
        sut = new DefaultRefinerEngine(realCatalog());
    }

    /**
     * Builds an AuditNode with the given target, id, label, and scores.
     * Children and parent are wired separately by the caller.
     */
    private AuditNode buildNode(AuditTarget target, String id, String label, Map<String, Double> scores) {
        AuditNode node = new AuditNode();
        node.setTarget(target);
        node.setScores(scores);
        node.setChildren(Collections.emptyList());
        // Sin entidad, el motor resuelve todo nodo al id "root" y las tareas de
        // nodos distintos se vuelven indistinguibles. Los tests que verifican
        // QUE nodo quedo tareado necesitan que el id sea real.
        node.setEntity(new AuditableEntity() {
            @Override
            public String getId() {
                return id;
            }

            @Override
            public String getLabel() {
                return label;
            }

            @Override
            public String getCode() {
                return id;
            }
        });
        return node;
    }

    /**
     * Links parent → children and sets parent back-pointers so the tree is fully wired.
     */
    private void link(AuditNode parent, List<AuditNode> children) {
        parent.setChildren(children);
        for (AuditNode child : children) {
            child.setParent(parent);
        }
    }

    /**
     * Builds a minimal 5-level tree:
     *   COURSE → MILESTONE → TOPIC → KNOWLEDGE → QUIZ
     *
     * The quiz node carries the given lemma-absence score. The milestone and course
     * nodes carry no lemma-absence score (so no LEMMA_ABSENCE task would come from them).
     */
    private AuditReport buildTreeWithQuizLemmaAbsenceScore(double quizScore) {
        AuditNode courseNode = buildNode(AuditTarget.COURSE, "course-1", "My Course", Collections.emptyMap());
        AuditNode milestoneNode = buildNode(AuditTarget.MILESTONE, "ms-1", "Milestone A1", Collections.emptyMap());
        AuditNode topicNode = buildNode(AuditTarget.TOPIC, "topic-1", "Topic 1", Collections.emptyMap());
        AuditNode knowledgeNode = buildNode(AuditTarget.KNOWLEDGE, "knowledge-1", "Knowledge 1", Collections.emptyMap());
        AuditNode quizNode = buildNode(AuditTarget.QUIZ, "quiz-1", "Quiz 1", Map.of("lemma-absence", quizScore));

        link(knowledgeNode, List.of(quizNode));
        link(topicNode, List.of(knowledgeNode));
        link(milestoneNode, List.of(topicNode));
        link(courseNode, List.of(milestoneNode));

        return new AuditReport(courseNode);
    }

    @Test
    @DisplayName("should include LEMMA_ABSENCE tasks targeting QUIZ when quiz has lemma-absence score below 1.0")
    @Tag("FEAT-RCLA")
    @Tag("F-RCLA-R001")
    public void shouldIncludeLEMMAABSENCETasksTargetingQUIZWhenQuizHasLemmaabsenceScoreBelow10() {
        // A quiz contains a word whose CEFR level is higher than the quiz level, so its
        // lemma-absence score is 0.7 (below 1.0). Per R001, the engine must emit a
        // LEMMA_ABSENCE task targeting QUIZ for this node.
        AuditReport report = buildTreeWithQuizLemmaAbsenceScore(0.7);

        RefinementPlan plan = sut.plan(report, "audit-001");

        List<RefinementTask> lemmaAbsenceTasks = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.LEMMA_ABSENCE)
                .toList();

        Assertions.assertEquals(1, lemmaAbsenceTasks.size(),
                "Expected exactly one LEMMA_ABSENCE task for the quiz with score 0.7");
        Assertions.assertEquals(AuditTarget.QUIZ, lemmaAbsenceTasks.get(0).getNodeTarget(),
                "The LEMMA_ABSENCE task must target QUIZ, not MILESTONE or COURSE");
    }

    @Test
    @DisplayName("should not include LEMMA_ABSENCE tasks targeting MILESTONE or COURSE in the refinement plan")
    @Tag("FEAT-RCLA")
    @Tag("F-RCLA-R001")
    public void shouldNotIncludeLEMMAABSENCETasksTargetingMILESTONEOrCOURSEInTheRefinementPlan() {
        // The milestone and course nodes have a lemma-absence score below 1.0. Per R001,
        // these must NOT produce LEMMA_ABSENCE tasks. Only QUIZ-level lemma-absence matters.
        AuditNode courseNode = buildNode(AuditTarget.COURSE, "course-1", "My Course",
                Map.of("lemma-absence", 0.6));
        AuditNode milestoneNode = buildNode(AuditTarget.MILESTONE, "ms-1", "Milestone A1",
                Map.of("lemma-absence", 0.5));
        AuditNode topicNode = buildNode(AuditTarget.TOPIC, "topic-1", "Topic 1", Collections.emptyMap());
        AuditNode knowledgeNode = buildNode(AuditTarget.KNOWLEDGE, "knowledge-1", "Knowledge 1", Collections.emptyMap());
        // The quiz has a perfect score — no LEMMA_ABSENCE task at quiz level either
        AuditNode quizNode = buildNode(AuditTarget.QUIZ, "quiz-1", "Quiz 1",
                Map.of("lemma-absence", 1.0));

        link(knowledgeNode, List.of(quizNode));
        link(topicNode, List.of(knowledgeNode));
        link(milestoneNode, List.of(topicNode));
        link(courseNode, List.of(milestoneNode));

        AuditReport report = new AuditReport(courseNode);

        RefinementPlan plan = sut.plan(report, "audit-002");

        long lemmaAbsenceCount = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.LEMMA_ABSENCE)
                .count();

        Assertions.assertEquals(0, lemmaAbsenceCount,
                "No LEMMA_ABSENCE tasks must be generated for MILESTONE or COURSE nodes");
    }

    @Test
    @DisplayName("should not generate LEMMA_ABSENCE task for quiz with lemma-absence score equal to 1.0")
    @Tag("FEAT-RCLA")
    @Tag("F-RCLA-R001")
    public void shouldNotGenerateLEMMAABSENCETaskForQuizWithLemmaabsenceScoreEqualTo10() {
        // A quiz with a perfect lemma-absence score of 1.0 has no misplaced vocabulary.
        // The engine must not emit a LEMMA_ABSENCE task for it.
        AuditReport report = buildTreeWithQuizLemmaAbsenceScore(1.0);

        RefinementPlan plan = sut.plan(report, "audit-003");

        long lemmaAbsenceCount = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.LEMMA_ABSENCE)
                .count();

        Assertions.assertEquals(0, lemmaAbsenceCount,
                "No LEMMA_ABSENCE task should be generated when the quiz score is exactly 1.0");
    }

    @Test
    @DisplayName("should still generate COCA_BUCKETS and LEMMA_RECURRENCE tasks at MILESTONE and COURSE level after re-routing")
    @Tag("FEAT-RCLA")
    @Tag("F-RCLA-R001")
    public void shouldStillGenerateCOCABUCKETSAndLEMMARECURRENCETasksAtMILESTONEAndCOURSELevelAfterRerouting(
            ) {
        // R001 re-routes only LEMMA_ABSENCE. COCA_BUCKETS and LEMMA_RECURRENCE at MILESTONE
        // and COURSE level must continue to produce tasks when their scores are below 1.0.
        AuditNode courseNode = buildNode(AuditTarget.COURSE, "course-1", "My Course",
                Map.of("coca-buckets-distribution", 0.6, "lemma-recurrence", 0.7));
        AuditNode milestoneNode = buildNode(AuditTarget.MILESTONE, "ms-1", "Milestone A1",
                Map.of("coca-buckets-distribution", 0.5, "lemma-recurrence", 0.8));
        AuditNode topicNode = buildNode(AuditTarget.TOPIC, "topic-1", "Topic 1", Collections.emptyMap());
        AuditNode knowledgeNode = buildNode(AuditTarget.KNOWLEDGE, "knowledge-1", "Knowledge 1", Collections.emptyMap());
        AuditNode quizNode = buildNode(AuditTarget.QUIZ, "quiz-1", "Quiz 1",
                Map.of("lemma-absence", 1.0));

        link(knowledgeNode, List.of(quizNode));
        link(topicNode, List.of(knowledgeNode));
        link(milestoneNode, List.of(topicNode));
        link(courseNode, List.of(milestoneNode));

        AuditReport report = new AuditReport(courseNode);

        RefinementPlan plan = sut.plan(report, "audit-004");

        long cocaTaskCount = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.COCA_BUCKETS)
                .count();
        long lrecTaskCount = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.LEMMA_RECURRENCE)
                .count();
        long lemmaAbsenceCount = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.LEMMA_ABSENCE)
                .count();

        Assertions.assertTrue(cocaTaskCount > 0,
                "COCA_BUCKETS tasks must still be generated at MILESTONE/COURSE level after LEMMA_ABSENCE re-routing");
        Assertions.assertTrue(lrecTaskCount > 0,
                "LEMMA_RECURRENCE tasks must still be generated at MILESTONE/COURSE level after LEMMA_ABSENCE re-routing");
        Assertions.assertEquals(0, lemmaAbsenceCount,
                "No LEMMA_ABSENCE tasks must appear since the quiz score is 1.0");
    }

    @Test
    @DisplayName("should include one QUIZ_INSTRUCTION task targeting the quiz for each quiz whose quiz-instruction score is below 1.0")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R017")
    public void shouldIncludeOneQUIZINSTRUCTIONTaskTargetingTheQuizForEachQuizWhoseQuizinstructionScoreIsBelow10() {
        // Three quizzes carry a quiz-instruction verdict of non-compliance, one per severity
        // of F-QINST-R002 (minor=0.6, major=0.3, critical=0.0). Per R017, every one of them
        // must produce exactly one QUIZ_INSTRUCTION task targeting that quiz.
        AuditNode courseNode = buildNode(AuditTarget.COURSE, "course-1", "My Course", Collections.emptyMap());
        AuditNode milestoneNode = buildNode(AuditTarget.MILESTONE, "ms-1", "Milestone A1", Collections.emptyMap());
        AuditNode topicNode = buildNode(AuditTarget.TOPIC, "topic-1", "Topic 1", Collections.emptyMap());
        AuditNode knowledgeNode = buildNode(AuditTarget.KNOWLEDGE, "knowledge-1", "Knowledge 1", Collections.emptyMap());
        AuditNode quizMinor = buildNode(AuditTarget.QUIZ, "quiz-minor", "Quiz Minor",
                Map.of("quiz-instruction", 0.6));
        AuditNode quizMajor = buildNode(AuditTarget.QUIZ, "quiz-major", "Quiz Major",
                Map.of("quiz-instruction", 0.3));
        AuditNode quizCritical = buildNode(AuditTarget.QUIZ, "quiz-critical", "Quiz Critical",
                Map.of("quiz-instruction", 0.0));

        link(knowledgeNode, List.of(quizMinor, quizMajor, quizCritical));
        link(topicNode, List.of(knowledgeNode));
        link(milestoneNode, List.of(topicNode));
        link(courseNode, List.of(milestoneNode));

        AuditReport report = new AuditReport(courseNode);

        RefinementPlan plan = sut.plan(report, "audit-qinst-001");

        List<RefinementTask> quizInstructionTasks = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.QUIZ_INSTRUCTION)
                .toList();

        Assertions.assertEquals(3, quizInstructionTasks.size(),
                "Expected exactly one QUIZ_INSTRUCTION task per quiz with a non-compliant verdict");
        Assertions.assertTrue(
                quizInstructionTasks.stream().allMatch(t -> t.getNodeTarget() == AuditTarget.QUIZ),
                "Every QUIZ_INSTRUCTION task must target the quiz, not an ancestor node");

        List<String> taskedQuizIds = quizInstructionTasks.stream()
                .map(RefinementTask::getNodeId)
                .sorted()
                .toList();
        Assertions.assertEquals(List.of("quiz-critical", "quiz-major", "quiz-minor"), taskedQuizIds,
                "Each of the three non-compliant quizzes must get its own QUIZ_INSTRUCTION task, one per quiz");
    }

    @Test
    @DisplayName("should not include any QUIZ_INSTRUCTION task for a quiz that complies with its instruction nor for a quiz with no quiz-instruction score at all")
    @Tag("FEAT-QINST")
    @Tag("F-QINST-R017")
    public void shouldNotIncludeAnyQUIZINSTRUCTIONTaskForAQuizThatCompliesWithItsInstructionNorForAQuizWithNoQuizinstructionScoreAtAll() {
        // Two distinct situations that must both be excluded from the plan per R017:
        // - quiz-compliant: the judge found no violation, score is exactly 1.0 (maximum).
        // - quiz-unjudged: pending/failed per F-QINST-R004, so it has NO "quiz-instruction"
        //   key at all in its scores map (it carries a different analysis' score instead).
        // A third, genuinely non-compliant quiz is included as a control: without it, a system
        // that generates NO QUIZ_INSTRUCTION task for anything would vacuously satisfy this
        // test, so the control quiz's task is what proves the other two were excluded on
        // purpose rather than by a mechanism that is simply not producing tasks at all.
        AuditNode courseNode = buildNode(AuditTarget.COURSE, "course-1", "My Course", Collections.emptyMap());
        AuditNode milestoneNode = buildNode(AuditTarget.MILESTONE, "ms-1", "Milestone A1", Collections.emptyMap());
        AuditNode topicNode = buildNode(AuditTarget.TOPIC, "topic-1", "Topic 1", Collections.emptyMap());
        AuditNode knowledgeNode = buildNode(AuditTarget.KNOWLEDGE, "knowledge-1", "Knowledge 1", Collections.emptyMap());
        AuditNode quizCompliant = buildNode(AuditTarget.QUIZ, "quiz-compliant", "Quiz Compliant",
                Map.of("quiz-instruction", 1.0));
        AuditNode quizUnjudged = buildNode(AuditTarget.QUIZ, "quiz-unjudged", "Quiz Unjudged",
                Map.of("lemma-absence", 0.9));
        AuditNode quizControlNonCompliant = buildNode(AuditTarget.QUIZ, "quiz-control-noncompliant",
                "Quiz Control Non-compliant", Map.of("quiz-instruction", 0.6));

        link(knowledgeNode, List.of(quizCompliant, quizUnjudged, quizControlNonCompliant));
        link(topicNode, List.of(knowledgeNode));
        link(milestoneNode, List.of(topicNode));
        link(courseNode, List.of(milestoneNode));

        AuditReport report = new AuditReport(courseNode);

        RefinementPlan plan = sut.plan(report, "audit-qinst-002");

        List<RefinementTask> quizInstructionTasks = plan.getTasks().stream()
                .filter(t -> t.getDiagnosisKind() == DiagnosisKind.QUIZ_INSTRUCTION)
                .toList();

        Assertions.assertEquals(1, quizInstructionTasks.size(),
                "Only the genuinely non-compliant control quiz should get a QUIZ_INSTRUCTION task; "
                        + "the compliant quiz and the unjudged quiz must not");
        Assertions.assertEquals("quiz-control-noncompliant", quizInstructionTasks.get(0).getNodeId(),
                "The single QUIZ_INSTRUCTION task must target the control quiz, not the compliant "
                        + "or the unjudged one");
    }

    @Test
    @DisplayName("should derive from the 29/9 analysis the same 4.036 tasks as before the contract: 3.051 SENTENCE_LENGTH, 950 LEMMA_ABSENCE, 25 KNOWLEDGE_INSTRUCTIONS_LENGTH, 6 KNOWLEDGE_TITLE_LENGTH, 3 COCA_BUCKETS and 1 LEMMA_RECURRENCE")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R013")
    public void shouldDeriveFromThe299AnalysisTheSame4036TasksAsBeforeTheContract3051SENTENCELENGTH950LEMMAABSENCE25KNOWLEDGEINSTRUCTIONSLENGTH6KNOWLEDGETITLELENGTH3COCABUCKETSAnd1LEMMARECURRENCE() {
        // R013: the plan bindings of the catalog reproduce the old lists and switch exactly -- the
        // 4.036 tasks of the plan 2026-09-30T11-54-12, derived from the analysis 2026-09-30T11-54-02,
        // task by task and in the same order.
        AuditReport base = new AuditReport(baseTree());

        RefinementPlan plan = sut.plan(base, "2026-09-30T11-54-02");

        List<String> tasks = new ArrayList<>();
        Map<DiagnosisKind, Integer> byKind = new TreeMap<>();
        for (RefinementTask task : plan.getTasks()) {
            tasks.add(task.getNodeTarget() + "\t" + task.getNodeId() + "\t" + task.getNodeLabel() + "\t"
                    + task.getDiagnosisKind());
            byKind.merge(task.getDiagnosisKind(), 1, Integer::sum);
        }
        Assertions.assertEquals(4036, tasks.size(), "R013: the same 4.036 tasks");
        Map<DiagnosisKind, Integer> expected = new TreeMap<>(Map.of(DiagnosisKind.SENTENCE_LENGTH, 3051,
                DiagnosisKind.LEMMA_ABSENCE, 950, DiagnosisKind.KNOWLEDGE_INSTRUCTIONS_LENGTH, 25,
                DiagnosisKind.KNOWLEDGE_TITLE_LENGTH, 6, DiagnosisKind.COCA_BUCKETS, 3, DiagnosisKind.LEMMA_RECURRENCE, 1));
        Assertions.assertEquals(expected, byKind, "R013: 3.051 + 950 + 25 + 6 + 3 + 1");
        Assertions.assertEquals(readLines("plan.tsv.gz"), tasks,
                "R013: task by task, in the order of the plan made before the contract");
        Assertions.assertTrue(sut.unconvertedScores(base).isEmpty(),
                "the base ran without the judge: no errors analyzer has scores to declare");
    }

    @Test
    @DisplayName("should declare, instead of dropping them in silence, the analyzer and the number of nodes whose scores below 1 it could not turn into tasks because the analyzer has no task kind, as happened to the judge before F-QINST-R017")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R004")
    public void shouldDeclareInsteadOfDroppingThemInSilenceTheAnalyzerAndTheNumberOfNodesWhoseScoresBelow1ItCouldNotTurnIntoTasksBecauseTheAnalyzerHasNoTaskKindAsHappenedToTheJudgeBeforeFQINSTR017() {
        // R004 inv. 3: before F-QINST-R017 the plan had no task kind for the judge and dropped its
        // scores without a word. An errors analyzer without a task kind is declared, not dropped.
        DefaultRefinerEngine engine = new DefaultRefinerEngine(new DefaultAnalyzerCatalog(List.of(
                provider(errorsCard("quiz-instruction"), Optional.empty()))));
        AuditReport report = reportWithQuizScores("quiz-instruction", 0.3, 0.0, 0.6, 1.0);

        List<UnconvertedScoreCount> unconverted = engine.unconvertedScores(report);

        Assertions.assertTrue(engine.plan(report, "a1").getTasks().isEmpty(), "no task kind, no task");
        Assertions.assertEquals(1, unconverted.size());
        Assertions.assertEquals("quiz-instruction", unconverted.get(0).getAnalyzer(), "R004: which analyzer");
        Assertions.assertEquals(3, unconverted.get(0).getNodeCount(), "R004: how many nodes below 1");
        Assertions.assertFalse(unconverted.get(0).getReason().isBlank(), "R004: and why");
    }

    @Test
    @DisplayName("should declare as unconverted the scores below 1 of an analyzer whose plan binding names a task kind the plan does not know")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R004")
    public void shouldDeclareAsUnconvertedTheScoresBelow1OfAnAnalyzerWhosePlanBindingNamesATaskKindThePlanDoesNotKnow() {
        // R004 inv. 3: a binding whose task kind is not a DiagnosisKind of the plan (a new analyzer
        // whose constant was not added) is declared too.
        DefaultRefinerEngine engine = new DefaultRefinerEngine(new DefaultAnalyzerCatalog(List.of(
                provider(errorsCard("pista-coherente"), Optional.of(new AnalyzerPlanBinding("HINT_COHERENCE",
                        List.of(AuditTarget.QUIZ)))))));
        AuditReport report = reportWithQuizScores("pista-coherente", 0.0, 0.5);

        List<UnconvertedScoreCount> unconverted = engine.unconvertedScores(report);

        Assertions.assertTrue(engine.plan(report, "a1").getTasks().isEmpty());
        Assertions.assertEquals(1, unconverted.size());
        Assertions.assertEquals("pista-coherente", unconverted.get(0).getAnalyzer());
        Assertions.assertEquals(2, unconverted.get(0).getNodeCount());
        Assertions.assertTrue(unconverted.get(0).getReason().contains("HINT_COHERENCE"),
                "R004: the reason names the unknown task kind: " + unconverted.get(0).getReason());
    }

    @Test
    @DisplayName("should turn the scores below 1 of a new errors analyzer into tasks through its plan binding, without the plan knowing its name")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R004")
    public void shouldTurnTheScoresBelow1OfANewErrorsAnalyzerIntoTasksThroughItsPlanBindingWithoutThePlanKnowingItsName() {
        // R004 / TECH_SPEC: the plan is not edited to add an analyzer -- its binding is enough.
        // pista-coherente is a name the plan never heard of; its binding names a task kind it knows.
        DefaultRefinerEngine engine = new DefaultRefinerEngine(new DefaultAnalyzerCatalog(List.of(
                provider(errorsCard("pista-coherente"), Optional.of(new AnalyzerPlanBinding("QUIZ_INSTRUCTION",
                        List.of(AuditTarget.QUIZ)))))));
        AuditReport report = reportWithQuizScores("pista-coherente", 0.0, 1.0, 0.5);

        RefinementPlan plan = engine.plan(report, "a1");

        Assertions.assertEquals(List.of("q0", "q2"), plan.getTasks().stream().map(RefinementTask::getNodeId).toList(),
                "R004: one task per quiz below 1, worst first");
        plan.getTasks().forEach(task -> Assertions.assertEquals(DiagnosisKind.QUIZ_INSTRUCTION, task.getDiagnosisKind()));
        Assertions.assertTrue(engine.unconvertedScores(report).isEmpty(), "nothing left unconverted");
    }

    @Test
    @DisplayName("should declare nothing about lemma-count, whose scores below 1 on the levels and the course (67,0 %) have no task as before, because the declaration covers only errors analyzers")
    @Tag("FEAT-HALL")
    @Tag("F-HALL-R004")
    public void shouldDeclareNothingAboutLemmacountWhoseScoresBelow1OnTheLevelsAndTheCourse670HaveNoTaskAsBeforeBecauseTheDeclarationCoversOnlyErrorsAnalyzers() {
        // R004 / R013: lemma-count is a vocabulary analyzer without tasks, as before the contract;
        // the declaration covers only the errors family, so its 67,0 % declares nothing.
        AuditNode course = buildNode(AuditTarget.COURSE, "root", "Course", new LinkedHashMap<>(Map.of("lemma-count", 0.67)));
        AuditNode level = buildNode(AuditTarget.MILESTONE, "m-b2", "B2", new LinkedHashMap<>(Map.of("lemma-count", 0.34)));
        course.setChildren(List.of(level));

        AuditReport report = new AuditReport(course);

        Assertions.assertTrue(sut.plan(report, "a1").getTasks().isEmpty(), "lemma-count makes no tasks");
        Assertions.assertTrue(sut.unconvertedScores(report).isEmpty(), "R004: and declares nothing");
    }

    /**
     * FEAT-HALL: the plan reads the bindings of the catalog, one per provider. These are the
     * eight real providers, as Main registers them; their configurations only feed the cards,
     * so mocks are enough to read the bindings.
     */
    static com.learney.contentaudit.auditdomain.AnalyzerCatalog realCatalog() {
        return new com.learney.contentaudit.auditdomain.findingengine.DefaultAnalyzerCatalog(java.util.List.of(
                new com.learney.contentaudit.auditdomain.SentenceLengthAnalyzerProvider(null,
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.SentenceLengthConfig.class)),
                new com.learney.contentaudit.auditdomain.KnowledgeTitleLengthAnalyzerProvider(),
                new com.learney.contentaudit.auditdomain.KnowledgeInstructionsLengthAnalyzerProvider(),
                new com.learney.contentaudit.auditdomain.coca.CocaBucketsAnalyzerProvider(null,
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.CocaBucketsConfig.class)),
                new com.learney.contentaudit.auditdomain.lrec.LemmaRecurrenceAnalyzerProvider(
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.LemmaRecurrenceConfig.class)),
                new com.learney.contentaudit.auditdomain.labs.LemmaAbsenceAnalyzerProvider(null,
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.LemmaAbsenceConfig.class), null),
                new com.learney.contentaudit.auditdomain.lemmacount.LemmaCountAnalyzerProvider(null,
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.LemmaCountConfig.class)),
                new com.learney.contentaudit.auditdomain.quizinstructionengine.DefaultQuizInstructionAnalyzerFactory(
                        null, null, null,
                        org.mockito.Mockito.mock(com.learney.contentaudit.auditdomain.QuizInstructionConfig.class))));
    }

    /** The tree of the analysis 2026-09-30T11-54-02: every node, in preorder, with its scores. */
    private AuditNode baseTree() {
        Deque<AuditNode> path = new ArrayDeque<>();
        AuditNode root = null;
        for (String line : readLines("nodes.tsv.gz")) {
            String[] fields = line.split("\t", -1);
            AuditTarget target = AuditTarget.valueOf(fields[0]);
            Map<String, Double> scores = new LinkedHashMap<>();
            if (!fields[3].isEmpty()) {
                for (String pair : fields[3].split(";")) {
                    int eq = pair.indexOf('=');
                    scores.put(pair.substring(0, eq), Double.parseDouble(pair.substring(eq + 1)));
                }
            }
            AuditNode node = buildNode(target, fields[1], fields[2], scores);
            node.setChildren(new ArrayList<>());
            int depth = List.of(AuditTarget.COURSE, AuditTarget.MILESTONE, AuditTarget.TOPIC, AuditTarget.KNOWLEDGE,
                    AuditTarget.QUIZ).indexOf(target);
            while (path.size() > depth) {
                path.pop();
            }
            if (path.isEmpty()) {
                root = node;
            } else {
                node.setParent(path.peek());
                path.peek().getChildren().add(node);
            }
            path.push(node);
        }
        Assertions.assertNotNull(root);
        return root;
    }

    private List<String> readLines(String fixture) {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(new GZIPInputStream(
                getClass().getResourceAsStream("/fhall-base-2026-09-30/" + fixture)), StandardCharsets.UTF_8))) {
            return reader.lines().toList();
        } catch (IOException e) {
            throw new AssertionError("fixture " + fixture + " unreadable", e);
        }
    }

    /** A course with one quiz per score of the analyzer: q0, q1... */
    private AuditReport reportWithQuizScores(String analyzer, double... scores) {
        AuditNode course = buildNode(AuditTarget.COURSE, "root", "Course", new LinkedHashMap<>());
        List<AuditNode> quizzes = new ArrayList<>();
        for (int i = 0; i < scores.length; i++) {
            quizzes.add(buildNode(AuditTarget.QUIZ, "q" + i, "Quiz " + i, new LinkedHashMap<>(Map.of(analyzer, scores[i]))));
        }
        course.setChildren(quizzes);
        return new AuditReport(course);
    }

    private static AnalyzerDescriptor errorsCard(String name) {
        return new AnalyzerDescriptor(name, "Checks " + name, AuditTarget.QUIZ, "¿" + name + "?", "El ejercicio",
                List.of(new AnalyzerRuleCard("rule-" + name, "La regla", AnalysisCost.INSTANT)), "Ningun error",
                AnalyzerFamily.ERRORS, List.of(AuditTarget.QUIZ), List.of(FindingResolution.PANEL), AnalysisCost.INSTANT);
    }

    private static AnalyzerProvider provider(AnalyzerDescriptor card, Optional<AnalyzerPlanBinding> binding) {
        return new AnalyzerProvider() {
            @Override
            public String analyzerName() {
                return card.getName();
            }

            @Override
            public AnalyzerDescriptor describe() {
                return card;
            }

            @Override
            public ContentAnalyzer create(EvaluationRunPolicy policy) {
                throw new AssertionError("the plan never builds an analyzer");
            }

            @Override
            public Optional<AnalyzerPlanBinding> planBinding() {
                return binding;
            }

            @Override
            public Optional<SelfDescribingConfig> config() {
                return Optional.empty();
            }
        };
    }
}
