package com.learney.contentaudit.revisioninfrastructure.candidatejudgment;

import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.quizsentence.QuizSentenceConverter;
import com.learney.contentaudit.coursedomain.quizsentenceengine.DefaultQuizSentenceConverter;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriterionEvaluator;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisioninfrastructure.lagen.LagenConfig;
import com.sentinel.agents.framework.state.RunState;
import dev.langchain4j.model.chat.ChatModel;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.annotation.processing.Generated;

/**
 * Backend of {@link CandidateCriterionEvaluator} for the two judgment criteria
 * (FAITHFUL_TRANSLATION, SOLVABLE_SAME_KIND -- F-QICOR-R004 criterios 4/5),
 * running the declarative {@code candidate-judgment} graph. One instance per
 * criterion (the graph judges exactly one criterion per invocation); {@link
 * DefaultCandidateJudgmentEvaluatorFactory} constructs one per {@link
 * CorrectionCriterion} it is asked for.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class AgentCandidateJudgmentEvaluator implements CandidateCriterionEvaluator {

    private static final String AGENT_NAME = "candidate-judgment";

    // Needed only to reconstruct the quizSentence DSL (brackets + cues) that the
    // judge prompt expects from the raw QuizTemplateEntity.form; this evaluator has
    // no injected QuizSentenceConverter (not part of its declared contract), so it
    // builds the same zero-arg wiring the composition root uses elsewhere
    // (DefaultQuizSentenceConverter.create()).
    private static final QuizSentenceConverter QUIZ_SENTENCE_CONVERTER =
            DefaultQuizSentenceConverter.create();

    private final CorrectionCriterion criterion;

    private final CandidateJudgmentRuntimeLauncher agentRuntimeLauncher;

    private final CandidateJudgmentVerdictParser verdictParser;

    private final ChatModel chatModel;

    private final LagenConfig config;

    public AgentCandidateJudgmentEvaluator(CorrectionCriterion criterion,
            CandidateJudgmentRuntimeLauncher agentRuntimeLauncher,
            CandidateJudgmentVerdictParser verdictParser, ChatModel chatModel, LagenConfig config) {
        this.criterion = criterion;
        this.agentRuntimeLauncher = agentRuntimeLauncher;
        this.verdictParser = verdictParser;
        this.chatModel = chatModel;
        this.config = config;
    }

    @Override
    public CorrectionCriterion criterion() {
        return criterion;
    }

    @Override
    public CriterionVerdict evaluate(CandidateAssessmentInput input) {
        CourseElementSnapshot originalSnapshot = input.getOriginal();
        CourseElementSnapshot candidateSnapshot = input.getCandidate();
        QuizTemplateEntity originalQuiz = originalSnapshot != null ? originalSnapshot.getQuiz() : null;
        QuizTemplateEntity candidateQuiz = candidateSnapshot != null ? candidateSnapshot.getQuiz() : null;
        if (originalQuiz == null || candidateQuiz == null) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "No se pudo juzgar: falta el ejercicio original o el candidato");
        }

        Map<String, String> inputs = new LinkedHashMap<>();
        inputs.put("criterion", criterion.name());
        inputs.put("cefrLevel", input.getCefrLevelLabel() != null
                ? input.getCefrLevelLabel()
                : (input.getCefrLevel() != null ? input.getCefrLevel().name() : ""));
        inputs.put("knowledgeTitle", orEmpty(input.getKnowledgeTitle()));
        inputs.put("knowledgeInstructions", orEmpty(input.getKnowledgeInstructions()));
        inputs.put("sentenceMode",
                input.getSentenceMode() != null ? input.getSentenceMode().name() : "");
        inputs.put("originalQuizSentence", quizSentenceOf(originalQuiz));
        inputs.put("originalTranslation", orEmpty(originalQuiz.getTranslation()));
        inputs.put("candidateQuizSentence", quizSentenceOf(candidateQuiz));
        inputs.put("candidateTranslation", orEmpty(candidateQuiz.getTranslation()));

        RunState runState;
        try {
            runState = agentRuntimeLauncher.launch(AGENT_NAME, inputs, chatModel);
        } catch (Exception e) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "El juez de candidato no esta disponible: " + e.getMessage());
        }

        if (runState.isHaltedRun()) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "El juez de candidato interrumpio la corrida: " + runState.terminationReason());
        }

        return verdictParser.parse(runState, criterion);
    }

    private String quizSentenceOf(QuizTemplateEntity quiz) {
        return quiz.getForm() != null ? QUIZ_SENTENCE_CONVERTER.serialize(quiz.getForm()) : "";
    }

    private static String orEmpty(String value) {
        return value != null ? value : "";
    }
}
