package com.learney.contentaudit.revisioninfrastructure.candidatejudgment;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.sentinel.agents.framework.state.ArtifactPointer;
import com.sentinel.agents.framework.state.RunState;
import java.nio.file.Files;
import java.util.Map;
import javax.annotation.processing.Generated;

/**
 * Parses the {@code candidate-judgment} graph's {@code criterionVerdict}
 * artifact (see {@code .sentinel/agents/candidate-judgment/scripts/emit.sh}):
 * {@code {"criterion": string, "outcome": "PASSED"|"FAILED"|"NOT_EVALUABLE",
 * "detail": string}}.
 *
 * <p>Unlike the corrector's candidate parser, this never throws: the graph's
 * own emit.sh always produces a well-formed artifact, defaulting to {@code
 * NOT_EVALUABLE} when the judge itself exhausted its attempts (its own
 * comment: reproving would assert the candidate regressed something, and an
 * infrastructure failure asserts nothing about the candidate). This parser
 * mirrors that stance for its own failure modes (missing artifact, unreadable
 * file, malformed JSON, unrecognized outcome) -- degrading to {@code
 * NOT_EVALUABLE} rather than throwing, so one judge hiccup blocks only its own
 * criterion instead of aborting the whole assessment.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultCandidateJudgmentVerdictParser implements CandidateJudgmentVerdictParser {

    static final String ARTIFACT_KEY = "criterionVerdict";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Override
    public CriterionVerdict parse(RunState runState, CorrectionCriterion criterion) {
        Map<String, ArtifactPointer> artifacts = runState != null ? runState.artifacts() : null;
        if (artifacts == null || !artifacts.containsKey(ARTIFACT_KEY)) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "El juez de candidato no produjo el artifact criterionVerdict en esta corrida");
        }

        ArtifactPointer pointer = artifacts.get(ARTIFACT_KEY);
        String rawJson;
        try {
            rawJson = Files.readString(pointer.location());
        } catch (Exception e) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "No se pudo leer el veredicto del juez: " + e.getMessage());
        }

        JsonNode root;
        try {
            root = MAPPER.readTree(stripJsonFence(rawJson.trim()));
        } catch (Exception e) {
            return new CriterionVerdict(criterion, CriterionOutcome.NOT_EVALUABLE,
                    "El veredicto del juez no es JSON valido: " + e.getMessage());
        }

        String outcomeText = root.path("outcome").asText(null);
        CriterionOutcome outcome;
        try {
            outcome = outcomeText != null
                    ? CriterionOutcome.valueOf(outcomeText)
                    : CriterionOutcome.NOT_EVALUABLE;
        } catch (IllegalArgumentException e) {
            outcome = CriterionOutcome.NOT_EVALUABLE;
        }

        String detail = root.path("detail").asText("");
        return new CriterionVerdict(criterion, outcome, detail);
    }

    private static String stripJsonFence(String text) {
        if (text.startsWith("```")) {
            int firstNewline = text.indexOf('\n');
            int lastFence = text.lastIndexOf("```");
            if (firstNewline >= 0 && lastFence > firstNewline) {
                return text.substring(firstNewline + 1, lastFence).trim();
            }
        }
        return text;
    }
}
