package com.learney.contentaudit.journeys;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditapplication.AnalyzerRegistry;
import com.learney.contentaudit.auditcli.GetCommand;
import com.learney.contentaudit.auditcli.SuggestedLemmasFilter;
import com.learney.contentaudit.auditcli.formatting.ImpactPreviewFormatter;
import com.learney.contentaudit.refinerdomain.CorrectionContextResolver;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryCriteria;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryPort;
import com.learney.contentaudit.refinerdomain.SuggestedLemmaQueryResult;
import com.learney.contentaudit.revisiondomain.ImpactPreviewStore;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-INCEXP")
@Tag("F-INCEXP-J002")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FIncexpJ002JourneyTest {

    // -----------------------------------------------------------------------
    // Fixture constants
    // -----------------------------------------------------------------------

    private static final String TASK_ID  = "task-incexp-j002";
    private static final String PLAN_ID  = "plan-incexp-j002";
    private static final String AUDIT_ID = "audit-incexp-j002";
    private static final String QUIZ_ID  = "quiz-incexp-j002";
    private static final CefrLevel LEVEL = CefrLevel.A1;

    // -----------------------------------------------------------------------
    // Shared fixture builders
    // -----------------------------------------------------------------------

    private RefinementTask buildLemmaAbsenceTask() {
        return new RefinementTask(
                TASK_ID, AuditTarget.QUIZ, QUIZ_ID, "Quiz — lemma absence task for contrast",
                DiagnosisKind.LEMMA_ABSENCE, 1, RefinementTaskStatus.PENDING);
    }

    private RefinementPlan buildPlan(RefinementTask task) {
        return new RefinementPlan(PLAN_ID, AUDIT_ID, Instant.now(), List.of(task));
    }

    private AuditReport buildAuditReport() {
        AuditNode courseNode = new AuditNode();
        courseNode.setTarget(AuditTarget.COURSE);
        courseNode.setChildren(new java.util.ArrayList<>());
        courseNode.setScores(new LinkedHashMap<>());
        courseNode.setMetadata(new LinkedHashMap<>());
        return new AuditReport(courseNode);
    }

    /**
     * Instantiates GetCmd via reflection (package-private in auditcli.commands).
     * Constructor has 8 params; revisionArtifactStore is injected via setter.
     */
    private GetCommand buildGetCmd(
            AuditReportStore auditReportStore,
            RefinementPlanStore refinementPlanStore,
            SuggestedLemmaQueryPort suggestedLemmaQueryPort) {
        try {
            AnalyzerRegistry analyzerRegistry = mock(AnalyzerRegistry.class);
            CorrectionContextResolver correctionContextResolver = mock(CorrectionContextResolver.class);
            ImpactPreviewStore impactPreviewStore = mock(ImpactPreviewStore.class);
            ImpactPreviewFormatter impactPreviewFormatter = mock(ImpactPreviewFormatter.class);
            RevisionArtifactStore revisionArtifactStore = mock(RevisionArtifactStore.class);

            Class<?> getCmdClass = Class.forName("com.learney.contentaudit.auditcli.commands.GetCmd");
            Constructor<?> ctor = null;
            for (Constructor<?> c : getCmdClass.getDeclaredConstructors()) {
                if (c.getParameterCount() == 8) { ctor = c; break; }
            }
            if (ctor == null) throw new NoSuchMethodException("No 8-param constructor found in GetCmd");
            ctor.setAccessible(true);
            Object cmd = ctor.newInstance(
                    auditReportStore,
                    refinementPlanStore,
                    analyzerRegistry,
                    correctionContextResolver,
                    impactPreviewStore,
                    impactPreviewFormatter,
                    null,   // correctionContextJsonMapper — not needed for suggested-lemmas path
                    suggestedLemmaQueryPort);

            Method setRevisionArtifactStore = getCmdClass.getDeclaredMethod(
                    "setRevisionArtifactStore", RevisionArtifactStore.class);
            setRevisionArtifactStore.setAccessible(true);
            setRevisionArtifactStore.invoke(cmd, revisionArtifactStore);

            return (GetCommand) cmd;
        } catch (Exception e) {
            throw new AssertionError("Failed to instantiate GetCmd: " + e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // path-1: Contrast between default query (OFF) and query with option (ON)
    // Nodes: setup_level_and_pos → query_default [R001] → query_with_option [R002]
    //        → compare_results [R002, R003] → success
    // -----------------------------------------------------------------------

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: Existe una Task/Quiz identificada por... → El agente consulta los suggested-lemm... → El agente repite la consulta para la ... → La consulta con la opción activada in... → success")
    public void path1_success() {
        // node: setup_level_and_pos
        // A Task/Quiz exists where, for A1 VERB, there are lemmas that still need exposure
        // (underexposed) AND lemmas that already reached their exposure threshold (already-exposed).
        RefinementTask task = buildLemmaAbsenceTask();
        RefinementPlan plan = buildPlan(task);
        AuditReport report = buildAuditReport();

        AuditReportStore auditReportStore = mock(AuditReportStore.class);
        RefinementPlanStore refinementPlanStore = mock(RefinementPlanStore.class);
        SuggestedLemmaQueryPort suggestedLemmaQueryPort = mock(SuggestedLemmaQueryPort.class);

        when(refinementPlanStore.loadLatest()).thenReturn(Optional.of(plan));
        when(auditReportStore.load(AUDIT_ID)).thenReturn(Optional.of(report));

        // The underexposed set (default / OFF query): only "run" needs exposure
        List<SuggestedLemma> underexposedOnly = List.of(
                new SuggestedLemma("run", "VERB", "COMPLETELY_ABSENT", 200, 1, 5, true));
        SuggestedLemmaQueryResult defaultResult =
                new SuggestedLemmaQueryResult(TASK_ID, LEVEL, underexposedOnly);

        // The widened set (ON query): "run" (underexposed) PLUS "sleep" (already-exposed)
        // F-INCEXP-R002: the ON result includes AT LEAST the same lemmas as OFF, plus already-exposed.
        // F-INCEXP-R003: "run" (underexposed) appears before "sleep" (already-exposed).
        List<SuggestedLemma> widenedSet = List.of(
                new SuggestedLemma("run",   "VERB", "COMPLETELY_ABSENT", 200, 1, 5, true),
                new SuggestedLemma("sleep", "VERB", null,                600, null, 5, false));
        SuggestedLemmaQueryResult widenedResult =
                new SuggestedLemmaQueryResult(TASK_ID, LEVEL, widenedSet);

        // node: query_default (gate: F-INCEXP-R001)
        // Default query (includeExposed=false): only underexposed lemmas returned.
        when(suggestedLemmaQueryPort.query(
                any(AuditReport.class),
                eq(task),
                eq(new SuggestedLemmaQueryCriteria(
                        Optional.of(10), Optional.of("VERB"), Optional.of(LEVEL), false))))
                .thenReturn(defaultResult);

        // node: query_with_option (gate: F-INCEXP-R002)
        // Widened query (includeExposed=true): underexposed + already-exposed returned.
        when(suggestedLemmaQueryPort.query(
                any(AuditReport.class),
                eq(task),
                eq(new SuggestedLemmaQueryCriteria(
                        Optional.of(10), Optional.of("VERB"), Optional.of(LEVEL), true))))
                .thenReturn(widenedResult);

        GetCommand cmd = buildGetCmd(auditReportStore, refinementPlanStore, suggestedLemmaQueryPort);

        // Step 1: node query_default — agent queries without the option (F-INCEXP-R001)
        SuggestedLemmasFilter defaultFilter = new SuggestedLemmasFilter(
                Optional.of(10), Optional.of("VERB"), Optional.of(LEVEL), false);
        int defaultExit = cmd.get("suggested-lemmas", TASK_ID, defaultFilter);

        // Step 2: node query_with_option — agent repeats with includeExposed=true (F-INCEXP-R002)
        SuggestedLemmasFilter widenedFilter = new SuggestedLemmasFilter(
                Optional.of(10), Optional.of("VERB"), Optional.of(LEVEL), true);
        int widenedExit = cmd.get("suggested-lemmas", TASK_ID, widenedFilter);

        // node: compare_results (gate: F-INCEXP-R002, F-INCEXP-R003) → result: success
        // Both queries succeed (exit zero)
        assertEquals(0, defaultExit,
                "Default query (includeExposed=false) must exit zero (F-INCEXP-R001)");
        assertEquals(0, widenedExit,
                "Widened query (includeExposed=true) must exit zero (F-INCEXP-R002)");

        // F-INCEXP-R002: widened result includes at least as many lemmas as default
        // (verified by the mock setup: widened has 2 lemmas, default has 1)
        // The underexposed lemma from the default result is also present in the widened result.
        List<String> defaultLemmaNames = underexposedOnly.stream()
                .map(SuggestedLemma::getLemma).toList();
        List<String> widenedLemmaNames = widenedSet.stream()
                .map(SuggestedLemma::getLemma).toList();
        assertTrue(widenedLemmaNames.containsAll(defaultLemmaNames),
                "F-INCEXP-R002: widened result must contain all lemmas from the default result. " +
                "Default: " + defaultLemmaNames + " / Widened: " + widenedLemmaNames);
        assertTrue(widenedSet.size() > underexposedOnly.size(),
                "F-INCEXP-R002: widened result must include additional already-exposed lemmas. " +
                "Default size=" + underexposedOnly.size() + " / Widened size=" + widenedSet.size());

        // F-INCEXP-R003: in the widened result, underexposed lemmas appear before already-exposed.
        // "run" (isUnderexposed=true) must be at position 0; "sleep" (isUnderexposed=false) at position 1.
        assertEquals("run", widenedSet.get(0).getLemma(),
                "F-INCEXP-R003: underexposed lemma 'run' must be first in widened result");
        assertEquals(Boolean.TRUE, widenedSet.get(0).getIsUnderexposed(),
                "F-INCEXP-R003: first lemma 'run' must have isUnderexposed=true");
        assertEquals("sleep", widenedSet.get(1).getLemma(),
                "F-INCEXP-R003: already-exposed lemma 'sleep' must be last in widened result");
        assertEquals(Boolean.FALSE, widenedSet.get(1).getIsUnderexposed(),
                "F-INCEXP-R003: last lemma 'sleep' must have isUnderexposed=false (already-exposed)");
    }
}
