package com.learney.contentaudit.journeys;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.coursedomain.CourseValidator;
import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.KnowledgeEntity;
import com.learney.contentaudit.coursedomain.MilestoneEntity;
import com.learney.contentaudit.coursedomain.MultipleChoiceEntity;
import com.learney.contentaudit.coursedomain.MultipleChoiceItemEntity;
import com.learney.contentaudit.coursedomain.NodeKind;
import com.learney.contentaudit.coursedomain.QuizTemplateEntities;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.RootNodeEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.coursedomain.TopicEntity;
import com.learney.contentaudit.coursedomain.quizsentenceengine.DefaultQuizSentenceConverter;
import com.learney.contentaudit.courseinfrastructure.FileSystemCourseRepository;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.LemmaAbsenceQuizCandidate;
import com.learney.contentaudit.revisiondomain.ProposalDecisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.ProposalDecisionService;
import com.learney.contentaudit.revisiondomain.RevisionArtifact;
import com.learney.contentaudit.revisiondomain.RevisionArtifactStore;
import com.learney.contentaudit.revisiondomain.RevisionEngineConfig;
import com.learney.contentaudit.revisiondomain.RevisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.RevisionVerdict;
import com.learney.contentaudit.revisiondomain.engine.DefaultLemmaAbsenceProposalDeriver;
import com.learney.contentaudit.revisiondomain.engine.DefaultProposalDecisionServiceFactory;
import com.learney.contentaudit.revisiondomain.preservation.PreservationViolation;
import com.learney.contentaudit.revisiondomain.preservation.RepairReport;
import com.learney.contentaudit.revisiondomain.preservationengine.DefaultPreservationFactory;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.io.TempDir;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-OPMUL")
@Tag("F-OPMUL-J003")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FOpmulJ003JourneyTest {

    // The course lives on disk and goes through the real FileSystemCourseRepository every time: a
    // knowledge with a CLOZE and its multiple-choice sibling, modeled on two quizzes of the
    // 2026-09-29 backup, each carrying data the system does not interpret (production's backup
    // fields and the MC's copy of its old CLOZE form). approve and repair are the real services;
    // only the stores of proposals and plans are faked. A no-op validator: F-COURSE's structural
    // rules are not what this journey exercises.

    private static final CourseValidator NO_OP_VALIDATOR = course -> { };

    private static final String PLAN_ID = "plan-opmul-j003";
    private static final String AUDIT_ID = "audit-opmul-j003";
    private static final String KNOWLEDGE_ID = "400000000000000000000031";
    private static final String CLOZE_ID = "500000000000000000000031";
    private static final String MC_ID = "500000000000000000000032";

    private final FileSystemCourseRepository repository = new FileSystemCourseRepository(NO_OP_VALIDATOR);

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El usuario opera sobre un curso con M... → Cada archivo del curso queda identico... [Lo carga y lo guarda sin cambios] → success")
    public void path1_loCargaYLoGuardaSinCambios_success(@TempDir Path work) throws IOException {
        // Step: operar -- a course with MC and data not interpreted, written as the system writes it.
        Path original = work.resolve("original");
        repository.save(course(), original);

        Path resaved = work.resolve("resaved");
        repository.save(repository.load(original), resaved);

        // Step: identico (gate F-OPMUL-R001) -- every file, byte for byte.
        List<Path> files = files(original);
        assertTrue(files.size() >= 5, "the course is written as a whole tree: " + files);
        for (Path file : files) {
            Path relative = original.relativize(file);
            assertArrayEquals(Files.readAllBytes(file), Files.readAllBytes(resaved.resolve(relative.toString())),
                    "R001: byte difference in " + relative);
        }
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El usuario opera sobre un curso con M... → El CLOZE revisado conserva sus datos ... [Aprueba la correccion de un CLOZE, o de la etiqueta de su knowledge, que tiene un hermano MC] → success")
    public void path2_apruebaLaCorreccionDeUnCLOZEODeLaEtiquetaDeSuKnowledgeQueTieneUnHermanoMC_success(
            @TempDir Path courseDir) {
        // Step: operar -- the course on disk and a pending lexical correction of the CLOZE, derived
        // by the real deriver.
        repository.save(course(), courseDir);
        CourseEntity loaded = repository.load(courseDir);
        QuizTemplateEntity clozeBefore = quiz(loaded, CLOZE_ID);
        QuizTemplateEntity siblingBefore = quiz(loaded, MC_ID);
        CourseElementSnapshot clozeSnapshot = new CourseElementSnapshot(AuditTarget.QUIZ, CLOZE_ID, clozeBefore, null);
        CourseElementSnapshot correctedCloze = new DefaultLemmaAbsenceProposalDeriver(DefaultQuizSentenceConverter.create())
                .derive(clozeSnapshot, new LemmaAbsenceQuizCandidate("It ____ [was] hot inside.", "Hacia calor adentro."),
                        SentenceMode.FILL);
        RevisionProposal clozeProposal = new RevisionProposal("p-cloze", "t-cloze", PLAN_ID, AUDIT_ID,
                DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, CLOZE_ID, clozeSnapshot, correctedCloze,
                "lexical correction", "lemma-absence-llm", Instant.now(), null, null, null);

        RevisionArtifactStore artifactStore = mock(RevisionArtifactStore.class);
        when(artifactStore.findByProposalId(eq("p-cloze"), any())).thenReturn(Optional.of(pending(clozeProposal)));
        when(artifactStore.save(any())).thenReturn("revisions/" + PLAN_ID);
        ProposalDecisionService decisions = decisionService(artifactStore);

        // Step: nada_se_pierde (gate F-OPMUL-R002) -- first the CLOZE correction.
        assertEquals(ProposalDecisionOutcomeKind.APPROVED_APPLIED,
                decisions.approve("p-cloze", Optional.of(PLAN_ID), Optional.empty(), courseDir).getKind());
        CourseEntity afterCloze = repository.load(courseDir);
        QuizTemplateEntity revisedCloze = quiz(afterCloze, CLOZE_ID);
        assertEquals(List.of("It was hot inside."), revisedCloze.getSentences(), "the correction is applied");
        assertEquals(clozeBefore.getUnmodeledFields(), revisedCloze.getUnmodeledFields(),
                "R002: the corrected CLOZE keeps the quiz data the system does not interpret");
        assertEquals(clozeBefore.getForm().getUnmodeledFields(), revisedCloze.getForm().getUnmodeledFields(),
                "R002: the corrected CLOZE keeps the form data the system does not interpret");
        assertEquals(siblingBefore, quiz(afterCloze, MC_ID),
                "R002: the multiple-choice sibling stays identical, options included");

        // Then a correction of the knowledge label: the sibling changes its title and nothing else.
        KnowledgeEntity labelBefore = knowledge(repository.load(courseDir));
        KnowledgeEntity labelAfter = knowledge(repository.load(courseDir));
        labelAfter.setLabel("Todas las formas de be");
        RevisionProposal labelProposal = new RevisionProposal("p-label", "t-label", PLAN_ID, AUDIT_ID,
                DiagnosisKind.KNOWLEDGE_TITLE_LENGTH, AuditTarget.KNOWLEDGE, KNOWLEDGE_ID,
                new CourseElementSnapshot(AuditTarget.KNOWLEDGE, KNOWLEDGE_ID, null, labelBefore),
                new CourseElementSnapshot(AuditTarget.KNOWLEDGE, KNOWLEDGE_ID, null, labelAfter),
                "shorter label", "knowledge-title-agent", Instant.now(), null, null, null);
        when(artifactStore.findByProposalId(eq("p-label"), any())).thenReturn(Optional.of(pending(labelProposal)));
        assertEquals(ProposalDecisionOutcomeKind.APPROVED_APPLIED,
                decisions.approve("p-label", Optional.of(PLAN_ID), Optional.empty(), courseDir).getKind());
        CourseEntity afterLabel = repository.load(courseDir);
        QuizTemplateEntity expectedSibling = QuizTemplateEntities.copyOf(siblingBefore);
        expectedSibling.setTitle("Todas las formas de be");
        assertEquals(expectedSibling, quiz(afterLabel, MC_ID),
                "R002 (F-RPRES-R004): the multiple-choice sibling only changes its title");
        assertEquals(revisedCloze.getUnmodeledFields(), quiz(afterLabel, CLOZE_ID).getUnmodeledFields(),
                "R002: aligning the titles keeps the CLOZE's data the system does not interpret");
    }

    @Test
    @Order(3)
    @Tag("path-3")
    @DisplayName("path-3: El usuario opera sobre un curso con M... → repair no repara el MC: sigue siendo ... [Repara el curso y un MC tiene una foto de cuando era CLOZE] → success")
    public void path3_reparaElCursoYUnMCTieneUnaFotoDeCuandoEraCLOZE_success(@TempDir Path courseDir)
            throws IOException {
        // Step: operar -- an approved revision recorded the MC when it was still a CLOZE.
        repository.save(course(), courseDir);
        byte[] quizzesBefore = Files.readAllBytes(quizzesFile(courseDir));
        CourseEntity loaded = repository.load(courseDir);
        QuizTemplateEntity multipleChoice = quiz(loaded, MC_ID);
        QuizTemplateEntity untouched = QuizTemplateEntities.copyOf(multipleChoice);
        QuizTemplateEntity clozeEra = QuizTemplateEntities.copyOf(multipleChoice);
        clozeEra.setKind("CLOZE");
        clozeEra.setForm(new FormEntity("CLOZE", 1.0, "", "", List.of(
                text("They usually eat pizza"), cloze("at|on"), text("the weekend.")), null, null));
        clozeEra.setUnmodeledFields(null);

        RepairReport report = new DefaultPreservationFactory()
                .createRepair(storeWithApprovedSnapshot(MC_ID, clozeEra))
                .repair(loaded);
        repository.save(report.getCourse(), courseDir);

        // Step: mc_intacto (gate F-OPMUL-R007) -- nothing repaired: still multiple choice, with its
        // options and its data, and the file on disk exactly as it was.
        assertEquals(0, report.getElementsRepaired(), "R007: repair restores nothing from a CLOZE-era snapshot");
        assertEquals(untouched, quiz(repository.load(courseDir), MC_ID),
                "R007: the quiz stays multiple choice, with its options and its data");
        assertArrayEquals(quizzesBefore, Files.readAllBytes(quizzesFile(courseDir)),
                "R007: the exercise stays exactly as it was");
    }

    @Test
    @Order(4)
    @Tag("path-4")
    @DisplayName("path-4: El usuario opera sobre un curso con M... → repair no borra esos datos: el CLOZE ... [Repara el curso y un CLOZE tiene datos no interpretados que su foto no conocia] → success")
    public void path4_reparaElCursoYUnCLOZETieneDatosNoInterpretadosQueSuFotoNoConocia_success(
            @TempDir Path courseDir) {
        // Step: operar -- the CLOZE lost the name of its form (a degradation repair must undo) and
        // carries data the system does not interpret; its snapshot predates that data.
        CourseEntity course = course();
        quiz(course, CLOZE_ID).getForm().setName(null);
        repository.save(course, courseDir);
        CourseEntity loaded = repository.load(courseDir);
        QuizTemplateEntity cloze = quiz(loaded, CLOZE_ID);
        Map<String, Object> quizData = cloze.getUnmodeledFields();
        Map<String, Object> formData = cloze.getForm().getUnmodeledFields();
        QuizTemplateEntity snapshot = QuizTemplateEntities.copyOf(cloze);
        snapshot.setForm(new FormEntity("CLOZE", 1.0, "", "", cloze.getForm().getSentenceParts(), null, null));
        snapshot.setUnmodeledFields(null);

        RepairReport report = new DefaultPreservationFactory()
                .createRepair(storeWithApprovedSnapshot(CLOZE_ID, snapshot))
                .repair(loaded);
        repository.save(report.getCourse(), courseDir);

        // Step: datos_intactos (gate F-OPMUL-R008) -- the degradation is undone, the data stays.
        List<String> restored = report.getRestored().stream().map(PreservationViolation::getPath).toList();
        assertEquals(List.of("form.name"), restored, "repair restores what the snapshot knew and today lacks");
        QuizTemplateEntity repaired = quiz(repository.load(courseDir), CLOZE_ID);
        assertEquals("", repaired.getForm().getName());
        assertEquals(quizData, repaired.getUnmodeledFields(),
                "R008: repair keeps the quiz data its snapshot did not know");
        assertEquals(formData, repaired.getForm().getUnmodeledFields(),
                "R008: repair keeps the form data its snapshot did not know");
    }

    // ---------------------------------------------------------------------------------------------
    // Services and stores
    // ---------------------------------------------------------------------------------------------

    private ProposalDecisionService decisionService(RevisionArtifactStore artifactStore) {
        RefinementPlanStore planStore = mock(RefinementPlanStore.class);
        when(planStore.load(PLAN_ID)).thenReturn(Optional.of(new RefinementPlan(PLAN_ID, AUDIT_ID, Instant.now(),
                List.of(new RefinementTask("t-cloze", AuditTarget.QUIZ, CLOZE_ID, "Be", DiagnosisKind.LEMMA_ABSENCE,
                                1, RefinementTaskStatus.PENDING),
                        new RefinementTask("t-label", AuditTarget.KNOWLEDGE, KNOWLEDGE_ID, "Be",
                                DiagnosisKind.KNOWLEDGE_TITLE_LENGTH, 1, RefinementTaskStatus.PENDING)))));
        RevisionEngineConfig config = new RevisionEngineConfig();
        config.setArtifactStore(artifactStore);
        config.setCourseRepository(repository);
        config.setRefinementPlanStore(planStore);
        return new DefaultProposalDecisionServiceFactory().create(config);
    }

    private static RevisionArtifact pending(RevisionProposal proposal) {
        return new RevisionArtifact(proposal, RevisionVerdict.PENDING_APPROVAL, null,
                RevisionOutcomeKind.PENDING_APPROVAL_PERSISTED, null, null, null, null);
    }

    /** A store holding one approved lexical revision of {@code quizId}, which recorded {@code snapshot}. */
    private static RevisionArtifactStore storeWithApprovedSnapshot(String quizId, QuizTemplateEntity snapshot) {
        CourseElementSnapshot before = new CourseElementSnapshot(AuditTarget.QUIZ, quizId, snapshot, null);
        RevisionProposal proposal = new RevisionProposal("p-old", "t-old", "plan-old", "audit-old",
                DiagnosisKind.LEMMA_ABSENCE, AuditTarget.QUIZ, quizId, before, before, "old correction",
                "lemma-absence-llm", Instant.parse("2026-08-01T00:00:00Z"), null, null, null);
        RevisionArtifactStore store = mock(RevisionArtifactStore.class);
        when(store.list()).thenReturn(List.of(new RevisionArtifact(proposal, RevisionVerdict.APPROVED, null,
                RevisionOutcomeKind.APPROVED_APPLIED, Instant.parse("2026-08-01T00:05:00Z"), null, null, null)));
        return store;
    }

    // ---------------------------------------------------------------------------------------------
    // The course
    // ---------------------------------------------------------------------------------------------

    private static CourseEntity course() {
        FormEntity clozeForm = new FormEntity("CLOZE", 1.0, "", "",
                List.of(text("It"), cloze("is|'s"), text("hot inside.")), null, null);
        clozeForm.setUnmodeledFields(new LinkedHashMap<>(Map.of("hint", "(be)")));
        QuizTemplateEntity clozeQuiz = baseQuiz(CLOZE_ID, "CLOZE", clozeForm, "Hace calor adentro.",
                List.of("It is hot inside.", "It 's hot inside."));
        Map<String, Object> clozeData = new LinkedHashMap<>();
        clozeData.put("instructionsAntesDeShortForms", "Escribe oraciones en presente simple.");
        clozeData.put("miniTheoryAntesDeShortForms", "Elige am, is o are segun el sujeto.");
        clozeQuiz.setUnmodeledFields(clozeData);

        FormEntity mcForm = new FormEntity("MULTIPLE_CHOICE", 1.0, "", "",
                List.of(text("They usually eat pizza"), gap(), text("the weekend.")),
                new MultipleChoiceEntity("SINGLE", List.of(
                        new MultipleChoiceItemEntity("-", 0.0, "-"),
                        new MultipleChoiceItemEntity("at", 1.0, "at"),
                        new MultipleChoiceItemEntity("in", 0.0, "in"))), null);
        QuizTemplateEntity mcQuiz = baseQuiz(MC_ID, "MULTIPLE_CHOICE", mcForm, "Suelen comer pizza el fin de semana.",
                List.of("They usually eat pizza at the weekend."));
        Map<String, Object> formCloze = new LinkedHashMap<>();
        formCloze.put("kind", "CLOZE");
        formCloze.put("incidence", Map.of("$numberDouble", "1.0"));
        formCloze.put("label", "");
        formCloze.put("name", "");
        formCloze.put("sentenceParts", List.of(
                part("TEXT", "They usually eat pizza", null),
                part("CLOZE", "", List.of("at|on")),
                part("TEXT", "the weekend.", null)));
        Map<String, Object> mcData = new LinkedHashMap<>();
        mcData.put("formCloze", formCloze);
        mcData.put("instructionsAnteriores", "Elegi 'in', 'on' o 'at'.");
        mcData.put("instructionsAntesDeRevisar", "Elige 'in', 'on' o 'at'.");
        mcQuiz.setUnmodeledFields(mcData);

        KnowledgeEntity knowledge = new KnowledgeEntity();
        knowledge.setId(KNOWLEDGE_ID);
        knowledge.setCode(KNOWLEDGE_ID);
        knowledge.setKind(NodeKind.KNOWLEDGE);
        knowledge.setLabel("Todas las formas");
        knowledge.setOldId("55555555-5555-5555-5555-555555555555");
        knowledge.setParentId("300000000000000000000031");
        knowledge.setIsRule(true);
        knowledge.setInstructions("Usa short forms si es posible.");
        knowledge.setOrder(1);
        knowledge.setSlug("todas-las-formas");
        knowledge.setQuizTemplates(new ArrayList<>(List.of(clozeQuiz, mcQuiz)));

        TopicEntity topic = new TopicEntity();
        topic.setId("300000000000000000000031");
        topic.setCode("300000000000000000000031");
        topic.setKind(NodeKind.TOPIC);
        topic.setLabel("Present Simple");
        topic.setOldId("33333333-3333-3333-3333-333333333333");
        topic.setParentId("200000000000000000000031");
        topic.setRuleIds(List.of(KNOWLEDGE_ID));
        topic.setOrder(1);
        topic.setSlug("present-simple");
        topic.setKnowledges(List.of(knowledge));

        MilestoneEntity milestone = new MilestoneEntity();
        milestone.setId("200000000000000000000031");
        milestone.setCode("200000000000000000000031");
        milestone.setKind(NodeKind.MILESTONE);
        milestone.setLabel("A1");
        milestone.setOldId("11111111-1111-1111-1111-111111111111");
        milestone.setParentId("100000000000000000000031");
        milestone.setChildren(List.of("300000000000000000000031"));
        milestone.setOrder(1);
        milestone.setSlug("a1");
        milestone.setTopics(List.of(topic));

        RootNodeEntity root = new RootNodeEntity();
        root.setId("100000000000000000000031");
        root.setCode("root");
        root.setKind(NodeKind.ROOT);
        root.setChildren(List.of("200000000000000000000031"));
        root.setMilestones(List.of(milestone));

        CourseEntity course = new CourseEntity();
        course.setId("000000000000000000000031");
        course.setTitle("english-course");
        course.setKnowledgeIds(List.of(KNOWLEDGE_ID));
        course.setRoot(root);
        course.setSlug("english-course");
        return course;
    }

    private static QuizTemplateEntity baseQuiz(String id, String kind, FormEntity form, String translation,
            List<String> sentences) {
        QuizTemplateEntity quiz = new QuizTemplateEntity();
        quiz.setId(id);
        quiz.setOidId(id);
        quiz.setKind(kind);
        quiz.setKnowledgeId(KNOWLEDGE_ID);
        quiz.setTitle("Todas las formas");
        quiz.setInstructions("Usa short forms si es posible.");
        quiz.setTranslation(translation);
        quiz.setTheoryId("a1.01.Present_Simple");
        quiz.setTopicName("Present Simple");
        quiz.setForm(form);
        quiz.setDifficulty(0.0);
        quiz.setRetries(0.0);
        quiz.setNoScoreRetries(0.0);
        quiz.setCode("");
        quiz.setAudioUrl("");
        quiz.setImageUrl("");
        quiz.setAnswerAudioUrl("A1.01.17.07");
        quiz.setAnswerImageUrl("");
        quiz.setMiniTheory("");
        quiz.setSuccessMessage("");
        quiz.setSentences(sentences);
        return quiz;
    }

    private static SentencePartEntity text(String text) {
        return new SentencePartEntity(SentencePartKind.TEXT, text, null);
    }

    private static SentencePartEntity cloze(String answer) {
        return new SentencePartEntity(SentencePartKind.CLOZE, "", List.of(answer));
    }

    private static SentencePartEntity gap() {
        return new SentencePartEntity(SentencePartKind.CLOZE, "", null);
    }

    /** A sentence part as production keeps it inside a backup form: a plain map. */
    private static Map<String, Object> part(String kind, String text, List<String> options) {
        Map<String, Object> part = new LinkedHashMap<>();
        part.put("kind", kind);
        part.put("text", text);
        part.put("options", options);
        return part;
    }

    private static KnowledgeEntity knowledge(CourseEntity course) {
        return course.getRoot().getMilestones().get(0).getTopics().get(0).getKnowledges().get(0);
    }

    private static QuizTemplateEntity quiz(CourseEntity course, String quizId) {
        return knowledge(course).getQuizTemplates().stream().filter(q -> quizId.equals(q.getId()))
                .findFirst().orElseThrow();
    }

    private static Path quizzesFile(Path courseDir) throws IOException {
        try (Stream<Path> paths = Files.walk(courseDir)) {
            return paths.filter(p -> p.getFileName().toString().equals("quizzes.json")).findFirst().orElseThrow();
        }
    }

    private static List<Path> files(Path root) throws IOException {
        try (Stream<Path> paths = Files.walk(root)) {
            return paths.filter(Files::isRegularFile).sorted().toList();
        }
    }
}
