package com.learney.contentaudit.journeys;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableKnowledge;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.AuditableTopic;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.DefaultKnowledgeDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultTopicDiagnoses;
import com.learney.contentaudit.auditdomain.SentenceLengthDiagnosis;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.LemmaPlacementDiagnosis;
import com.learney.contentaudit.auditdomain.labs.MisplacedLemma;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.LemmaAbsenceContextResolver;
import com.learney.contentaudit.refinerdomain.LengthDirection;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-RCLALEN")
@Tag("F-RCLALEN-J002")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FRclalenJ002JourneyTest {

    // -----------------------------------------------------------------------
    // Tree builder helpers
    // -----------------------------------------------------------------------

    private AuditNode buildCourseNode() {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.COURSE);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        return node;
    }

    private AuditNode buildMilestoneNode(AuditNode parent, AuditableMilestone milestone,
            DefaultLevelDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.MILESTONE);
        node.setEntity(milestone);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildTopicNode(AuditNode parent, AuditableTopic topic) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.TOPIC);
        node.setEntity(topic);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(new DefaultTopicDiagnoses());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildKnowledgeNode(AuditNode parent, AuditableKnowledge knowledge) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.KNOWLEDGE);
        node.setEntity(knowledge);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(new DefaultKnowledgeDiagnoses());
        parent.getChildren().add(node);
        return node;
    }

    private AuditNode buildQuizNode(AuditNode parent, AuditableQuiz quiz,
            DefaultQuizDiagnoses diagnoses) {
        AuditNode node = new AuditNode();
        node.setTarget(AuditTarget.QUIZ);
        node.setEntity(quiz);
        node.setParent(parent);
        node.setChildren(new ArrayList<>());
        node.setScores(new LinkedHashMap<>());
        node.setMetadata(new LinkedHashMap<>());
        node.setDiagnoses(diagnoses);
        parent.getChildren().add(node);
        return node;
    }

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El usuario obtiene una tarea LEMMA_AB... → El sistema construye el contexto base... → El sistema deriva lengthDirection del... → El comando muestra el contexto enriqu... → success")
    public void path1_success() {
        // -----------------------------------------------------------------------
        // Step: solicitar_tarea
        // User obtains a LEMMA_ABSENCE task for a quiz whose sentence is already
        // within the expected token range for its CEFR level (A1: 5-8).
        // Concrete values: 6 tokens, range 5-8, so delta = 0.
        // -----------------------------------------------------------------------
        RefinementTask task = new RefinementTask(
                "task-j002-001", AuditTarget.QUIZ, "quiz-within-range-001",
                "Quiz 1 - L1.T1.K1",
                DiagnosisKind.LEMMA_ABSENCE, 1, RefinementTaskStatus.PENDING);

        // -----------------------------------------------------------------------
        // Step: construir_y_enriquecer (gate F-RCLALEN-R001, F-RCLALEN-R003)
        // Build the audit tree: the quiz has a SentenceLengthDiagnosis with
        // tokenCount=6, targetMin=5, targetMax=8, delta=0 (within range).
        // The same quiz node also carries a LemmaPlacementDiagnosis so that the
        // LEMMA_ABSENCE context resolver can proceed (F-RCLA-R005).
        // -----------------------------------------------------------------------
        // Quiz entity: A1-level sentence with 6 tokens (within 5-8 range)
        AuditableQuiz quiz = new AuditableQuiz(
                List.of(), "quiz-within-range-001", "Quiz 1", "Q001",
                "Ella va al mercado hoy",
                List.of("She goes to the market today"),
                null);

        AuditableKnowledge knowledge = new AuditableKnowledge(
                List.of(), "Affirmative sentences in the present simple",
                "Escribe la forma afirmativa", true,
                "knowledge-j002-001", "Knowledge 1", "K001");

        AuditableTopic topic = new AuditableTopic(
                List.of(), "topic-j002-001", "Present Simple", "T001");

        AuditableMilestone milestone = new AuditableMilestone(
                List.of(), "ms-a1-j002-001", "A1", "M001");

        // SentenceLengthDiagnosis: tokenCount=6, range=[5,8], delta=0 (within range).
        // Gate F-RCLALEN-R003: read from the same quiz node used for LemmaPlacementDiagnosis.
        SentenceLengthDiagnosis slDiagnosis = new SentenceLengthDiagnosis(
                6, 5, 8, CefrLevel.A1, 0, 4);

        // LemmaPlacementDiagnosis: "want" (B1) misplaced in A1 quiz.
        MisplacedLemma misplaced = new MisplacedLemma(
                new LemmaAndPos("want", "VERB"),
                CefrLevel.B1, CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE,
                890, null);

        DefaultQuizDiagnoses quizDiagnoses = new DefaultQuizDiagnoses();
        quizDiagnoses.setSentenceLengthDiagnosis(slDiagnosis);
        quizDiagnoses.setLemmaAbsenceDiagnosis(new LemmaPlacementDiagnosis(1, List.of(misplaced)));

        // Milestone carries an absent-lemma diagnosis so suggested lemmas can be sourced.
        AbsentLemma absentLemma = new AbsentLemma(
                new LemmaAndPos("go", "VERB"),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                List.of(),
                PriorityLevel.HIGH,
                120,
                null);
        LemmaAbsenceLevelDiagnosis absenceDiagnosis = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A1, 100, 1, 1.0, 90.0,
                0.8, 0.0, 0.0, null, List.of(absentLemma), List.of(), 1, 0, 0);
        DefaultLevelDiagnoses milestoneDiagnoses = new DefaultLevelDiagnoses();
        milestoneDiagnoses.setLemmaAbsenceDiagnosis(absenceDiagnosis);

        // Build tree: COURSE → MILESTONE → TOPIC → KNOWLEDGE → QUIZ
        AuditNode courseRoot = buildCourseNode();
        AuditNode milestoneNode = buildMilestoneNode(courseRoot, milestone, milestoneDiagnoses);
        AuditNode topicNode = buildTopicNode(milestoneNode, topic);
        AuditNode knowledgeNode = buildKnowledgeNode(topicNode, knowledge);
        buildQuizNode(knowledgeNode, quiz, quizDiagnoses);

        AuditReport report = new AuditReport(courseRoot);

        // -----------------------------------------------------------------------
        // Step: derivar_direccion (gate F-RCLALEN-R002)
        // Resolver reads SentenceLengthDiagnosis and derives lengthDirection from delta.
        // delta == 0 → KEEP_SAME.
        // -----------------------------------------------------------------------
        LemmaAbsenceContextResolver resolver = new LemmaAbsenceContextResolver();
        Optional<LemmaAbsenceCorrectionContext> result = resolver.resolve(report, task);

        // Context must be present (resolver found LemmaPlacementDiagnosis on the quiz node).
        assertTrue(result.isPresent(),
                "Context must be present when LemmaPlacementDiagnosis exists on the quiz node");
        LemmaAbsenceCorrectionContext context = result.get();

        // Gate F-RCLALEN-R001: length fields are populated from SentenceLengthDiagnosis.
        assertEquals(Integer.valueOf(6), context.getTokenCount(),
                "tokenCount must be 6 (copied from SentenceLengthDiagnosis per R001)");
        assertEquals(Integer.valueOf(5), context.getTargetMin(),
                "targetMin must be 5 (A1 range lower bound per R001)");
        assertEquals(Integer.valueOf(8), context.getTargetMax(),
                "targetMax must be 8 (A1 range upper bound per R001)");
        assertEquals(Integer.valueOf(0), context.getDelta(),
                "delta must be 0 (sentence is within range per R001)");

        // Gate F-RCLALEN-R002: lengthDirection derived from delta == 0 → KEEP_SAME.
        assertNotNull(context.getLengthDirection(),
                "lengthDirection must never be null (R002 guarantees a non-null enum value)");
        assertEquals(LengthDirection.KEEP_SAME, context.getLengthDirection(),
                "lengthDirection must be KEEP_SAME when delta == 0 (per R002)");

        // -----------------------------------------------------------------------
        // Step: presentar_contexto (gate F-RCLALEN-R005, F-RCLALEN-R006)
        // The context now carries all fields needed for the JSON serialization (R005)
        // and the CLI Length line (R006).
        //
        // R005: tokenCount, targetMin, targetMax, delta and lengthDirection are present
        //       and will be serialized by the formatter as:
        //         "tokenCount": 6, "targetRange": {"min": 5, "max": 8},
        //         "delta": 0, "lengthDirection": "KEEP_SAME"
        //
        // R006: the CLI Length line must render as:
        //         "6 tokens (target: 5-8, delta: 0, direction: KEEP_SAME)"
        //       Verified by composing the expected string from the context fields.
        // -----------------------------------------------------------------------

        // R005 — verify every JSON-serializable field is non-null and carries the expected value.
        assertNotNull(context.getTokenCount(), "R005: tokenCount must be present (not omitted)");
        assertNotNull(context.getTargetMin(), "R005: targetMin (targetRange.min) must be present");
        assertNotNull(context.getTargetMax(), "R005: targetMax (targetRange.max) must be present");
        assertNotNull(context.getDelta(), "R005: delta must be present");
        assertNotNull(context.getLengthDirection(), "R005: lengthDirection must be present");
        assertEquals(LengthDirection.KEEP_SAME, context.getLengthDirection(),
                "R005: lengthDirection serializes as 'KEEP_SAME' (not UNKNOWN — diagnosis is available)");

        // R006 — compose the CLI Length line from context fields and verify it matches
        //         the expected format: "6 tokens (target: 5-8, delta: 0, direction: KEEP_SAME)"
        int tokenCount = context.getTokenCount();
        int targetMin = context.getTargetMin();
        int targetMax = context.getTargetMax();
        int delta = context.getDelta();
        String direction = context.getLengthDirection().name();
        // Delta format: positive → "+N", zero → "0", negative → "-N" (F-RCLALEN-R006)
        String deltaStr = delta > 0 ? "+" + delta : String.valueOf(delta);
        String lengthLine = tokenCount + " tokens (target: " + targetMin + "-" + targetMax
                + ", delta: " + deltaStr + ", direction: " + direction + ")";

        assertEquals("6 tokens (target: 5-8, delta: 0, direction: KEEP_SAME)", lengthLine,
                "R006: Length line must match the expected format for the KEEP_SAME case");

        // Base LEMMA_ABSENCE context fields must also be populated (F-RCLA-R003).
        assertEquals("She goes to the market today", context.getSentence());
        assertEquals("Ella va al mercado hoy", context.getTranslation());
        assertEquals("Affirmative sentences in the present simple", context.getKnowledgeTitle());
        assertEquals("Present Simple", context.getTopicLabel());
        assertEquals(CefrLevel.A1, context.getCefrLevel());
    }
}
