package com.learney.contentaudit.agentruntimeinfrastructure;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface AgentDefinitionLocator {
    AgentDefinitionLocation locate(String agentName);

    AgentDefinitionLocation locateUnderProjectRoot(String projectRoot, String agentName);
}
