package com.learney.contentaudit.quizinstructioninfrastructure;

import com.learney.contentaudit.agentruntimeinfrastructure.AgentDefinitionLocator;
import com.learney.contentaudit.agentruntimeinfrastructure.AgentGraphRunner;
import com.learney.contentaudit.evaluationledgerdomain.Evaluator;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface QuizInstructionJudgeFactory {
    Evaluator create(QuizInstructionJudgeConfig config, AgentGraphRunner agentGraphRunner,
            AgentDefinitionLocator agentDefinitionLocator);
}
