package com.learney.contentaudit.auditdomain.journeys;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultQuizDiagnoses;
import com.learney.contentaudit.auditdomain.LevelDiagnoses;
import com.learney.contentaudit.auditdomain.QuizDiagnoses;
import com.learney.contentaudit.auditdomain.labs.AbsenceAssessment;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.LemmaPlacementDiagnosis;
import com.learney.contentaudit.auditdomain.labs.MisplacedLemma;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-DLABS")
@Tag("F-DLABS-J002")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FDlabsJ002JourneyTest {
    @Test
    @Order(1)
    @Tag("path-1")
    @Tag("F-DLABS-R003")
    @Tag("F-DLABS-R005")
    @Tag("F-DLABS-R009")
    @Tag("F-DLABS-R011")
    @Tag("F-DLABS-R012")
    @DisplayName("path-1: El consumidor (por ejemplo, el futuro... → El consumidor solicita el nodo ancest... → El consumidor obtiene el LemmaAbsence... [El milestone ancestro existe] → El consumidor cruza los lemas mal ubi... → success")
    public void path1_elMilestoneAncestroExiste_success() {
        // Step 1: identificar_quiz_problematico
        // Gate: F-DLABS-R003, F-DLABS-R009
        // Build a quiz node with a LemmaPlacementDiagnosis containing a misplaced lemma
        MisplacedLemma misplacedLemma = new MisplacedLemma(
                new LemmaAndPos("run", "VERB"),
                CefrLevel.A1,
                CefrLevel.B1,
                AbsenceType.APPEARS_TOO_LATE,
                500,
                null
        );
        LemmaPlacementDiagnosis quizPlacementDiagnosis = new LemmaPlacementDiagnosis(
                1,
                List.of(misplacedLemma)
        );
        DefaultQuizDiagnoses quizDiagnoses = new DefaultQuizDiagnoses();
        quizDiagnoses.setLemmaAbsenceDiagnosis(quizPlacementDiagnosis);

        AuditableQuiz quizEntity = new AuditableQuiz(
                "She runs every day.", null, "quiz-001", "She runs every day.", "Q1", null
        );
        AuditNode quizNode = new AuditNode(quizEntity, AuditTarget.QUIZ, null,
                Collections.emptyList(), Collections.emptyMap(), Collections.emptyMap(),
                quizDiagnoses);

        // Verify the quiz placement diagnosis is accessible via typed access (R003 + R009)
        QuizDiagnoses quizNodeDiagnoses = (QuizDiagnoses) quizNode.getDiagnoses();
        Optional<LemmaPlacementDiagnosis> quizDiagnosisResult = quizNodeDiagnoses.getLemmaAbsenceDiagnosis();
        assertTrue(quizDiagnosisResult.isPresent(), "Quiz must expose LemmaPlacementDiagnosis (R009)");
        assertEquals(1, quizDiagnosisResult.get().getMisplacedLemmaCount(),
                "Misplaced lemma count must reflect the fixture (R009)");
        assertEquals("run", quizDiagnosisResult.get().getMisplacedLemmas().get(0).getLemmaAndPos().getLemma(),
                "Misplaced lemma must be accessible via typed fields (R003)");

        // Step 2: navegar_a_milestone
        // Gate: F-DLABS-R011
        // Build a milestone node with LemmaAbsenceLevelDiagnosis and set as parent of quiz
        AbsentLemma absentLemma = new AbsentLemma(
                new LemmaAndPos("walk", "VERB"),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                Collections.emptyList(),
                PriorityLevel.HIGH,
                300,
                null
        );
        LemmaAbsenceLevelDiagnosis levelDiagnosis = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A1,
                50,
                5,
                10.0,
                0.95,
                0.8,
                0.1,
                0.05,
                AbsenceAssessment.NEEDS_IMPROVEMENT,
                List.of(absentLemma),
                Collections.emptyList(),
                1,
                0,
                0
        );
        DefaultLevelDiagnoses levelDiagnosesObj = new DefaultLevelDiagnoses();
        levelDiagnosesObj.setLemmaAbsenceDiagnosis(levelDiagnosis);

        AuditNode milestoneNode = new AuditNode(null, AuditTarget.MILESTONE, null,
                List.of(quizNode), Collections.emptyMap(), Collections.emptyMap(),
                levelDiagnosesObj);
        quizNode.setParent(milestoneNode);

        // Navigate from quiz to milestone ancestor (R011)
        Optional<AuditNode> milestoneAncestor = quizNode.ancestor(AuditTarget.MILESTONE);
        assertTrue(milestoneAncestor.isPresent(), "Milestone ancestor must be found (R011)");

        // Step 3: obtener_diagnostico_nivel
        // Gate: F-DLABS-R003, F-DLABS-R005, F-DLABS-R012
        // Access LemmaAbsenceLevelDiagnosis from the navigated milestone node (R003 + R005 + R012)
        LevelDiagnoses milestoneDiagnoses = (LevelDiagnoses) milestoneAncestor.get().getDiagnoses();
        Optional<LemmaAbsenceLevelDiagnosis> levelDiagnosisResult = milestoneDiagnoses.getLemmaAbsenceDiagnosis();
        assertTrue(levelDiagnosisResult.isPresent(),
                "Milestone must expose LemmaAbsenceLevelDiagnosis (R005)");
        assertEquals(50, levelDiagnosisResult.get().getTotalExpected(),
                "Total expected lemmas must be accessible via typed fields (R003)");
        assertEquals(5, levelDiagnosisResult.get().getTotalAbsent(),
                "Total absent lemmas must be accessible via typed fields (R003)");
        assertEquals(AbsenceAssessment.NEEDS_IMPROVEMENT, levelDiagnosisResult.get().getAssessment(),
                "Assessment must be accessible via typed fields (R003)");

        // Step 4: cruzar_datos
        // Cross misplaced lemmas from quiz with absent lemmas from level to identify replacements (R012)
        String misplacedLemmaName = quizDiagnosisResult.get().getMisplacedLemmas().get(0).getLemmaAndPos().getLemma();
        String absentLemmaName = levelDiagnosisResult.get().getAbsentLemmas().get(0).getLemmaAndPos().getLemma();
        assertFalse(misplacedLemmaName.isEmpty(),
                "Misplaced lemma name must be accessible for cross-analysis (R012)");
        assertFalse(absentLemmaName.isEmpty(),
                "Absent lemma name must be accessible for cross-analysis (R012)");
        assertEquals("run", misplacedLemmaName, "Misplaced lemma from quiz must be 'run'");
        assertEquals("walk", absentLemmaName, "Absent lemma from milestone must be 'walk'");
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @Tag("F-DLABS-R011")
    @DisplayName("path-2: El consumidor (por ejemplo, el futuro... → El consumidor solicita el nodo ancest... → El sistema informa que no se pudo nav... [No se encuentra el milestone ancestro (estructura de arbol incompleta)] → failure")
    public void path2_noSeEncuentraElMilestoneAncestroEstructuraDeArbolIncompleta_failure() {
        // Step 1: identificar_quiz_problematico
        // Gate: F-DLABS-R003, F-DLABS-R009
        // Build a quiz node with a LemmaPlacementDiagnosis but NO milestone ancestor
        MisplacedLemma misplacedLemma = new MisplacedLemma(
                new LemmaAndPos("eat", "VERB"),
                CefrLevel.A1,
                CefrLevel.A2,
                AbsenceType.APPEARS_TOO_LATE,
                200,
                null
        );
        LemmaPlacementDiagnosis quizPlacementDiagnosis = new LemmaPlacementDiagnosis(
                1,
                List.of(misplacedLemma)
        );
        DefaultQuizDiagnoses quizDiagnoses = new DefaultQuizDiagnoses();
        quizDiagnoses.setLemmaAbsenceDiagnosis(quizPlacementDiagnosis);

        // Quiz node has no parent — the tree is incomplete, no milestone ancestor
        AuditableQuiz quizEntity = new AuditableQuiz(
                "She eats lunch.", null, "quiz-002", "She eats lunch.", "Q2", null
        );
        AuditNode quizNode = new AuditNode(quizEntity, AuditTarget.QUIZ, null,
                Collections.emptyList(), Collections.emptyMap(), Collections.emptyMap(),
                quizDiagnoses);

        // Step 2: navegar_a_milestone
        // Gate: F-DLABS-R011
        // Navigate from quiz to milestone ancestor — must return empty because tree is incomplete
        Optional<AuditNode> milestoneAncestor = quizNode.ancestor(AuditTarget.MILESTONE);

        // Step 3: error_navegacion
        // System informs that navigation to milestone ancestor failed (R011 — returns absence indication)
        assertFalse(milestoneAncestor.isPresent(),
                "Ancestor navigation must return empty when milestone ancestor is absent (R011)");
    }
}
