package com.learney.contentaudit.auditdomain.lemmacount;

import com.learney.contentaudit.auditdomain.AnalyzerDescriptor;
import com.learney.contentaudit.auditdomain.AnalyzerProvider;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.ContentAnalyzer;
import com.learney.contentaudit.auditdomain.EvaluationRunPolicy;
import com.learney.contentaudit.auditdomain.EvpCatalogPort;
import com.learney.contentaudit.auditdomain.LemmaCountConfig;
import com.learney.contentaudit.auditdomain.SelfDescribingConfig;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerFamily;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerPlanBinding;
import com.learney.contentaudit.auditdomain.catalog.AnalyzerRuleCard;
import com.learney.contentaudit.auditdomain.finding.AnalysisCost;
import com.learney.contentaudit.auditdomain.finding.FindingResolution;
import com.learney.contentaudit.auditdomain.lrec.DefaultContentWordFilter;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaCountAnalyzerProvider implements AnalyzerProvider {
    private final EvpCatalogPort evpCatalogPort;

    private final LemmaCountConfig lemmaCountConfig;

    public LemmaCountAnalyzerProvider(EvpCatalogPort evpCatalogPort,
            LemmaCountConfig lemmaCountConfig) {
        this.evpCatalogPort = evpCatalogPort;
        this.lemmaCountConfig = lemmaCountConfig;
    }

    @Override
    public String analyzerName() {
        return LemmaCountAnalyzer.ANALYZER_NAME;
    }

    @Override
    public AnalyzerDescriptor describe() {
        return new AnalyzerDescriptor(
                LemmaCountAnalyzer.ANALYZER_NAME,
                LemmaCountAnalyzer.DESCRIPTION,
                AuditTarget.COURSE,
                "¿Cada palabra aparece en suficientes oraciones?",
                "Las oraciones distintas en que aparece cada lema de contenido, con su nivel CEFR según el EVP",
                List.of(new AnalyzerRuleCard(LemmaCountAnalyzer.RULE_UNDER_EXPOSED,
                        "Hay lemas que aparecen en menos oraciones distintas que la meta",
                        AnalysisCost.INSTANT)),
                "Cada lema de contenido en al menos " + lemmaCountConfig.getThreshold() + " oraciones distintas",
                AnalyzerFamily.VOCABULARY,
                List.of(AuditTarget.MILESTONE, AuditTarget.COURSE),
                List.of(FindingResolution.RANK_ONLY),
                AnalysisCost.INSTANT);
    }

    @Override
    public ContentAnalyzer create(EvaluationRunPolicy policy) {
        return new LemmaCountAnalyzer(new DefaultContentWordFilter(),
                new EvpThenNlpLemmaCefrLevelResolver(evpCatalogPort), lemmaCountConfig);
    }

    /** lemma-count makes no tasks, as before the contract (F-HALL-R013). */
    @Override
    public Optional<AnalyzerPlanBinding> planBinding() {
        return Optional.empty();
    }

    @Override
    public Optional<SelfDescribingConfig> config() {
        return Optional.of(lemmaCountConfig);
    }
}
