package com.learney.contentaudit.auditdomain.lemmacount;

import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaCountResult {
    private int thresholdN;

    private Optional<Double> courseScore;

    private List<LevelLemmaCountResult> levels;

    private List<UnassignedLemmaEntry> unassigned;

    public LemmaCountResult() {
    }

    public LemmaCountResult(int thresholdN, Optional<Double> courseScore,
            List<LevelLemmaCountResult> levels, List<UnassignedLemmaEntry> unassigned) {
        this.thresholdN = thresholdN;
        this.courseScore = courseScore;
        this.levels = levels;
        this.unassigned = unassigned;
    }

    public int getThresholdN() {
        return this.thresholdN;
    }

    public void setThresholdN(int thresholdN) {
        this.thresholdN = thresholdN;
    }

    public Optional<Double> getCourseScore() {
        return this.courseScore;
    }

    public void setCourseScore(Optional<Double> courseScore) {
        this.courseScore = courseScore;
    }

    public List<LevelLemmaCountResult> getLevels() {
        return this.levels;
    }

    public void setLevels(List<LevelLemmaCountResult> levels) {
        this.levels = levels;
    }

    public List<UnassignedLemmaEntry> getUnassigned() {
        return this.unassigned;
    }

    public void setUnassigned(List<UnassignedLemmaEntry> unassigned) {
        this.unassigned = unassigned;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LemmaCountResult that = (LemmaCountResult) o;
        return Objects.equals(this.thresholdN, that.thresholdN)
                    && Objects.equals(this.courseScore, that.courseScore)
                    && Objects.equals(this.levels, that.levels)
                    && Objects.equals(this.unassigned, that.unassigned);
    }

    @Override
    public int hashCode() {
        return Objects.hash(thresholdN, courseScore, levels, unassigned);
    }
}
