package com.learney.contentaudit.auditdomain.lemmacount;

import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableMilestone;
import com.learney.contentaudit.auditdomain.AuditableQuiz;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.ContentAnalyzer;
import com.learney.contentaudit.auditdomain.ContentWordFilter;
import com.learney.contentaudit.auditdomain.DefaultCourseDiagnoses;
import com.learney.contentaudit.auditdomain.DefaultLevelDiagnoses;
import com.learney.contentaudit.auditdomain.LemmaCountConfig;
import com.learney.contentaudit.auditdomain.NlpToken;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaCountAnalyzer implements ContentAnalyzer {

    private static final String ANALYZER_NAME = "lemma-count";

    private final ContentWordFilter contentWordFilter;
    private final LemmaCefrLevelResolver lemmaCefrLevelResolver;
    private final LemmaCountConfig lemmaCountConfig;

    // lemma -> set of quiz IDs that contain it (R004: distinct sentences)
    private final Map<LemmaAndPos, Set<String>> lemmaQuizIds = new HashMap<>();

    public LemmaCountAnalyzer(ContentWordFilter contentWordFilter,
            LemmaCefrLevelResolver lemmaCefrLevelResolver, LemmaCountConfig lemmaCountConfig) {
        this.contentWordFilter = contentWordFilter;
        this.lemmaCefrLevelResolver = lemmaCefrLevelResolver;
        this.lemmaCountConfig = lemmaCountConfig;
    }

    @Override
    public Void onKnowledge(AuditNode node) {
        return null;
    }

    @Override
    public Void onQuiz(AuditNode node) {
        AuditableQuiz quiz = (AuditableQuiz) node.getEntity();
        if (quiz == null || quiz.getTokens() == null) {
            return null;
        }
        String quizId = quiz.getId();
        // Track distinct content-word lemmas seen in this quiz (R004: one sentence = one count)
        Set<LemmaAndPos> seenInThisQuiz = new HashSet<>();
        for (NlpToken token : quiz.getTokens()) {
            if (token == null || token.getLemma() == null || token.getLemma().isEmpty()) {
                continue;
            }
            if (!contentWordFilter.isContentWord(token)) {
                continue;
            }
            LemmaAndPos lp = new LemmaAndPos(token.getLemma(), token.getPosTag());
            seenInThisQuiz.add(lp);
        }
        // For each distinct lemma in this quiz, record this quiz ID (R004, R005)
        for (LemmaAndPos lp : seenInThisQuiz) {
            lemmaQuizIds.computeIfAbsent(lp, k -> new HashSet<>()).add(quizId);
        }
        return null;
    }

    @Override
    public Void onMilestone(AuditNode node) {
        return null;
    }

    @Override
    public Void onTopic(AuditNode node) {
        return null;
    }

    @Override
    public Void onCourseComplete(AuditNode rootNode) {
        int thresholdN = lemmaCountConfig.getThreshold();

        // Build LemmaCountStats for each lemma (R006, R009-R011)
        Map<CefrLevel, List<LemmaCountStats>> statsByLevel = new EnumMap<>(CefrLevel.class);
        List<UnassignedLemmaEntry> unassigned = new ArrayList<>();

        for (Map.Entry<LemmaAndPos, Set<String>> entry : lemmaQuizIds.entrySet()) {
            LemmaAndPos lp = entry.getKey();
            int count = entry.getValue().size();
            double score = Math.min((double) count / thresholdN, 1.0);
            Optional<CefrLevel> level = lemmaCefrLevelResolver.resolve(lp, Optional.empty());

            if (level.isPresent()) {
                LemmaCountStats stats = new LemmaCountStats(lp, count, score, level);
                statsByLevel.computeIfAbsent(level.get(), k -> new ArrayList<>()).add(stats);
            } else {
                // R011: no CEFR from any source -> unassigned group
                unassigned.add(new UnassignedLemmaEntry(lp, count));
            }
        }

        // Compute per-level results (R012)
        List<LevelLemmaCountResult> levelResults = new ArrayList<>();
        for (CefrLevel level : CefrLevel.values()) {
            List<LemmaCountStats> statsForLevel = statsByLevel.getOrDefault(level, Collections.emptyList());
            if (statsForLevel.isEmpty()) {
                continue;
            }
            double levelScore = statsForLevel.stream()
                    .mapToDouble(LemmaCountStats::getScore)
                    .average()
                    .orElse(0.0);

            List<LemmaCountStats> subExposed = new ArrayList<>();
            for (LemmaCountStats s : statsForLevel) {
                if (s.getScore() < 1.0) {
                    subExposed.add(s);
                }
            }
            // Sort sub-exposed by count ascending (most urgent first per R017)
            subExposed.sort(Comparator.comparingInt(LemmaCountStats::getCount));

            levelResults.add(new LevelLemmaCountResult(level, levelScore, statsForLevel.size(), subExposed));
        }

        // Compute course score (R013, R014)
        Optional<Double> courseScore = levelResults.isEmpty()
                ? Optional.empty()
                : Optional.of(levelResults.stream()
                        .mapToDouble(LevelLemmaCountResult::getScore)
                        .average()
                        .orElse(0.0));

        LemmaCountResult result = new LemmaCountResult(thresholdN, courseScore, levelResults, unassigned);

        // Write course-level score and diagnosis (R015)
        double scoreValue = courseScore.orElse(0.0);
        rootNode.getScores().put(ANALYZER_NAME, scoreValue);
        if (rootNode.getDiagnoses() instanceof DefaultCourseDiagnoses) {
            DefaultCourseDiagnoses cd = (DefaultCourseDiagnoses) rootNode.getDiagnoses();
            cd.setLemmaCountDiagnosis(new LemmaCountCourseDiagnosis(result));
        }

        // Write per-milestone (level) diagnosis (R017)
        List<AuditNode> milestoneNodes = rootNode.getChildren() != null
                ? rootNode.getChildren() : Collections.emptyList();
        for (LevelLemmaCountResult lvl : levelResults) {
            AuditNode milestoneNode = findMilestoneNodeForLevel(milestoneNodes, lvl.getLevel());
            if (milestoneNode != null) {
                milestoneNode.getScores().put(ANALYZER_NAME, lvl.getScore());
                if (milestoneNode.getDiagnoses() instanceof DefaultLevelDiagnoses) {
                    DefaultLevelDiagnoses ld = (DefaultLevelDiagnoses) milestoneNode.getDiagnoses();
                    ld.setLemmaCountDiagnosis(new LemmaCountLevelDiagnosis(lvl));
                }
            }
        }

        return null;
    }

    private AuditNode findMilestoneNodeForLevel(List<AuditNode> milestoneNodes, CefrLevel level) {
        for (AuditNode node : milestoneNodes) {
            if (node.getEntity() instanceof AuditableMilestone) {
                AuditableMilestone milestone = (AuditableMilestone) node.getEntity();
                try {
                    CefrLevel nodeLevel = CefrLevel.valueOf(milestone.getLabel());
                    if (level.equals(nodeLevel)) {
                        return node;
                    }
                } catch (IllegalArgumentException ignored) {
                }
            }
        }
        return null;
    }

    @Override
    public String getName() {
        return ANALYZER_NAME;
    }

    @Override
    public AuditTarget getTarget() {
        return AuditTarget.COURSE;
    }

    @Override
    public String getDescription() {
        return "Counts distinct sentences per content-word lemma and scores exposure by CEFR level";
    }
}
