package com.learney.contentaudit.agentruntimeinfrastructure.llmprovider;

import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LlmProviderRejected implements LlmProviderResolution {
    private String providerName;

    private String missingInput;

    private LlmProviderRejectionKind kind;

    public LlmProviderRejected() {
    }

    public LlmProviderRejected(String providerName, String missingInput,
            LlmProviderRejectionKind kind) {
        this.providerName = providerName;
        this.missingInput = missingInput;
        this.kind = kind;
    }

    public String getProviderName() {
        return this.providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public String getMissingInput() {
        return this.missingInput;
    }

    public void setMissingInput(String missingInput) {
        this.missingInput = missingInput;
    }

    public LlmProviderRejectionKind getKind() {
        return this.kind;
    }

    public void setKind(LlmProviderRejectionKind kind) {
        this.kind = kind;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LlmProviderRejected that = (LlmProviderRejected) o;
        return Objects.equals(this.providerName, that.providerName)
                    && Objects.equals(this.missingInput, that.missingInput)
                    && Objects.equals(this.kind, that.kind);
    }

    @Override
    public int hashCode() {
        return Objects.hash(providerName, missingInput, kind);
    }
}
