package com.learney.contentaudit.refinerdomain;

import com.learney.contentaudit.auditdomain.AuditReport;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface RefinerEngine {
    RefinementPlan plan(AuditReport report, String auditId);

    Optional<RefinementTask> nextTask(RefinementPlan plan);

    List<UnconvertedScoreCount> unconvertedScores(AuditReport report);
}
