package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessment;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessor;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriterionEvaluator;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateLengthMeasurement;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateLengthMeter;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateRanking;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.annotation.processing.Generated;

/**
 * F-QICOR-R004/R013/R014/R015: submits a candidate to the WHOLE registered
 * catalog -- no early return on the first non-PASSED verdict, unlike the
 * pre-F-QICOR-R012 design, because without every criterion's verdict there is
 * nothing to count or rank (R013 detail: "sin corte al primer no-PASSED no
 * habria como contar cuantos cumple"). Three conditions decide {@code
 * eligible} -- the gate for competing at all (F-QICOR-R016): {@link
 * CorrectionCriterion#INSTRUCTION_COMPLIANCE} (F-QICOR-R005, the first
 * absolute criterion), {@link CorrectionCriterion#REAL_WORLD_SENSE}
 * (F-QICOR-R016, the second absolute criterion), and whether the candidate is
 * a real change over the original (F-QICOR-R001/R010). {@link
 * CorrectionCriterion#LENGTH_IN_RANGE} never adds to {@code satisfiedCriteria}
 * and never appears in {@code unmetCriteria} (F-QICOR-R011); its structured
 * measurement travels on its own field instead. Neither {@code
 * INSTRUCTION_COMPLIANCE} nor {@code REAL_WORLD_SENSE} adds to {@code
 * satisfiedCriteria} either -- they are gates, not members of the "no
 * empeorar" catalog (F-QICOR-R004) nor of {@link CandidateRanking#precedence()}
 * (F-QICOR-R013: every candidate that competes satisfies both absolutes by
 * construction, so counting either would add the same unit to every
 * competitor and never break a tie) -- but each DOES appear in {@code
 * unmetCriteria} when it fails, since {@link
 * com.learney.contentaudit.revisiondomain.NoAcceptableCandidateException} and
 * the R006 "correccion no lograda" desenlace need to be able to name it as
 * the reason nothing was entregable. A {@code NOT_EVALUABLE} outcome on
 * either absolute counts exactly like {@code FAILED} for eligibility -- the
 * prudent reading is the same in both cases (R013): "could not verify" is
 * never treated as "passed by omission".
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultCandidateAssessor implements CandidateAssessor {

    // F-QICOR-R013: the five criteria that count towards satisfiedCriteria and that
    // CandidateRanking's precedence order breaks ties over. INSTRUCTION_COMPLIANCE gates
    // eligibility instead of adding to the count; LENGTH_IN_RANGE never adds either.
    private static final List<CorrectionCriterion> COUNTED_CATALOG = List.of(
            CorrectionCriterion.SCOPED_EDIT,
            CorrectionCriterion.LEVEL_VOCABULARY,
            CorrectionCriterion.DISTINCTNESS,
            CorrectionCriterion.FAITHFUL_TRANSLATION,
            CorrectionCriterion.SOLVABLE_SAME_KIND);

    private final Map<CorrectionCriterion, CandidateCriterionEvaluator> evaluatorsByCriterion;

    private final CandidateLengthMeter lengthMeter;

    private final CandidateRanking ranking;

    public DefaultCandidateAssessor(Map<CorrectionCriterion, CandidateCriterionEvaluator> evaluatorsByCriterion,
            CandidateLengthMeter lengthMeter, CandidateRanking ranking) {
        this.evaluatorsByCriterion = evaluatorsByCriterion;
        this.lengthMeter = lengthMeter;
        this.ranking = ranking;
    }

    @Override
    public CandidateAssessment assess(CandidateAssessmentInput input) {
        List<CriterionVerdict> verdicts = new ArrayList<>();
        for (CorrectionCriterion criterion : catalog()) {
            CandidateCriterionEvaluator evaluator = evaluatorsByCriterion.get(criterion);
            verdicts.add(evaluator.evaluate(input));
        }

        boolean instructionCompliant = false;
        boolean realWorldSenseCompliant = false;
        int satisfiedCriteria = 0;
        List<CriterionVerdict> unmetCriteria = new ArrayList<>();
        for (CriterionVerdict verdict : verdicts) {
            CorrectionCriterion criterion = verdict.getCriterion();
            boolean passed = verdict.getOutcome() == CriterionOutcome.PASSED;

            if (criterion == CorrectionCriterion.LENGTH_IN_RANGE) {
                // F-QICOR-R011: never counted, never declared among unmet criteria -- it has
                // its own declaration (lengthMeasurement below).
                continue;
            }
            if (criterion == CorrectionCriterion.INSTRUCTION_COMPLIANCE) {
                instructionCompliant = passed;
                if (!passed) {
                    unmetCriteria.add(verdict);
                }
                continue;
            }
            if (criterion == CorrectionCriterion.REAL_WORLD_SENSE) {
                // F-QICOR-R016: second absolute criterion, same slot pattern as
                // INSTRUCTION_COMPLIANCE above -- NOT_EVALUABLE counts as not-compliant (an
                // absolute never approves by omission), it never adds to satisfiedCriteria or
                // to CandidateRanking's precedence (every competing candidate satisfies it by
                // construction, so it could never break a tie), and it only lands in
                // unmetCriteria when this candidate turns out ineligible.
                realWorldSenseCompliant = passed;
                if (!passed) {
                    unmetCriteria.add(verdict);
                }
                continue;
            }

            if (COUNTED_CATALOG.contains(criterion) && passed) {
                satisfiedCriteria++;
            } else if (!passed) {
                unmetCriteria.add(verdict);
            }
        }

        boolean realChange = isRealChange(input);
        // F-QICOR-R001/R005/R010/R013/R016: only a candidate that complies with its
        // instruction, describes something that can happen in the real world, AND
        // constitutes a real change over the original competes at all.
        boolean eligible = instructionCompliant && realWorldSenseCompliant && realChange;

        CandidateLengthMeasurement lengthMeasurement = lengthMeter.measure(input);

        CandidateAssessment assessment = new CandidateAssessment(
                verdicts, eligible, realChange, satisfiedCriteria, unmetCriteria, lengthMeasurement, null);
        assessment.setRankKey(ranking.rankKey(assessment));
        return assessment;
    }

    @Override
    public List<CorrectionCriterion> catalog() {
        List<CorrectionCriterion> active = new ArrayList<>();
        if (evaluatorsByCriterion == null) {
            return active;
        }
        for (CorrectionCriterion criterion : CorrectionCriterion.values()) {
            if (evaluatorsByCriterion.containsKey(criterion)) {
                active.add(criterion);
            }
        }
        return active;
    }

    private boolean isRealChange(CandidateAssessmentInput input) {
        QuizTemplateEntity originalQuiz = quizOf(input.getOriginal());
        QuizTemplateEntity candidateQuiz = quizOf(input.getCandidate());
        return !Objects.equals(originalQuiz, candidateQuiz);
    }

    private QuizTemplateEntity quizOf(CourseElementSnapshot snapshot) {
        return snapshot != null ? snapshot.getQuiz() : null;
    }
}
