package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessor;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriteriaConfig;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriteriaDefaults;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriteriaFactory;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriterionEvaluator;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CourseQuizCorpus;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultCandidateCriteriaFactory implements CandidateCriteriaFactory {

    // DOUBT-DISTINCION-ALCANCE / DOUBT-PRESUPUESTO-CORRECCION-adjacent knobs: no rule
    // fixes an exact number, so these are the developer-chosen defaults, consistent
    // with the eval_distinct.sh precedent already in use for the lemma-absence
    // pipeline (difflib+Jaccard, 0.85). The course-wide comparison uses a stricter
    // threshold since it is meant to catch only gross, unmistakable coincidences.
    private static final CandidateCriteriaDefaults DEFAULTS =
            new CandidateCriteriaDefaults(0.85, 0.9, true);

    @Override
    public CandidateAssessor create(CandidateCriteriaConfig config) {
        Map<CorrectionCriterion, CandidateCriterionEvaluator> evaluators = new LinkedHashMap<>();

        evaluators.put(CorrectionCriterion.SCOPED_EDIT, new ScopedEditCriterion());
        evaluators.put(CorrectionCriterion.LENGTH_IN_RANGE,
                new LengthInRangeCriterion(config.getTokenizer(), config.getSentenceLengthConfig()));
        evaluators.put(CorrectionCriterion.LEVEL_VOCABULARY,
                new LevelVocabularyCriterion(config.getLexicalEvaluator(), config.getTokenizer()));

        double siblingSimilarityThreshold = config.getSiblingSimilarityThreshold() != null
                ? config.getSiblingSimilarityThreshold()
                : DEFAULTS.getSiblingSimilarityThreshold();
        double courseSimilarityThreshold = config.getCourseSimilarityThreshold() != null
                ? config.getCourseSimilarityThreshold()
                : DEFAULTS.getCourseSimilarityThreshold();
        boolean courseWideDistinctness = config.getCourseWideDistinctness() != null
                ? config.getCourseWideDistinctness()
                : DEFAULTS.isCourseWideDistinctness();
        CourseQuizCorpus quizCorpus = new AuditReportQuizCorpus(config.getAuditReportStore());
        evaluators.put(CorrectionCriterion.DISTINCTNESS, new DistinctnessCriterion(
                quizCorpus, siblingSimilarityThreshold, courseSimilarityThreshold,
                courseWideDistinctness));

        // F-QICOR-R004 criterios 4/5 (juicio): aportados por la infraestructura
        // (revision-infrastructure.candidatejudgment). Ausentes -> esos criterios no
        // entran al catalogo activo (CandidateCriteriaConfig.judgmentEvaluators doc).
        List<CandidateCriterionEvaluator> judgmentEvaluators = config.getJudgmentEvaluators();
        if (judgmentEvaluators != null) {
            for (CandidateCriterionEvaluator judgmentEvaluator : judgmentEvaluators) {
                evaluators.put(judgmentEvaluator.criterion(), judgmentEvaluator);
            }
        }

        evaluators.put(CorrectionCriterion.INSTRUCTION_COMPLIANCE, new InstructionComplianceCriterion(
                config.getComplianceChecker(), config.getSubjectViewFactory()));

        return new DefaultCandidateAssessor(evaluators);
    }
}
