package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriterionEvaluator;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CourseQuizCorpus;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisiondomain.candidatecriteria.QuizSimilarity;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;

/**
 * F-QICOR-R004 criterio 3: the candidate must not be confusable with its
 * knowledge siblings, nor (approximately) with the rest of the course
 * (DOUBT-DISTINCION-ALCANCE opcion A). Siblings are compared in full here --
 * they already travel verbatim on {@code CandidateAssessmentInput} -- while the
 * rest of the course is delegated to {@link CourseQuizCorpus}, an approximate,
 * cheaper search over the whole audited course.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DistinctnessCriterion implements CandidateCriterionEvaluator {
    private final CourseQuizCorpus quizCorpus;

    private final double siblingSimilarityThreshold;

    private final double courseSimilarityThreshold;

    private final boolean courseWideDistinctness;

    public DistinctnessCriterion(CourseQuizCorpus quizCorpus, double siblingSimilarityThreshold,
            double courseSimilarityThreshold, boolean courseWideDistinctness) {
        this.quizCorpus = quizCorpus;
        this.siblingSimilarityThreshold = siblingSimilarityThreshold;
        this.courseSimilarityThreshold = courseSimilarityThreshold;
        this.courseWideDistinctness = courseWideDistinctness;
    }

    @Override
    public CorrectionCriterion criterion() {
        return CorrectionCriterion.DISTINCTNESS;
    }

    @Override
    public CriterionVerdict evaluate(CandidateAssessmentInput input) {
        CourseElementSnapshot candidateSnapshot = input.getCandidate();
        QuizTemplateEntity candidateQuiz = candidateSnapshot != null ? candidateSnapshot.getQuiz() : null;
        String candidateSentence = canonicalSentence(candidateQuiz);
        if (candidateSentence.isBlank()) {
            return new CriterionVerdict(criterion(), CriterionOutcome.NOT_EVALUABLE,
                    "No se pudo comparar: el candidato no tiene oracion canonica");
        }

        List<String> siblings = input.getSiblingQuizSentences();
        if (siblings != null) {
            for (String sibling : siblings) {
                double score = QuizSimilarityScorer.similarity(candidateSentence, sibling);
                if (score >= siblingSimilarityThreshold) {
                    return new CriterionVerdict(criterion(), CriterionOutcome.FAILED,
                            "El candidato se confunde con un ejercicio hermano del mismo"
                                    + " knowledge (similitud " + score + ")");
                }
            }
        }

        if (courseWideDistinctness) {
            Optional<QuizSimilarity> mostSimilar = quizCorpus.mostSimilar(
                    input.getSourceAuditId(), candidateSentence, input.getSubjectRef());
            if (mostSimilar.isPresent() && mostSimilar.get().getScore() >= courseSimilarityThreshold) {
                return new CriterionVerdict(criterion(), CriterionOutcome.FAILED,
                        "El candidato se confunde con el ejercicio '" + mostSimilar.get().getQuizId()
                                + "' del resto del curso (similitud " + mostSimilar.get().getScore()
                                + ")");
            }
        }

        return new CriterionVerdict(criterion(), CriterionOutcome.PASSED,
                "El candidato se distingue de sus hermanos y del resto del curso");
    }

    private String canonicalSentence(QuizTemplateEntity quiz) {
        if (quiz == null) {
            return "";
        }
        List<String> sentences = quiz.getSentences();
        return (sentences != null && !sentences.isEmpty()) ? sentences.get(0) : "";
    }
}
