package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessment;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateLengthMeasurement;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultCandidateRankingTest {

    private static final CandidateLengthMeasurement IN_RANGE_LENGTH =
            new CandidateLengthMeasurement(8, 6, 10, true, true);
    private static final CandidateLengthMeasurement OUT_OF_RANGE_LENGTH =
            new CandidateLengthMeasurement(13, 6, 10, false, true);

    private final DefaultCandidateRanking ranking = new DefaultCandidateRanking();

    private static CriterionVerdict failed(CorrectionCriterion criterion) {
        return new CriterionVerdict(criterion, CriterionOutcome.FAILED, criterion + " was reproached.");
    }

    // Competes (eligible=true, realChange=true): the catalog counts five criteria
    // (SCOPED_EDIT, LEVEL_VOCABULARY, DISTINCTNESS, FAITHFUL_TRANSLATION,
    // SOLVABLE_SAME_KIND) — INSTRUCTION_COMPLIANCE gates eligibility instead of adding
    // to the count, and LENGTH_IN_RANGE never adds either (F-QICOR-R011). verdicts is
    // populated with only the unmet ones, since rankKey never reads the passing ones.
    private static CandidateAssessment eligibleAssessment(int satisfiedCriteria,
            List<CriterionVerdict> unmetCriteria, CandidateLengthMeasurement lengthMeasurement) {
        return new CandidateAssessment(unmetCriteria, true, true, satisfiedCriteria, unmetCriteria,
                lengthMeasurement, null);
    }

    // Does not compete: either the instruction was not met or the candidate was not a
    // real change over the original (F-QICOR-R001, F-QICOR-R010). satisfiedCriteria is
    // still supplied explicitly so a test can show that no count rescues it.
    private static CandidateAssessment ineligibleAssessment(int satisfiedCriteria,
            CandidateLengthMeasurement lengthMeasurement) {
        List<CriterionVerdict> verdicts = List.of(failed(CorrectionCriterion.INSTRUCTION_COMPLIANCE));
        return new CandidateAssessment(verdicts, false, true, satisfiedCriteria, List.of(), lengthMeasurement, null);
    }

    @Test
    @DisplayName("should rank above the candidate that satisfies more criteria of the catalog")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldRankAboveTheCandidateThatSatisfiesMoreCriteriaOfTheCatalog() {
        // Same two unmet criteria in both, plus one more for the lower-scoring one, so
        // only the COUNT differs — precedence never has to break a tie here.
        CandidateAssessment fourCriteria = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.DISTINCTNESS)), IN_RANGE_LENGTH);
        CandidateAssessment threeCriteria = eligibleAssessment(3,
                List.of(failed(CorrectionCriterion.DISTINCTNESS), failed(CorrectionCriterion.SCOPED_EDIT)),
                IN_RANGE_LENGTH);

        String fourCriteriaKey = ranking.rankKey(fourCriteria);
        String threeCriteriaKey = ranking.rankKey(threeCriteria);

        assertTrue(ranking.better(threeCriteriaKey, fourCriteriaKey));
        assertFalse(ranking.better(fourCriteriaKey, threeCriteriaKey));
    }

    @Test
    @DisplayName("should break a tie between candidates that satisfy the same number of criteria in favour of the one that satisfies the criterion of higher precedence")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldBreakATieBetweenCandidatesThatSatisfyTheSameNumberOfCriteriaInFavourOfTheOneThatSatisfiesTheCriterionOfHigherPrecedence(
            ) {
        // Both satisfy 4 of 5; they differ only in WHICH one they miss. Failing
        // resolvability (precedence 1, worst) must lose to failing scoped edit
        // (precedence 5, least harmful) — R013 acceptance criterion (b).
        CandidateAssessment failsResolvability = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.SOLVABLE_SAME_KIND)), IN_RANGE_LENGTH);
        CandidateAssessment failsScopedEdit = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.SCOPED_EDIT)), IN_RANGE_LENGTH);

        String failsResolvabilityKey = ranking.rankKey(failsResolvability);
        String failsScopedEditKey = ranking.rankKey(failsScopedEdit);

        assertTrue(ranking.better(failsResolvabilityKey, failsScopedEditKey));
        assertFalse(ranking.better(failsScopedEditKey, failsResolvabilityKey));
    }

    @Test
    @DisplayName("should declare the precedence of the criteria from the one whose failure harms the student most down to the one that only costs the operator a longer read")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldDeclareThePrecedenceOfTheCriteriaFromTheOneWhoseFailureHarmsTheStudentMostDownToTheOneThatOnlyCostsTheOperatorALongerRead(
            ) {
        List<CorrectionCriterion> precedence = ranking.precedence();

        assertEquals(List.of(
                CorrectionCriterion.SOLVABLE_SAME_KIND,
                CorrectionCriterion.FAITHFUL_TRANSLATION,
                CorrectionCriterion.LEVEL_VOCABULARY,
                CorrectionCriterion.DISTINCTNESS,
                CorrectionCriterion.SCOPED_EDIT), precedence);
    }

    @Test
    @DisplayName("should rank a candidate that does not compete below every candidate that does, however many criteria it satisfies")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldRankACandidateThatDoesNotCompeteBelowEveryCandidateThatDoesHoweverManyCriteriaItSatisfies(
            ) {
        // The non-competing candidate satisfies every OTHER criterion (5 of 5); the
        // competing one satisfies none besides the instruction it had to meet to
        // compete at all (0 of 5) — R013 acceptance criterion (c).
        CandidateAssessment doesNotCompeteButSatisfiesFive = ineligibleAssessment(5, IN_RANGE_LENGTH);
        CandidateAssessment competesButSatisfiesNone = eligibleAssessment(0, List.of(
                failed(CorrectionCriterion.SCOPED_EDIT), failed(CorrectionCriterion.LEVEL_VOCABULARY),
                failed(CorrectionCriterion.DISTINCTNESS), failed(CorrectionCriterion.FAITHFUL_TRANSLATION),
                failed(CorrectionCriterion.SOLVABLE_SAME_KIND)), IN_RANGE_LENGTH);

        String doesNotCompeteKey = ranking.rankKey(doesNotCompeteButSatisfiesFive);
        String competesKey = ranking.rankKey(competesButSatisfiesNone);

        assertTrue(ranking.better(doesNotCompeteKey, competesKey));
        assertFalse(ranking.better(competesKey, doesNotCompeteKey));
    }

    @Test
    @DisplayName("should let the length decide only between two candidates that satisfy exactly the same criteria")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldLetTheLengthDecideOnlyBetweenTwoCandidatesThatSatisfyExactlyTheSameCriteria(
            ) {
        // Nothing else distinguishes them: same eligibility, same 5-of-5 satisfied
        // criteria, no unmet criterion to consult precedence over. Only then may length
        // decide — R013 acceptance criterion (d).
        CandidateAssessment inRange = eligibleAssessment(5, List.of(), IN_RANGE_LENGTH);
        CandidateAssessment outOfRange = eligibleAssessment(5, List.of(), OUT_OF_RANGE_LENGTH);

        String inRangeKey = ranking.rankKey(inRange);
        String outOfRangeKey = ranking.rankKey(outOfRange);

        assertTrue(ranking.better(outOfRangeKey, inRangeKey));
        assertFalse(ranking.better(inRangeKey, outOfRangeKey));
    }

    @Test
    @DisplayName("should rank an out-of-range candidate that stays solvable above an in-range one that does not")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldRankAnOutofrangeCandidateThatStaysSolvableAboveAnInrangeOneThatDoesNot() {
        // This is the decision the feature was rewritten around: "un ejercicio bien
        // escrito fuera de rango vale mas que uno mal escrito dentro" (F-QICOR-R011).
        // Well written and out of range: satisfies every other criterion, including
        // resolvability; length is the only thing wrong, and length never counts.
        CandidateAssessment wellWrittenOutOfRange = eligibleAssessment(5, List.of(), OUT_OF_RANGE_LENGTH);
        // Badly written and in range: fails resolvability, the costliest criterion to
        // the student there is.
        CandidateAssessment poorlyWrittenInRange = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.SOLVABLE_SAME_KIND)), IN_RANGE_LENGTH);

        String wellWrittenOutOfRangeKey = ranking.rankKey(wellWrittenOutOfRange);
        String poorlyWrittenInRangeKey = ranking.rankKey(poorlyWrittenInRange);

        assertTrue(ranking.better(poorlyWrittenInRangeKey, wellWrittenOutOfRangeKey));
        assertFalse(ranking.better(wellWrittenOutOfRangeKey, poorlyWrittenInRangeKey));
    }

    @Test
    @DisplayName("should keep the incumbent champion when the challenger ranks equal, so the candidate seen first is the one delivered")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldKeepTheIncumbentChampionWhenTheChallengerRanksEqualSoTheCandidateSeenFirstIsTheOneDelivered(
            ) {
        // Two independently produced assessments that tie on every dimension rankKey
        // encodes. A caller conducting the retry loop of F-QICOR-R012 would compute the
        // first one's key when it sees it, then the second's key once the retry
        // produces it — replacing the champion only when better(incumbent, challenger)
        // is true.
        CandidateAssessment seenFirst = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.LEVEL_VOCABULARY)), IN_RANGE_LENGTH);
        CandidateAssessment seenSecond = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.LEVEL_VOCABULARY)), IN_RANGE_LENGTH);

        String seenFirstKey = ranking.rankKey(seenFirst);
        String seenSecondKey = ranking.rankKey(seenSecond);

        assertEquals(seenFirstKey, seenSecondKey);
        assertFalse(ranking.better(seenFirstKey, seenSecondKey));
    }

    @Test
    @DisplayName("should rank the candidate that describes something impossible below the one that describes something possible but changed more than the violation signalled")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R013")
    public void shouldRankTheCandidateThatDescribesSomethingImpossibleBelowTheOneThatDescribesSomethingPossibleButChangedMoreThanTheViolationSignalled(
            ) {
        // The real task-876 pair (F-QICOR-R016): "Does she drink meat?" respects the
        // scoped edit -- only the flagged hole/mark changed -- and passes every other
        // criterion of the catalog (5 of 5), but describes something impossible, so
        // REAL_WORLD_SENSE fails. That criterion gates eligibility instead of joining
        // the catalog count or precedence() (F-QICOR-R013), so it does not compete at
        // all, however many criteria it satisfies. "Does she drink milk?" changes
        // "meat", which no violation signalled, so it fails SCOPED_EDIT (4 of 5) -- but
        // it has sense, so it competes and wins — R013 acceptance criterion (h).
        CandidateAssessment describesSomethingImpossible = new CandidateAssessment(
                List.of(failed(CorrectionCriterion.REAL_WORLD_SENSE)), false, true, 5,
                List.of(), IN_RANGE_LENGTH, null);
        CandidateAssessment describesSomethingPossibleButChangedMore = eligibleAssessment(4,
                List.of(failed(CorrectionCriterion.SCOPED_EDIT)), IN_RANGE_LENGTH);

        String describesSomethingImpossibleKey = ranking.rankKey(describesSomethingImpossible);
        String describesSomethingPossibleButChangedMoreKey =
                ranking.rankKey(describesSomethingPossibleButChangedMore);

        assertTrue(ranking.better(describesSomethingImpossibleKey,
                describesSomethingPossibleButChangedMoreKey));
        assertFalse(ranking.better(describesSomethingPossibleButChangedMoreKey,
                describesSomethingImpossibleKey));
    }
}
