package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessment;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateCriterionEvaluator;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultCandidateAssessorTest {

    private CandidateCriterionEvaluator scopedEditEvaluator;
    private CandidateCriterionEvaluator lengthEvaluator;
    private CandidateCriterionEvaluator vocabularyEvaluator;
    private CandidateAssessmentInput assessmentInput;

    @BeforeEach
    void setUp() {
        scopedEditEvaluator = mock(CandidateCriterionEvaluator.class);
        lengthEvaluator = mock(CandidateCriterionEvaluator.class);
        vocabularyEvaluator = mock(CandidateCriterionEvaluator.class);
        when(scopedEditEvaluator.criterion()).thenReturn(CorrectionCriterion.SCOPED_EDIT);
        when(lengthEvaluator.criterion()).thenReturn(CorrectionCriterion.LENGTH_IN_RANGE);
        when(vocabularyEvaluator.criterion()).thenReturn(CorrectionCriterion.LEVEL_VOCABULARY);
        assessmentInput = buildInput();
    }

    private static QuizTemplateEntity quiz() {
        List<SentencePartEntity> sentenceParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("ate")),
                new SentencePartEntity(SentencePartKind.TEXT, " breakfast every morning.", null));
        FormEntity form = new FormEntity("CLOZE", 1.0, "", "", sentenceParts);
        return new QuizTemplateEntity("quiz-1", "quiz-1", "CLOZE", "knowledge-1", "Daily routines",
                "Complete with the past simple form", "Ella desayuno todas las mañanas.",
                "milestone.1.routines", "Daily Routines", form, 0.0, 0.0, 0.0, "", "", "", "", "",
                "", "", List.of("She ate breakfast every morning."));
    }

    private static CandidateAssessmentInput buildInput() {
        QuizTemplateEntity quiz = quiz();
        CourseElementSnapshot snapshot = new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-1", quiz, null);
        return new CandidateAssessmentInput("quiz-1", "audit-1", snapshot, snapshot, CefrLevel.A1,
                "Daily Routines", "Past simple narration", "Complete with the past simple form", "A1",
                SentenceMode.FILL, List.of(), List.of("eats"));
    }

    private static CriterionVerdict passed(CorrectionCriterion criterion) {
        return new CriterionVerdict(criterion, CriterionOutcome.PASSED, null);
    }

    @Test
    @DisplayName("should accept a candidate only when every criterion of the active catalog returned a passing verdict")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldAcceptACandidateOnlyWhenEveryCriterionOfTheActiveCatalogReturnedAPassingVerdict(
            ) {
        when(scopedEditEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.SCOPED_EDIT));
        when(lengthEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.LENGTH_IN_RANGE));
        when(vocabularyEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.LEVEL_VOCABULARY));
        Map<CorrectionCriterion, CandidateCriterionEvaluator> registry = Map.of(
                CorrectionCriterion.SCOPED_EDIT, scopedEditEvaluator,
                CorrectionCriterion.LENGTH_IN_RANGE, lengthEvaluator,
                CorrectionCriterion.LEVEL_VOCABULARY, vocabularyEvaluator);
        DefaultCandidateAssessor assessor = new DefaultCandidateAssessor(registry);

        CandidateAssessment assessment = assessor.assess(assessmentInput);

        assertTrue(assessment.isAccepted());
        assertEquals(3, assessment.getVerdicts().size());
        assertTrue(assessment.getVerdicts().stream().allMatch(v -> v.getOutcome() == CriterionOutcome.PASSED));
    }

    @Test
    @DisplayName("should refuse a candidate as soon as one criterion returns a failing verdict, whichever criterion it is")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldRefuseACandidateAsSoonAsOneCriterionReturnsAFailingVerdictWhicheverCriterionItIs(
            ) {
        when(scopedEditEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.SCOPED_EDIT));
        when(lengthEvaluator.evaluate(assessmentInput)).thenReturn(new CriterionVerdict(
                CorrectionCriterion.LENGTH_IN_RANGE, CriterionOutcome.FAILED,
                "12 tokens, fuera del rango 6-10 de A1"));
        when(vocabularyEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.LEVEL_VOCABULARY));
        Map<CorrectionCriterion, CandidateCriterionEvaluator> registry = Map.of(
                CorrectionCriterion.SCOPED_EDIT, scopedEditEvaluator,
                CorrectionCriterion.LENGTH_IN_RANGE, lengthEvaluator,
                CorrectionCriterion.LEVEL_VOCABULARY, vocabularyEvaluator);
        DefaultCandidateAssessor assessor = new DefaultCandidateAssessor(registry);

        CandidateAssessment assessment = assessor.assess(assessmentInput);

        assertFalse(assessment.isAccepted());
        assertTrue(assessment.getVerdicts().stream()
                .anyMatch(v -> v.getCriterion() == CorrectionCriterion.LENGTH_IN_RANGE
                        && v.getOutcome() == CriterionOutcome.FAILED));
    }

    @Test
    @DisplayName("should refuse a candidate whose criterion could not be evaluated, instead of letting an unverified candidate through")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldRefuseACandidateWhoseCriterionCouldNotBeEvaluatedInsteadOfLettingAnUnverifiedCandidateThrough(
            ) {
        when(scopedEditEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.SCOPED_EDIT));
        when(lengthEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.LENGTH_IN_RANGE));
        when(vocabularyEvaluator.evaluate(assessmentInput)).thenReturn(new CriterionVerdict(
                CorrectionCriterion.LEVEL_VOCABULARY, CriterionOutcome.NOT_EVALUABLE,
                "el analizador lexico no respondio"));
        Map<CorrectionCriterion, CandidateCriterionEvaluator> registry = Map.of(
                CorrectionCriterion.SCOPED_EDIT, scopedEditEvaluator,
                CorrectionCriterion.LENGTH_IN_RANGE, lengthEvaluator,
                CorrectionCriterion.LEVEL_VOCABULARY, vocabularyEvaluator);
        DefaultCandidateAssessor assessor = new DefaultCandidateAssessor(registry);

        CandidateAssessment assessment = assessor.assess(assessmentInput);

        assertFalse(assessment.isAccepted());
        assertTrue(assessment.getVerdicts().stream()
                .anyMatch(v -> v.getCriterion() == CorrectionCriterion.LEVEL_VOCABULARY
                        && v.getOutcome() == CriterionOutcome.NOT_EVALUABLE));
    }

    @Test
    @DisplayName("should carry in the assessment the criterion that blocked the candidate together with the detail of why it failed")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R006")
    public void shouldCarryInTheAssessmentTheCriterionThatBlockedTheCandidateTogetherWithTheDetailOfWhyItFailed(
            ) {
        String detail = "La oracion corregida tiene 14 tokens; el rango objetivo de A1 es 6-10.";
        when(scopedEditEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.SCOPED_EDIT));
        when(lengthEvaluator.evaluate(assessmentInput)).thenReturn(new CriterionVerdict(
                CorrectionCriterion.LENGTH_IN_RANGE, CriterionOutcome.FAILED, detail));
        when(vocabularyEvaluator.evaluate(assessmentInput)).thenReturn(passed(CorrectionCriterion.LEVEL_VOCABULARY));
        Map<CorrectionCriterion, CandidateCriterionEvaluator> registry = Map.of(
                CorrectionCriterion.SCOPED_EDIT, scopedEditEvaluator,
                CorrectionCriterion.LENGTH_IN_RANGE, lengthEvaluator,
                CorrectionCriterion.LEVEL_VOCABULARY, vocabularyEvaluator);
        DefaultCandidateAssessor assessor = new DefaultCandidateAssessor(registry);

        CandidateAssessment assessment = assessor.assess(assessmentInput);

        assertFalse(assessment.isAccepted());
        CriterionVerdict blocking = assessment.getVerdicts().stream()
                .filter(v -> v.getCriterion() == CorrectionCriterion.LENGTH_IN_RANGE)
                .findFirst()
                .orElseThrow(() -> new AssertionError(
                        "the assessment must carry a verdict for the criterion that blocked the candidate"));
        assertEquals(CriterionOutcome.FAILED, blocking.getOutcome());
        assertEquals(detail, blocking.getDetail());
    }
}
