package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.quizinstruction.InstructionSeverity;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionComplianceChecker;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionComplianceResult;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionComplianceStatus;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionSubjectView;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionSubjectViewFactory;
import com.learney.contentaudit.auditdomain.quizinstruction.QuizInstructionVerdict;
import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class InstructionComplianceCriterionTest {

    private QuizInstructionComplianceChecker complianceChecker;
    private QuizInstructionSubjectViewFactory subjectViewFactory;
    private InstructionComplianceCriterion criterion;

    @BeforeEach
    void setUp() {
        complianceChecker = mock(QuizInstructionComplianceChecker.class);
        subjectViewFactory = mock(QuizInstructionSubjectViewFactory.class);
        criterion = new InstructionComplianceCriterion(complianceChecker, subjectViewFactory);
    }

    private static QuizTemplateEntity quiz(String clozeOption, String sentenceText) {
        List<SentencePartEntity> sentenceParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of(clozeOption)),
                new SentencePartEntity(SentencePartKind.TEXT, " breakfast every morning.", null));
        FormEntity form = new FormEntity("CLOZE", 1.0, "", "", sentenceParts);
        return new QuizTemplateEntity("quiz-1", "quiz-1", "CLOZE", "knowledge-1", "Daily routines",
                "Complete with the past simple form", "Ella desayuno todas las mañanas.",
                "milestone.1.routines", "Daily Routines", form, 0.0, 0.0, 0.0, "", "", "", "", "",
                "", "", List.of(sentenceText));
    }

    private static CourseElementSnapshot snapshot(QuizTemplateEntity quiz) {
        return new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-1", quiz, null);
    }

    private static CandidateAssessmentInput input(QuizTemplateEntity original, QuizTemplateEntity candidate,
            List<String> signalledFragments) {
        return new CandidateAssessmentInput("quiz-1", "audit-1", snapshot(original), snapshot(candidate),
                CefrLevel.A1, "Daily Routines", "Past simple narration",
                "Complete with the past simple form", "A1", SentenceMode.FILL, List.of(), signalledFragments);
    }

    @Test
    @DisplayName("should pass a candidate that the instruction validation declares compliant")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R005")
    public void shouldPassACandidateThatTheInstructionValidationDeclaresCompliant() {
        QuizTemplateEntity original = quiz("eats", "She eats breakfast every morning.");
        QuizTemplateEntity candidate = quiz("ate", "She ate breakfast every morning.");
        CandidateAssessmentInput assessmentInput = input(original, candidate, List.of("eats"));
        QuizInstructionSubjectView view = new QuizInstructionSubjectView("quiz-1", "A1", "Daily Routines",
                "Past simple narration", "Complete with the past simple form", candidate.getForm().getSentenceParts());
        when(subjectViewFactory.fromQuiz(candidate, "A1", "Daily Routines", "Past simple narration",
                "Complete with the past simple form")).thenReturn(view);
        QuizInstructionVerdict compliantVerdict = new QuizInstructionVerdict(true, 0.95, InstructionSeverity.NONE,
                "Cumple la consigna.", List.of(), List.of());
        when(complianceChecker.check(view)).thenReturn(new QuizInstructionComplianceResult(
                QuizInstructionComplianceStatus.EVALUATED, compliantVerdict, null, "judge-v3", false));

        CriterionVerdict verdict = criterion.evaluate(assessmentInput);

        assertEquals(CorrectionCriterion.INSTRUCTION_COMPLIANCE, verdict.getCriterion());
        assertEquals(CriterionOutcome.PASSED, verdict.getOutcome());
    }

    @Test
    @DisplayName("should fail a candidate that resolved only part of the violations and still breaches its instruction")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R005")
    public void shouldFailACandidateThatResolvedOnlyPartOfTheViolationsAndStillBreachesItsInstruction(
            ) {
        QuizTemplateEntity original = quiz("eats", "She eats breakfast every morning.");
        // The candidate fixed the tense but still leaves another, unrelated violation
        // unresolved (e.g. the response admits more than one word where the
        // instruction demands exactly one) — the checker still declares non-compliance.
        QuizTemplateEntity candidate = quiz("ate", "She ate breakfast every morning.");
        CandidateAssessmentInput assessmentInput = input(original, candidate, List.of("eats", "one word"));
        QuizInstructionSubjectView view = new QuizInstructionSubjectView("quiz-1", "A1", "Daily Routines",
                "Past simple narration", "Complete with the past simple form", candidate.getForm().getSentenceParts());
        when(subjectViewFactory.fromQuiz(candidate, "A1", "Daily Routines", "Past simple narration",
                "Complete with the past simple form")).thenReturn(view);
        QuizInstructionVerdict stillBreaches = new QuizInstructionVerdict(false, 0.9, InstructionSeverity.MAJOR,
                "La respuesta acepta mas de una palabra.", List.of(), List.of());
        when(complianceChecker.check(view)).thenReturn(new QuizInstructionComplianceResult(
                QuizInstructionComplianceStatus.EVALUATED, stillBreaches, null, "judge-v3", false));

        CriterionVerdict verdict = criterion.evaluate(assessmentInput);

        assertEquals(CriterionOutcome.FAILED, verdict.getOutcome());
    }

    @Test
    @DisplayName("should submit the corrected quiz as a whole to the instruction validation, with its parts, its level and its knowledge instruction, instead of checking the violations one by one")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R005")
    public void shouldSubmitTheCorrectedQuizAsAWholeToTheInstructionValidationWithItsPartsItsLevelAndItsKnowledgeInstructionInsteadOfCheckingTheViolationsOneByOne(
            ) {
        QuizTemplateEntity original = quiz("eats", "She eats breakfast every morning.");
        QuizTemplateEntity candidate = quiz("ate", "She ate breakfast every morning.");
        // Three violations were signalled — a per-violation check would call the judge
        // three times; a whole-exercise check calls it exactly once.
        CandidateAssessmentInput assessmentInput = input(original, candidate,
                List.of("eats", "one word", "past tense"));
        QuizInstructionSubjectView view = new QuizInstructionSubjectView("quiz-1", "A1", "Daily Routines",
                "Past simple narration", "Complete with the past simple form", candidate.getForm().getSentenceParts());
        when(subjectViewFactory.fromQuiz(any(), any(), any(), any(), any())).thenReturn(view);
        QuizInstructionVerdict compliantVerdict = new QuizInstructionVerdict(true, 0.95, InstructionSeverity.NONE,
                "Cumple la consigna.", List.of(), List.of());
        when(complianceChecker.check(view)).thenReturn(new QuizInstructionComplianceResult(
                QuizInstructionComplianceStatus.EVALUATED, compliantVerdict, null, "judge-v3", false));

        criterion.evaluate(assessmentInput);

        ArgumentCaptor<QuizTemplateEntity> quizCaptor = ArgumentCaptor.forClass(QuizTemplateEntity.class);
        ArgumentCaptor<String> levelCaptor = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> topicCaptor = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> titleCaptor = ArgumentCaptor.forClass(String.class);
        ArgumentCaptor<String> instructionsCaptor = ArgumentCaptor.forClass(String.class);
        verify(subjectViewFactory).fromQuiz(quizCaptor.capture(), levelCaptor.capture(), topicCaptor.capture(),
                titleCaptor.capture(), instructionsCaptor.capture());
        assertEquals(candidate, quizCaptor.getValue());
        assertEquals("A1", levelCaptor.getValue());
        assertEquals("Daily Routines", topicCaptor.getValue());
        assertEquals("Past simple narration", titleCaptor.getValue());
        assertEquals("Complete with the past simple form", instructionsCaptor.getValue());
        verify(complianceChecker, times(1)).check(view);
    }

    @Test
    @DisplayName("should refuse a candidate whose instruction validation could not be obtained, instead of assuming that it complies")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R005")
    public void shouldRefuseACandidateWhoseInstructionValidationCouldNotBeObtainedInsteadOfAssumingThatItComplies(
            ) {
        QuizTemplateEntity original = quiz("eats", "She eats breakfast every morning.");
        QuizTemplateEntity candidate = quiz("ate", "She ate breakfast every morning.");
        CandidateAssessmentInput assessmentInput = input(original, candidate, List.of("eats"));
        QuizInstructionSubjectView view = new QuizInstructionSubjectView("quiz-1", "A1", "Daily Routines",
                "Past simple narration", "Complete with the past simple form", candidate.getForm().getSentenceParts());
        when(subjectViewFactory.fromQuiz(candidate, "A1", "Daily Routines", "Past simple narration",
                "Complete with the past simple form")).thenReturn(view);
        when(complianceChecker.check(view)).thenReturn(new QuizInstructionComplianceResult(
                QuizInstructionComplianceStatus.UNAVAILABLE, null, "El juez no respondio a tiempo.", null, false));

        CriterionVerdict verdict = criterion.evaluate(assessmentInput);

        assertEquals(CriterionOutcome.NOT_EVALUABLE, verdict.getOutcome());
    }
}
