package com.learney.contentaudit.revisiondomain.candidatecriteriaengine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.CefrLevel;
import com.learney.contentaudit.auditdomain.NlpToken;
import com.learney.contentaudit.auditdomain.NlpTokenizer;
import com.learney.contentaudit.auditdomain.lexicalflags.MisplacedWordFlag;
import com.learney.contentaudit.auditdomain.lexicalflags.OutOfCatalogFlag;
import com.learney.contentaudit.auditdomain.lexicalflags.SentenceLexicalEvaluator;
import com.learney.contentaudit.auditdomain.lexicalflags.SentenceLexicalFlags;
import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.QuizTemplateEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateAssessmentInput;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionOutcome;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LevelVocabularyCriterionTest {

    private static final CefrLevel LEVEL = CefrLevel.A1;

    private NlpTokenizer tokenizer;
    private SentenceLexicalEvaluator lexicalEvaluator;
    private LevelVocabularyCriterion criterion;

    @BeforeEach
    void setUp() {
        tokenizer = mock(NlpTokenizer.class);
        lexicalEvaluator = mock(SentenceLexicalEvaluator.class);
        criterion = new LevelVocabularyCriterion(lexicalEvaluator, tokenizer);
    }

    private static QuizTemplateEntity quiz(List<SentencePartEntity> sentenceParts, String sentenceText) {
        FormEntity form = new FormEntity("CLOZE", 1.0, "", "", sentenceParts);
        return new QuizTemplateEntity("quiz-1", "quiz-1", "CLOZE", "knowledge-1", "Daily routines",
                "Complete with the correct verb", "Traduccion de la oracion.",
                "milestone.1.routines", "Daily Routines", form, 0.0, 0.0, 0.0, "", "", "", "", "",
                "", "", List.of(sentenceText));
    }

    private static CourseElementSnapshot snapshot(QuizTemplateEntity quiz) {
        return new CourseElementSnapshot(AuditTarget.QUIZ, "quiz-1", quiz, null);
    }

    private static CandidateAssessmentInput input(QuizTemplateEntity original, QuizTemplateEntity candidate,
            List<String> signalledFragments) {
        return new CandidateAssessmentInput("quiz-1", "audit-1", snapshot(original), snapshot(candidate),
                LEVEL, "Daily Routines", "Verb forms", "Complete with the correct verb", "A1",
                SentenceMode.FILL, List.of(), signalledFragments);
    }

    @Test
    @DisplayName("should fail a candidate that introduces a word misplaced for the level that the original quiz did not have")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldFailACandidateThatIntroducesAWordMisplacedForTheLevelThatTheOriginalQuizDidNotHave(
            ) {
        String originalSentence = "She arrives at school every day.";
        String candidateSentence = "She commences at school every day.";
        List<SentencePartEntity> originalParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("arrives")),
                new SentencePartEntity(SentencePartKind.TEXT, " at school every day.", null));
        List<SentencePartEntity> candidateParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("commences")),
                new SentencePartEntity(SentencePartKind.TEXT, " at school every day.", null));
        QuizTemplateEntity original = quiz(originalParts, originalSentence);
        QuizTemplateEntity candidate = quiz(candidateParts, candidateSentence);

        List<NlpToken> originalTokens = List.of(new NlpToken("arrives", "arrive", "VERB", 480, false, false));
        List<NlpToken> candidateTokens = List.of(new NlpToken("commences", "commence", "VERB", 6200, false, false));
        when(tokenizer.analyzeTokens(originalSentence)).thenReturn(originalTokens);
        when(tokenizer.analyzeTokens(candidateSentence)).thenReturn(candidateTokens);
        when(lexicalEvaluator.evaluate(originalTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(), List.of()));
        MisplacedWordFlag newMisplaced = new MisplacedWordFlag("commence", "VERB", CefrLevel.B2, LEVEL);
        when(lexicalEvaluator.evaluate(candidateTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(newMisplaced), List.of()));

        CriterionVerdict verdict = criterion.evaluate(input(original, candidate, List.of("arrives")));

        assertEquals(CorrectionCriterion.LEVEL_VOCABULARY, verdict.getCriterion());
        assertEquals(CriterionOutcome.FAILED, verdict.getOutcome());
    }

    @Test
    @DisplayName("should fail a candidate that introduces an out-of-catalog word that the original quiz did not have")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldFailACandidateThatIntroducesAnOutofcatalogWordThatTheOriginalQuizDidNotHave(
            ) {
        String originalSentence = "She arrives at school every day.";
        String candidateSentence = "She perambulates at school every day.";
        List<SentencePartEntity> originalParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("arrives")),
                new SentencePartEntity(SentencePartKind.TEXT, " at school every day.", null));
        List<SentencePartEntity> candidateParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("perambulates")),
                new SentencePartEntity(SentencePartKind.TEXT, " at school every day.", null));
        QuizTemplateEntity original = quiz(originalParts, originalSentence);
        QuizTemplateEntity candidate = quiz(candidateParts, candidateSentence);

        List<NlpToken> originalTokens = List.of(new NlpToken("arrives", "arrive", "VERB", 480, false, false));
        List<NlpToken> candidateTokens = List.of(
                new NlpToken("perambulates", "perambulate", "VERB", null, false, false));
        when(tokenizer.analyzeTokens(originalSentence)).thenReturn(originalTokens);
        when(tokenizer.analyzeTokens(candidateSentence)).thenReturn(candidateTokens);
        when(lexicalEvaluator.evaluate(originalTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(), List.of()));
        OutOfCatalogFlag newOutOfCatalog = new OutOfCatalogFlag("perambulate", "VERB", null);
        when(lexicalEvaluator.evaluate(candidateTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(), List.of(newOutOfCatalog)));

        CriterionVerdict verdict = criterion.evaluate(input(original, candidate, List.of("arrives")));

        assertEquals(CriterionOutcome.FAILED, verdict.getOutcome());
    }

    @Test
    @DisplayName("should pass a candidate that keeps a lexical flag the original already had and adds none of its own")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R004")
    public void shouldPassACandidateThatKeepsALexicalFlagTheOriginalAlreadyHadAndAddsNoneOfItsOwn(
            ) {
        String originalSentence = "She sprints to catch the bus.";
        String candidateSentence = "She sprints to catch the coach.";
        List<SentencePartEntity> originalParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She sprints to catch the ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("bus")),
                new SentencePartEntity(SentencePartKind.TEXT, ".", null));
        List<SentencePartEntity> candidateParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "She sprints to catch the ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("coach")),
                new SentencePartEntity(SentencePartKind.TEXT, ".", null));
        QuizTemplateEntity original = quiz(originalParts, originalSentence);
        QuizTemplateEntity candidate = quiz(candidateParts, candidateSentence);

        // "sprint" was already flagged as misplaced for A1 in the original; the
        // correction only swaps "bus" for "coach" and keeps that pre-existing flag.
        MisplacedWordFlag preexisting = new MisplacedWordFlag("sprint", "VERB", CefrLevel.B1, LEVEL);
        List<NlpToken> originalTokens = List.of(new NlpToken("sprints", "sprint", "VERB", 3000, false, false));
        List<NlpToken> candidateTokens = List.of(new NlpToken("sprints", "sprint", "VERB", 3000, false, false));
        when(tokenizer.analyzeTokens(originalSentence)).thenReturn(originalTokens);
        when(tokenizer.analyzeTokens(candidateSentence)).thenReturn(candidateTokens);
        when(lexicalEvaluator.evaluate(originalTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(preexisting), List.of()));
        when(lexicalEvaluator.evaluate(candidateTokens, LEVEL))
                .thenReturn(new SentenceLexicalFlags(List.of(preexisting), List.of()));

        CriterionVerdict verdict = criterion.evaluate(input(original, candidate, List.of("bus")));

        assertEquals(CriterionOutcome.PASSED, verdict.getOutcome());
    }

    @Test
    @DisplayName("should judge the level vocabulary with the same lexical evaluator the audit applies, instead of an approximation of it")
    @Tag("FEAT-QICOR")
    @Tag("F-QICOR-R015")
    public void shouldJudgeTheLevelVocabularyWithTheSameLexicalEvaluatorTheAuditAppliesInsteadOfAnApproximationOfIt() {
        // Deliberately NOT the class-level LEVEL constant (A1) the other three tests share: if the
        // criterion judged vocabulary against a level of its own instead of the one this candidate is
        // actually being measured against, this test would still pass with A1 by coincidence.
        CefrLevel level = CefrLevel.B1;
        String originalSentence = "He works in the city centre.";
        String candidateSentence = "He commutes in the city centre.";
        List<SentencePartEntity> originalParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "He ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("works")),
                new SentencePartEntity(SentencePartKind.TEXT, " in the city centre.", null));
        List<SentencePartEntity> candidateParts = List.of(
                new SentencePartEntity(SentencePartKind.TEXT, "He ", null),
                new SentencePartEntity(SentencePartKind.CLOZE, "", List.of("commutes")),
                new SentencePartEntity(SentencePartKind.TEXT, " in the city centre.", null));
        QuizTemplateEntity original = quiz(originalParts, originalSentence);
        QuizTemplateEntity candidate = quiz(candidateParts, candidateSentence);

        List<NlpToken> originalTokens = List.of(new NlpToken("works", "work", "VERB", 500, false, false));
        List<NlpToken> candidateTokens = List.of(new NlpToken("commutes", "commute", "VERB", 2400, false, false));
        when(tokenizer.analyzeTokens(originalSentence)).thenReturn(originalTokens);
        when(tokenizer.analyzeTokens(candidateSentence)).thenReturn(candidateTokens);
        when(lexicalEvaluator.evaluate(originalTokens, level))
                .thenReturn(new SentenceLexicalFlags(List.of(), List.of()));
        when(lexicalEvaluator.evaluate(candidateTokens, level))
                .thenReturn(new SentenceLexicalFlags(List.of(), List.of()));

        // Built by hand instead of via the input(...) helper, which hardcodes the shared A1 LEVEL
        // constant — this scenario needs a level of its own to be a meaningful parity check.
        CandidateAssessmentInput customInput = new CandidateAssessmentInput(
                "quiz-1", "audit-1", snapshot(original), snapshot(candidate), level,
                "Daily Routines", "Verb forms", "Complete with the correct verb", "B1",
                SentenceMode.FILL, List.of(), List.of("works"));

        CriterionVerdict verdict = criterion.evaluate(customInput);

        assertEquals(CorrectionCriterion.LEVEL_VOCABULARY, verdict.getCriterion());
        // F-QICOR-R015(b): the vocabulary verdict must coincide with "el analisis lexico" — i.e. use
        // the SAME NlpTokenizer + SentenceLexicalEvaluator ports the audit itself uses, fed the exact
        // sentence text and the exact CEFR level this input carried, never a criterion-local
        // approximation of vocabulary fitness.
        verify(tokenizer).analyzeTokens(originalSentence);
        verify(tokenizer).analyzeTokens(candidateSentence);
        verify(lexicalEvaluator).evaluate(originalTokens, level);
        verify(lexicalEvaluator).evaluate(candidateTokens, level);
    }
}
