package com.learney.contentaudit.coursedomain.quizsentenceengine;

import com.learney.contentaudit.coursedomain.FormEntity;
import com.learney.contentaudit.coursedomain.SentenceMode;
import com.learney.contentaudit.coursedomain.SentencePartEntity;
import com.learney.contentaudit.coursedomain.SentencePartKind;
import com.learney.contentaudit.coursedomain.quizsentence.QuizSentenceConverter;

import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-SMODE")
@Tag("F-SMODE-J001")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FSmodeJ001JourneyTest {

    // ── helpers ──────────────────────────────────────────────────────────────

    private static FormEntity form(SentencePartEntity... parts) {
        return new FormEntity("CLOZE", 1.0, "", "", Arrays.asList(parts));
    }

    private static SentencePartEntity text(String t) {
        return new SentencePartEntity(SentencePartKind.TEXT, t, null);
    }

    private static SentencePartEntity cloze(String... options) {
        return new SentencePartEntity(SentencePartKind.CLOZE, "", Arrays.asList(options));
    }

    /** Colapsa espacios multiples y recorta (equivalencia R010). */
    private static String normalize(String s) {
        return s.trim().replaceAll("\\s+", " ");
    }

    // ── paths ─────────────────────────────────────────────────────────────────

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El sistema toma un quiz basado en sen... → El sistema determina el modo de frase... → El sistema construye la frase canonic... [El modo del knowledge es FILL] → El sistema calcula el conteo de token... → success")
    public void path1_elModoDelKnowledgeEsFILL_success() {
        // ── Contexto: knowledge con modo FILL (F-SMODE-R001, R002) ─────────────
        // El modo FILL representa un ejercicio de relleno: el alumno completa
        // una palabra dentro de una oracion con hueco.
        // Fixture basado en el ejemplo canonico del REQUIREMENT:
        //   "She dances ___ (good/well)." con respuesta "well"
        //   → frase canonica puntuable: "She dances well."
        QuizSentenceConverter converter = new DefaultQuizSentenceConverter(
                new QuizSentenceSerializer(),
                new QuizSentenceParser(),
                new PlainSentenceDeriver(new WhitespaceNormalizer()));

        // Nodo tomar_quiz: quiz basado en sentencias listo para puntuar longitud
        FormEntity quiz = form(
                text("She dances"),
                cloze("well"),
                text(" (good/well).")
        );

        // Nodo leer_modo: el sistema determina el modo del knowledge al que pertenece el quiz.
        // Gate F-SMODE-R001: el knowledge tiene modo valido (FILL — uno de exactamente dos valores).
        // Gate F-SMODE-R002: el modo es uniforme dentro del knowledge (se pasa una sola vez, aqui FILL).
        // La bifurcacion [El modo del knowledge es FILL] conduce al nodo frase_completa.
        SentenceMode modoKnowledge = SentenceMode.FILL;

        // Nodo frase_completa (gate F-SMODE-R003):
        // El sistema construye la frase canonica como la oracion completa con el hueco relleno.
        List<String> fraseCanonica = assertDoesNotThrow(
                () -> converter.toPlainSentences(quiz, modoKnowledge),
                "toPlainSentences con modo FILL no debe lanzar excepcion");

        // Nodo puntuar (gate F-SMODE-R005):
        // El score de longitud se calcula sobre la frase canonica determinada por el modo,
        // no sobre una concatenacion ciega de todas las partes.
        // Verificacion observable: la frase canonica en indice 0 es la oracion completa con
        // el hueco relleno ("She dances well."), con el hint (good/well) excluido.
        assertFalse(fraseCanonica.isEmpty(),
                "F-SMODE-R003 (FILL): el resultado no debe estar vacio");
        assertEquals("She dances well.", normalize(fraseCanonica.get(0)),
                "F-SMODE-R003 (FILL): la frase canonica puntuable es la oracion completa con el hueco relleno; "
                        + "obtenido: " + fraseCanonica.get(0));

        // F-SMODE-R005: el token count de la frase canonica refleja solo las palabras de
        // la oracion completa rellena (3 tokens: "She", "dances", "well") — no hay arrastre
        // de partes adicionales ni del hint "(good/well)".
        // Verificacion: la cadena no contiene el hint "(good/well)" ni fragmentos duplicados.
        assertFalse(normalize(fraseCanonica.get(0)).contains("good"),
                "F-SMODE-R005 (FILL): el hint '(good/well)' no debe aparecer en la frase canonica puntuable");
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El sistema toma un quiz basado en sen... → El sistema determina el modo de frase... → El sistema construye la frase canonic... [El modo del knowledge es REWRITE] → El sistema calcula el conteo de token... → success")
    public void path2_elModoDelKnowledgeEsREWRITE_success() {
        // ── Contexto: knowledge con modo REWRITE (F-SMODE-R001, R002) ──────────
        // El modo REWRITE representa un ejercicio de transformacion/reescritura:
        // el alumno transforma una oracion fuente en otra forma.
        // Caso real del bug (REQUIREMENT, R004):
        //   fuente TEXT: "You should watch the DVD."
        //   respuesta CLOZE: "Watch the DVD."
        //   El sistema antes producia "You should watch the DVD. Watch the DVD." (10 tokens).
        //   Bajo REWRITE, debe producir SOLO "Watch the DVD." (4 tokens).
        QuizSentenceConverter converter = new DefaultQuizSentenceConverter(
                new QuizSentenceSerializer(),
                new QuizSentenceParser(),
                new PlainSentenceDeriver(new WhitespaceNormalizer()));

        // Nodo tomar_quiz: quiz de reescritura con oracion fuente (TEXT-andamio) y respuesta (CLOZE)
        FormEntity quiz = form(
                text("You should watch the DVD."),   // oracion fuente/prompt — andamio pedagogico
                cloze("Watch the DVD.")               // oracion respuesta — lo que escribe el alumno
        );

        // Nodo leer_modo: el sistema determina el modo del knowledge al que pertenece el quiz.
        // Gate F-SMODE-R001: el knowledge tiene modo valido (REWRITE — uno de exactamente dos valores).
        // Gate F-SMODE-R002: el modo es uniforme dentro del knowledge (se pasa una sola vez, aqui REWRITE).
        // La bifurcacion [El modo del knowledge es REWRITE] conduce al nodo frase_solo_respuesta.
        SentenceMode modoKnowledge = SentenceMode.REWRITE;

        // Nodo frase_solo_respuesta (gates F-SMODE-R003 y F-SMODE-R004):
        // El sistema construye la frase canonica como SOLO la oracion respuesta,
        // sin incluir la oracion fuente/prompt (TEXT-andamio excluido totalmente).
        List<String> fraseCanonica = assertDoesNotThrow(
                () -> converter.toPlainSentences(quiz, modoKnowledge),
                "toPlainSentences con modo REWRITE no debe lanzar excepcion");

        // Nodo puntuar (gate F-SMODE-R005):
        // El score de longitud se calcula sobre la frase canonica determinada por el modo.
        // Verificacion observable clave (F-SMODE-R004):
        //   - La frase canonica es "Watch the DVD." (4 tokens), NO la concatenacion de 10 tokens.
        //   - La oracion fuente "You should watch the DVD." no aporta ningun token.
        assertFalse(fraseCanonica.isEmpty(),
                "F-SMODE-R003 (REWRITE): el resultado no debe estar vacio");

        String canonicaObtenida = normalize(fraseCanonica.get(0));

        assertEquals("Watch the DVD.", canonicaObtenida,
                "F-SMODE-R003/R004 (REWRITE): la frase canonica puntuable es SOLO la oracion respuesta; "
                        + "obtenida: " + canonicaObtenida);

        // F-SMODE-R004 (exclusion total de la fuente):
        // La oracion fuente no debe aparecer concatenada ni parcialmente en la frase canonica.
        assertFalse(canonicaObtenida.contains("You should"),
                "F-SMODE-R004: la oracion fuente 'You should...' no debe incluirse en la frase canonica REWRITE");
        assertFalse(canonicaObtenida.contains("You should watch the DVD."),
                "F-SMODE-R004: la concatenacion fuente+respuesta no es la frase canonica REWRITE");

        // F-SMODE-R005: el score de longitud se calcula sobre la frase canonica determinada por el modo,
        // no sobre una concatenacion ciega de todas las partes.
        // La frase "Watch the DVD." es mas corta que la concatenacion "You should watch the DVD. Watch the DVD."
        // — este corte es lo que R005 garantiza: el scoring recibe la frase canonica del modo, no el total.
        // Verificacion de contencido: la canonica no contiene la fuente, por lo tanto el tokenizador
        // linguistico vera menos tokens de los que veria si incluyera la oracion fuente.
        assertTrue(canonicaObtenida.length() < "You should watch the DVD. Watch the DVD.".length(),
                "F-SMODE-R005: la frase canonica REWRITE es mas corta que la concatenacion fuente+respuesta; "
                        + "obtenida: '" + canonicaObtenida + "'");
    }
}
