package com.learney.contentaudit.revisiondomain.impactpreview;

import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DimensionDelta {
    private String dimension;

    private ScoreDelta delta;

    public DimensionDelta() {
    }

    public DimensionDelta(String dimension, ScoreDelta delta) {
        this.dimension = dimension;
        this.delta = delta;
    }

    public String getDimension() {
        return this.dimension;
    }

    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    public ScoreDelta getDelta() {
        return this.delta;
    }

    public void setDelta(ScoreDelta delta) {
        this.delta = delta;
    }

    /** Record-style accessor alias for tests (F-PIPRE). */
    public String dimension() { return this.dimension; }
    /** Record-style accessor alias for tests (F-PIPRE). */
    public ScoreDelta delta() { return this.delta; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DimensionDelta that = (DimensionDelta) o;
        return Objects.equals(this.dimension, that.dimension)
                    && Objects.equals(this.delta, that.delta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dimension, delta);
    }
}
