package com.learney.contentaudit.revisiondomain.impactpreview;

import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface ImpactPreviewComputer {
    ImpactPreview compute(CourseEntity currentCourse, RevisionProposal proposal);
}
