package com.learney.contentaudit.auditcli;

import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public interface SetActiveAnalysisCommand {
    Integer setActive(String auditId, String planId);
}
