package com.learney.contentaudit.auditdomain;

import com.learney.contentaudit.auditdomain.labs.AbsenceAssessment;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-LABS")
@Tag("F-LABS-J003")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FLabsJ003JourneyTest {
    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El usuario filtra los lemas ausentes ... → El usuario revisa en que niveles post... → El usuario agrega el lema en su nivel... [El lema aparece un solo nivel despues del esperado (por ejemplo, A2 esperado, aparece en B1)] → success")
    public void path1_elLemaApareceUnSoloNivelDespuesDelEsperadoPorEjemploA2EsperadoApareceEnB1_success(
            ) {
        // Step: filtrar_too_late — filter APPEARS_TOO_LATE lemmas for A2 level.
        // The lemma "book" is expected at A2 but only appears in B1 (one level later).
        AbsentLemma tooLateLemma = new AbsentLemma(
                new LemmaAndPos("book", "NOUN"),
                CefrLevel.A2,
                AbsenceType.APPEARS_TOO_LATE,
                List.of(CefrLevel.B1),
                PriorityLevel.HIGH,
                520,
                "education");

        // Also include a COMPLETELY_ABSENT and an APPEARS_TOO_EARLY lemma to confirm filtering
        AbsentLemma completelyAbsent = new AbsentLemma(
                new LemmaAndPos("pen", "NOUN"),
                CefrLevel.A2,
                AbsenceType.COMPLETELY_ABSENT,
                Collections.emptyList(),
                PriorityLevel.HIGH,
                890,
                "objects");

        AbsentLemma tooEarly = new AbsentLemma(
                new LemmaAndPos("negotiate", "VERB"),
                CefrLevel.B2,
                AbsenceType.APPEARS_TOO_EARLY,
                List.of(CefrLevel.A2),
                PriorityLevel.LOW,
                4800,
                "business");

        LemmaAbsenceLevelDiagnosis a2Diagnosis = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A2,
                60, 2, 3.33, 0.85,
                0.85, 0.80, 1.0,
                AbsenceAssessment.NEEDS_IMPROVEMENT,
                List.of(tooLateLemma, completelyAbsent, tooEarly),
                Collections.emptyList(),
                2, 0, 1);

        // Step: revisar_ubicacion — filter to only APPEARS_TOO_LATE lemmas for A2
        List<AbsentLemma> tooLateForA2 = a2Diagnosis.getAbsentLemmas().stream()
                .filter(l -> l.getAbsenceType() == AbsenceType.APPEARS_TOO_LATE
                        && l.getExpectedLevel() == CefrLevel.A2)
                .collect(Collectors.toList());

        assertFalse(tooLateForA2.isEmpty(),
                "There must be at least one APPEARS_TOO_LATE lemma for the A2 level");
        assertEquals(1, tooLateForA2.size(),
                "Exactly one APPEARS_TOO_LATE lemma is expected for A2");

        AbsentLemma candidate = tooLateForA2.get(0);
        assertEquals(CefrLevel.A2, candidate.getExpectedLevel(),
                "Lemma must be expected at A2");
        assertFalse(candidate.getPresentInLevels().isEmpty(),
                "Lemma must have at least one level where it is present");

        // Compute distance: minimum ordinal difference between presentInLevels and expectedLevel
        CefrLevel expectedLevel = candidate.getExpectedLevel();
        int minPresentOrdinal = candidate.getPresentInLevels().stream()
                .mapToInt(CefrLevel::ordinal)
                .min()
                .getAsInt();
        int distance = minPresentOrdinal - expectedLevel.ordinal();

        // Decision branch: distance == 1 → reforzar_nivel
        // (A2 ordinal=1, B1 ordinal=2 → distance=1)
        assertEquals(1, distance,
                "Distance must be 1 (A2 expected, B1 present): takes the reforzar_nivel branch");

        // Step: reforzar_nivel — the corrective action is to reinforce at the expected level.
        // The lemma appears in B1 so its presence there can be kept as reinforcement;
        // the user adds it at A2 where it was expected but missing.
        assertEquals(CefrLevel.B1, candidate.getPresentInLevels().get(0),
                "Lemma must be present in B1 (one level after expected A2)");
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El usuario filtra los lemas ausentes ... → El usuario revisa en que niveles post... → El usuario introduce el lema en su ni... [El lema aparece dos o mas niveles despues del esperado (por ejemplo, A1 esperado, aparece en B2)] → success")
    public void path2_elLemaApareceDosOMasNivelesDespuesDelEsperadoPorEjemploA1EsperadoApareceEnB2_success(
            ) {
        // Step: filtrar_too_late — filter APPEARS_TOO_LATE lemmas for A1 level.
        // The lemma "cat" is expected at A1 but only appears in B2 (three levels later).
        AbsentLemma tooLateLemma = new AbsentLemma(
                new LemmaAndPos("cat", "NOUN"),
                CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE,
                List.of(CefrLevel.B2),
                PriorityLevel.HIGH,
                420,
                "animals");

        // Include a lemma that appears at A2 (distance=1) to confirm the filter picks the right path
        AbsentLemma tooLateShortDistance = new AbsentLemma(
                new LemmaAndPos("dog", "NOUN"),
                CefrLevel.A1,
                AbsenceType.APPEARS_TOO_LATE,
                List.of(CefrLevel.A2),
                PriorityLevel.HIGH,
                310,
                "animals");

        LemmaAbsenceLevelDiagnosis a1Diagnosis = new LemmaAbsenceLevelDiagnosis(
                CefrLevel.A1,
                80, 2, 2.5, 0.95,
                1.0, 0.75, 1.0,
                AbsenceAssessment.NEEDS_IMPROVEMENT,
                List.of(tooLateLemma, tooLateShortDistance),
                Collections.emptyList(),
                2, 0, 0);

        // Step: revisar_ubicacion — filter APPEARS_TOO_LATE lemmas for A1
        List<AbsentLemma> tooLateForA1 = a1Diagnosis.getAbsentLemmas().stream()
                .filter(l -> l.getAbsenceType() == AbsenceType.APPEARS_TOO_LATE
                        && l.getExpectedLevel() == CefrLevel.A1)
                .collect(Collectors.toList());

        assertFalse(tooLateForA1.isEmpty(),
                "There must be APPEARS_TOO_LATE lemmas for the A1 level");
        assertEquals(2, tooLateForA1.size(),
                "Both too-late lemmas are expected at A1");

        // Find the lemma with the large gap (A1 expected, B2 present → distance=3 >= 2)
        AbsentLemma longDistanceLemma = tooLateForA1.stream()
                .filter(l -> l.getPresentInLevels().contains(CefrLevel.B2))
                .findFirst()
                .orElseThrow(() -> new AssertionError("Expected a lemma present in B2"));

        assertEquals(CefrLevel.A1, longDistanceLemma.getExpectedLevel(),
                "Lemma must be expected at A1");

        // Compute distance for the long-gap lemma
        CefrLevel expectedLevel = longDistanceLemma.getExpectedLevel();
        int minPresentOrdinal = longDistanceLemma.getPresentInLevels().stream()
                .mapToInt(CefrLevel::ordinal)
                .min()
                .getAsInt();
        int distance = minPresentOrdinal - expectedLevel.ordinal();

        // Decision branch: distance >= 2 → introducir_progresion
        // (A1 ordinal=0, B2 ordinal=3 → distance=3)
        assertTrue(distance >= 2,
                "Distance must be >= 2 (A1 expected, B2 present): takes the introducir_progresion branch");
        assertEquals(3, distance,
                "Distance must be exactly 3 (A1 → B2 spans three levels)");

        // Step: introducir_progresion — the corrective action is to introduce the lemma
        // at the expected level (A1) and in the intermediate levels (A2, B1) to build
        // a proper progression towards where it currently appears (B2).
        // Verify the intermediate levels span the gap: A2 and B1 lie between A1 and B2.
        List<CefrLevel> allLevels = List.of(CefrLevel.values());
        int expectedOrdinal = expectedLevel.ordinal();
        int presentOrdinal = minPresentOrdinal;
        long intermediateCount = allLevels.stream()
                .filter(l -> l.ordinal() > expectedOrdinal && l.ordinal() < presentOrdinal)
                .count();
        assertEquals(2, intermediateCount,
                "There must be 2 intermediate levels (A2 and B1) between A1 and B2 where the lemma should be progressively introduced");
    }
}
