package com.learney.contentaudit.auditdomain;

import com.learney.contentaudit.auditdomain.labs.AbsenceAssessment;
import com.learney.contentaudit.auditdomain.labs.AbsenceRecommendation;
import com.learney.contentaudit.auditdomain.labs.AbsenceType;
import com.learney.contentaudit.auditdomain.labs.AbsentLemma;
import com.learney.contentaudit.auditdomain.labs.EffortLevel;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceCourseDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAbsenceLevelDiagnosis;
import com.learney.contentaudit.auditdomain.labs.LemmaAndPos;
import com.learney.contentaudit.auditdomain.labs.PriorityLevel;
import com.learney.contentaudit.auditdomain.labs.RecommendationAction;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel — journey test stubs"
)
@Tag("F-LABS")
@Tag("F-LABS-J005")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FLabsJ005JourneyTest {

    // -----------------------------------------------------------------------
    // Volume threshold: <= 10 total affected lemmas = manageable, > 10 = high
    // per R030: 1-5 lemmas → LOW effort, 6-15 → MEDIUM, 16+ → HIGH
    // -----------------------------------------------------------------------
    private static final int MANAGEABLE_VOLUME_THRESHOLD = 10;

    // -----------------------------------------------------------------------
    // Helpers to build AbsentLemma fixtures
    // -----------------------------------------------------------------------

    private AbsentLemma highPriorityAbsentLemma(String lemma, int cocaRank) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, "NOUN"),
                CefrLevel.A1,
                AbsenceType.COMPLETELY_ABSENT,
                Collections.emptyList(),
                PriorityLevel.HIGH,
                cocaRank,
                "general");
    }

    private AbsentLemma mediumPriorityAbsentLemma(String lemma, int cocaRank) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, "VERB"),
                CefrLevel.B1,
                AbsenceType.COMPLETELY_ABSENT,
                Collections.emptyList(),
                PriorityLevel.MEDIUM,
                cocaRank,
                "general");
    }

    private AbsentLemma lowPriorityAbsentLemma(String lemma, int cocaRank) {
        return new AbsentLemma(
                new LemmaAndPos(lemma, "VERB"),
                CefrLevel.B2,
                AbsenceType.APPEARS_TOO_LATE,
                List.of(CefrLevel.B2),
                PriorityLevel.LOW,
                cocaRank,
                "general");
    }

    /**
     * Builds a list of N absent lemmas (HIGH priority, COCA rank < 1000) representing
     * a manageable volume (count <= MANAGEABLE_VOLUME_THRESHOLD).
     */
    private List<AbsentLemma> buildManageableHighPriorityLemmas() {
        // 3 HIGH-priority lemmas → total affected lemmas = 3 (<= 10 = manageable)
        return List.of(
                highPriorityAbsentLemma("cat", 420),
                highPriorityAbsentLemma("dog", 310),
                highPriorityAbsentLemma("house", 250));
    }

    /**
     * Builds a list of N absent lemmas (HIGH priority) representing a high volume
     * (count > MANAGEABLE_VOLUME_THRESHOLD).
     */
    private List<AbsentLemma> buildHighVolumeHighPriorityLemmas() {
        // 12 HIGH-priority lemmas → total affected lemmas = 12 (> 10 = alto)
        List<AbsentLemma> lemmas = new ArrayList<>();
        String[] words = {"cat", "dog", "house", "water", "food", "book",
                "door", "tree", "bird", "fish", "hand", "eye"};
        int[] ranks = {420, 310, 250, 180, 390, 450, 520, 600, 700, 730, 280, 350};
        for (int i = 0; i < words.length; i++) {
            lemmas.add(highPriorityAbsentLemma(words[i], ranks[i]));
        }
        return lemmas;
    }

    /**
     * Builds a list of MEDIUM/LOW priority absent lemmas with manageable volume.
     */
    private List<AbsentLemma> buildManageableMediumLowPriorityLemmas() {
        // 4 MEDIUM/LOW-priority lemmas → total = 4 (<= 10 = manageable)
        return List.of(
                mediumPriorityAbsentLemma("consider", 1500),
                mediumPriorityAbsentLemma("achieve", 2100),
                lowPriorityAbsentLemma("integrate", 3800),
                lowPriorityAbsentLemma("facilitate", 4200));
    }

    /**
     * Builds a list of MEDIUM/LOW priority absent lemmas with high volume.
     */
    private List<AbsentLemma> buildHighVolumeMediumLowPriorityLemmas() {
        // 12 MEDIUM/LOW-priority lemmas → total = 12 (> 10 = alto)
        List<AbsentLemma> lemmas = new ArrayList<>();
        String[] mediumWords = {"consider", "achieve", "discuss", "involve",
                "require", "suggest", "maintain", "establish"};
        String[] lowWords = {"integrate", "facilitate", "synthesize", "collaborate"};
        int[] mediumRanks = {1500, 2100, 1800, 2300, 1900, 2500, 2200, 2800};
        int[] lowRanks = {3800, 4200, 4500, 4800};
        for (int i = 0; i < mediumWords.length; i++) {
            lemmas.add(mediumPriorityAbsentLemma(mediumWords[i], mediumRanks[i]));
        }
        for (int i = 0; i < lowWords.length; i++) {
            lemmas.add(lowPriorityAbsentLemma(lowWords[i], lowRanks[i]));
        }
        return lemmas;
    }

    /**
     * Builds a recommendation from the given affected lemmas, action, priority, and effort.
     */
    private AbsenceRecommendation buildRecommendation(RecommendationAction action,
            PriorityLevel priority, EffortLevel effort, CefrLevel targetLevel,
            List<AbsentLemma> affectedLemmas, String description) {
        return new AbsenceRecommendation(
                action,
                description,
                priority,
                affectedLemmas,
                effort,
                0.1 * affectedLemmas.size(),
                targetLevel);
    }

    /**
     * Counts the total number of affected lemmas across all recommendations.
     */
    private int totalAffectedLemmaCount(List<AbsenceRecommendation> recommendations) {
        return recommendations.stream()
                .mapToInt(r -> r.getAffectedLemmas().size())
                .sum();
    }

    @Test
    @Order(1)
    @Tag("path-1")
    @DisplayName("path-1: El usuario revisa la lista de recomen... → El usuario filtra las recomendaciones... → El usuario revisa los lemas afectados... [Hay recomendaciones de prioridad HIGH] → El usuario estima el volumen total de... → El usuario implementa las correccione... [El volumen es manejable] → success")
    public void path1_hayRecomendacionesDePrioridadHIGH_elVolumenEsManejable_success() {
        // Step: revisar_recomendaciones — gate [F-LABS-R027, F-LABS-R028]
        // The analysis produced recommendations with structure and action types per R027/R028.
        // Each recommendation has: action, description, priority, affectedLemmas, effortLevel,
        // expectedImpact, targetLevel.

        // 3 HIGH-priority affected lemmas for A1 (COCA rank < 1000 per R011) → manageable volume
        List<AbsentLemma> affectedLemmas = buildManageableHighPriorityLemmas();

        // R028: COMPLETELY_ABSENT → ADD_VOCABULARY action
        // R029: A1 level → priority is always HIGH regardless of lemma priority
        // R030: 1-5 lemmas → LOW effort
        AbsenceRecommendation highRec = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.HIGH,
                EffortLevel.LOW,
                CefrLevel.A1,
                affectedLemmas,
                "Agregar oraciones que contengan los lemas ausentes en el nivel A1");

        List<AbsenceRecommendation> recommendations = List.of(highRec);

        // Step: filtrar_por_prioridad — at least one HIGH recommendation exists
        long highCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.HIGH)
                .count();
        assertTrue(highCount > 0,
                "There must be at least one HIGH-priority recommendation (filtrar_por_prioridad: Hay recomendaciones de prioridad HIGH)");

        // Step: revisar_detalle_critico — gate [F-LABS-R029, F-LABS-R030]
        // R027: each recommendation has all required fields
        assertFalse(highRec.getAffectedLemmas().isEmpty(),
                "Recommendation must list the affected lemmas (R027)");
        assertEquals(CefrLevel.A1, highRec.getTargetLevel(),
                "Recommendation must target the level where vocabulary is absent (R027)");
        assertEquals(RecommendationAction.ADD_VOCABULARY, highRec.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");

        // R029: A1 recommendations are always HIGH priority
        assertEquals(PriorityLevel.HIGH, highRec.getPriority(),
                "Recommendations for A1 must have HIGH priority regardless of lemma priority (R029)");

        // R030: 1-5 affected lemmas → LOW effort
        assertEquals(EffortLevel.LOW, highRec.getEffortLevel(),
                "Effort level must be LOW for 1-5 affected lemmas (R030)");
        assertTrue(highRec.getAffectedLemmas().size() <= 5,
                "Affected lemmas count must be 1-5 to yield LOW effort (R030)");

        // Step: estimar_volumen — total affected lemmas across all recommendations
        int totalVolume = totalAffectedLemmaCount(recommendations);
        assertTrue(totalVolume <= MANAGEABLE_VOLUME_THRESHOLD,
                "Total affected lemmas must be <= 10 to be considered manageable volume");

        // Step: implementar_directamente — low volume means direct implementation is viable
        // The user decides to implement the corrections directly and re-run the audit.
        // Outcome: success — the plan is to implement all HIGH recommendations in one cycle.
        String planDecision = totalVolume <= MANAGEABLE_VOLUME_THRESHOLD
                ? "implementar_directamente"
                : "crear_plan_iterativo";
        assertEquals("implementar_directamente", planDecision,
                "With manageable volume, user implements corrections directly (implementar_directamente → success)");
    }

    @Test
    @Order(2)
    @Tag("path-2")
    @DisplayName("path-2: El usuario revisa la lista de recomen... → El usuario filtra las recomendaciones... → El usuario revisa los lemas afectados... [Hay recomendaciones de prioridad HIGH] → El usuario estima el volumen total de... → El usuario crea un plan de mejora ite... [El volumen es alto] → success")
    public void path2_hayRecomendacionesDePrioridadHIGH_elVolumenEsAlto_success() {
        // Step: revisar_recomendaciones — gate [F-LABS-R027, F-LABS-R028]
        // Analysis produced multiple HIGH-priority recommendations covering many lemmas.

        // 12 HIGH-priority affected lemmas across two recommendations for A1 → high volume
        List<AbsentLemma> firstBatch = buildHighVolumeHighPriorityLemmas().subList(0, 7);
        List<AbsentLemma> secondBatch = buildHighVolumeHighPriorityLemmas().subList(7, 12);

        // R028: COMPLETELY_ABSENT → ADD_VOCABULARY; APPEARS_TOO_LATE → INTRODUCE_EARLIER
        // R029: A1 level → priority always HIGH
        // R030: 6-15 affected lemmas → MEDIUM effort
        AbsenceRecommendation highRec1 = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.HIGH,
                EffortLevel.MEDIUM,
                CefrLevel.A1,
                firstBatch,
                "Agregar oraciones que contengan los lemas ausentes en el nivel A1");

        AbsenceRecommendation highRec2 = buildRecommendation(
                RecommendationAction.INTRODUCE_EARLIER,
                PriorityLevel.HIGH,
                EffortLevel.MEDIUM,
                CefrLevel.A1,
                secondBatch,
                "Introducir los lemas ausentes en el nivel esperado (A1) ademas de donde ya aparecen");

        List<AbsenceRecommendation> recommendations = List.of(highRec1, highRec2);

        // Step: filtrar_por_prioridad — at least one HIGH recommendation exists
        long highCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.HIGH)
                .count();
        assertTrue(highCount > 0,
                "There must be at least one HIGH-priority recommendation (filtrar_por_prioridad: Hay recomendaciones de prioridad HIGH)");

        // Step: revisar_detalle_critico — gate [F-LABS-R029, F-LABS-R030]
        // R027: each recommendation targets the affected level with full detail
        assertEquals(CefrLevel.A1, highRec1.getTargetLevel(),
                "First recommendation must target A1 (R027)");
        assertEquals(CefrLevel.A1, highRec2.getTargetLevel(),
                "Second recommendation must target A1 (R027)");

        // R028: action types match the absence type
        assertEquals(RecommendationAction.ADD_VOCABULARY, highRec1.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");
        assertEquals(RecommendationAction.INTRODUCE_EARLIER, highRec2.getAction(),
                "APPEARS_TOO_LATE lemmas require INTRODUCE_EARLIER action (R028)");

        // R029: A1 recommendations are always HIGH priority
        recommendations.forEach(r ->
                assertEquals(PriorityLevel.HIGH, r.getPriority(),
                        "All A1 recommendations must have HIGH priority (R029)"));

        // R030: 6-15 affected lemmas → MEDIUM effort
        recommendations.forEach(r ->
                assertEquals(EffortLevel.MEDIUM, r.getEffortLevel(),
                        "Effort must be MEDIUM for 6-15 affected lemmas (R030)"));
        assertTrue(highRec1.getAffectedLemmas().size() >= 6 && highRec1.getAffectedLemmas().size() <= 15,
                "First recommendation must have 6-15 lemmas to yield MEDIUM effort (R030)");

        // Step: estimar_volumen — total affected lemmas across all recommendations
        int totalVolume = totalAffectedLemmaCount(recommendations);
        assertTrue(totalVolume > MANAGEABLE_VOLUME_THRESHOLD,
                "Total affected lemmas must be > 10 to be considered high volume");

        // Step: crear_plan_iterativo — high volume requires iterative improvement plan
        // The user creates an iterative plan prioritizing highest-impact recommendations.
        // Outcome: success — plan is created iteratively across multiple cycles.
        String planDecision = totalVolume <= MANAGEABLE_VOLUME_THRESHOLD
                ? "implementar_directamente"
                : "crear_plan_iterativo";
        assertEquals("crear_plan_iterativo", planDecision,
                "With high volume, user creates an iterative improvement plan (crear_plan_iterativo → success)");
    }

    @Test
    @Order(3)
    @Tag("path-3")
    @DisplayName("path-3: El usuario revisa la lista de recomen... → El usuario filtra las recomendaciones... → El usuario revisa las recomendaciones... [Solo hay recomendaciones de prioridad MEDIUM o LOW] → El usuario estima el volumen total de... → El usuario implementa las correccione... [El volumen es manejable] → success")
    public void path3_soloHayRecomendacionesDePrioridadMEDIUMOLOW_elVolumenEsManejable_success() {
        // Step: revisar_recomendaciones — gate [F-LABS-R027, F-LABS-R028]
        // Analysis produced only MEDIUM/LOW recommendations (B1/B2 levels with medium/low lemas).
        // No HIGH-priority recommendations exist.

        // 4 MEDIUM/LOW-priority affected lemmas → manageable volume (<= 10)
        List<AbsentLemma> mediumLemmas = List.of(
                mediumPriorityAbsentLemma("consider", 1500),
                mediumPriorityAbsentLemma("achieve", 2100));
        List<AbsentLemma> lowLemmas = List.of(
                lowPriorityAbsentLemma("integrate", 3800),
                lowPriorityAbsentLemma("facilitate", 4200));

        // R028: COMPLETELY_ABSENT → ADD_VOCABULARY
        // R029: B1 level + MEDIUM lemma priority → MEDIUM recommendation priority
        // R030: 1-5 lemmas → LOW effort
        AbsenceRecommendation mediumRec = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.MEDIUM,
                EffortLevel.LOW,
                CefrLevel.B1,
                mediumLemmas,
                "Agregar oraciones que contengan los lemas ausentes en el nivel B1");

        // R029: B1 level + LOW lemma priority → LOW recommendation priority
        // R030: 1-5 lemmas → LOW effort
        AbsenceRecommendation lowRec = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.LOW,
                EffortLevel.LOW,
                CefrLevel.B2,
                lowLemmas,
                "Agregar oraciones que contengan los lemas ausentes en el nivel B2");

        List<AbsenceRecommendation> recommendations = List.of(mediumRec, lowRec);

        // Step: filtrar_por_prioridad — no HIGH recommendations → path goes to revisar_prioridades_menores
        long highCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.HIGH)
                .count();
        assertEquals(0, highCount,
                "There must be no HIGH-priority recommendations — only MEDIUM or LOW (filtrar_por_prioridad: Solo hay recomendaciones de prioridad MEDIUM o LOW)");

        long mediumOrLowCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.MEDIUM
                        || r.getPriority() == PriorityLevel.LOW)
                .count();
        assertEquals(recommendations.size(), mediumOrLowCount,
                "All recommendations must be MEDIUM or LOW priority");

        // Step: revisar_prioridades_menores — user reviews MEDIUM/LOW recommendations
        // R027: recommendations have all required fields
        recommendations.forEach(r -> {
            assertFalse(r.getAffectedLemmas().isEmpty(),
                    "Each recommendation must list affected lemmas (R027)");
            assertTrue(r.getExpectedImpact() > 0,
                    "Each recommendation must have a positive expected impact (R027)");
        });

        // R028: action type matches absence type (COMPLETELY_ABSENT → ADD_VOCABULARY)
        assertEquals(RecommendationAction.ADD_VOCABULARY, mediumRec.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");
        assertEquals(RecommendationAction.ADD_VOCABULARY, lowRec.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");

        // R029: B1 + MEDIUM lemas → MEDIUM priority; B1/B2 + LOW lemas → LOW priority
        assertEquals(PriorityLevel.MEDIUM, mediumRec.getPriority(),
                "B1 recommendation with MEDIUM lemmas must have MEDIUM priority (R029)");
        assertEquals(PriorityLevel.LOW, lowRec.getPriority(),
                "B2 recommendation with LOW lemmas must have LOW priority (R029)");

        // R030: 1-5 affected lemmas → LOW effort
        assertEquals(EffortLevel.LOW, mediumRec.getEffortLevel(),
                "Effort must be LOW for 1-5 affected lemmas (R030)");
        assertEquals(EffortLevel.LOW, lowRec.getEffortLevel(),
                "Effort must be LOW for 1-5 affected lemmas (R030)");

        // Step: estimar_volumen — total affected lemmas across all recommendations
        int totalVolume = totalAffectedLemmaCount(recommendations);
        assertTrue(totalVolume <= MANAGEABLE_VOLUME_THRESHOLD,
                "Total affected lemmas must be <= 10 to be considered manageable volume");

        // Step: implementar_directamente — manageable volume with no HIGH-priority items
        // Outcome: success — all recommendations can be addressed directly in one cycle.
        String planDecision = totalVolume <= MANAGEABLE_VOLUME_THRESHOLD
                ? "implementar_directamente"
                : "crear_plan_iterativo";
        assertEquals("implementar_directamente", planDecision,
                "With MEDIUM/LOW recommendations and manageable volume, user implements directly (implementar_directamente → success)");
    }

    @Test
    @Order(4)
    @Tag("path-4")
    @DisplayName("path-4: El usuario revisa la lista de recomen... → El usuario filtra las recomendaciones... → El usuario revisa las recomendaciones... [Solo hay recomendaciones de prioridad MEDIUM o LOW] → El usuario estima el volumen total de... → El usuario crea un plan de mejora ite... [El volumen es alto] → success")
    public void path4_soloHayRecomendacionesDePrioridadMEDIUMOLOW_elVolumenEsAlto_success() {
        // Step: revisar_recomendaciones — gate [F-LABS-R027, F-LABS-R028]
        // Analysis produced only MEDIUM/LOW recommendations but covering many lemmas (high volume).
        // No HIGH-priority recommendations exist.

        // 12 MEDIUM/LOW-priority affected lemmas → high volume (> 10)
        List<AbsentLemma> mediumLemmas = buildHighVolumeMediumLowPriorityLemmas().subList(0, 8);
        List<AbsentLemma> lowLemmas = buildHighVolumeMediumLowPriorityLemmas().subList(8, 12);

        // R030: 6-15 lemmas → MEDIUM effort
        // R029: B1 level + MEDIUM lemas → MEDIUM priority
        AbsenceRecommendation mediumRec = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.MEDIUM,
                EffortLevel.MEDIUM,
                CefrLevel.B1,
                mediumLemmas,
                "Agregar oraciones que contengan los lemas ausentes en el nivel B1");

        // R029: B2 level + LOW lemas → LOW priority
        // R030: 1-5 lemmas → LOW effort
        AbsenceRecommendation lowRec = buildRecommendation(
                RecommendationAction.ADD_VOCABULARY,
                PriorityLevel.LOW,
                EffortLevel.LOW,
                CefrLevel.B2,
                lowLemmas,
                "Agregar oraciones que contengan los lemas ausentes en el nivel B2");

        List<AbsenceRecommendation> recommendations = List.of(mediumRec, lowRec);

        // Step: filtrar_por_prioridad — no HIGH recommendations → revisar_prioridades_menores
        long highCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.HIGH)
                .count();
        assertEquals(0, highCount,
                "There must be no HIGH-priority recommendations — only MEDIUM or LOW (filtrar_por_prioridad: Solo hay recomendaciones de prioridad MEDIUM o LOW)");

        long mediumOrLowCount = recommendations.stream()
                .filter(r -> r.getPriority() == PriorityLevel.MEDIUM
                        || r.getPriority() == PriorityLevel.LOW)
                .count();
        assertEquals(recommendations.size(), mediumOrLowCount,
                "All recommendations must be MEDIUM or LOW priority");

        // Step: revisar_prioridades_menores — user reviews MEDIUM/LOW recommendations
        // R027: each recommendation has full detail: action, description, priority,
        // affectedLemmas, effortLevel, expectedImpact, targetLevel
        recommendations.forEach(r -> {
            assertFalse(r.getAffectedLemmas().isEmpty(),
                    "Each recommendation must list affected lemmas (R027)");
            assertTrue(r.getExpectedImpact() > 0,
                    "Each recommendation must have a positive expected impact (R027)");
            assertTrue(r.getTargetLevel() != null,
                    "Each recommendation must specify the target CEFR level (R027)");
        });

        // R028: action types match the absence types
        assertEquals(RecommendationAction.ADD_VOCABULARY, mediumRec.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");
        assertEquals(RecommendationAction.ADD_VOCABULARY, lowRec.getAction(),
                "COMPLETELY_ABSENT lemmas require ADD_VOCABULARY action (R028)");

        // R029: B1 + MEDIUM lemas → MEDIUM priority; B2 + LOW lemas → LOW priority
        assertEquals(PriorityLevel.MEDIUM, mediumRec.getPriority(),
                "B1 recommendation with MEDIUM lemmas must have MEDIUM priority (R029)");
        assertEquals(PriorityLevel.LOW, lowRec.getPriority(),
                "B2 recommendation with LOW lemmas must have LOW priority (R029)");

        // R030: effort matches lemma count
        assertEquals(EffortLevel.MEDIUM, mediumRec.getEffortLevel(),
                "Effort must be MEDIUM for 6-15 affected lemmas (R030)");
        assertEquals(EffortLevel.LOW, lowRec.getEffortLevel(),
                "Effort must be LOW for 1-5 affected lemmas (R030)");
        assertTrue(mediumRec.getAffectedLemmas().size() >= 6,
                "mediumRec must have >= 6 lemmas to yield MEDIUM effort (R030)");
        assertTrue(lowRec.getAffectedLemmas().size() <= 5,
                "lowRec must have <= 5 lemmas to yield LOW effort (R030)");

        // Step: estimar_volumen — total affected lemmas across all recommendations
        int totalVolume = totalAffectedLemmaCount(recommendations);
        assertTrue(totalVolume > MANAGEABLE_VOLUME_THRESHOLD,
                "Total affected lemmas must be > 10 to be considered high volume");

        // Step: crear_plan_iterativo — even without HIGH priority, the large volume
        // requires breaking the work into multiple improvement cycles.
        // Outcome: success — iterative plan created, prioritizing by expected impact.
        String planDecision = totalVolume <= MANAGEABLE_VOLUME_THRESHOLD
                ? "implementar_directamente"
                : "crear_plan_iterativo";
        assertEquals("crear_plan_iterativo", planDecision,
                "With MEDIUM/LOW recommendations but high volume, user creates iterative plan (crear_plan_iterativo → success)");
    }
}
