package com.learney.contentaudit.auditdomain.coca;

import com.learney.contentaudit.auditdomain.CocaBucketsConfig;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class DefaultImprovementPlanner implements ImprovementPlanner {

    @Override
    public List<ImprovementDirective> plan(List<LevelBucketDistribution> levels,
            BandConfiguration bandConfig, CocaBucketsConfig config) {
        List<ImprovementDirective> directives = new ArrayList<>();

        if (levels == null) {
            return directives;
        }

        for (LevelBucketDistribution level : levels) {
            // Level-wide bucket results
            generateDirectivesForBuckets(
                    level.getBucketResults(), level.getLevelName(), bandConfig, directives);

            // Quarter results (R033)
            List<QuarterResult> quarters = level.getQuarterResults();
            if (quarters != null) {
                for (QuarterResult quarter : quarters) {
                    String quarterLevelName = level.getLevelName() + " Q" + quarter.getIndex();
                    generateDirectivesForBuckets(
                            quarter.getBucketResults(), quarterLevelName, bandConfig, directives);
                }
            }
        }

        return directives;
    }

    private void generateDirectivesForBuckets(List<BucketResult> bucketResults,
            String levelName, BandConfiguration bandConfig, List<ImprovementDirective> directives) {
        if (bucketResults == null) {
            return;
        }

        for (BucketResult result : bucketResults) {
            AssessmentState assessment = result.getAssessment();
            // Only generate directives for DEFICIENT or EXCESSIVE (R032)
            if (assessment != AssessmentState.DEFICIENT && assessment != AssessmentState.EXCESSIVE) {
                continue;
            }

            FrequencyBand band = findBand(result.getBandName(), bandConfig);
            int fromRank = band != null ? band.getLowerBound() : 0;
            int toRank = band != null ? band.getUpperBound() : 0;

            ImprovementDirectiveType type = assessment == AssessmentState.DEFICIENT
                    ? ImprovementDirectiveType.ENRICH
                    : ImprovementDirectiveType.REDUCE;

            directives.add(new ImprovementDirective(
                    type,
                    result.getBandName(),
                    levelName,
                    fromRank,
                    toRank,
                    result.getPercentage(),
                    result.getTargetPercentage()
            ));
        }
    }

    private FrequencyBand findBand(String bandName, BandConfiguration bandConfig) {
        if (bandConfig == null || bandConfig.getBands() == null) {
            return null;
        }
        for (FrequencyBand band : bandConfig.getBands()) {
            if (bandName.equals(band.getName())) {
                return band;
            }
        }
        return null;
    }
}
