package com.learney.contentaudit.auditcli.commands;

import java.util.concurrent.Callable;

import javax.annotation.processing.Generated;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Spec;
import picocli.CommandLine.Model.CommandSpec;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
@Command(
        name = "content-audit",
        description = "Content quality audit tool for educational courses.%n%n"
                + "Analyzes course content for sentence length, vocabulary distribution,%n"
                + "title length, and other quality metrics across CEFR levels.",
        mixinStandardHelpOptions = true,
        version = "content-audit 0.0.1",
        footer = {
                "",
                "Examples:",
                "  # Run a full audit on a course",
                "  content-audit analyze db/english-course",
                "",
                "  # List available analyzers",
                "  content-audit analyzer list",
                "",
                "  # Show config for a specific analyzer",
                "  content-audit analyzer config sentence-length",
        }
)
class ContentAuditCmd implements Callable<Integer> {
    @Spec
    CommandSpec spec;

    @Override
    public Integer call() throws Exception {
        spec.commandLine().usage(System.out);
        return 0;
    }
}
