package com.learney.contentaudit.auditcli.commands;

import com.learney.contentaudit.auditcli.RefinerReviseCommand;
import com.learney.contentaudit.revisiondomain.RevisionEngine;
import java.util.concurrent.Callable;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
final class RefinerReviseCmd implements RefinerReviseCommand, Callable<Integer> {
    private final RevisionEngine revisionEngine;

    public RefinerReviseCmd(RevisionEngine revisionEngine) {
        this.revisionEngine = revisionEngine;
    }

    @Override
    public int revise(String planId, String taskId) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public Integer call() throws Exception {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
