package com.learney.contentaudit.revisioninfrastructure.lagenopenai;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.argThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.learney.contentaudit.refinerdomain.LemmaAbsenceCorrectionContext;
import com.learney.contentaudit.refinerdomain.MisplacedLemmaContext;
import com.learney.contentaudit.refinerdomain.SuggestedLemma;
import com.learney.contentaudit.revisiondomain.ProposalStrategyFailedException;
import com.learney.contentaudit.revisiondomain.lemmaabsence.LemmaAbsenceGeneratorResponse;
import com.learney.contentaudit.revisioninfrastructure.lagen.LlmGenerationFailureCategory;
import com.learney.contentaudit.auditdomain.CefrLevel;
import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.output.Response;
import java.net.ConnectException;
import java.net.SocketTimeoutException;
import java.util.List;
import javax.annotation.processing.Generated;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class LemmaAbsenceLlmGeneratorTest {

    private static final String STRATEGY_NAME = "lemma-absence-llm";
    private static final String TASK_ID = "task-42";

    private ChatLanguageModel mockModel;
    private LemmaAbsencePromptBuilder mockPromptBuilder;
    private LemmaAbsenceResponseParser mockResponseParser;
    private LangChainErrorClassifier mockErrorClassifier;
    private LemmaAbsenceLlmGenerator generator;

    @BeforeEach
    void setUp() {
        mockModel = mock(ChatLanguageModel.class);
        mockPromptBuilder = mock(LemmaAbsencePromptBuilder.class);
        mockResponseParser = mock(LemmaAbsenceResponseParser.class);
        mockErrorClassifier = mock(LangChainErrorClassifier.class);
        generator = new LemmaAbsenceLlmGenerator(
                mockModel, mockPromptBuilder, mockResponseParser, mockErrorClassifier, STRATEGY_NAME);
    }

    private static LemmaAbsenceCorrectionContext buildContext() {
        return new LemmaAbsenceCorrectionContext(
                TASK_ID,
                "She runs every morning.",
                "Ella corre cada mañana.",
                "Daily Routines",
                "Write simple present tense sentences.",
                "Everyday Life",
                CefrLevel.A1,
                List.of(new MisplacedLemmaContext("run", "VERB", CefrLevel.B1, CefrLevel.A1, 150)),
                List.of(new SuggestedLemma("walk", "VERB", "A1 level synonym", 80)),
                "She ____[runs|walks] every morning."
        );
    }

    @SuppressWarnings("unchecked")
    private static Response<AiMessage> aiResponse(String text) {
        AiMessage aiMessage = AiMessage.from(text);
        return Response.from(aiMessage);
    }

    @Test
    @DisplayName("generate returns a LemmaAbsenceGeneratorResponse parsed from the model output on the happy path")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R005")
    public void generateReturnsALemmaAbsenceGeneratorResponseParsedFromTheModelOutputOnTheHappyPath(
            ) {
        // R005: when the model responds with valid JSON, generate() returns a LemmaAbsenceGeneratorResponse
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("You are a specialist...");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("Correct this exercise...");
        when(mockModel.generate(anyList())).thenReturn(aiResponse(
                "{\"quizSentence\": \"She ____[walks|runs].\", \"translation\": \"Ella camina.\"}"));
        LemmaAbsenceGeneratorResponse expectedResponse =
                new LemmaAbsenceGeneratorResponse("She ____[walks|runs].", "Ella camina.");
        when(mockResponseParser.parse(any(), any(), any())).thenReturn(expectedResponse);

        LemmaAbsenceGeneratorResponse result = generator.generate(ctx);

        assertEquals("She ____[walks|runs].", result.getQuizSentence(),
                "generate() must return the parsed quizSentence (R005)");
        assertEquals("Ella camina.", result.getTranslation(),
                "generate() must return the parsed translation (R005)");
    }

    @Test
    @DisplayName("generate sends both the system prompt and the user prompt produced from the context to the model")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R003")
    public void generateSendsBothTheSystemPromptAndTheUserPromptProducedFromTheContextToTheModel() {
        // R003: "todos los campos poblados de ese contexto deben informar la generación"
        // The generator must send both a SystemMessage and a UserMessage containing the context.
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("SYSTEM: You are a specialist.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("USER: Context data here.");
        when(mockModel.generate(anyList())).thenReturn(aiResponse(
                "{\"quizSentence\": \"She ____[walks|runs].\", \"translation\": \"Ella camina.\"}"));
        when(mockResponseParser.parse(any(), any(), any()))
                .thenReturn(new LemmaAbsenceGeneratorResponse("She ____[walks|runs].", "Ella camina."));

        generator.generate(ctx);

        // Verify that generate() was called with a list containing BOTH a SystemMessage and a UserMessage
        verify(mockModel).generate(argThat((List<ChatMessage> messages) -> {
            boolean hasSystem = messages.stream().anyMatch(m -> m instanceof SystemMessage
                    && ((SystemMessage) m).text().equals("SYSTEM: You are a specialist."));
            boolean hasUser = messages.stream().anyMatch(m -> m instanceof UserMessage
                    && ((UserMessage) m).singleText().equals("USER: Context data here."));
            return hasSystem && hasUser;
        }));
    }

    @Test
    @DisplayName("generate issues exactly one round-trip to the model per invocation (no automatic retry)")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R007")
    public void generateIssuesExactlyOneRoundtripToTheModelPerInvocationNoAutomaticRetry() {
        // R007: "el sistema no reintenta la consulta automáticamente"
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenReturn(aiResponse(
                "{\"quizSentence\": \"She ____[walks|runs].\", \"translation\": \"Ella camina.\"}"));
        when(mockResponseParser.parse(any(), any(), any()))
                .thenReturn(new LemmaAbsenceGeneratorResponse("She ____[walks|runs].", "Ella camina."));

        generator.generate(ctx);

        // chatModel.generate() must be called exactly ONCE (no retry)
        verify(mockModel, times(1)).generate(anyList());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException without persisting any partial response when the parser rejects the raw text")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R007")
    public void generateRaisesProposalStrategyFailedExceptionWithoutPersistingAnyPartialResponseWhenTheParserRejectsTheRawText(
            ) {
        // R007: "ante cualquier falla, el sistema no entrega LemmaAbsenceGeneratorResponse parcial"
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenReturn(aiResponse("not valid json"));
        // The parser rejects the raw text
        when(mockResponseParser.parse(any(), any(), any()))
                .thenThrow(new ProposalStrategyFailedException(STRATEGY_NAME, TASK_ID,
                        "LLM_RESPONSE_MALFORMED: not valid JSON"));

        // generate() must re-throw the parser's exception (not return a partial response)
        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx),
                "Parser failure must propagate as ProposalStrategyFailedException (R007)"
        );

        assertTrue(thrown.getReason().contains("LLM_RESPONSE_MALFORMED"),
                "Exception must carry the parser's failure reason (R007): " + thrown.getReason());
    }

    @Test
    @DisplayName("generate prefixes the failure reason with the LlmGenerationFailureCategory name returned by the classifier")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generatePrefixesTheFailureReasonWithTheLlmGenerationFailureCategoryNameReturnedByTheClassifier(
            ) {
        // R006: "la categoría viaja en el reason de modo que sea legible por humanos"
        // The reason format is "CATEGORY_NAME: detail"
        // ConnectException is checked; wrap it so Mockito accepts thenThrow.
        // The generator catches Exception, passes the wrapper to classify(); stub by the wrapper ref.
        LemmaAbsenceCorrectionContext ctx = buildContext();
        ConnectException connectEx = new ConnectException("Connection refused");
        RuntimeException wrapped = new RuntimeException("LLM call failed", connectEx);
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(wrapped);
        when(mockErrorClassifier.classify(wrapped)).thenReturn(LlmGenerationFailureCategory.LLM_UNREACHABLE);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith(LlmGenerationFailureCategory.LLM_UNREACHABLE.name()),
                "reason must start with the category name (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate embeds the strategyName 'lemma-absence-llm' inside the message of any ProposalStrategyFailedException it raises")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R001")
    public void generateEmbedsTheStrategyNameLemmaabsencellmInsideTheMessageOfAnyProposalStrategyFailedExceptionItRaises(
            ) {
        // R001: strategy name 'lemma-absence-llm' must be identifiable in every failure report
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(new RuntimeException("Unexpected failure"));
        when(mockErrorClassifier.classify(any())).thenReturn(LlmGenerationFailureCategory.LLM_OTHER);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertEquals(STRATEGY_NAME, thrown.getStrategyName(),
                "strategyName must be 'lemma-absence-llm' (R001)");
        assertTrue(thrown.getMessage().contains(STRATEGY_NAME),
                "Exception message must embed 'lemma-absence-llm' (R001): " + thrown.getMessage());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_RESPONSE_EMPTY when the model returns empty text")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMRESPONSEEMPTYWhenTheModelReturnsEmptyText(
            ) {
        // R006 LLM_RESPONSE_EMPTY: "string vacío, ausencia total de texto"
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenReturn(aiResponse(""));  // empty response
        // The parser raises LLM_RESPONSE_EMPTY for empty text
        when(mockResponseParser.parse(any(), any(), any()))
                .thenThrow(new ProposalStrategyFailedException(STRATEGY_NAME, TASK_ID,
                        "LLM_RESPONSE_EMPTY: model returned no content"));

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_RESPONSE_EMPTY"),
                "reason must start with LLM_RESPONSE_EMPTY (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_RESPONSE_MALFORMED when the model returns text the parser cannot interpret")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMRESPONSEMALFORMEDWhenTheModelReturnsTextTheParserCannotInterpret(
            ) {
        // R006 LLM_RESPONSE_MALFORMED: "el modelo produjo contenido pero no cumple R005"
        LemmaAbsenceCorrectionContext ctx = buildContext();
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenReturn(aiResponse("Sorry, I cannot help with that."));
        when(mockResponseParser.parse(any(), any(), any()))
                .thenThrow(new ProposalStrategyFailedException(STRATEGY_NAME, TASK_ID,
                        "LLM_RESPONSE_MALFORMED: response is not valid JSON"));

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_RESPONSE_MALFORMED"),
                "reason must start with LLM_RESPONSE_MALFORMED (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_OTHER when the model client throws a Throwable not matched by any specific category")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMOTHERWhenTheModelClientThrowsAThrowableNotMatchedByAnySpecificCategory(
            ) {
        // R006 LLM_OTHER: catch-all for unrecognised Throwables from the model client
        LemmaAbsenceCorrectionContext ctx = buildContext();
        RuntimeException unexpected = new RuntimeException("Something weird happened");
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(unexpected);
        when(mockErrorClassifier.classify(unexpected)).thenReturn(LlmGenerationFailureCategory.LLM_OTHER);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_OTHER"),
                "reason must start with LLM_OTHER (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_UNREACHABLE when the model client throws ConnectException")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMUNREACHABLEWhenTheModelClientThrowsConnectException(
            ) {
        // R006 LLM_UNREACHABLE: "conexión rechazada" -> ConnectException
        // ConnectException is a checked exception; wrap it so Mockito accepts thenThrow.
        // The generator catches Exception, passes the wrapper to classify(); the real classifier
        // walks getCause() and finds ConnectException. The mock classifier returns the expected category.
        LemmaAbsenceCorrectionContext ctx = buildContext();
        ConnectException connectEx = new ConnectException("Connection refused to localhost:1234");
        RuntimeException wrapped = new RuntimeException("LLM call failed", connectEx);
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(wrapped);
        when(mockErrorClassifier.classify(wrapped)).thenReturn(LlmGenerationFailureCategory.LLM_UNREACHABLE);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_UNREACHABLE"),
                "reason must start with LLM_UNREACHABLE (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_TIMEOUT when the model client throws SocketTimeoutException")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMTIMEOUTWhenTheModelClientThrowsSocketTimeoutException(
            ) {
        // R006 LLM_TIMEOUT: "la consulta excedió el budget de tiempo configurado"
        // SocketTimeoutException is checked; wrap it so Mockito accepts thenThrow.
        LemmaAbsenceCorrectionContext ctx = buildContext();
        SocketTimeoutException timeoutEx = new SocketTimeoutException("Read timed out after 30s");
        RuntimeException wrapped = new RuntimeException("LLM call timed out", timeoutEx);
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(wrapped);
        when(mockErrorClassifier.classify(wrapped)).thenReturn(LlmGenerationFailureCategory.LLM_TIMEOUT);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_TIMEOUT"),
                "reason must start with LLM_TIMEOUT (R006), got: " + thrown.getReason());
    }

    @Test
    @DisplayName("generate raises ProposalStrategyFailedException with reason prefixed LLM_AUTH_FAILED when the model client throws an OpenAiHttpException with status 401")
    @Tag("FEAT-LAGEN")
    @Tag("F-LAGEN-R006")
    public void generateRaisesProposalStrategyFailedExceptionWithReasonPrefixedLLMAUTHFAILEDWhenTheModelClientThrowsAnOpenAiHttpExceptionWithStatus401(
            ) {
        // R006 LLM_AUTH_FAILED: "credenciales inválidas o ausentes"
        LemmaAbsenceCorrectionContext ctx = buildContext();
        dev.ai4j.openai4j.OpenAiHttpException authEx =
                new dev.ai4j.openai4j.OpenAiHttpException(401, "Unauthorized");
        when(mockPromptBuilder.buildSystemPrompt()).thenReturn("System prompt.");
        when(mockPromptBuilder.buildUserPrompt(ctx)).thenReturn("User prompt.");
        when(mockModel.generate(anyList())).thenThrow(new RuntimeException("HTTP 401", authEx));
        when(mockErrorClassifier.classify(any())).thenReturn(LlmGenerationFailureCategory.LLM_AUTH_FAILED);

        ProposalStrategyFailedException thrown = assertThrows(
                ProposalStrategyFailedException.class,
                () -> generator.generate(ctx)
        );

        assertTrue(thrown.getReason().startsWith("LLM_AUTH_FAILED"),
                "reason must start with LLM_AUTH_FAILED (R006), got: " + thrown.getReason());
    }
}
