package com.learney.contentaudit.revisiondomain.engine;
import com.learney.contentaudit.auditdomain.CourseMapper;
import com.learney.contentaudit.auditdomain.AuditEngine;
import com.learney.contentaudit.auditdomain.AuditNode;
import com.learney.contentaudit.auditdomain.AuditReport;
import com.learney.contentaudit.auditdomain.AuditReportStore;
import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.auditdomain.AuditableCourse;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.impactpreview.DimensionDelta;
import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreview;
import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreviewAvailability;
import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreviewComputer;
import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreviewUnavailability;
import com.learney.contentaudit.revisiondomain.impactpreview.ImpactPreviewUnavailabilityReason;
import com.learney.contentaudit.revisiondomain.impactpreview.LevelImpact;
import com.learney.contentaudit.revisiondomain.impactpreview.ScoreDelta;
import javax.annotation.processing.Generated;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Implementacion pura del puerto ImpactPreviewComputer.
 *
 * Algoritmo:
 * 1. Cargar el AuditReport baseline (loadLatest) - si no hay: UNAVAILABLE/BASE_AUDIT_UNAVAILABLE
 * 2. Verificar que el nodo objetivo existe - si no: UNAVAILABLE/TARGET_NODE_ABSENT
 * 3. Aplicar elementAfter en memoria via CourseElementLocator.replace
 * 4. Mapear el curso simulado a AuditableCourse y correr auditEngine.runAudit
 * 5. Calcular el diff jerarquico nodo→contenedores→curso
 *
 * Nunca lanza excepcion: todas las fallas se materializan como UNAVAILABLE (F-PIPRE-R009).
 * La simulacion no persiste nada - es funcion pura (F-PIPRE-R002).
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultImpactPreviewComputer implements ImpactPreviewComputer {
    private final CourseMapper courseMapper;

    private final AuditEngine auditEngine;

    private final CourseElementLocator elementLocator;

    private final AuditReportStore auditReportStore;

    public DefaultImpactPreviewComputer(CourseMapper courseMapper, AuditEngine auditEngine,
            CourseElementLocator elementLocator, AuditReportStore auditReportStore) {
        this.courseMapper = courseMapper;
        this.auditEngine = auditEngine;
        this.elementLocator = elementLocator;
        this.auditReportStore = auditReportStore;
    }

    @Override
    public ImpactPreview compute(CourseEntity currentCourse, RevisionProposal proposal) {
        String proposalId = proposal.getProposalId();

        // Paso 1: Cargar el AuditReport baseline
        // Usamos course.getId() para identificar el curso en el mensaje de error (F-PIPRE-R009)
        String courseId = currentCourse.getId();
        Optional<AuditReport> baselineOpt = auditReportStore.loadLatest();
        if (baselineOpt.isEmpty()) {
            return unavailable(proposalId,
                    ImpactPreviewUnavailabilityReason.BASE_AUDIT_UNAVAILABLE,
                    "No se encontro un AuditReport disponible para usar como linea base del curso '"
                            + courseId + "'");
        }
        AuditReport baseline = baselineOpt.get();

        AuditTarget nodeTarget = proposal.getNodeTarget();
        String nodeId = proposal.getNodeId();

        // Paso 2: Aplicar elementAfter en memoria (simulacion what-if) y verificar nodo
        AuditReport simulated;
        try {
            CourseEntity simulatedCourse = elementLocator.replace(currentCourse, proposal.getElementAfter());

            // Paso 3: Verificar que el nodo objetivo existe en el curso simulado (F-PIPRE-R009)
            Optional<CourseElementSnapshot> snapshotOpt =
                    elementLocator.snapshot(simulatedCourse, nodeTarget, nodeId);
            if (snapshotOpt.isEmpty()) {
                return unavailable(proposalId,
                        ImpactPreviewUnavailabilityReason.TARGET_NODE_ABSENT,
                        "El nodo objetivo '" + nodeId + "' (" + nodeTarget
                                + ") no se encontro en el curso simulado");
            }

            // Paso 4: Mapear el curso simulado a AuditableCourse y auditar
            AuditableCourse auditableCourse = courseMapper.map(simulatedCourse);
            simulated = auditEngine.runAudit(auditableCourse);
        } catch (Exception e) {
            return unavailable(proposalId,
                    ImpactPreviewUnavailabilityReason.SIMULATION_FAILED,
                    "La simulacion de auditoria fallo: " + e.getMessage());
        }

        // Paso 5: Calcular el diff jerarquico
        List<LevelImpact> levelImpacts = buildLevelImpacts(baseline, simulated, nodeTarget, nodeId);

        return new ImpactPreview(
                proposalId,
                Instant.now(),
                ImpactPreviewAvailability.AVAILABLE,
                null,
                levelImpacts);
    }

    // -------------------------------------------------------------------------
    // Calculo del diff jerarquico
    // -------------------------------------------------------------------------

    /**
     * Construye la lista de LevelImpact recorriendo la cadena jerarquica desde el
     * nodo objetivo hasta el COURSE, en orden de hoja a raiz.
     *
     * Para cada nivel que corresponde a la cadena de la propuesta, buscamos el nodo
     * en el arbol de ambos reportes (baseline y simulado) y calculamos los deltas de
     * scores por dimension.
     */
    private List<LevelImpact> buildLevelImpacts(AuditReport baseline, AuditReport simulated,
            AuditTarget nodeTarget, String nodeId) {

        List<LevelImpact> impacts = new ArrayList<>();

        // Niveles relevantes en orden de hoja a raiz segun el tipo del nodo objetivo
        List<AuditTarget> chain = buildChain(nodeTarget);

        for (AuditTarget level : chain) {
            String targetNodeId = level == nodeTarget ? nodeId : null;
            AuditNode baseNode = findNode(baseline.getRoot(), level, targetNodeId);
            AuditNode simNode = findNode(simulated.getRoot(), level, targetNodeId);

            if (baseNode == null || simNode == null) {
                // Este nivel no existe en uno de los reportes; omitir (R004: no inventar niveles)
                continue;
            }

            LevelImpact levelImpact = buildLevelImpact(level,
                    baseNode.getEntity() != null ? baseNode.getEntity().getId() : targetNodeId,
                    baseNode.getScores(), simNode.getScores());
            impacts.add(levelImpact);
        }

        return impacts;
    }

    /**
     * Cadena jerarquica desde el nodo objetivo hasta COURSE, en orden hoja→raiz.
     * Solo incluye niveles que estan por encima (o igual) al nodo objetivo.
     */
    private List<AuditTarget> buildChain(AuditTarget nodeTarget) {
        // Orden completo: QUIZ < KNOWLEDGE < TOPIC < MILESTONE < COURSE
        List<AuditTarget> fullChain = List.of(
                AuditTarget.QUIZ,
                AuditTarget.KNOWLEDGE,
                AuditTarget.TOPIC,
                AuditTarget.MILESTONE,
                AuditTarget.COURSE);

        int startIdx = fullChain.indexOf(nodeTarget);
        if (startIdx < 0) {
            startIdx = 0;
        }
        return fullChain.subList(startIdx, fullChain.size());
    }

    /**
     * Busca un nodo en el arbol del reporte por target y, opcionalmente, por nodeId.
     * Para niveles superiores al nodo objetivo (KNOWLEDGE, TOPIC, MILESTONE, COURSE)
     * buscamos el ancestro del nodo objetivo; para el nodo objetivo buscamos por id.
     */
    private AuditNode findNode(AuditNode root, AuditTarget target, String nodeId) {
        if (root == null) {
            return null;
        }
        return findNodeDfs(root, target, nodeId);
    }

    private AuditNode findNodeDfs(AuditNode node, AuditTarget target, String nodeId) {
        if (node == null) {
            return null;
        }
        if (node.getTarget() == target) {
            if (nodeId == null) {
                // Para niveles superiores al nodo objetivo, tomamos el primero que encontramos
                // con el target correcto (el ancestro que contiene la cadena)
                return node;
            }
            // Si la entidad es null, aceptamos el nodo como coincidencia (no hay ID para distinguir)
            if (node.getEntity() == null) {
                return node;
            }
            if (nodeId.equals(node.getEntity().getId())) {
                return node;
            }
        }
        if (node.getChildren() != null) {
            for (AuditNode child : node.getChildren()) {
                AuditNode found = findNodeDfs(child, target, nodeId);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    /**
     * Construye un LevelImpact calculando el delta de cada score presente en ambos nodos.
     * Si una dimension solo esta en uno de los dos reportes, se omite (R005: solo pares evaluados).
     */
    private LevelImpact buildLevelImpact(AuditTarget target, String nodeId,
            Map<String, Double> baseScores, Map<String, Double> simScores) {

        Map<String, Double> base = baseScores != null ? baseScores : Map.of();
        Map<String, Double> sim = simScores != null ? simScores : Map.of();

        // Score agregado: promedio de todas las dimensiones disponibles en ambos reportes
        double baseAvg = base.values().stream().mapToDouble(Double::doubleValue).average().orElse(0.0);
        double simAvg = sim.values().stream().mapToDouble(Double::doubleValue).average().orElse(0.0);
        ScoreDelta aggregateDelta = new ScoreDelta(baseAvg, simAvg, simAvg - baseAvg);

        // Deltas por dimension: solo los pares (nivel, dimension) evaluados en ambos reportes
        List<DimensionDelta> dimensionDeltas = new ArrayList<>();
        for (Map.Entry<String, Double> entry : base.entrySet()) {
            String dimension = entry.getKey();
            if (sim.containsKey(dimension)) {
                double beforeVal = entry.getValue();
                double afterVal = sim.get(dimension);
                ScoreDelta delta = new ScoreDelta(beforeVal, afterVal, afterVal - beforeVal);
                dimensionDeltas.add(new DimensionDelta(dimension, delta));
            }
        }

        return new LevelImpact(target, nodeId, aggregateDelta, dimensionDeltas);
    }

    // -------------------------------------------------------------------------
    // Helper para construir UNAVAILABLE
    // -------------------------------------------------------------------------

    private static ImpactPreview unavailable(String proposalId,
            ImpactPreviewUnavailabilityReason reason, String detail) {
        ImpactPreviewUnavailability unavailability = new ImpactPreviewUnavailability(reason, detail);
        return new ImpactPreview(
                proposalId,
                Instant.now(),
                ImpactPreviewAvailability.UNAVAILABLE,
                unavailability,
                List.of());
    }
}
