package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.auditdomain.AuditTarget;
import com.learney.contentaudit.coursedomain.CourseEntity;
import com.learney.contentaudit.revisiondomain.CourseElementLocator;
import com.learney.contentaudit.revisiondomain.CourseElementSnapshot;
import java.util.Optional;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultCourseElementLocator implements CourseElementLocator {
    @Override
    public Optional<CourseElementSnapshot> snapshot(CourseEntity course, AuditTarget target,
            String nodeId) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public CourseEntity replace(CourseEntity course, CourseElementSnapshot replacement) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
