package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.refinerdomain.DiagnosisKind;
import com.learney.contentaudit.refinerdomain.RefinementPlan;
import com.learney.contentaudit.refinerdomain.RefinementPlanStore;
import com.learney.contentaudit.refinerdomain.RefinementTask;
import com.learney.contentaudit.refinerdomain.RefinementTaskStatus;
import com.learney.contentaudit.revisiondomain.QuizInstructionCorrectionRunStore;
import com.learney.contentaudit.revisiondomain.QuizInstructionCorrectionRunner;
import com.learney.contentaudit.revisiondomain.RevisionEngine;
import com.learney.contentaudit.revisiondomain.RevisionOutcome;
import com.learney.contentaudit.revisiondomain.RevisionOutcomeKind;
import com.learney.contentaudit.revisiondomain.RevisionProposal;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CandidateLengthMeasurement;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CorrectionCriterion;
import com.learney.contentaudit.revisiondomain.candidatecriteria.CriterionVerdict;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionCorrectionConfig;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionCorrectionRunReport;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionCorrectionRunRequest;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionTaskOutcome;
import com.learney.contentaudit.revisiondomain.quizinstruction.QuizInstructionTaskOutcomeKind;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;

/**
 * F-QICOR-R008/R009 (journey J002): drives one bounded batch of QUIZ_INSTRUCTION
 * tasks through {@link RevisionEngine#revise}, counting each task into exactly
 * one of the four declared outcomes -- proposed, not corrected, diagnosis
 * stale, or not attempted (tasks past the tope) -- plus {@code failed} so the
 * arithmetic against {@code attempted} closes. Delegates the actual
 * revalidate/generate/assess loop entirely to {@link QuizInstructionReviser}
 * via the shared {@link RevisionEngine}; this class only sequences tasks,
 * bounds spend, and translates {@link RevisionOutcomeKind} into the run
 * report's own vocabulary.
 */
@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
class DefaultQuizInstructionCorrectionRunner implements QuizInstructionCorrectionRunner {

    private static final int DEFAULT_MAX_CORRECTIONS_PER_RUN = 20;

    private static final int DEFAULT_MAX_ATTEMPTS = 3;

    private final RevisionEngine revisionEngine;

    private final RefinementPlanStore refinementPlanStore;

    private final QuizInstructionCorrectionRunStore runStore;

    private final QuizInstructionCorrectionConfig config;

    public DefaultQuizInstructionCorrectionRunner(RevisionEngine revisionEngine,
            RefinementPlanStore refinementPlanStore, QuizInstructionCorrectionRunStore runStore,
            QuizInstructionCorrectionConfig config) {
        this.revisionEngine = revisionEngine;
        this.refinementPlanStore = refinementPlanStore;
        this.runStore = runStore;
        this.config = config;
    }

    @Override
    public QuizInstructionCorrectionRunReport run(QuizInstructionCorrectionRunRequest request) {
        Instant startedAt = Instant.now();

        RefinementPlan plan = refinementPlanStore.load(request.getPlanId())
                .orElseThrow(() -> new IllegalArgumentException(
                        "Plan not found: " + request.getPlanId()));

        int maxCorrections = resolveMaxCorrections(request);

        List<RefinementTask> allTasks = plan.getTasks() != null ? plan.getTasks() : List.of();
        List<RefinementTask> eligibleTasks = new ArrayList<>();
        for (RefinementTask task : allTasks) {
            if (task.getDiagnosisKind() == DiagnosisKind.QUIZ_INSTRUCTION
                    && task.getStatus() == RefinementTaskStatus.PENDING) {
                eligibleTasks.add(task);
            }
        }

        int attempted = 0;
        int proposed = 0;
        int notCorrected = 0;
        int diagnosisStale = 0;
        int failed = 0;
        int proposedWithUnmetCriteria = 0;
        int proposedOutOfLengthRange = 0;
        List<String> notAttempted = new ArrayList<>();
        List<QuizInstructionTaskOutcome> outcomes = new ArrayList<>();
        // F-QICOR / DOUBT-TAREA-CAIDA opcion B: a diagnosis-stale task is marked STALE
        // so the next run does not pay the same revalidation query again; the audit
        // eventually retires the task on its own once it no longer flags the quiz.
        Map<String, RefinementTaskStatus> statusUpdates = new LinkedHashMap<>();

        for (RefinementTask task : eligibleTasks) {
            if (attempted >= maxCorrections) {
                notAttempted.add(task.getId());
                continue;
            }
            attempted++;

            RevisionOutcome outcome;
            try {
                outcome = revisionEngine.revise(
                        request.getPlanId(), task.getId(), request.getCoursePath(), null);
            } catch (RuntimeException e) {
                failed++;
                outcomes.add(new QuizInstructionTaskOutcome(task.getId(), task.getNodeId(),
                        QuizInstructionTaskOutcomeKind.FAILED, List.of(), e.getMessage(), null, 0, null, false));
                continue;
            }

            RevisionOutcomeKind kind = outcome.getKind();
            if (kind == RevisionOutcomeKind.APPROVED_APPLIED
                    || kind == RevisionOutcomeKind.PENDING_APPROVAL_PERSISTED) {
                proposed++;
                RevisionProposal resultProposal = outcome.getArtifact() != null
                        ? outcome.getArtifact().getProposal()
                        : null;
                String proposalId = resultProposal != null ? resultProposal.getProposalId() : null;
                // F-QICOR-R014/R011: the proposal itself already carries what it did not meet
                // and how it measured -- read back verbatim, never recomputed here.
                List<CriterionVerdict> unmetCriteria =
                        resultProposal != null ? resultProposal.getUnmetCriteria() : null;
                CandidateLengthMeasurement lengthMeasurement =
                        resultProposal != null ? resultProposal.getLengthMeasurement() : null;
                boolean outOfLengthRange = lengthMeasurement != null && !lengthMeasurement.isInRange();
                if (unmetCriteria != null && !unmetCriteria.isEmpty()) {
                    proposedWithUnmetCriteria++;
                }
                if (outOfLengthRange) {
                    proposedOutOfLengthRange++;
                }
                outcomes.add(new QuizInstructionTaskOutcome(task.getId(), task.getNodeId(),
                        QuizInstructionTaskOutcomeKind.PROPOSED, List.of(), null, proposalId, 1,
                        unmetCriteria, outOfLengthRange));
            } else if (kind == RevisionOutcomeKind.DIAGNOSIS_NOT_SUSTAINED) {
                diagnosisStale++;
                statusUpdates.put(task.getId(), RefinementTaskStatus.STALE);
                outcomes.add(new QuizInstructionTaskOutcome(task.getId(), task.getNodeId(),
                        QuizInstructionTaskOutcomeKind.DIAGNOSIS_STALE, List.of(),
                        outcome.getErrorMessage(), null, 0, null, false));
            } else if (kind == RevisionOutcomeKind.NO_ACCEPTABLE_CANDIDATE) {
                notCorrected++;
                List<CorrectionCriterion> failedCriteria =
                        parseFailedCriteria(outcome.getErrorMessage());
                outcomes.add(new QuizInstructionTaskOutcome(task.getId(), task.getNodeId(),
                        QuizInstructionTaskOutcomeKind.NOT_CORRECTED, failedCriteria,
                        outcome.getErrorMessage(), null, resolveMaxAttempts(), null, false));
            } else {
                failed++;
                outcomes.add(new QuizInstructionTaskOutcome(task.getId(), task.getNodeId(),
                        QuizInstructionTaskOutcomeKind.FAILED, List.of(),
                        outcome.getErrorMessage(), null, 0, null, false));
            }
        }

        if (!statusUpdates.isEmpty()) {
            List<RefinementTask> updatedTasks = new ArrayList<>(allTasks.size());
            for (RefinementTask task : allTasks) {
                RefinementTaskStatus newStatus = statusUpdates.get(task.getId());
                if (newStatus != null) {
                    task.setStatus(newStatus);
                }
                updatedTasks.add(task);
            }
            RefinementPlan updatedPlan = new RefinementPlan(
                    plan.getId(), plan.getSourceAuditId(), plan.getCreatedAt(), updatedTasks);
            refinementPlanStore.save(updatedPlan);
        }

        Instant finishedAt = Instant.now();
        QuizInstructionCorrectionRunReport report = new QuizInstructionCorrectionRunReport(
                null,
                request.getPlanId(),
                plan.getSourceAuditId(),
                startedAt,
                finishedAt,
                maxCorrections,
                eligibleTasks.size(),
                attempted,
                proposed,
                notCorrected,
                diagnosisStale,
                failed,
                notAttempted,
                outcomes,
                proposedWithUnmetCriteria,
                proposedOutOfLengthRange);

        String runId = runStore.save(report);
        report.setRunId(runId);
        return report;
    }

    private int resolveMaxCorrections(QuizInstructionCorrectionRunRequest request) {
        Integer requested = request.getMaxCorrections();
        if (requested != null && requested > 0) {
            return requested;
        }
        Integer configured = config != null ? config.getMaxCorrectionsPerRun() : null;
        return configured != null && configured > 0 ? configured : DEFAULT_MAX_CORRECTIONS_PER_RUN;
    }

    private int resolveMaxAttempts() {
        Integer configured = config != null ? config.getMaxAttempts() : null;
        return configured != null && configured > 0 ? configured : DEFAULT_MAX_ATTEMPTS;
    }

    /**
     * {@link RevisionOutcome} only carries a human-readable {@code errorMessage};
     * {@link com.learney.contentaudit.revisiondomain.NoAcceptableCandidateException}'s
     * structured {@code failedCriteria} does not survive
     * {@code DefaultRevisionEngine}'s catch-and-convert (by design, mirroring how
     * every other reviser failure becomes a plain outcome + message). Recovering the
     * named criteria for the run report's own {@code failedCriteria} field is done by
     * matching each {@link CorrectionCriterion} name against the message text -- the
     * exact same names {@code NoAcceptableCandidateException} formats into it.
     */
    private List<CorrectionCriterion> parseFailedCriteria(String message) {
        List<CorrectionCriterion> found = new ArrayList<>();
        if (message == null) {
            return found;
        }
        for (CorrectionCriterion criterion : CorrectionCriterion.values()) {
            if (message.contains(criterion.name())) {
                found.add(criterion);
            }
        }
        return found;
    }
}
