package com.learney.contentaudit.revisiondomain.engine;

import com.learney.contentaudit.revisiondomain.QuizInstructionProposalStrategy;
import java.util.List;
import java.util.Objects;
import javax.annotation.processing.Generated;

@Generated(
        value = "com.sentinel.SentinelEngine",
        comments = "Generated by Sentinel"
)
public class QuizInstructionProposalStrategyRegistryConfig {
    private List<QuizInstructionProposalStrategy> strategies;

    private String activeStrategyName;

    public QuizInstructionProposalStrategyRegistryConfig() {
    }

    public QuizInstructionProposalStrategyRegistryConfig(
            List<QuizInstructionProposalStrategy> strategies, String activeStrategyName) {
        this.strategies = strategies;
        this.activeStrategyName = activeStrategyName;
    }

    public List<QuizInstructionProposalStrategy> getStrategies() {
        return this.strategies;
    }

    public void setStrategies(List<QuizInstructionProposalStrategy> strategies) {
        this.strategies = strategies;
    }

    public String getActiveStrategyName() {
        return this.activeStrategyName;
    }

    public void setActiveStrategyName(String activeStrategyName) {
        this.activeStrategyName = activeStrategyName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        QuizInstructionProposalStrategyRegistryConfig that = (QuizInstructionProposalStrategyRegistryConfig) o;
        return Objects.equals(this.strategies, that.strategies)
                    && Objects.equals(this.activeStrategyName, that.activeStrategyName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(strategies, activeStrategyName);
    }
}
